### ISSUE TITLE
Light level overlay

### ISSUE THREAD

**Issue by VuuI** [shedaniel/RoughlyEnoughItems#10]
Any plans to port over NEI's light level overlay? there's currently no equivelant for SMP 1.13 and it's a feature alot of people miss.

**Comment by MelanX** [comment]
Yes, I need that, too. 
But I was thinking about doing it for myself. Just a mod which shows the lightlevel. If REI is faster (1.14) it would be nice but I'll try to write a lightlevel mod.

**Comment by shedaniel** [comment]
Not sure if I am going to add it to REI, maybe a separate mod would be better.

EDIT: I won't be doing it

**Comment by shedaniel** [comment]
Grid for Rift (You can get it here: https://minecraft.curseforge.com/projects/grid) already have a similar feature: /grid spawns

**Comment by shedaniel** [comment]
Another Mod: https://minecraft.curseforge.com/projects/simple-light-overlay-rift

**Comment by MelanX** [comment]
unfortunally not 1.14 and not open source :/ I wish I could port it.. but porting a 1.12 mod is horrible. Espacially as a Java noob

**Comment by shedaniel** [comment]
I might be implementing it in REI for Fabric, but not for Rift

**Comment by shedaniel** [comment]
What's your idea? Making it for another extra mod or implementing in REI?

**Comment by MelanX** [comment]
I tried to make an extra mod but it took a few days to just run an edited version of example mod (custom modid, other archive base...)

**Comment by shedaniel** [comment]
You can do it xD

**Comment by MelanX** [comment]
I'm too stupid xD I wanted to port MoreOverlays (just the lightlevel part) but I cannot find anything in Minecraft code xD it's too hard for me xD

**Comment by shedaniel** [comment]
I will be doing this after fixing all the nasty bugs.

**Comment by shedaniel** [comment]
The mod is here: https://minecraft.curseforge.com/projects/light-overlay
Wait for CurseForge to approve the project
