### ISSUE TITLE
[Feature] Ctrl+F to select search bar

### ISSUE THREAD

**Issue by TheonlyTazz** [shedaniel/RoughlyEnoughItems#100]
**Describe the solution you'd like**
when opening an inventory, pressing Ctrl+F automaticly "activates" REI search bar so you don't have to use the mouse to click on it

**Comment by Madis0** [comment]
Can not confirm it working on 3.0 pre1.

**Comment by shedaniel** [comment]
The default keybind for this is unbound.

**Comment by Madis0** [comment]
Got it. However, after binding the key, the key will also be inputted to the search field.

E.g binding to _p_ will make the search field activate on _p_ press, but also write "p" to the field.

**Comment by shedaniel** [comment]
Got it, please open another issue for this.
