### ISSUE TITLE
[Feature] Option for disabling tag category

### ISSUE THREAD

**Issue by SandWoodJones** [shedaniel/RoughlyEnoughItems#1001]
### What is your feature request?

I don't see much use for it and to me its just annoying. An option for disabling it would be nice.

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Should be done via #669 as an option to hide categories

**Comment by ardissaps** [comment]
up this
