### ISSUE TITLE
[issue ] Can't run your mod

### ISSUE THREAD

**Issue by Scorpions95** [shedaniel/RoughlyEnoughItems#1003]
### What happened?

Simple veinminer doesnt run, i mean i can't activate it, download all needed mods from here
https://www.curseforge.com/minecraft/mc-mods/search?category=&search=Simple+veinminer
https://i.gyazo.com/2b5c99d2a40d5352d74a2168401674b2.png
i got all these mod and can't use mod
what i need to do to activate it?

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
there is no error log
```

### Anything else?

Can't activate mod

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
didn't know rei is a vein miner mod

**Comment by Scorpions95** [comment]
> didn't know rei is a vein miner mod

still can't activate it
https://i.gyazo.com/19b97766528f2880e9ec72abc0729480.png
donwload REI from the same place
