### ISSUE TITLE
[Bug] search bar is not working, 1.19 on fabric

### ISSUE THREAD

**Issue by alexioron** [shedaniel/RoughlyEnoughItems#1009]
### What happened?

the search bar doesnt work when typed it, rei just stays the same as if there was nothing typed at all, the same as the other reports of this bug

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/alexioron/f26d58eb97f176c3af64ff1848977795
```

### Anything else?

using this modpack on curseforge: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Your issue is caused by Fabric Seasons, you could put the blame onto REI for asynchronously searching, but I feel like Fabric Seasons should add a check on their end instead.
