### ISSUE TITLE
[Feature] Change width of sidebar

### ISSUE THREAD

**Issue by bambanah** [shedaniel/RoughlyEnoughItems#101]
**Describe the solution you'd like**
Currently, the list of items on the side comes right to the edge of the container menu, sometimes covering buttons added by other mods. It would be nice to change how many columns are displayed.

**Comment by shedaniel** [comment]
Other mods can register exclusion zones

**Comment by bambanah** [comment]
Would still be really cool to change it, if it's not too hard to implement!

**Comment by shedaniel** [comment]
Can I get a mod to test?

**Comment by bambanah** [comment]
I know easier chests definitely has the sort button on the right, not sure if it's updated to 1.14.2 yet though.

**Comment by shedaniel** [comment]
Tell Easier Chests to support REI Exclusions.

**Comment by shedaniel** [comment]
Closing this because this is invalid.
