### ISSUE TITLE
[Bug] REI doesn't run

### ISSUE THREAD

**Issue by Simplebenja** [shedaniel/RoughlyEnoughItems#1011]
### What happened?

I'm able to run minecraft, and enter a world, but REI doesn't show up in the inventori window, the options for configuration doesn't show up in the configuration menu, "R" and "U" does nothing, also in the "mods" menu from the main menu REI doesn't show up in the list of instaled mods (cloth config and architectury DOES show up in the list)
JEI works fine
I'm using Tlauncher, FORGE 41.0.107, architectury-5.10.32-forge, cloth-config-7.0.73-forge and RoughlyEnoughItems-9.1.517
Sorry for the engrish

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
There is no crash log
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
No latest.log attached.

Also according to EULA we do not support TLauncher, I am closing the issue. This is a violation as providing support can also harm the project, please understand.
