### ISSUE TITLE
[Bug/Feature] Favourites are always Scrolled instead of Paginated.

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1017]
### What happened?

There's no option to change it, and even though the normal entry list is set to Paginated, the Favourites tab is still Scrolled.

I didn't know if this was a bug or not, I'm very sorry if it's the latter.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
N/A
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
This is intended behaviour. I didn't expect people to have that many favourites in the first place.
