### ISSUE TITLE
[Feature] Disable "dispose box" when drag and dropping.

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1018]
### What is your feature request?

As seen in the gif posted in #1016, trying to move items makes that box appear.

However, it makes it impossible to move something to or from those bottom rows that it hides, and there's no option to complete disable it.

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
I don't think I will move forward with this, this isn't the proper fix to that issue you linked
