### ISSUE TITLE
[Feature] Grouped items like in recipe book.

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1019]
### What is your feature request?

In the recipe book, alternative recipes for the same item (for example, different colors of beds) are all grouped into the same slot, saving a lot of space.

This should be implemented as an option, at least for the favourites list.

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by MaxNeedsSnacks** [comment]
This already exists in the form of collapsible entries (introduced in REI 8.3)

You can use a scripting mod like KubeJS to create custom groups yourself, though I'm assuming REI won't create any groups on its own as it might cause confusion for some users

**Comment by sayore** [comment]
Groups in favorites would be pretty poggers 👍

**Comment by shedaniel** [comment]
This has been implemented now.

**Comment by shedaniel** [comment]
@sayore Please open a new issue for your suggestion.
