### ISSUE TITLE
[Bug] Crash clicking compost tab on the dye recipe for a sea pickle

### ISSUE THREAD

**Issue by mattts1** [shedaniel/RoughlyEnoughItems#105]
**Describe the bug**
Crash when clicking compost tab on the dye recipe for a sea pickle

**Steps to Reproduce**
- First Step: open the recipe for the dye made from the sea pickle
- Second Step: Click on the compost tab above the recipe.

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14] 1.14.2
 - Mod Loader: [e.g. forge, fabric] Fabric

**Logs**
Crash log: https://pastebin.com/yAMZ1088

**Comment by shedaniel** [comment]
Reproduced.
