### ISSUE TITLE
[Feature] Configure Keybinding for Clearing Search Field

### ISSUE THREAD

**Issue by joelra** [shedaniel/RoughlyEnoughItems#1056]
### What is your feature request?

It would be nice to have a configuration option to clear the search box. That way a user could bind the clear to a key rather than having to use right click on the mouse. Would help increase accessibility.

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Or I mean if you’re already focused on the text field, use ctrl backspace?
