### ISSUE TITLE
CRASH ON LOAD(fabric 1.14.2-build 2)

### ISSUE THREAD

**Issue by SDUBZ** [shedaniel/RoughlyEnoughItems#106]
Farbic: 1.14.2-build 2
fab api: fabric-api-0.3.0+build.184
cotton-0.7.3+1.14.2-SNAPSHOT
crash report:
[crash-2019-06-15_13.42.21-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/3292674/crash-2019-06-15_13.42.21-client.txt)

**Comment by shedaniel** [comment]
The log says that suppress-unknown-item is causing the crash. Also try not to use caps on the title

**Comment by SDUBZ** [comment]
yeah i accidentally had caps on sorry and i referenced this issue with supressed unknown once i worked out it was it causing the crash
