### ISSUE TITLE
[Bug] REI Not Showing

### ISSUE THREAD

**Issue by KingPenguin0s** [shedaniel/RoughlyEnoughItems#1062]
### What happened?

My game was really laggy and I think I clicked the wrong button or something and now REI is not showing. I've tried everything including uninstalling and re-installing the mod, checking all my settings and asking my friends for help. I don't know how to solve the problem.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
I didn't have a relevant log output
```

### Anything else?

![2022-08-08_08 57 05](https://user-images.githubusercontent.com/110813109/183368853-71b7326f-c864-43de-8dff-8c00ce2b3d24.png)
![2022-08-08_08 57 15](https://user-images.githubusercontent.com/110813109/183368856-7e6530de-3f77-4fe9-a347-f9564a63b47c.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Try clicking Ctrl+O?

**Comment by KingPenguin0s** [comment]
> 

That worked! Thank you so much
