### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1067]
### What happened?

https://paste.gg/p/anonymous/09f4ccc048974e71b02af4d0c09663bc

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [x] Others

### Relevant log output

```shell
https://paste.gg/p/anonymous/09f4ccc048974e71b02af4d0c09663bc
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please DO NOT use paste.gg, I am unable to access it. Please open a new issue with the logs on GitHub Gists or just paste it.
