### ISSUE TITLE
[Bug]recipe listing showing off screen far left RoughlyEnoughItems-2.9.4+build.129

### ISSUE THREAD

**Issue by SDUBZ** [shedaniel/RoughlyEnoughItems#107]
![2019-06-15_14 33 02](https://user-images.githubusercontent.com/14084377/59546991-97f97180-8f7a-11e9-8f8a-20cb9f552f4d.png)

**Comment by shedaniel** [comment]
Logs?

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/3293832/latest.log)
here you go :D

**Comment by shedaniel** [comment]
Doesn't seem like there's any issue, can you zip up your mods folder so I can test?

**Comment by SDUBZ** [comment]
you want the configs too

**Comment by SDUBZ** [comment]
okay im uploading now will post zip once done :)

**Comment by SDUBZ** [comment]
here you go https://mega.nz/#!RtoDxQbZ!WwlwzaEZCK8vqTVaQLKv56TNkNBk30pZqRmaylCRD4A :D

**Comment by SDUBZ** [comment]
i fixed it somehow i switched to creative and then back to survival juts thought i would give you this lil info

**Comment by shedaniel** [comment]
Alright

**Comment by shedaniel** [comment]
Not actually a bug

**Comment by shedaniel** [comment]
I've reproduced and fixed.

**Comment by shedaniel** [comment]
Fixed in 2.9.5
