### ISSUE TITLE
[Feature] View item/material enchantability

### ISSUE THREAD

**Issue by CyberFoxar** [shedaniel/RoughlyEnoughItems#1084]
### What is your feature request?

Once upon a time, I remember an version of "* enough items" that would show the enchantability of a given item.

It is somewhat related to #137 , #386 and #903 as they touch upon similar stuff.

Maybe enchantability could be in a toggle option and then displayed in the item tooltip ?

Thanks !

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by unilock** [comment]
Viewing compatible enchantments per item was/is a feature implemented by [Not Enough Resources](https://www.curseforge.com/minecraft/mc-mods/notenoughresources) and [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer). Relevant(?) files:
[NER - EnchantmentRegistry.java](https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/registry/EnchantmentRegistry.java)
[JER - EnchantmentRegistry.java](https://github.com/way2muchnoise/JustEnoughResources/blob/master/Common/src/main/java/jeresources/registry/EnchantmentRegistry.java)

The equivalent mod [Roughly Enough Resources](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources) does *not* implement this feature. Maybe it'd be worth making an issue on [that mod's bug tracker](https://github.com/theorbtwo/RoughlyEnoughResources/issues)?

(Note that JER's "enchantability" feature *does* work on Fabric, for what it's worth.)

Example:
<img width="638" alt="Screen Shot 2022-10-19 at 8 57 38 AM" src="https://user-images.githubusercontent.com/11802133/196697371-f0cf3166-dbb5-4a69-8628-a174d840421c.png">

**Comment by CyberFoxar** [comment]
@unilock Viewing enchantements is already a feature that's somewhat available, and is very useful.
What this issue is after is viewing the hidden [enchantability](https://minecraft.fandom.com/wiki/Enchanting_mechanics#Enchantability) variable. Few mods take time to document it, yet it is very valuable information when trying to choose what material to make a given tool/armor of.

For what it's worth, [Silent Gear](https://github.com/SilentChaos512/Silent-Gear) has a feature where it dumps a table containing this information and a slew of others, viewing all the vanilla-related ones in REI would be very interesting.

**Comment by unilock** [comment]
I feel like that's a feature better suited for a tooltip mod, such as [Inspecio](https://modrinth.com/mod/inspecio) or [Peek](https://modrinth.com/mod/peek).

I made an example mod that shows an enchantable item's enchantability value in its tooltip:
https://github.com/unilock/GetEnchantability

(I should probably open a pull request on one of the mods I mentioned...)

**Comment by CyberFoxar** [comment]
> I feel like that's a feature better suited for a tooltip mod,

True ! Though I know how tooltips can quickly get bloated... I didn't realize the tooltips in REI were not made by the mod, oops.

I feel this number could be exposed in one of the already-present tabs, like the enchantements one you showed from REI. I'll take your suggestion and ask in their repo if they're intrested in adding it.

**Comment by shedaniel** [comment]
I believe this would be out of scope for REI, and suggestions for the tooltip mods are listed above.
