### ISSUE TITLE
[Bug] Disable Recipe Book removes buttons added by other mods

### ISSUE THREAD

**Issue by briansemrau** [shedaniel/RoughlyEnoughItems#109]
**Describe the bug**
When the recipe book is disabled, other buttons added to the inventory screen by other mods are also disabled. (Specifically in my mod [Cosmetic Armor Slots](https://github.com/briansemrau/Cosmetic-Armor-Slots)

**Steps to Reproduce**
- Enable the "Disable Recipe Book" feature

**Screenshots**
Screenshots not necessary, but see [here](https://github.com/briansemrau/Cosmetic-Armor-Slots/issues/1).

**Environment (please complete the following information with the version):**
 - Minecraft 1.14.2
 - Mod Loader: Fabric 0.3.0

**Logs**
https://pastebin.com/BVjDpEFP

**Additional context**
In the 1.14.2 mappings, I believe RecipeBookButtonWidget was renamed to TexturedButtonWidget (not confirmed). Any other mods that add these buttons will probably face the same issue.

The issue is caused by [this line](https://github.com/shedaniel/RoughlyEnoughItems/blob/5e9a5691c42b535eb9bb410fe366edfbae93192d/src/main/java/me/shedaniel/rei/RoughlyEnoughItemsCore.java#L219). Unfortunately I don't know how to differentiate buttons to pick out the recipe book button, so I can't offer a possible fix.

**Comment by shedaniel** [comment]
Thanks for looking into the root of the issue! Please try build 132 and let's hope that it fixes the issue.

**Comment by briansemrau** [comment]
Confirmed, this is fixed in the latest build.
