### ISSUE TITLE
[Feature] Disable tag category and processing

### ISSUE THREAD

**Issue by Xetaxheb** [shedaniel/RoughlyEnoughItems#1095]
### What is your feature request?

A config option to disable tag category completely and disable whatever processing is done to support it on boot (if it's any real overhead)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Duplicate of #669
