### ISSUE TITLE
[Feature] set day or night buttons

### ISSUE THREAD

**Issue by jdroo** [shedaniel/RoughlyEnoughItems#110]
A button to set day or night, and maybe also an option to lock it at the selection made.

pic just showing night and day icons.
![](https://i.imgur.com/3hOuFL2.png)

Tho building on that idea, maybe make it possible to add your own buttons in the settings under the action tab, basically just add a "+" button, when pressed it makes a new blank button that you can name and set the command it uses, kinda like how you can change the commands for gamemode, weather and the give command, and it will just add a button in line with the rest of your default buttons. Maybe make it grab icons to use from the mods folder or something so peeps can add their own icons, that or just use text on the buttons if the icon idea does not work for you.

**Comment by shedaniel** [comment]
Seems doable.

**Comment by jdroo** [comment]
i unno, just thinking back to the days of toomanyitems, they had that feature, also another feature to add is a magnet button, that when on pulls all dropped items towards the player.

**Comment by shedaniel** [comment]
Magnet probably won’t be added

**Comment by shedaniel** [comment]
I need weather icons lmao

**Comment by jdroo** [comment]
> 
> 
> Magnet probably won’t be added

Any reason why that wont be added? It's useful for skyblock maps hahaha

**Comment by shedaniel** [comment]
> 
> Any reason why that wont be added? It's useful for skyblock maps hahaha

Because it is outside the scope of REI

**Comment by Minenash** [comment]
Not sure if this is the best spot to put this, but also having these buttons all on the top row if theirs room?
