### ISSUE TITLE
[Bug/Oversight] Fluid rendering uses the FluidRenderHandler instead of the FluidVariantRenderHandler

### ISSUE THREAD

**Issue by TropheusJ** [shedaniel/RoughlyEnoughItems#1108]
### What happened?

Fluid colors are queried through `FluidRenderHandlerRegistry`, but it should be using `FluidVariantRendering` when possible.
![image](https://user-images.githubusercontent.com/60247969/187722997-777d9904-a4cd-4c75-99fa-a3ff8813ceb6.png)

This prevents using NBT to adjust the color:
![image](https://user-images.githubusercontent.com/60247969/187723579-c70960a1-ccc1-490e-a6ad-20a86292d11f.png)

`FluidVariantRendering` should also be used for tooltips in `FluidEntryDefinition$FluidEntryRenderer.`

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A
```

### Anything else?

Create used to have a [custom fluid entry stack renderer](https://github.com/Fabricators-of-Create/Create/blob/00469935463c5a74c29897380923c419ab220240/src/main/java/com/simibubi/create/compat/rei/FluidStackEntryRenderer.java) that worked.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please open an issue for this in https://github.com/architectury/architectury-api

**Comment by TropheusJ** [comment]
oops, didn't realize that class was part of arch.

**Comment by shedaniel** [comment]
I will close the issue here.
