### ISSUE TITLE
Option to separate mods into their own pages

### ISSUE THREAD

**Issue by edeetee** [shedaniel/RoughlyEnoughItems#111]
I would appreciate a view to separate the pages by mod.
I imagine a setting to allow separating each mod into it's own page.
A Mod/Minecraft title will appear beside the page number, clicking on it will go back to the first page of vanilla mc.
The pagination will go back to the first page of that mod, or if already on the first page, back to the first page of vanilla.

I am currently seeing if I can get this working on my fork.

**Comment by shedaniel** [comment]
Hmm seems hard

**Comment by shedaniel** [comment]
This sounds too complex for the user and for the mod. It will just be weird tbh
