### ISSUE TITLE
Resource Pack textures

### ISSUE THREAD

**Issue by Slye-Fox** [shedaniel/RoughlyEnoughItems#113]
How do I fix this?
https://i.imgur.com/ETYpXzt.png

**Comment by shedaniel** [comment]
Your texture pack supports REI?

**Comment by Slye-Fox** [comment]
Not currently, it's what I was working on.
But I can't find what is making the grey parts left.

**Comment by shedaniel** [comment]
Well ugh, the colours are hardcoded. I need to add support for that

**Comment by Slye-Fox** [comment]
My suggestion would be to use those squares in the top right of recipecontainer.png

**Comment by shedaniel** [comment]
Working on this

**Comment by shedaniel** [comment]
REi now renders with 9 patch in 3.6.6 and 4.1.5
