### ISSUE TITLE
[Feature] Categories in Categories

### ISSUE THREAD

**Issue by Shadowdragon019** [shedaniel/RoughlyEnoughItems#1130]
### What is your feature request?

Ability to make categories inside categories.
![Untitled](https://user-images.githubusercontent.com/67480398/190844447-d0528d0e-2b04-4823-b483-e7e529bc8ffa.png)

This would work lovely with #1112

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by sayore** [comment]
Actually kinda the same GUI Class this would fall my Feature request would fall into https://github.com/shedaniel/RoughlyEnoughItems/issues/1158

**Comment by shedaniel** [comment]
I believe this would be too complicated for the end user, but doesn't offer much to the user as well, I think they should just all be separate categories.
