### ISSUE TITLE
[Bug] Tipped Arrow recipes still show when removed

### ISSUE THREAD

**Issue by Shadowdragon019** [shedaniel/RoughlyEnoughItems#1131]
### What happened?

I've removed the Tipped Arrow recipes but they still show.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No logs relevant to my knowledge
```

### Anything else?

![image](https://user-images.githubusercontent.com/67480398/190919948-5d1615ba-1e61-4ae9-ae20-6c21b28a7133.png)
![image](https://user-images.githubusercontent.com/67480398/190919949-9d6836c4-28df-4928-a1b5-993c1aa5e245.png)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Shibva** [comment]
While its irrelevant; I have a similar issue @shedaniel 

Except its a pre-existing recipe that ONCE existed.

Ill make a seprate issue on this though its best described like this but in reverse; (Ie, the recipe still exist but the mod that adds it is removed and its on a world-save basis)

**Comment by shedaniel** [comment]
@Shibva This issue is not resolved yet, it is “completed”, but the fix is not released yet.
