### ISSUE TITLE
[Bug] No displayed matched category spam

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#1138]
### What happened?

tons of spam from v8.3.5.4.9 v1.18.2 mc... not even just no displayed matched category spam but it seems there's tons of spam coming from REI in other areas in latest log... thousands and thousands of lines.

Looks like category issues

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
latest; https://gist.github.com/itsdinkd/c498dc4fab386565cb5b15e9e1889684

rei; https://gist.github.com/itsdinkd/5df52a9496a7575899bed016cee3b478

(ignore crash in latest.log, that is irrelevent)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I do not see any spam from your latest.log, it is normal for REI to log _some_ data to the log to help debugging.
