### ISSUE TITLE
[Bug] Recipe Ids not shown in some cases

### ISSUE THREAD

**Issue by Abalieno** [shedaniel/RoughlyEnoughItems#1139]
### What happened?

I was advised in KubeJS discord to report this.

Supposedly, the recipe should have an ID shown in that tooltip.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No log
farmers-delight-fabric-1.18.2-1.2.1.jar being used in this example
```

### Anything else?

![tyjuk](https://user-images.githubusercontent.com/4656436/193383822-391d6cd6-3a56-4a65-b632-83d1fb50186c.jpg)

![iliul](https://user-images.githubusercontent.com/4656436/193383823-b77fe3f8-c7ff-4620-b7f9-69c2cfba93c4.jpg)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ground-fruit** [comment]
Seems like this is the case for some non-vanilla crafting methods.
Minecraft 1.19.2
Fabric 0.14.11
REI 9.1.574

Some examples I've noticed:
CREATE
+ create:blasting
+ create:crushing
+ create:compacting
+ create:cutting
+ create:deploying
+ create:emptying
+ create:filling
+ create:haunting
+ create:item_application
+ create:mechanical_crafting
+ create:milling
+ create:mixing
+ create:pressing
+ create:sandpaper_polishing
+ create:sequenced_assembly
+ create:smelting
+ create:smoking
+ create:splashing

FARMERS DELIGHT
+ farmersdelight:cutting

AD ASTRA
+ ad_astra:nasa_workbench
+ ad_astra:comressing
+ ad_astra:cryo_fuel_conversion


An example from Create:
<img width="852" alt="Screen Shot 2022-12-02 at 18 27 10" src="https://user-images.githubusercontent.com/105956363/205412776-087c7c01-a07b-4b05-8bc0-c420049a33c3.png">

**Comment by shedaniel** [comment]
The mods providing the integration should report it's ID to REI, please refer them to the getDisplayLocation method in the Display class.
