### ISSUE TITLE
[Bug] Crash upon clicking in-game config `More Options`

### ISSUE THREAD

**Issue by rlnt** [shedaniel/RoughlyEnoughItems#1141]
### What happened?

When using REI on Forge 1.19.2, your client will crash when you open the in-game config menu by clicking the gear next to the REI search bar and selecting `More Options`.

I am in a dev environment so the log might look odd. REI dependencies are pulled automatically from maven as transitive dependencies. A crash report is at the bottom.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/DAmNRelentless/eb83b1dc99ea152e57d54fdff8c8fe6c
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Your Cloth Config is too old.

**Comment by rlnt** [comment]
It was pulled transitive by the REI dependency tho 😐
