### ISSUE TITLE
Hiding Entries

### ISSUE THREAD

**Issue by Geekerandy** [shedaniel/RoughlyEnoughItems#115]
NEI/NEI-addons to JEI had a feature where you could "hide" items from the item panel. Can we have it here as well?

**Additional context**

![NEI_JEI](https://user-images.githubusercontent.com/14936715/60232087-573e0a00-9850-11e9-9cd8-98860538afc9.PNG)

**Comment by PanoptesDreams** [comment]
Hi, please add this feature!
You're updating frequently and not really adding anything.

Someone told me they prefer the normal crafting book over JEI because it's just filled with crap.

**Comment by shedaniel** [comment]
There are a few ways to do this:
- NEI Subsets (I do not like this at all)
- JEI List Edit Mode
- or some random other methods
This seems like a big feature and will take a lot of time out of me so don't expect me to do this soon.

**Comment by PanoptesDreams** [comment]
As long as it's on your radar that's good.
I'm a fan of an App ID blacklist or Item ID black list

**Comment by shedaniel** [comment]
https://streamable.com/qlpl0 is done.
