### ISSUE TITLE
[Feature] 隐藏开启拼音输入法物品下面的拼音字母

### ISSUE THREAD

**Issue by WarmRhombus** [shedaniel/RoughlyEnoughItems#1156]
### What is your feature request?

1：开启拼音搜索后，物品下面的注音看的有点不舒服。
希望可以在设置里添加个可以隐藏的按钮
![1](https://user-images.githubusercontent.com/88981285/196253299-7f8f02ce-8cae-4fe1-ae38-d9df526de41f.png)

### What do you think this change is of?

- [x] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
I am separating the issue, please don't report two issues with one issue.
