### ISSUE TITLE
[Bug] CHANGE ME

### ISSUE THREAD

**Issue by Gamerbolts** [shedaniel/RoughlyEnoughItems#1157]
### What happened?

I was scrolling through the items list and crashed

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Crash Log: https://gist.github.com/Gamerbolts/034af81f06a60625e5f38b674199c29e
REI Log: https://gist.github.com/Gamerbolts/e082292a3babffea3e6d12823afb9cb2
Main Log: https://gist.github.com/Gamerbolts/0a420e560d743818e3db6c6df42f3e3a
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please report to RER, it is their issue
