### ISSUE TITLE
[Bug] 1.14.3 fabric crashing on hitting recipe button

### ISSUE THREAD

**Issue by Kylebartaous** [shedaniel/RoughlyEnoughItems#116]
The bug
- Attempting to hit the recipe key bind r, on a few blocks & items w/ in the gui of rei, would cause it to crash.

Steps to Reproduce the bug
- Click the recipe button then hovering over a block or item, in rei

Minecraft version & loader
 - Minecraft 1.14.3
 - Fabric for 1.14.3 build 155
- Twitch launcher

Crash log, & latest logs
- Crash log: https://pastebin.com/8gsrF2jS
- Latest log #1: https://pastebin.com/fzYgTkFw
- Latest log: #2: https://pastebin.com/61JUAKTY

Other thoughts
- Probably just going to have to go from first page, top to bottom, clicking r for recipe on everything, seeing a lot of block & items that could cause it to crash.

- You may also want to try hitting the U key to look at it's usage, I haven't really tested if clicking use on ever thing was also causing any problems, but it may also be tied to this problem

- So It seems then trying to get the recipe of a block or item, that doesn't have any, it would cause that to crash, Some blocks, items i tried testing were, dirt block, grass block, sweet berry's. Guessing it could it trying to pull for a recipe, but can't find any. possibly need to add some checks, if that block or item, would, or wouldn't, have another tier down below it self, that is a recipe, or not. since some things that are, from world gen, or a plant, have no tier below it's self, w/ out using the extra add on mod, roughly enough resources to show more info about it, world gen wise where you would say find sweet berry's in the world & there y lvl.

**Comment by Kylebartaous** [comment]
Could the problem, for sweet berry's at least, but a problem w/ either, then roughly enough add-on's merged w/ main rei project, & or the roughly enough resources trying to pull for recipe / where in the world that block / item is from, causing it ? May want to look at possibly around that.

**Comment by theorbtwo** [comment]
This is actually a bug in Roughly Enough Resources, not Roughly Enough Items.  (It can be difficult to tell as a user, but in this case a big giveaway is uk.me.desert_island.  If you see that, blame me.)  This is RER doing a really bad job with handing running on a client.  That's currently at the "known problem" stage -- I'm planning on handling that, but haven't quite gotten there yet.  Sorry.
