### ISSUE TITLE
[Bug] Checking Applied Energistics 2's Meteorite Compass recipe causes game to crash 

### ISSUE THREAD

**Issue by cl0ck-byte** [shedaniel/RoughlyEnoughItems#1177]
### What happened?

If you're trying to check Applied Energistics 2's Meteorite Compass recipe, the game will crash.

Possibly because REI can't handle charger recipe overview.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/cl0ck-byte/b0ccd2cca4e5abf3974cf8b3cdd0cf2f
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by cl0ck-byte** [comment]
Issue persists even after https://github.com/shedaniel/RoughlyEnoughItems/commit/9535ea4f28dc628275aa7a5b840375928648c662

**Comment by shedaniel** [comment]
AE2 is applying both its JEI and REI integration, they should disable the REI one or the JEI one on Forge.

**Comment by shedaniel** [comment]
This should be fixed with an update of REI, REI Plugin Compatibilities and AE2
