### ISSUE TITLE
[Bug] Missing UI 

### ISSUE THREAD

**Issue by antiguy1994** [shedaniel/RoughlyEnoughItems#1179]
### What happened?

Missing UI on the command shortcuts linked the screenshot. Using medieval minecraft modpack v9 1.19.2 fabric 0.14.9 I uninstalled JEI, JEI Resources & Professions with latest fabric REI, REI Resources & Professions and updated twilight forest to the lastest version linked the version below

[https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4055624](url)
![2022-10-28_22 06 08](https://user-images.githubusercontent.com/116933679/198812910-3085654f-e2f9-400f-b732-62cc4c1e778c.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
I put logs in the anything else
```

### Anything else?

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9892952/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9892954/latest.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9892955/rei-issues.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
They are not missing, your texturepack "Excalibur Mod Support" lack the latest REI button textures.
