### ISSUE TITLE
[Bug]  not compatible with moreoverlay updated

### ISSUE THREAD

**Issue by 0Yimeng0** [shedaniel/RoughlyEnoughItems#1185]
### What happened?

The game crashes on load when moreoverlay is installed.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/0Yimeng0/83611ad3cdc78ca858bc394dfc051866
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9916036/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/9916037/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by cl0ck-byte** [comment]
There is literally a message saying that REI is not compatible with More Overlays if you've ever managed to boot the game properly

**Comment by Xetaxheb** [comment]
This is true and https://www.curseforge.com/minecraft/mc-mods/light-overlay exists, as well as the inventory highlighting being part of REI by default.

The real question is whether a region boundary mod even exists in recent versions? of course you can use F3+G although the region boundary was nice for some niche uses but probably isn't that important realistically.

**Comment by shedaniel** [comment]
Region Boundary is a thing with vanilla minecraft already. REI + Light Overlay should replace More Overlays.
