### ISSUE TITLE
[Bug] crash happened randomly while switching the tabs on the top of gui. 

### ISSUE THREAD

**Issue by ZZZank** [shedaniel/RoughlyEnoughItems#1186]
### What happened?

A crash happened randomly while switching the tabs on the top of gui. 
The crash report mentioned IndexOutOfBoundsException. 
An older version（8.3.543）did not have this problem, while the newest version for 1182 still has this problem.

崩溃会发生在切换合成表顶端的标签时，提示IndexOutOfBoundsException
旧版本（8.3.543）或者jei没有这个问题，最新版的rei(8.3.563)仍然存在这个问题

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[crash-2022-10-30_22.05.15-client.txt](https://github.com/DM-Earth/Cabricality/files/9925305/crash-2022-10-30_22.05.15-client.txt)
[crash-2022-10-31_23.21.04-client.txt](https://github.com/DM-Earth/Cabricality/files/9925306/crash-2022-10-31_23.21.04-client.txt)
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please use English

**Comment by ZZZank** [comment]
> Please use English

has changed the title and contents, sorry

**Comment by MattB70** [comment]
I have spoken to two others who have experienced the same on version 8.3.561 for Forge. Very similar crash output. Same exception.
