### ISSUE TITLE
[Feature] Use Recipe Book button to show/hide REI

### ISSUE THREAD

**Issue by CapoFantasma97** [shedaniel/RoughlyEnoughItems#119]
Currently there's an option to hide the book, but it would be interesting to add an option to recycle it to show/hide REI, so it's not on your face when you don't need it. No "enough items" mod has done it yet.

**Comment by shedaniel** [comment]
Press "O"? It will hide REI.

**Comment by CapoFantasma97** [comment]
> Press "O"? It will hide REI.

I already use O for other stuff. Not that it means anything, I already have the show/hide bound to a nearby key anyway. But it would be a cool thing to have, clicking the GUI button and it opens a much better recipe finder than the vanilla one.

**Comment by shedaniel** [comment]
I don’t really understand but you are saying that the recipe book button should open / close REI as an option?

**Comment by CapoFantasma97** [comment]
> I don’t really understand but you are saying that the recipe book button should open / close REI as an option?

Yes exactly.

**Comment by shedaniel** [comment]
Alright this is doable.

**Comment by shedaniel** [comment]
Don’t expect this to be done soon as I am waiting for the 1.15 cycle

**Comment by shedaniel** [comment]
Nevermind, this is declined.
