### ISSUE TITLE
Most recent update fabric 8.3.564 is broken

### ISSUE THREAD

**Issue by Fade-Alchemist** [shedaniel/RoughlyEnoughItems#1192]
### What happened?

The first time I loaded my game with this version, the game loaded in as expected. But, when I searched for an item, no searches produced results. In fact, if I left the search bar empty there were no items displayed. Then the game crashed (no error message) and I was never able to get back in, the world would fail out upon loading. 
I was not able to get back into my world until I downgraded to the previous version - fabric 8.3.563
[crash-2022-11-05_11.49.36-server.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9944341/crash-2022-11-05_11.49.36-server.txt)
[crash-2022-11-05_11.34.19-server.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9944342/crash-2022-11-05_11.34.19-server.txt)
[crash-2022-11-05_11.28.45-server.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9944343/crash-2022-11-05_11.28.45-server.txt)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
I put it here but your system says it is too long and will not post my bug report. They are attached to my bug description.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe the crashes experienced is not caused by REI, advancements are crashing, which REI does not touch. If possible can you also attach the latest.log and rei.log from the logs folder.

**Comment by Technici4n** [comment]
You can fix this by installing this mod on your server: https://www.curseforge.com/minecraft/mc-mods/advancements-debug.

**Comment by shedaniel** [comment]
Thanks @Technici4n! @Fade-Alchemist your issue is not related to REI and you can fix that using Tech's mod.
