### ISSUE TITLE
[Feature] Add compatibility with JEI plugin Just Enough Calculation on Forge 1.18.2

### ISSUE THREAD

**Issue by UraraChiya** [shedaniel/RoughlyEnoughItems#1197]
### What is your feature request?

[Just Enough Calculation](https://github.com/Towdium/JustEnoughCalculation) 

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
They added support for REI!
