### ISSUE TITLE
[Bug] R/U functionality stops working after using Refined Storage search

### ISSUE THREAD

**Issue by tivec** [shedaniel/RoughlyEnoughItems#1212]
### What happened?

When first opening a RS grid, you can use U and R to search for recipes in the mod. If you select the search field in the grid, then deselect it, the U/R buttons stop working until you close the grid and open it again. 

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
There is no log that is relevant.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Namoku** [comment]
This happens too with applied energistics terminals

**Comment by shedaniel** [comment]
Should be fixed with https://github.com/shedaniel/RoughlyEnoughItems/commit/2caa595aa94d46ddaefc5ecdb79f7ec834f7eae8
