### ISSUE TITLE
[Bug] java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1025

### ISSUE THREAD

**Issue by Taskeren** [shedaniel/RoughlyEnoughItems#1213]
### What happened?

Just crashed.
Rei used in FTB Stoneblock 3 (v1.0.2 of the pack).

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

[crash-2022-11-13_12.49.47-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/9996535/crash-2022-11-13_12.49.47-client.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe this is now resolved
