### ISSUE TITLE
[Feature] Use reflection to determine if REI should display its gui

### ISSUE THREAD

**Issue by zly2006** [shedaniel/RoughlyEnoughItems#1222]
### What is your feature request?

I am a mod developer and I used `HandledScreen` to pass on extended information. But REI treats my screen as an inventory, and displayed its gui on the top of my screen.

Here's a way that i suggest:

I want REI to check the screen before displaying gui: (1) if this class has a public method, like `shouldReiDisplayGui`, which returns `bool`. (2) only display gui when this method returns true.

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
REI exposes a way to do it via REI's API, and without ugly hacks like reflection: https://www.craft.do/s/qj8mHyTVd7qkOZ/b/76D2B72D-660A-4CE7-8205-E2F578EAE897/Screens_(Client)

To register your own OverlayDecider, check [Constructing Plugins](https://www.craft.do/s/qj8mHyTVd7qkOZ/b/0078E0DE-2724-4FD8-BFB4-ABEAEC431E16/Constructing_Plugins) and override `registerScreens`.
