### ISSUE TITLE
Cheat Mode

### ISSUE THREAD

**Issue by Raleford** [shedaniel/RoughlyEnoughItems#123]
version 1.14.3
When cheat mode is active I'm getting an error that the command is unknown when attempting to spawn something in.

It's running /minecraft:give when it seems to just want /give

I don't know if this has changed or if it's a command block thing, I don't know much about command blocks, but just thought I'd post it here.

**Comment by shedaniel** [comment]
There is a config setting to fix this

**Comment by Raleford** [comment]
Ah ok, thank you
