### ISSUE TITLE
[Bug] CHANGE ME

### ISSUE THREAD

**Issue by DarkCrystalll** [shedaniel/RoughlyEnoughItems#1233]
### What happened?

![image](https://user-images.githubusercontent.com/118486124/203577643-732ab28a-dc67-4c67-b504-c07bc769091f.png)

合成方式不见了，其他都还在，机械动力的自动合成倒是显示着
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10077549/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10077550/rei.log)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
日志见正文
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please report to vinery, also create the issue in English for readability
