### ISSUE TITLE
[Bug] Crash in some scenarios

### ISSUE THREAD

**Issue by spunchbop121** [shedaniel/RoughlyEnoughItems#1239]
### What happened?

Mod crashes while entering text in the search field - 1.19.2 Fabric

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Latest.log - https://pastebin.com/reWZWcHE

REI.log - https://pastebin.com/188PguxF

crash-client.txt - https://pastebin.com/RW0cVhbn
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [ ] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Please report to Every Compat
