### ISSUE TITLE
[Bug] Server crash with REI and Avaritia

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#1240]
### What happened?

Place down the Extreme Crafting Table
Find any recipes made it in and click on the + to transfer items
Server crash

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://pste.me/@/L14ZmjZilnU
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Fixed in latest REI Plugin Compatibilities.
