### ISSUE TITLE
Inventory highlighting hint appears bugged when search bar is above or below item list

### ISSUE THREAD

**Issue by vrad-exe** [shedaniel/RoughlyEnoughItems#1247]
### What happened?

When the search bar position is set to above or below the item list instead of bottom center, the hint when inventory highlighting is enabled appears bugged in two different ways.

When set to above the item list, it appears offscreen:
![image](https://user-images.githubusercontent.com/19228201/204122111-b9ec702e-8d30-451d-ba2e-096ef3923aff.png)

When set to below the item list, the hint background appears behind the items but the text appears in front:
![image](https://user-images.githubusercontent.com/19228201/204122102-dd3035bf-ce52-4a3a-b8af-2d09b4476457.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
It's a visual bug/mistake, there's no related log output
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe I have fixed this issue, please check with the latest REI update. Thanks!

**Comment by shedaniel** [comment]
I think this has been resolved now! Please re-open if otherwise!
