### ISSUE TITLE
[Feature] Add Double Pinyin IME

### ISSUE THREAD

**Issue by Duoq233** [shedaniel/RoughlyEnoughItems#1256]
### What is your feature request?

增加常双拼输入法，列如：小鹤双拼、自然码

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by rozbrajaczpoziomow** [comment]
hmm yes, makes sense...
https://i.imgur.com/5M9Rk9Y.png
