### ISSUE TITLE
[Bug] Start crash SB3

### ISSUE THREAD

**Issue by Gloval** [shedaniel/RoughlyEnoughItems#1262]
### What happened?

A Friend is getting a start up crash in StoneBlock 3.

No removed mods but have added Lootr, polymorph, Waystones, Storage Drawers and Framed Compacting Drawers to the server and client.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://pastebin.com/85HQRQQV
```

### Anything else?

This is for joining a server we are both on.  I am running the same mods and do not get this crash or the REI-ReloadPlugins/ERRORs her client is getting.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Gloval** [comment]
Can provide my client start log as comparison reference if needed.

**Comment by shedaniel** [comment]
Where is the crash?
The "createFocusLink is not supported in REI yet!" is an error but not a crash

**Comment by Gloval** [comment]
https://pastebin.com/85HQRQQV
Log is posted here.

**Comment by Gloval** [comment]
When I say crash, she gets the red Mojang load screen, it processes along for a bit then closes out. Same load out as my system. I do not get these REI errors.

**Comment by shedaniel** [comment]
Are you sure that's the correct logs? Your logs show you joining a server, which doesn't match the description of being stuck in the loading screen

**Comment by shedaniel** [comment]
I am closing the issue because the question was not answered and this issue has became stale. Please re-open this issue if it persists.
