### ISSUE TITLE
[Feature] Favorites list

### ISSUE THREAD

**Issue by nop** [shedaniel/RoughlyEnoughItems#127]
Favorites on left side of inventory :)

**Comment by shedaniel** [comment]
This could be possible, I am still thinking whether I want to do this or any other ways to do favourites.

**Comment by jivvy** [comment]
I second this. A tab or an option to have a bookmark panel on the left side would be fantastic. Even like a Windows desktop format where you can drag and drop could be cool.

**Comment by shedaniel** [comment]
I am thinking of a pinned items section, I don’t really want to add too much to the already crowded inventory.

**Comment by shedaniel** [comment]
part 1 of world domination is complete, 3 other parts to go.
