### ISSUE TITLE
[Feature] Making Search mode more visually friendly

### ISSUE THREAD

**Issue by jivvy** [shedaniel/RoughlyEnoughItems#128]
**Describe the solution you'd like**
Extending the darkened areas around items that are not found in the inventory to include the borders, it can allow the user to spot items much more quickly! 

Here's a picture:

![image](https://user-images.githubusercontent.com/24281896/61996108-54545600-b056-11e9-9b9b-9ce571d3b18f.png)

Proposed appearance:

![removed-borders](https://user-images.githubusercontent.com/24281896/61996489-6c2dd900-b05a-11e9-80b5-49907987fee6.PNG)

This might be more difficult than it's worth. Maybe you're changing some texture somewhere and you'd have to re-do the system, but if it's simple, then that'd be great :)

**Comment by shedaniel** [comment]
I am currently testing to see if this is viable. If so, this would be a config setting.

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/62766679-9e612100-bac5-11e9-80b0-0b162c9584ce.png)
Simply extending the dark overlay is not viable. If I do want to implement this could potentially break mods not using the vanilla slot textures.
