### ISSUE TITLE
[Feature] Reduced animation in category pagination, for accessibility

### ISSUE THREAD

**Issue by Toadby** [shedaniel/RoughlyEnoughItems#1281]
### What is your feature request?

**Background info**
Hi, I just started playing a modpack* that is using REI version 8.3.571. Since I last used REI, the appearance and behavior of the category panels has been changed.
*I asked the modpack creators and they told me they haven't modified REI on their end, I hope that's correct! It is hard for me to verify because I need a lot of mods installed in order for this issue to come up.

To me it seems like the category list has been turned into a carousel display rather than pagination like it was before, which is noticeable both in the addition of animations when selecting next / previous page, and also in the way the display adjusts to keep the selected tab in the center when possible.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/16440384/208330291-9da5365a-54ca-47a1-90f3-81f9046d938d.png">
<img width="414" alt="image" src="https://user-images.githubusercontent.com/16440384/208330279-bace58a3-6a03-4445-abe4-18bad036957f.png">
Screenshots are two adjacent "pages". The element in the far right of the first screenshot becomes the element on the left of the second picture, in order to justify the selected element to the center. Animations not pictured :)

**The problem**
For me, the changes make this panel disorienting and difficult to use. The fact that the selected panel stays centered means I am constantly having to readjust to the position when changing pages, and the animations are difficult for me to look at. It is hard to avoid because I have to interact with it anytime I want to look up a different kind of recipe

**Suggestion**
I would love to see options to:
1. Disable the animation. Reduced animations are a common accessibility feature, I think this alone would make a big difference.
2. Treat these categories as traditional tabs, which retain their position when switching between them rather than centering the active tab. Also, to leave empty space at the end of the last page if there are not enough tabs to populate the whole UI, rather than aligning everything to the right in a way that also changes the position of the tabs.

This interface would be a lot easier for me to use if the tabs stayed in the same position on their respective pages (obviously excluding cases where a different set / number of tabs are shown) and if the transitions happened instantly rather than sliding / animating in.

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by MaxNeedsSnacks** [comment]
I feel like this should maybe be combined with less animations in other areas of REI (such as favourites) into a single "reduced motion" mode maybe? Since there are some other things like pinning recipes and entries moving due to the screen bounds changing for instance that might also be a bit disorienting
