### ISSUE TITLE
[Bug] Items deleted during click and drag

### ISSUE THREAD

**Issue by Nixill** [shedaniel/RoughlyEnoughItems#1301]
### What happened?

When you click-and-drag items (either button) across multiple slots of an inventory, if you let go atop the item panel, all items that you just placed and that remained on the cursor are deleted.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Logfiles attached, though I'm not quite sure they're necessary here since this isn't a crash and the logs don't seem to mention anything at the time of the incident.
```

### Anything else?

This bug was re-tested from a fresh modpack (i.e. without other mods, default config, default in-game options) but was discovered in a well-used modpack. These log files are from the fresh pack: [rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10322540/rei.log) and [rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10322542/rei-issues.log).

It's also worth noting that Mouse Tweaks (present in the original modpack, not the fresh pack) makes this issue slightly less bad because it treats right-click-and-drag as individual mouse-clicks, so when I discovered this bug with one, I didn't lose quite everything.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Can you record a video illustrating what you mean?

**Comment by Nixill** [comment]
[Here ya go!](https://youtu.be/SJPeOY3Y908)

**Comment by shedaniel** [comment]
I believe that's just the artifact of the cheat mode "Delete Items" feature. I am not sure if that requires fixing.
