### ISSUE TITLE
Effects crash

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1308]
### What happened?

Drink the potion and open the backpack

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
crash-2023-01-02_17.18.02-client
https://pastebin.ubuntu.com/p/pXHfmzHhfj/
latest
https://pastebin.ubuntu.com/p/ZHM3vSy4gP/
rei
https://pastebin.ubuntu.com/p/mdggbjHjfG/
rei-issues
https://pastebin.ubuntu.com/p/H78mppQ5vY/
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ghost** [comment]
It seems that because ([Mini Effects](https://www.curseforge.com/minecraft/mc-mods/mini-effects))

**Comment by shedaniel** [comment]
Caused by Mini Effects, they modify REI and crash. Please check if there are an update to Mini Effects to fix this, otherwise you are out of luck.
