### ISSUE TITLE
[Bug] Missing item names in REI pane.

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#131]
**Describe the bug**
REI is breaking Torcherino's Item names in REI pane.

**Steps to Reproduce**
Just have torcherino install on latest version of rei for 1.14.4

**Screenshots**
Original Item is called "Compressed Torcherino" but it happens for all Torcherino items (except Lanterinos due to their different name)
![Missing Item Name](https://cdn.discordapp.com/attachments/572099498050977840/608935025706008576/unknown.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - Mod Loader: fabric
 - Mod Version: v2.9.7 Build 143

**Logs**
Not applicable.

**Comment by shedaniel** [comment]
Reproduced.

**Comment by shedaniel** [comment]
Semi-solved by adding "appendModNames" in config, I will work on this in the future later
