### ISSUE TITLE
[Feature] Recipe Lookup

### ISSUE THREAD

**Issue by JeremyFredLin** [shedaniel/RoughlyEnoughItems#1310]
### What is your feature request?

1. Create中，可以使用动力搅拌机混合加热制作药水。在JEI中，不同药水的配方是单独显示的（图一）。但在REI中，所有药水都被视作同种液体，就需要在249页中找到需要的那一页（图二）。
2. Create中，沙砾有12%的概率可以被洗涤成铁粒，对沙砾按<kbd>U</kbd>可以查看此配方（图三），但对铁粒按<kbd>R</kbd>，JEI可以查看，REI无法查看此配方（图四）。
![截图 2023-01-04 13-49-35](https://user-images.githubusercontent.com/73016094/210492248-0da257d8-1c77-4aaa-9a9e-a785a04c1598.png)
![截图 2023-01-04 13-48-29](https://user-images.githubusercontent.com/73016094/210492158-1fdcd928-688c-45cd-8e7d-0717c0173678.png)
![截图 2023-01-04 13-54-04](https://user-images.githubusercontent.com/73016094/210492792-90c0edd7-3139-4d43-aeb1-2fc806c3e4e2.png)
![截图 2023-01-04 13-54-26](https://user-images.githubusercontent.com/73016094/210492795-cd672e1b-bfd5-4f2d-b093-fc64370d28da.png)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
First, this is an issue and is wrongly submitted as a feature request.
Second, this issue tracker is English only, not everyone in the world speaks another language.
