### ISSUE TITLE
Incompatible with Mac

### ISSUE THREAD

**Issue by LemmaEOF** [shedaniel/RoughlyEnoughItems#132]
`java.awt` causes Minecraft to freeze when running on mac. All the REI widget classes use `Rectangle`, `Point`, and `Shape`, making the mod unusable on Mac. I would recommend reimplementing the necessary classes inside of REI yourself if you want to keep the same framework.

**Comment by shedaniel** [comment]
Fixing in v3.0-pre, hopefully out in September.
