### ISSUE TITLE
[Bug] (1.18.2) (Forge)

### ISSUE THREAD

**Issue by ACrazyD** [shedaniel/RoughlyEnoughItems#1321]
### What happened?

Theres no recipes - Im working on a new modpack atm, and when i load up there are no recipes when selecting R over any item, modded or Vanilla.. || if i select the tags thingy (That thingy that allows you to see all the recipes from all recipe handlers) The recipes work - But when i press r only some things come up with Tags)

I have already checked to make sure i dont have JEI installed as well.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Only thing i really have are the logs Im linking Below.
```

### Anything else?

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10408007/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10408008/latest.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
`Registered 4506 displays`

Can you make a video explaining and going through the issue?

**Comment by ACrazyD** [comment]
Working on this now, was having an issue of no internet for a few days there

**Comment by ACrazyD** [comment]
Ok NVM I guess, Loaded up my streaming software to start recording even enabled my key thingy that shows what keys im pressing. and it just works now - i love when tech gives me the "Doctors Syndrome" - I guess sorry to waist a very small amount of time there...
