### ISSUE TITLE
[Bug] Startup crash on All the Mods 8 v1.0.8

### ISSUE THREAD

**Issue by KaceCottamLAI** [shedaniel/RoughlyEnoughItems#1327]
### What happened?

Crash during transition from mod loading progress bar -> main menu. I am using Prism Launcher. I disabled everything to do with JEI and confirmed that I can launch without JEI.

Expected: Load into main menu.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
 Description: Rendering overlay  
java.lang.RuntimeException: java.lang.AssertionError: REI Internals have not been initialized!
 Thread: Render thread
Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Minecraft Version: 1.19.2
Java Version: 17.0.5, Eclipse Adoptium
FML: 43.2 	
Forge: net.minecraftforge:43.2.3
```

### Anything else?

* I've tried deleting `forge_common.toml` and `forge_client.toml` in `config` folder. I turned on multithreaded chunk rendering before installing REI.
* I removed Just Enough Items, Just Enough Resources, and Just Enough Professions which is installed by default on ATM8.
* Attached crash log.
[crash-2023-01-15_16.52.44-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/10421702/crash-2023-01-15_16.52.44-client.txt)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by KaceCottamLAI** [comment]
Edit: Removing the `More Overlays Updated` mod seems to resolve this particular crash. Looks to be something with its JEI integration-- even when disabling the search mode in More Overlays' config file results in a crash.

**Comment by shedaniel** [comment]
REI is incompatible with More Overlays, please use Light Overlay, or other mods.
