### ISSUE TITLE
[Feature] Copy a recipe's ID for use in modpack development

### ISSUE THREAD

**Issue by vizthex123** [shedaniel/RoughlyEnoughItems#1333]
### What is your feature request?

JEI has this feature, and it seems REI has an unused keybind for it  (being "middle button" by default).

But, it seems to do nothing. I've changed the keybind too, and it still does nothing.

Would be great if it just copied a recipe's internal ID like JEI does.

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by vizthex123** [comment]
So I figured out you have to click the button over the + icon instead of the output or recipe itself, and the ID is also listed next to said + button.

So, ima change my issue asking that it be more clear: You can hover over the output item or recipe itself to see and copy its ID.

**Comment by shedaniel** [comment]
Sorry it is not explicit in the settings menu. However REI displays the recipe ID over in the + button and not the output item, and there is no good reason to move that to the output item _just because_ you are used to JEI’s output item. (Not every recipe has an output)

I am changing this issue to “Clarify + button usage next to the keybind”

**Comment by vizthex123** [comment]
alright.

also noticed that when rebinding the key after searching for it, it'll rebind the "hide overlay" keybind instead.

**Comment by shedaniel** [comment]
I am moving it to #1378
