### ISSUE TITLE
[Bug] Crash when trying to craft animalnet item (java.lang.ArithmeticException: / by zero) 

### ISSUE THREAD

**Issue by calloatti** [shedaniel/RoughlyEnoughItems#134]
**Describe the bug**

Crash when clicking on the "+" button when trying to craft an animalnet "Medium Animal Net" when the player does not enough iron to make the craft.

Also notice some crafting ingredients do not show on the screenshot.

**Steps to Reproduce**

1. Have all the items to craft an animalnet "Medium Animal Net"  in the inventory except iron
2. Search for the  "Medium Animal Net"
3. Click the + button
4. Crash

Note: If you have enough iron, it does not crash.

**Screenshots**

![2019-08-17_15 05 04](https://user-images.githubusercontent.com/12817862/63215672-7e9eae00-c100-11e9-8ed7-52e5e49fd405.png)

![2019-08-17_14 56 27](https://user-images.githubusercontent.com/12817862/63215631-f3bdb380-c0ff-11e9-84f1-4a8afb0fa205.png)

Having Iron does not crash:
![2019-08-17_14 56 49](https://user-images.githubusercontent.com/12817862/63215629-ee606900-c0ff-11e9-824b-a6b478b112d2.png)

How the recipe should look:

![image](https://user-images.githubusercontent.com/12817862/63215701-da693700-c100-11e9-9e2d-9510d05b49d9.png)

How it actually looks like:

![image](https://user-images.githubusercontent.com/12817862/63215704-e523cc00-c100-11e9-94d2-041262cd593d.png)

**Environment (please complete the following information with the version):**

AOF-Strawberry 2.3.0

Connected to EU server

**Logs**

https://paste.ee/p/vdD2u

**Additional context**

Don't know if this is REI or AnimalNet

https://github.com/AllOfFabric/AOF-Strawberry/releases/tag/2.3.0

https://www.curseforge.com/minecraft/mc-mods/animalnet

**Comment by calloatti** [comment]
Same thing happens with other items from the same mod.

**Comment by shedaniel** [comment]
I would say that this is related to the datapack syncing issue in AoF, like sometimes you can’t join in AoF. Because this happens randomly with random recipes having disappearing items.
