### ISSUE TITLE
[Bug] REI 10.0.586 Not compatible with Architectury 8.0.67

### ISSUE THREAD

**Issue by Jack-Works** [shedaniel/RoughlyEnoughItems#1341]
### What happened?

Cannot start. Minecraft 1.19.3

![image](https://user-images.githubusercontent.com/5390719/214208726-d2a6c6ba-9b91-4a08-9069-6837beea2e87.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Architectury 8.0 is for 1.19.4, you have downloaded the wrong version of architectury

**Comment by Jack-Works** [comment]
oh, I don't know 1.19.4 is out. thanks!
