### ISSUE TITLE
[Bug] Search bar inactive

### ISSUE THREAD

**Issue by Abalieno** [shedaniel/RoughlyEnoughItems#1342]
### What happened?

(this on latest REI, 1.19.2 fabric)

Whenever I right click on the search bar to delete what's there and type something else, I can't. I press keys and nothing is written on the search bar, even if I right click into it and it is in focus.

I need to exit inventory and open it again to be able to use it.

Similar, but unrelated problems: very often when I go hover on a item on the right panel, I press "R" to look up the recipe... nothing happens. Same for "U". I have to left click on the item, to "wake it up", and then all shortcuts start working again.

Another similar issue is with the left and right buttons on the recipe tabs (the big ones to switch between different machines). Sometime they get stuck. I can use the mouse wheel to move around, but the buttons don't work. It seems this is fixed with the "compact" style of those buttons.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
I don't think there's any.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Abalieno** [comment]
The issue of right clicking on the search bar and being unable to type in it seems related to the presence of EMI.

But since neither is fully compatible, I have to keep both, and use shortcuts to enable one or the other. Even if this appears to be a mod conflict, it should be solved. EMI UI is disabled, I right click on REI search bar and the input is properly cleared, and I see a blinking cursor. But what I type ends up on the EMI search bar, even if it's hidden and the output only shows up after I enable it again.

I suppose the shortcut not working on items may be related to a similar focus issue.

**Comment by shedaniel** [comment]
You know keeping both is a hack in the first place. There is no good way for us to fix this issue, either REI or EMI gets to cancel the key press action.

Choose one of us, it doesn’t matter which one you choose, this is just unfixable.

**Comment by Abalieno** [comment]
"Unfixable" but apparently fixed: https://github.com/emilyploszaj/emi/issues/140

"Choose one of us" is not a choice in a modpack.

**Comment by shedaniel** [comment]
/shrug
it isn’t unreasonable to say it is unfixable and rather unreasonable to expect both of them to work, you can fix one but there will always be more incompatibilities
mods generally expect one of the mods present, for example, implementing a search field sync function for emi / rei, mods would need to consider the situation where both of them are present and that’s simply dumb
**imo: rei and emi launching without crashing is already good enough**

unfortunately, it is a choice, and you base your mods around that choice, there are many mods with only rei support, and also mods with only emi support, it is not a good user experience to have both installed, or i mean you can go with the third choice jei \*wink*

im not even forcing you to use rei, just choose one or stop putting expectations that both should work at the same time

**Comment by Abalieno** [comment]
I don't see any incompatibilities, practical or theoretical.

I use shortcuts to swap between EMI and REI. They are not active at the same time. If I have one off and the other on, then only one set of shortcuts have to be active. In this case it was EMI catching focus when it was disabled, it's clearly a bug. Shortcuts should always be contextual. Shortcuts that work in the inventory screen don't need to be active outside of it, and this is a similar issue.

And yes, the choice to play or not to play. It's not an useful argument. Mods are already divided by minecraft version, forge/fabric, fabric/quilt, often also by shared libs with breaking changes like geckolib or porting lib (right now Twilight Forest doesn't work with Create).

If now we have a split even for recipe browsers, what's left? There's always choice. It still doesn't mean that this way of proceeding is reasonable.

**Comment by shedaniel** [comment]
just because _you_ don't see any incompatibilies doesn't mean there aren't any
for example, this is a piece of code in AE2 with its dual support for JEI and REI:
```java
public static String getExternalSearchText() {
    if (JEIFacade.instance().isEnabled()) {
        return Strings.nullToEmpty(JEIFacade.instance().getSearchText());
    } else if (REIFacade.instance().isEnabled()) {
        return Strings.nullToEmpty(REIFacade.instance().getSearchText());
    } else {
        return "";
    }
}
```
when both JEI and REI is present, which text does AE2 choose to copy?
to make sure things work, you would need mods to consider this use case, which is unpractical for most

it is not my fault if EMI catches all inputs.
it is neither REI's and EMI's fault there is a rift between recipe viewers

i don't understand the drama between fabric and quilt and frankly do not care at all
just don't blame us for the recipe viewers split

anyways, i play forge, use whatever you want, my answer on this thread will end here, i don't have the energy

**Comment by Abalieno** [comment]
Actually there's something on your end I just found out.

You also should check the "hide/show REI" shortcut on other keypresses like "show uses" and "show recipes". As I said, shortcuts should be contextual. So REI shouldn't keep those shortcuts active when REI itself isn't shown. (Or put it behind a custom toggle for some edge cases)

Right now even with REI turned off, it still keeps active "R" and "U". Either by default or as an option their logic should depend on whether or not NEI is shown/hidden.

(piece of code above simply tells me they should not be a concatenation of conditions. Just because there can be incompatibilities doesn't mean that things shouldn't be fixed and improved with practical use cases)

**Comment by shedaniel** [comment]
the rei key system is designed to respect R and U even if it is invisible, the O button is “toggle overlay”, and this wording is present in the source code as well
R and U and the corresponding recipe viewer is not a part of the overlay, and i think it is beneficial if someone wanted to use rei without the overlay

no one had complained about rei respecting r and u when the overlay is hidden, your case is the exception, rei shouldn’t be making an assumption that you have another recipe viewer

again, you are expecting too much of mod developers, we have lives, yours truly are an exception to most cases and mods shouldn’t really need to design for your use case
