### ISSUE TITLE
[Feature] Ignore cheat mode being enabled when no permission

### ISSUE THREAD

**Issue by whitebear60** [shedaniel/RoughlyEnoughItems#1349]
### What is your feature request?

I propose of automatically disabling cheat mode on servers when you have no permission (yellow gear), possibly by ignoring the cheat mode being enabled on those conditions (while preserving it being enabled when you have permissions or in singleplayer with cheats on)

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
I don't believe this is a good suggestion.
This would just cause confusion to players thinking otherwise.
It should be easy to toggle cheat mode, or use the "Cheat when Creative" option in the config menu.

Please tell if I misunderstand your suggestion.

**Comment by whitebear60** [comment]
Probably you've understood me correctly... My point was that there is no point in trying to cheat items, if we have no permission to do that, so instead show the recipe on click, just as we did if the cheating was disabled...
Probably the Cheat only when in creative setting does roughly the same thing, so...
________________________________
