### ISSUE TITLE
[Bug] Load crash

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1357]
### What happened?

Load crash

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
latest.log
https://gist.github.com/FanRenLa/d2b609a2a1d4b3dffa5a43e1e9a0e21f
crash-2023-02-09_15.53.30-server.txt
https://gist.github.com/FanRenLa/e0ed856e4d5aee5503ce6a2d0b70fae5

rei.log
https://gist.github.com/FanRenLa/97ae976af70997e599b87641fe616489
rei-issues.log
https://gist.github.com/FanRenLa/f153b641f4ee35460c55898da160d7be
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ghost** [comment]
RoughlyEnoughItems-9.1.587.jar
REIPluginCompatibilities-forge-9.0.44.jar

**Comment by shedaniel** [comment]
I don't really believe this is the case.
REI doesn't really do much on servers, please try without REI.

**Comment by shedaniel** [comment]
I am closing the issue because the question was not answered and this issue has became stale. Please re-open this issue if it persists.
