### ISSUE TITLE
[Feature] Back Keybind on recipe

### ISSUE THREAD

**Issue by shedaniel** [shedaniel/RoughlyEnoughItems#136]
**Describe the solution you'd like**
Pressing backspace should bring you back to the previous recipe.

**Comment by NightOps007** [comment]
@shedaniel Why'd you close this? It doesn't seem to be implemented yet. I think it's a very useful feature to have, ability to see the previous recipe even after looking into another. This way I can quickly come back from looking at component recipes for a complicated item. Any chance I'll see this in the future? Or did I miss it somewhere?

**Comment by shedaniel** [comment]
it's added, press backspace, please open a new issue if you want this to be configurable
