### ISSUE TITLE
[Feature] vision

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1361]
### What is your feature request?

![image](https://user-images.githubusercontent.com/83486178/218496962-1fc53dc2-6e1d-4beb-92f4-0e3b3ee5220b.png)
![image](https://user-images.githubusercontent.com/83486178/218497516-56d512cd-cca8-42de-80e0-d939ff57aef4.png)
Can we make this annoying thing go away?

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by ghost** [comment]
forge1.19.2
Not sure if other versions have it

**Comment by shedaniel** [comment]
the first option of 
![](https://user-images.githubusercontent.com/83486178/218497516-56d512cd-cca8-42de-80e0-d939ff57aef4.png)
