### ISSUE TITLE
[Bug] Some items have no name in REI

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#1362]
### What happened?

![image](https://user-images.githubusercontent.com/15698722/218923120-1139e08b-53e9-4fca-af74-1e39069c1008.png)
![image](https://user-images.githubusercontent.com/15698722/218923131-a00b0547-2d53-4f37-bb1c-6995a1316b23.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/80771012ca0ec025aff829c56a1e4582
https://gist.github.com/53c1dfd3dcacbff85b879dcbc053955c
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/218977069-fcfd3443-d593-431a-a70b-d2e13df949fb.png)
found another one

**Comment by MaxNeedsSnacks** [comment]
This happens when the item name is equal to the mod's display name. I was sure I'd reported this ages ago, but I guess not...?
