### ISSUE TITLE
[Bug] Black text on dark mode for villager professions

### ISSUE THREAD

**Issue by nsde** [shedaniel/RoughlyEnoughItems#1366]
### What happened?

When enabling dark mode in the REI settings, searching for “Villager” in REI and right-clicking the first result, the profession list seems to have the wrong color:
![image](https://user-images.githubusercontent.com/67185896/219788175-cc74ecf5-05c9-4b38-99a1-61b3f30fa6f2.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
-
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
This is impossible to fix for JEI plugins, JEI plugins do not expect dark mode and REI does not handle rendering the text for them.
