### ISSUE TITLE
[Bug] Pinned Recipes with JEI integration doesn't position correctly

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1375]
### What happened?

Move items message stick on the cursor when i have not full materials for pinned recipe

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
1
```

### Anything else?

![image](https://user-images.githubusercontent.com/51258962/222616148-0616709c-aef9-410e-947d-48c45afaa7fb.png)
cant send logs in pole above so : 
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10877615/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10877616/rei-issues.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/10877617/latest.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [x] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
I believe this is fixed on REIPC's side.
