### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rogenar** [shedaniel/RoughlyEnoughItems#1386]
### What is your feature request?

The names and constructions that come with 2 mods are the same. There are 2 nether star blocks with different types. I want to do the nether star block that comes with advanced combat. Because a special sword can be made with that block. The other nether star block is a block added by the blockus mod. I can't craft the special sword with that block. When I want to produce it, it produces the nether star block brought by the blockus mode. It does not produce the nether star block brought by the Advanced Combat mod. How can I craft the block I want even though the two items have the same recipe?

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
What? How does this have anything to do with REI?
