### ISSUE TITLE
[Bug] Can't write in search bar

### ISSUE THREAD

**Issue by Zano1999** [shedaniel/RoughlyEnoughItems#1402]
### What happened?

I can't write in the search bar, when I click on it to write the bar is selected but nothing happens if I write, strangely I can only enter text with CTRL+V

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Nothing new happening in the logs when i try to write
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by mosquitobird11** [comment]
I have this as well :( 
my mods:
![image](https://user-images.githubusercontent.com/10202766/236376862-05b871bd-1864-4bf2-a84b-f9c59debeec2.png)

**Comment by mosquitobird11** [comment]
Weird, through process of removing and adding mods, I have determined that REI is broken with optifine + optifabric

**Comment by shedaniel** [comment]
REI is not compatible with optifine. The general consensus with optifabric is that _if it works, it works, if it doesn't work, then too bad_.
Optifine is not open sourced, we cannot fix it.
