### ISSUE TITLE
Server Cant Sync

### ISSUE THREAD

**Issue by TysonTheEmber** [shedaniel/RoughlyEnoughItems#1407]
### What happened?

The server wont sync with the client and this is the log 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
[01:45:11] [Netty Epoll Server IO #4/ERROR]: Error receiving packet 106
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at net.minecraft.class_2540.method_10812(class_2540.java:638) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:179) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Anything else?

[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Sound Physics Remastered](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Small Ships [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Collective](https://www.curseforge.com/minecraft/mc-mods/collective)
[Starter Kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[Rotten Creatures](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[Better Third Person](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[o?o (owo-lib)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Fabric Waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[Cloth Config API (Fabric/Forge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[You're in Grave Danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[playerAnimator](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Explorify](https://www.curseforge.com/minecraft/mc-mods/explorify)
[Towns and Towers](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[TerraBlender](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[CorgiLib](https://www.curseforge.com/minecraft/mc-mods/corgilib)
[Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
[Architectury API (Fabric/Forge)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Epic Knights: Shields Armor and Weapons [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)
[YUNG's API](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[YUNG's Better Dungeons](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric)
[YUNG's Extras](https://www.curseforge.com/minecraft/mc-mods/yungs-extras-fabric)
[YUNG's Better Ocean Monuments](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
[Origins](https://www.curseforge.com/minecraft/mc-mods/origins)
[Iceberg](https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric)
[Prism](https://www.curseforge.com/minecraft/mc-mods/prism-fabric)
[Forge Config API Port](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips-fabric)
[Biome Music[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Goblin Traders [Fabric]](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric)
[ThonkUtil](https://www.curseforge.com/minecraft/mc-mods/thonkutil)
[End Goblin Traders (Fabric)](https://www.curseforge.com/minecraft/mc-mods/end-goblin-traders-fabric)
[Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Kambrik](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)
[Combat Roll](https://www.curseforge.com/minecraft/mc-mods/combat-roll)
[Enhanced Celestials](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric)
[Data Attributes](https://www.curseforge.com/minecraft/mc-mods/data-attributes)
[PlayerEx](https://www.curseforge.com/minecraft/mc-mods/playerex)
[The Graveyard (FABRIC)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric)
[Marium's Soulslike Weaponry](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry)
[Droplight](https://www.curseforge.com/minecraft/mc-mods/droplight)
[End Remastered](https://www.curseforge.com/minecraft/mc-mods/endremastered-fabric)
[Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Medieval Origins](https://www.curseforge.com/minecraft/mc-mods/medieval-origins)
[Integrated API](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[Create Fabric](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)
[Integrated Stronghold](https://www.curseforge.com/minecraft/mc-mods/integrated-stronghold)
[Eldritch Mobs](https://www.curseforge.com/minecraft/mc-mods/eldritch-mobs)
[Simply Swords [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Structory: Towers](https://www.curseforge.com/minecraft/mc-mods/structory-towers)
[RelicEx](https://www.curseforge.com/minecraft/mc-mods/relicex)
[The Lost Castle](https://www.curseforge.com/minecraft/mc-mods/the-lost-castle-fabric)
[Zenith](https://www.curseforge.com/minecraft/mc-mods/zenith)
[Projectile Damage Attribute](https://www.curseforge.com/minecraft/mc-mods/projectile-damage-attribute)
[Dungeon Difficulty](https://www.curseforge.com/minecraft/mc-mods/dungeon-difficulty)
[Mo' Structures](https://www.curseforge.com/minecraft/mc-mods/mo-structures)
[Item Borders](https://www.curseforge.com/minecraft/mc-mods/item-borders-fabric)
[Library Ferret - Fabric](https://www.curseforge.com/minecraft/mc-mods/library-ferret-fabric)
[Awesome Dungeon Nether edition - Fabric](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-fabric)
[Awesome Dungeon - Fabric](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-fabric)
[Awesome Dungeon The End edition - Fabric](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-fabric)
[Wavey Capes](https://www.curseforge.com/minecraft/mc-mods/waveycapes)
[Origins: Classes](https://www.curseforge.com/minecraft/mc-mods/origins-classes)
[Extra Classes - Origins](https://www.curseforge.com/minecraft/mc-mods/extra-classes-origins)
[The Impossible Library](https://www.curseforge.com/minecraft/mc-mods/the-impossible-library)
[Music Triggers](https://www.curseforge.com/minecraft/mc-mods/music-triggers)
[Better Villages - Fabric](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric)
[Hopo Better Ruined Portals](https://www.curseforge.com/minecraft/mc-mods/hopo-better-ruined-portals)
[SpoornPacks](https://www.curseforge.com/minecraft/mc-mods/spoornpacks)
[myLoot](https://www.curseforge.com/minecraft/mc-mods/myloot)
[On A Stick](https://www.curseforge.com/minecraft/mc-mods/onastick)
[Rhino](https://www.curseforge.com/minecraft/mc-mods/rhino)
[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Resourceful Config](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Creeper Overhaul](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)
[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)
[? Frame API](https://www.curseforge.com/minecraft/mc-mods/frame-api)
[? Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs)
[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend)
[MidnightLib](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Guard Villagers (Fabric/Quilt)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric)
[When Dungeons Arise - Fabric!](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
[Dawn API](https://www.curseforge.com/minecraft/mc-mods/dawn)
[Stoneholm, Underground Villages (Fabric)](https://www.curseforge.com/minecraft/mc-mods/stoneholm)
[This Rocks!](https://www.curseforge.com/minecraft/mc-mods/this-rocks)
[Sky Villages](https://www.curseforge.com/minecraft/mc-mods/sky-villages-fabric)
[Awesome Dungeon Ocean edition - Fabric](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-fabric)
[Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Sodium Extra](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Reese's Sodium Options](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Indium](https://www.curseforge.com/minecraft/mc-mods/indium)
[Memory Leak Fix](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[BetterF3](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Roughly Enough Items (REI)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Do a Barrel Roll](https://www.curseforge.com/minecraft/mc-mods/do-a-barrel-roll)
[Plasmo Voice](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice)
[Geckolib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Deeper and Darker](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Eating Animation [Fabric]](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[When Dungeons Arise](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Applied Energistics 2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[Farmer's Delight [Fabric]](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Botarium](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Resourceful Lib](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Resourceful Config](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Ad Astra](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Jade ?](https://www.curseforge.com/minecraft/mc-mods/jade)
[Chunks fade in](https://www.curseforge.com/minecraft/mc-mods/chunks-fade-in)
[Towns and Towers](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Essential Commands](https://www.curseforge.com/minecraft/mc-mods/essential-commands)
[Cardinal Components API](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Bosses of Mass Destruction](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction)
[CameraOverhaul](https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul)
[Roughly Enough Loot Tables](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-loot-tables)
[Pick Your Poison ?](https://www.curseforge.com/minecraft/mc-mods/pick-your-poison)
[Impaled](https://www.curseforge.com/minecraft/mc-mods/impaled)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement)
[Auto Config Updated API](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api)
[Iron Jetpacks Fabric](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks-fabric)
[Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization)
[Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution)
[Reborn Core](https://www.curseforge.com/minecraft/mc-mods/reborncore)
[Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn)
[Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor)
[Gobber [FABRIC]](https://www.curseforge.com/minecraft/mc-mods/gobber-fabric)
[Fastload](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Entity Collision FPS Fix](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric)
[CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Simple Copper Pipes](https://www.curseforge.com/minecraft/mc-mods/simple-copper-pipes)
[Alloy Forgery](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery)
[Mythic Metals](https://www.curseforge.com/minecraft/mc-mods/mythicmetals)
[Create Crafts & Additions](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Cultural Delights [Fabric]](https://www.curseforge.com/minecraft/mc-mods/cultural-delights-fabric)
[Farmer's Knives [Fabric]](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
[Origins Extra Keybinds](https://www.curseforge.com/minecraft/mc-mods/origins-extra-keybinds)
[Brewin' And Chewin' [Fabric]](https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric)
[Puzzles Lib](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Visual Workbench](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Powah! (Rearchitected)](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected)
[AE Additions - ExtraCells2 Fork](https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork)
[Create Slice & Dice](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[CreateFabric&REIBugFix](https://www.curseforge.com/minecraft/mc-mods/createfabricreibugfix)
[Craftify](https://www.curseforge.com/minecraft/mc-mods/craftify)
[Model Gap Fix](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix)
[AmbientSounds](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Better Ping Display [Fabric]](https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric)
[ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)
[Drip Sounds (Fabric)](https://www.curseforge.com/minecraft/mc-mods/dripsounds-fabric)
[Extended Drawers](https://www.curseforge.com/minecraft/mc-mods/extended-drawers)
[Immersive Paintings](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Balm](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[Inv View](https://www.curseforge.com/minecraft/mc-mods/inv-view)
[NoRecipeBook (Fabric)](https://www.curseforge.com/minecraft/mc-mods/norecipebook-fabric)
[Universal Ores](https://www.curseforge.com/minecraft/mc-mods/universal-ores-fabric)
[Crops Love Rain](https://www.curseforge.com/minecraft/mc-mods/crops-love-rain)
[Enderscape](https://www.curseforge.com/minecraft/mc-mods/enderscape)
[Almost Unified](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[FerriteCore](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Runelic](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Pig Pen Cipher](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Dark Utilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Lithium (Fabric)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Simply Light](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[FTB Library (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[FTB Essentials (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)
[CleanCut](https://www.curseforge.com/minecraft/mc-mods/cleancut)
[AdventureZ](https://www.curseforge.com/minecraft/mc-mods/adventurez)
[HT's TreeChop](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Illuminations ?](https://www.curseforge.com/minecraft/mc-mods/illuminations)
[Roughly Enough Professions (REP)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-professions-rep)
[FTB Teams (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
[Item Filters](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[FTB Quests (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric)
[Polymorph (Fabric)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Leaves Be Gone](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
[NetherPortalFix (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix-fabric)
[Roughly Enough Trades](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-trades)
[Expanded Delight [Fabric]](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Medieval Music[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/medieval-music)
[Nether's Delight (Fabric)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric)
[Farmer's Respite (Fabric)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric)
[Measurements](https://www.curseforge.com/minecraft/mc-mods/measurements)
[Ponder for KubeJS](https://www.curseforge.com/minecraft/mc-mods/ponder)
[Advancement Plaques [Fabric]](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques-fabric)
[Configured (Fabric)](https://www.curseforge.com/minecraft/mc-mods/configured-fabric)
[Nicer Skies](https://www.curseforge.com/minecraft/mc-mods/nicer-skies)
[ItemPhysic Lite](https://www.curseforge.com/minecraft/mc-mods/itemphysic-lite)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Armor Points ++](https://www.curseforge.com/minecraft/mc-mods/armorpoints)
[Tom's Simple Storage Mod (Fabric)](https://www.curseforge.com/minecraft/mc-mods/toms-storage-fabric)
[Modern Dynamics](https://www.curseforge.com/minecraft/mc-mods/modern-dynamics)
[Piercing Paxels](https://www.curseforge.com/minecraft/mc-mods/piercing-paxels)
[Greedy Grinding Mod - Avaritia (Fabric)](https://www.curseforge.com/minecraft/mc-mods/avaritia-port-fabric)
[Beacon Overhaul](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul)
[Player Skills](https://www.curseforge.com/minecraft/mc-mods/player-skills)
[Mob Skills](https://www.curseforge.com/minecraft/mc-mods/mob-skills)
[Item Skills](https://www.curseforge.com/minecraft/mc-mods/item-skills)
[Block Skills](https://www.curseforge.com/minecraft/mc-mods/block-skills)
[Dimension Skills](https://www.curseforge.com/minecraft/mc-mods/dimension-skills)
[Fluid Skills](https://www.curseforge.com/minecraft/mc-mods/fluid-skills)
[Connectivity[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Server Performance - Smooth Chunk Save[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Bountiful (Fabric)](https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric)
[Inventory Sorting](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [x] Yes

**Comment by shedaniel** [comment]
This is not caused by REI. See if your vanilla recipe book is populated with recipes, if it is not, then it is not REI's fault. REI relies on the vanilla recipe book's recipes, and have nothing to do with if it fails to load. Some other mods may be invoked.
