### ISSUE TITLE
[Feature] Migrate JEI Utilities Features

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1410]
### What is your feature request?

Please see Martmists-GH/fabric-mod-wishlist#115!

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by MaxNeedsSnacks** [comment]
Let's address these 1 by 1:

The view history feels like a good enough feature to add (though I'd say you should be able to disable it, or even have it disabled by default), and in principle you can already skip to recently viewed displays by pressing BACKSPACE in your inventory iirc

Recipe recording is already sort of implemented through pinning recipes, which in 8.4 will be able to be minimised down to just their output entries. Recipe preview is also already a thing, albeit slightly differently, in that it will just show the first recipe with matching ingredients for any given favourite entry (if it exists); then again, in tandem with pinned recipes this basically allows for the same functionality.  The `CTRL + W` shortcut to allow for instant transfer from such minimised displays is probably a good idea though. And as for bookmark resorting, this is trivial in REI as all favourite entries are draggable by default

**Comment by shedaniel** [comment]
I think this is a good idea, can you consider splitting this into different suggestions and opening different issues for each, of course, exclude the ones that already exist in REI.

**Comment by ghost** [comment]
> I think this is a good idea, can you consider splitting this into different suggestions and opening different issues for each, of course, exclude the ones that already exist in REI.

Sure thing, though I'll have to put effort into making sure a feature doesn't already exist in REI, as I'm not completely aware of all existing functionality.

EDIT: Didn't see Max's original reply. That helps a lot!

**Comment by ghost** [comment]
Alright, these have been migrated to separate issues.

May I also ask - does REI have an item ghosting feature? It allows you to click and drag item 'ghosts' out from the results pane to slots that hold 'ghost' items, such as filter slots. When you click and drag the item out it also draws this cool graphical line between your cursor holding the 'ghost' copy, and the item entry that you originally clicked on.

**Comment by shedaniel** [comment]
We do have a ghost ingredients system. It is a part of the comprehensive drag and drop system where you can drag items and drop them into accepted components, i.e. ghost slots or the favourites panel on the left, this also allows reordering the favourites.
The entire system is used in many corners of REI

**Comment by ghost** [comment]
> We do have a ghost ingredients system. It is a part of the comprehensive drag and drop system where you can drag items and drop them into accepted components, i.e. ghost slots or the favourites panel on the left, this also allows reordering the favourites.
The entire system is used in many corners of REI

Awesome, thanks. Been too busy to setup my own test environment and figured it was easier to ask!

**Comment by shedaniel** [comment]
I am going to close this issue because the recommendations have been split into several smaller issues.
