### ISSUE TITLE
[Feature] Recipe Transfer

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#1413]
### What is your feature request?

# Overview

This is a feature originally contributed by [JEI Utilities](https://www.curseforge.com/minecraft/mc-mods/jei-utilities), which unfortunately has not been updated past 1.12. There are also some potential improvements over the original implementation that I would like to suggest.

# Features

## From JEI Utilities
- [ ] You can press `ctrl + w` to quick-transfer a recipe from the recipe bookmark.

## REI-Exclusive
- [ ] Configurable binding?

---

_Note: Issue derived from #1410_

---

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
This is already a feature in REI. If you have enough ingredients, you can ctrl click to quick craft.
I believe REI had this feature before JEI Utilities did.

**Comment by ghost** [comment]
Ah, all good, wasn't aware. 😋
