### ISSUE TITLE
[Bug] Water and lava are useless

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#142]
**Describe the bug**
3.0 pre1 added the following items:
- Flowing Water
- Water
- Lava
- Flowing Lava

However, they cannot be given to the user nor do they show any relevant recipes. So why do they exist?

**Steps to Reproduce**
- Enable cheating
- Click on the items
- Nothing happens

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft 1.14.4
 - Mod Loader: Fabric 0.4.8 b 155

**Logs**
N/A

**Additional context**
N/A

**Comment by shedaniel** [comment]
I rushed this update out, real functionality would probably be added in 1.15 snapshots.
