### ISSUE TITLE
[Bug] Recipe Exporting not working

### ISSUE THREAD

**Issue by Noaaan** [shedaniel/RoughlyEnoughItems#1431]
### What happened?

Recipe exports do not produce real images, and do not throw any errors. 
Example recipe:
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/4163353/8609577c-605c-4c60-91d1-70acb25c720c)

Should produce the recipe, instead produces image linked below:
https://github.com/shedaniel/RoughlyEnoughItems/assets/4163353/f275cbea-7a7b-400f-8893-c9acd771bce9

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [x] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
No relevant log output, the action is completed without errors.
```

### Anything else?

Tested with REI build 12.0.622 and 12.0.625, running architechtury 9.0.5 and cloth 11.0.99

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by ByFe** [comment]
Same here with version 12.0.626 with architectury 9.1.10 and cloth config 11.1.106

**Comment by Luligabi1** [comment]
+1 on `REI 12.0.645` + `Architectury 9.1.12`

**Comment by 4nyNoob** [comment]
also on `architectury-fabric:9.1.12` `cloth-config-fabric:11.1.106` `RoughlyEnoughItems-fabric:12.0.652`

**Comment by Noaaan** [comment]
While I do not have a solution currently, I have identified that the issue is caused by the common code present in the `RecipeDisplayExporter`. This can be confirmed by the fact that this doesn't work on Forge either. Messing around with it it seems that the items are now being flipped and translated off-screen, and not correctly aligned. Simply put - the items and GUI for the recipe aren't inside the buffer, so they are not drawn correctly before exporting.

The code for copying the image is fine, so the culprit is in the attached source code below:
https://github.com/shedaniel/RoughlyEnoughItems/blob/3dc4238eb7a61a992d37a98b9035a9101c022f42/runtime/src/main/java/me/shedaniel/rei/impl/client/gui/RecipeDisplayExporter.java#L80-L105

**Comment by purejosh** [comment]
+1
