### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by ilobilo** [shedaniel/RoughlyEnoughItems#1437]
### What is your feature request?

Could you update this mod to 1.20.1?

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by rozbrajaczpoziomow** [comment]
It is on 1.20(.1)
