### ISSUE TITLE
[Feature] Villager recipe GUI should use villager GUI textures

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#144]
**Describe the solution you'd like**
I do think that the villager recipe view is unique to REI, so it is not very likely that resource pack makers want to add support for it. 
But since it looks very similar to the actual villager GUI, why not use the textures from it too? With tabs from creative inventory GUI.

Edit: I didn't quite think this through as the GUIs actually look rather different, however what could still be used are the **wide buttons on the left**.

**Additional context**
Related: #113

**Comment by shedaniel** [comment]
REI's selection of textures is far from vanilla's texture. If I use vanilla's, this will break more stuff.
