### ISSUE TITLE
[Bug] Search bar not able to be typed in.

### ISSUE THREAD

**Issue by TinyCoderJay** [shedaniel/RoughlyEnoughItems#1441]
### What happened?

Whenever I type into the REI Search bar on 1.19.4, it shows the blinking text line, but will not let me type into the bar. No matter what I put.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Won't let me paste.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment]
If you aren't able to paste it here then throw it in https://gist.github.com/ and paste the url to it

**Comment by SaiKhunNunPha** [comment]
I've discovered what's wrong. For some reason, having the Optifabric and Optifine mods installed with the REI fabric version prevents you from typing anything into the search field. We just need to wait for a fix soon.

**Comment by tamimd67** [comment]
> I've discovered what's wrong. For some reason, having the Optifabric and Optifine mods installed with the REI fabric version prevents you from typing anything into the search field. We just need to wait for a fix soon.

Well, it is August 19th and I am still having the issue of not being able to type in the REI search field.

**Comment by shedaniel** [comment]
Unfortunately, Optifabric is not supported with REI. It is impossible to test with Optifine, it is closed source, invasive, and not well maintained.
