### ISSUE TITLE
[Bug] Crash when open inventory (E)

### ISSUE THREAD

**Issue by mlengka93** [shedaniel/RoughlyEnoughItems#146]
**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - Mod Loader: fabric + Fabric API 0.3.1+build.208
 - REI version: [Fabric 1.14.x] v3.0-pre Build 2

**Logs**
https://pastebin.com/4mV0dcT7

**Comment by shedaniel** [comment]
REI 3.0 requires Cloth Config 1.0.0

**Comment by mlengka93** [comment]
i can't download from bintray com (time out, maybe my country blocked it), curseforge file latest only 0.5.3 pls add to curseforge

**Comment by drcrazy** [comment]
You shouldn't. Cloth config bundled with REI, or at least should be. Can you try to disable or remove cloth-config from your mods folder and try to launch it again?

**Comment by shedaniel** [comment]
Also uploaded Cloth Config to CF if you want it for whatever reason. (I forgot to)
