### ISSUE TITLE
[Feature] Disable JEI Compat for specific mod (Code wise)

### ISSUE THREAD

**Issue by Flemmli97** [shedaniel/RoughlyEnoughItems#1482]
### What is your feature request?

I would like a way to disable JEI compat for certain mods. I've wanted to include both jei + rei support in my mod but that caused some issues as rei is attempting to parse the jei integration part of my mod which causes it to cast `me.shedaniel.rei.jeicompat.wrap.JEIWrappedDisplay` to the rei display. 
A way to prevent rei to enable jei compat for a mod would be nice.

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Please follow this comment: https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/23#issuecomment-1332489186
