### ISSUE TITLE
[Bug] 2x2 recipes fail on crafting table

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#149]
**Describe the bug**
Recipes that take the 4x4 space work incorrectly when used in a crafting table via REI crafting system.

**Steps to Reproduce**
1. Obtain materials for a 4x4 recipe (e.g 4 wooden planks)
2. Open a crafting table
3. Open a recipe that uses items in 4x4 position (e.g. crafting table)
4. REI places items incorrectly:

```
1 2          1 2 3
3 4 becomes  4
```

**Screenshots**
![wrong](https://user-images.githubusercontent.com/8611110/63653007-e0e65700-c76f-11e9-835d-bc0b7e55f062.png)

**Environment (please complete the following information with the version):**
 - Minecraft 1.14.4
 - Fabric API 0.3.1 b 208
 - REI 3.1 pre-b 4

**Logs**
N/A

**Additional context**
N/A

**Comment by shedaniel** [comment]
Does it only happen on build 4?

**Comment by Madis0** [comment]
Haven't tested on other builds.

**Comment by shedaniel** [comment]
This fix caused an error: https://paste.ee/p/o2lhj
