### ISSUE TITLE
[Bug] Move Items button (+) places ingredients on the wrong slots

### ISSUE THREAD

**Issue by p3lim** [shedaniel/RoughlyEnoughItems#1492]
### What happened?

Happens with any recipe in a crafting table:
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/26496/bd94d3c4-ca40-412a-a016-f13f278b7710)
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/26496/f31fc243-45b4-4bf4-ae6b-a64b50a26a23)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
no log output
```

### Anything else?

Version 9.1.650 (latest available on modrinth for 1.19.2)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Pootleris** [comment]
same here porcodio

**Comment by dPandl** [comment]
This happens to me too

**Comment by Authrec** [comment]
I get this issue using REI 12.0.652, but downgrading to 12.0.648 the issue is no longer present.

**Comment by IWaltherI** [comment]
This problem also happened on version 1 18 2 forge. On the old version that I had for a long time - 8 3 6 42 - there is no such thing. And the thing is exactly in version 8 3 6 49 on 1 18 2, it was tested on assemblies and on a clean mine, where only the rei was and the library.

**Comment by kingstairs** [comment]
Confirming this with Fabric 1.19.2, any recipe.
Release .650 updated the "Transfer API", which I believe is what places recipe components in the crafting table grid, that is most likely the source of the problem.

**Comment by Fl414r** [comment]
1.20.1 same

**Comment by squid233** [comment]
Same in fabric 1.20.1 v12.0.652, with Lithium installed.

**Comment by shedaniel** [comment]
I cannot personally reproduce this issue, can someone send their logs here?

**Comment by FoxySophie** [comment]
It seems that Lithium is the culprit. Tested on 1.19.2 Fabric version 0.14.22, REI 9.1.657, Lithium 0.11.1

I had only REI and Lithium (and any required libraries) installed. With Lithium disabled shift clicking on the + for recipes works just fine. As soon as I enabled Lithium it was messing up the recipes. I attached the logs for both cases.

[with_lithium.zip](https://github.com/shedaniel/RoughlyEnoughItems/files/12657671/with_lithium.zip)
[without_lithium.zip](https://github.com/shedaniel/RoughlyEnoughItems/files/12657672/without_lithium.zip)

**Comment by shedaniel** [comment]
@szernex Thanks, I will test that right away

**Comment by MDMCK10** [comment]
Can reproduce.
Fabric 0.14.22 (1.20.2)
Lithium 0.12.0
REI 13.0.661

**Comment by shedaniel** [comment]
This issue is with how Lithium changed the implementation of CompoundNBT, this is an unfortunate issue that I have now workaround with.
