### ISSUE TITLE
[Bug] latest versiuonb fuck bad shit not wroking 

### ISSUE THREAD

**Issue by Pootleris** [shedaniel/RoughlyEnoughItems#1494]
### What happened?

when i put recipe it no work. bug wrong ricetta not fa porcoccocddidio. why not wroking nig bur?! bye fgriend hope u get it guyd ngi

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
hi mama g
```

### Anything else?

no!

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Pootleris** [comment]
ok try aghen not wroking but brawlallah gud plug out

**Comment by shedaniel** [comment]
Please create issues in English.
