### ISSUE TITLE
[Modrinth] You set 1.20.2-pre2 as compatible with 1.20-1.20.1

### ISSUE THREAD

**Issue by Fl414r** [shedaniel/RoughlyEnoughItems#1497]
### What happened?

Well, all it title.
![123](https://github.com/shedaniel/RoughlyEnoughItems/assets/74704475/4a3e4fd0-ac9f-4f97-bd1c-1947afc79e32)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Not bug
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by icynstant** [comment]
Yes, minecraft tells me to use mods versions for 1.20.2 when I play on 1.20.1
![awd](https://github.com/shedaniel/RoughlyEnoughItems/assets/127024748/a39277b7-a5c1-4eff-bf97-43a3c845b024)

**Comment by Splatllama** [comment]
also with curseforge download as above
![1 20 1](https://github.com/shedaniel/RoughlyEnoughItems/assets/140579170/dff47154-d1c8-4c0e-95b0-3ced5f44e071)

**Comment by vocaloidkiss** [comment]
yah, its a huge problem

**Comment by Fl414r** [comment]
Well, developer fixed it on Modrinth (and Curseforge)
![Снимок экрана (98)](https://github.com/shedaniel/RoughlyEnoughItems/assets/74704475/e4aab484-eaf8-4260-adeb-52289eb1e2b2)

**Comment by shedaniel** [comment]
@Fl414r Thanks for reporting! I wouldn’t have noticed if not for this. (Also sorry forgot to comment here after fixing)

**Comment by vocaloidkiss** [comment]
hhhh
just kidding

**Comment by Fl414r** [comment]
> hhhh just kidding

![angry](https://github.com/shedaniel/RoughlyEnoughItems/assets/74704475/3a086073-41a1-45ae-97c9-12f12a44cd97)

p.s. can I somehow close comments on my issue?

**Comment by vocaloidkiss** [comment]
cute  : )  : )
