### ISSUE TITLE
Item Panel Miscalculation

### ISSUE THREAD

**Issue by MelanX** [shedaniel/RoughlyEnoughItems#15]
the sidebar isn't right if recipe book is open
here an example:
I have the mouse here 
![2019-01-23_17 44 08](https://user-images.githubusercontent.com/26039509/51622277-8dd8c700-1f36-11e9-902a-3bfd1c3daf6f.png)
and if I left click there is the recipe for lime wool shown

**Comment by MelanX** [comment]
oh yes.. screenshot doesn't show mouse xD
it's above the bones in my inventory :D

**Comment by shedaniel** [comment]
Does reopening the inventory fix it? If not this is an issue.

**Comment by shedaniel** [comment]
Can you provide your REI & Minecraft version?

**Comment by MelanX** [comment]
Minecraft: 19w03c
REI: 2.1.0.43
Fabric: 0.1.4.77

**Comment by shedaniel** [comment]
Can't reproduce but I will keep trying

**Comment by MelanX** [comment]
maybe with GUI scale 3? I use that

**Comment by MelanX** [comment]
with GUI Scale Auto I have no problem with this bug

**Comment by shedaniel** [comment]
I've reproduced the issue and I will fix more bugs and publish to curseforge.

**Comment by Madis0** [comment]
Can confirm on v2.2.0.15/Minecraft 1.13.2 Rift fork.
It also does happen on automatic (same as 4 for me) GUI scale, the recipe book toggle is _partly_ covered.

**Comment by Madis0** [comment]
Can confirm on 2.2.0.16 on all GUI scales.

**Comment by shedaniel** [comment]
Seems like an issue not fixed properly.
