### ISSUE TITLE
[Bug] Issue with LightOverlay

### ISSUE THREAD

**Issue by NebelNidas** [shedaniel/RoughlyEnoughItems#150]
**Describe the bug**
When using the latest Roughly Enough Items (as of writing [Fabric 1.14.x - 19w34a] v3.1-pre Build 4), combined with LightOverlay and Optifine, I get the following result:
![2019-08-28_22 27 14](https://user-images.githubusercontent.com/48808497/63890616-aab10d80-c9e3-11e9-9029-fb5bebfd4a71.png)
When using any other REI version released before the above mentioned, it looks as expected:
![2019-08-28_22 28 30](https://user-images.githubusercontent.com/48808497/63890700-ce745380-c9e3-11e9-858f-d9f43879dc2d.png)

**Environment:**
 - Minecraft 1.14.4 
 - Mod Loader: Fabric Loader 0.4.8 Build 159

**Mods:**
 - fabric-api-0.3.1+build.208
 - LightOverlay-3.3.1
 - optifabric-0.5.1
 - OptiFine_1.14.4_HD_U_F3
 - RoughlyEnoughItems-3.1-pre+build.4

**Additional notes:**
In cases like these, the mod developers tend to blame the issues on Optifine. However, since it worked with all other versions before 3.1 Preview 4, I hope this will be investigated seriously.

**Comment by shedaniel** [comment]
Logs? Also please test on Light Overlay 3.4

**Comment by shedaniel** [comment]
Also using any kind of shaders? If so it might be related to https://github.com/shedaniel/LightOverlay-Fabric/issues/5
But if you are not using shaders, it might be a bug, please move this issue to that issue tracker.

**Comment by NebelNidas** [comment]
Oh, I didn't see there was an update available for LightOverlay. Unfortunately, it also doesn't work.
Yeah, I already investigated previous bug reports and checked if Optifine had enabled a shader by default, but it didn't. I tested if it had to do with specific Optifine settings, but neither of them solved the problem.
I don't think the issue should be moved to LightOverlay, cause the only thing which bricked it was the new REI version. I tested all previous Optifine, LightOverlay and REI versions, neither of them caused a problem except this one :/

**Comment by Cicero-Interactive** [comment]
Which log info do you need? The "\logs" subdirectory of the minecraft folder contains many, but they're all kinda useless

**Comment by NebelNidas** [comment]
I don't think this can help you, but here's the latest log file: https://pastebin.com/Jic1GeUH

**Comment by NebelNidas** [comment]
I now also installed the latest Fabric Loader (0.6.1 build 164), Fabric API (0.3.2 build 218) and REI (3.1 build 5), still the same issue

**Comment by shedaniel** [comment]
I have a general idea that this is caused by Cloth Events 0.5.1, please remove all mods and only put in Fabric API + Light Overlay + Cloth Events 0.5.1 and test again with Cloth Events 0.4.0.

**Comment by NebelNidas** [comment]
Yeah, you're right, it works with 0.4.0! Looks like they screwed something up...

**Comment by shedaniel** [comment]
Yeah I will move this into Light Overlay, https://github.com/shedaniel/LightOverlay-Fabric/issues/12
