### ISSUE TITLE
[Feature] Set vertical alignment with limited rows

### ISSUE THREAD

**Issue by Nemo157** [shedaniel/RoughlyEnoughItems#1502]
### What is your feature request?

Currently (12.0.652) if you set a "Vertical Entries Boundaries" or "Entries Rows Limit" then the displayed rows are vertically centered. I liked to use the similar functionality in JEI, where it's locked to the top and just measures down, to allow having a picture-in-picture movie overlay in the bottom-right that doesn't hide any results. To do the same thing with REI requires wasting a similar space at the top-right and only having a small strip of rows in the middle.

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Alignment is now being worked on with REI 8.4:

https://github.com/shedaniel/RoughlyEnoughItems/assets/34910653/0a3e5b55-6d44-4d47-9e2f-4ed37111f8a7
