### ISSUE TITLE
[Bug] Game crashes on opening inventory

### ISSUE THREAD

**Issue by KokSaker** [shedaniel/RoughlyEnoughItems#151]
**Describe the bug**
As soon as I press the inventory button, the game crashes.

**Steps to Reproduce**
- First Step
Install REI and dependencies
- Second Step
Press 'open inventory' button.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - Mod Loader: fabric

**Logs**
https://pastebin.com/ArqDeLYf

**Comment by shedaniel** [comment]
Cloth Config has to be on 1.1.1 or above.

**Comment by KokSaker** [comment]
It's listed as an embedded library though. Does it mean that I have to download the "Cloth Events API (Fabric)" separately too?
![dddddddddddd](https://user-images.githubusercontent.com/52161081/64004254-902b8100-cb16-11e9-9921-f123ba7ee5cd.png)
I don't know how exactly the github works and if you see a notification for the closed issues replies. So I am going to mention you here @shedaniel I apologize if I am bothering you. I just need a clarification on this.
