### ISSUE TITLE
[Question] How to add recipes to roughly enough items?

### ISSUE THREAD

**Issue by Ricenami** [shedaniel/RoughlyEnoughItems#1510]
### What happened?

I made custom recipes using craft tweaker and datapacks, but they don't show up on REI, how do I make it show up?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Not applicable
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
You need to actually code them in. I don't think this is doable with CraftTweaker.
