### ISSUE TITLE
[Bug] Crash after a couple seconds being inside of inventory.

### ISSUE THREAD

**Issue by vainlaind4in** [shedaniel/RoughlyEnoughItems#1511]
### What happened?

After opening inventory and scrolling through recipes, it crashes.

Expecting no crashing when scrolling through recipes.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://gist.github.com/vainlaind4in/636648aec7f24953e7edb4764dd147f6
```

### Anything else?

Minecraft Version: 1.20.1
Mod Version: 12.0.665

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Sodium is the cause of this crash.
