### ISSUE TITLE
[Feature] Reimplement "Move Items" on Servers without REI installed

### ISSUE THREAD

**Issue by NebelNidas** [shedaniel/RoughlyEnoughItems#152]
**Describe the solution you'd like**
Until 2.9.8 it was possible to press the "Move Items" button on every server, regardless if it had REI installed or not:
![Minecraft REI 2 9 8 on server](https://user-images.githubusercontent.com/48808497/64010927-f3b7ad80-cb1a-11e9-952a-87ce41e13e25.PNG)
With 3.0+ this feature is lost:
![Minecraft REI 3 1 b5 on server](https://user-images.githubusercontent.com/48808497/64010983-0cc05e80-cb1b-11e9-8dbb-88d4b2c327e6.PNG)

Can you please reimplement this feature? I don't understand why it has been taken out in the first place.

**Comment by shedaniel** [comment]
Yes, this feature is planned to be readded to REI but it will take some time.

**Comment by shedaniel** [comment]
And by some time, I guess I meant 3 hours.
