### ISSUE TITLE
error code 1 with a roughly enough items addon for compat

### ISSUE THREAD

**Issue by hi4444** [shedaniel/RoughlyEnoughItems#1523]
### What happened?

error code 1 when adding a rough enough item addon

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[2023-10-23-5.log.gz](https://github.com/shedaniel/RoughlyEnoughItems/files/13079087/2023-10-23-5.log.gz)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13079109/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13079116/rei-issues.log)
```

### Anything else?

i do got 2 beta mods for 1.19.2 endergetic expansion plus caverns and chasasm by abnormals

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Remove JEI

**Comment by hi4444** [comment]
i dont have jei though
