### ISSUE TITLE
[Bug] error code 1 when trying to launch with the Roughly Enough Items Server Component is a mod

### ISSUE THREAD

**Issue by hi4444** [shedaniel/RoughlyEnoughItems#1524]
### What happened?

error code 1

whenever i remove the sitems sever component it works but as long as its in there it breaks

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13120235/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13120239/rei.log)
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13120241/rei-issues.log)

### Anything else?

that i dont got jei in this i have the mod just enough items effect descriptions but it works with rei to and its your mod i listed thats the issue i also got this under rei issues [18:55:35] [REI-ReloadPlugins/ERROR] [REI] Creating unregistered recipe transfer handler, this is experimental!!: minecraft:plugins/crafting class vazkii.quark.addons.oddities.inventory.BackpackMenu

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [x] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
You shouldn't install server component and rei together, the server component is only used alongside jei on a server to support jei and rei clients at the same time.
