### ISSUE TITLE
[Bug] menu not showing up on right side of inventory on forge [1.20.4]

### ISSUE THREAD

**Issue by juliocoliveira** [shedaniel/RoughlyEnoughItems#1546]
### What happened?

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/6606725/213fe862-b872-4159-b41b-a4fdda1838ec)
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/6606725/acb45604-aad8-4562-ade5-ce4bc1103d43)
Same plugin works fine in Fabric

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
latest.log: https://gist.github.com/juliocoliveira/43dfaa01012c762ffa6ad646932e5fd0
rei.log: https://gist.github.com/juliocoliveira/1ce6495bd9b838c58a1a79be956130cc
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by juliocoliveira** [comment]
I found what the problem is, Is because some incompatibility with new Optifine Kai (https://livzmc.net/optikai/downloads)

**Comment by shedaniel** [comment]
REI does not support Optifine and its derivatives, please use alternative mods.
