### ISSUE TITLE
[Feature] Synchronize recipes from server

### ISSUE THREAD

**Issue by Tollainmear** [shedaniel/RoughlyEnoughItems#1554]
### What is your feature request?

Hi, I've found that if I alter recipes from the server side (like with kubejs), the recipes can't synchronize without the code being dispatched to the client side, but as we konw, synchronize files is not a easy thing for minecraft server hosters.

As far as I know, JEI has implemented this feature, and it's really convenient for our server hosters and modpack developers. So, I hope this feature is planned for REI development. If it is, I would greatly appreciate it!

Btw, thanks for your awsome work! No offence, in my view, I think before this feature implemented, use JEI mabey is a better choice for those server hosters.

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
The sync of recipes is done by vanilla, JEI doesn’t do it by itself. By standard, REI and JEI recipe syncs the same because we both don’t sync ourselves. There might be other issues that caused it to fail.

**Comment by Tollainmear** [comment]
> The sync of recipes is done by vanilla, JEI doesn’t do it by itself. By standard, REI and JEI recipe syncs the same because we both don’t sync ourselves. There might be other issues that caused it to fail.

I apologize for the incorrect assessment I made about REI. Compared to JEI, REI is indeed the mod I prefer. As you mentioned, if REI does support synchronized recipes, then I hereby attach a log file, hoping to help solve this problem. If you need me to provide more information, please let me know. Thanks for your help!

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13725520/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/13725532/rei.log)

Btw, I also find a log file named rei-issues.log which is empty.

**Comment by Tollainmear** [comment]
I will close this issue because the problem was solved for reasons unknown, thank you for your awsome work @shedaniel !
