### ISSUE TITLE
[Feature] Limit the number of items shown in item panel

### ISSUE THREAD

**Issue by Eliteneet** [shedaniel/RoughlyEnoughItems#158]
I'd like an option to limit the amount of items shown by default on the item panel. Either by max items per page, max number of columns shown, or show no items with an empty search field.

**Additional context**
I play at high resolution, so when I open my inventory there are hundreds of items shown on the item panel which cause fps drops especially with higher res resource packs, makes inventory management a headache.
My current solution is to type "zzz" into the search field so that I hide the items, but retain the search field without hiding everything.

**Comment by Dekamir** [comment]
I asked for this before in Discord, didn't get an answer. I suffer from this problem as well. Because of this, I constantly turn REI on and off. Would like a button on screen in inventory rather than pressing a keyboard button constantly (or a double click).

**Comment by shedaniel** [comment]
Entry Scaling is what this will be instead of limiting the number of items shown.

**Comment by Eliteneet** [comment]
What is "Entry Scaling" going to entail?

**Comment by shedaniel** [comment]
scaling the size of the items so it will display less

**Comment by Eliteneet** [comment]
So having tested this feature it doesn't really solve the issue. I'm still having a 50% fps loss even at 200% scaling while having REI shown.

FPS
World: 140
REI (Shown @100%): 40fps
REI (Shown @200%): 70fps
REI (Search "zzz"): 120fps
REI (Shown @100%): 125fps

Theres no way to empty the item panel when the search bar is empty? To only show items in the panel when there is a search query?
At 200% scaling the items are the size of the character model in the inventory, looks kind of ridiculous haha

**Comment by shedaniel** [comment]
What items are shown on the list when you have 200%? Some items might be more resource-intensive, such as potions and enchanting books.

**Comment by Eliteneet** [comment]
Tools from Tool builder and Materialisation, potions, and books.

**Comment by shedaniel** [comment]
Oh yeah those items have multiple layers and stuff and will be slower.

**Comment by Eliteneet** [comment]
That being said it is still a big improvement, just gotta make the items very large haha

**Comment by shedaniel** [comment]
can you turn on the debug entry list in technical and check the avg time for me

**Comment by Eliteneet** [comment]
![2020-01-01_23 58 55](https://user-images.githubusercontent.com/2501786/71657006-b5154800-2cf2-11ea-86dd-871a809a62d4.png)

**Comment by shedaniel** [comment]
I would say that's standard. I get ~12k for normal items and blocks and ~30k for complicated stuff

**Comment by Eliteneet** [comment]
My normal vanilla blocks are 16k-18k

**Comment by shedaniel** [comment]
Added in REI 5.7.2 by `Horizontal Entries Boundaries` and `Vertical Entries Boundaries`.
