### ISSUE TITLE
[Bug] can't show Sequenced Assembly in Create Mod

### ISSUE THREAD

**Issue by BlankAo** [shedaniel/RoughlyEnoughItems#1583]
### What happened?

![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/68088008/61106b5c-0c19-4a92-97e2-94cfa8612e70)

In Create mod,things such as Precision Mechanism and Train Track need Sequenced Assembly to create, but this kind of recipe is unable to show.

here is a mod that fix it but only in fabric : <https://github.com/HO-Artisan/CreateFabric-REIBugFix>

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Unfortunately nothing relevant, seems to just be omitting these items from the JEI list.
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment]
On Forge you can try using REIPC

**Comment by BlankAo** [comment]
> On Forge you can try using REIPC

oops i thought here is REIPC. my bad
