### ISSUE TITLE
[Feature] Sophisticated Backpack "compatibility"

### ISSUE THREAD

**Issue by Xaligal** [shedaniel/RoughlyEnoughItems#1586]
### What is your feature request?

Have the Recipe Bar go around the Crafting Tab in a Backpack.
![image](https://github.com/shedaniel/RoughlyEnoughItems/assets/91026414/dc2dc0dc-2187-40c6-9268-573dcd175b1c)

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by Jie-yang-1014** [comment]
+1 Same problem

**Comment by Jie-yang-1014** [comment]
> ### What is your feature request?
> Have the Recipe Bar go around the Crafting Tab in a Backpack. ![image](https://private-user-images.githubusercontent.com/91026414/309119387-dc2dc0dc-2187-40c6-9268-573dcd175b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjYxMTMsIm5iZiI6MTcwOTU2NTgxMywicGF0aCI6Ii85MTAyNjQxNC8zMDkxMTkzODctZGMyZGMwZGMtMjE4Ny00MGM2LTkyNjgtNTczZGNkMTc1YjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDE1MWU3MGNjMWY4ZjdlNzg2NDM2M2IxMmQ2ZDNiODE5NDM2Yjk0YTlkZmQwNGViNGI4ZmVlODFlYzQ1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hsf18eyclDySDAN8g4WZk2m3fPsO9NWCxH3XSsNDiCE)
> 
> ### What do you think this change is of?
> * [x]  Visual
> * [ ]  Recipe Lookup
> * [ ]  Cheat Mode
> * [ ]  Plugin Integration / JEI Plugin Compatibility
> * [ ]  Others

Hello, I've solved this by installing REIPC(REI Plugin Compatibilities) mod for REI,  and then everything works fine with Sophisticated Backpack and Sophisticated Storage， you can give it a try.

**Comment by Xaligal** [comment]
> > ### What is your feature request?
> > Have the Recipe Bar go around the Crafting Tab in a Backpack. ![image](https://private-user-images.githubusercontent.com/91026414/309119387-dc2dc0dc-2187-40c6-9268-573dcd175b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjYxMTMsIm5iZiI6MTcwOTU2NTgxMywicGF0aCI6Ii85MTAyNjQxNC8zMDkxMTkzODctZGMyZGMwZGMtMjE4Ny00MGM2LTkyNjgtNTczZGNkMTc1YjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDE1MWU3MGNjMWY4ZjdlNzg2NDM2M2IxMmQ2ZDNiODE5NDM2Yjk0YTlkZmQwNGViNGI4ZmVlODFlYzQ1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hsf18eyclDySDAN8g4WZk2m3fPsO9NWCxH3XSsNDiCE)
> > ### What do you think this change is of?
> > 
> > * [x]   Visual
> > * [ ]   Recipe Lookup
> > * [ ]   Cheat Mode
> > * [ ]   Plugin Integration / JEI Plugin Compatibility
> > * [ ]   Others
> 
> Hello, I've solved this by installing REIPC(REI Plugin Compatibilities) mod for REI, and then everything works fine with Sophisticated Backpack and Sophisticated Storage， you can give it a try.

Hey, with REIPC we have a crash that we can't report (Issue Templates are down or something like that), where if we click a recipe with Ad Astra's Compressor the game just freezes and crashes (seems like RAM/CPU usage goes way, way up since my entire PC's audio cuts out for a brief moment)

**Comment by Jie-yang-1014** [comment]
> > > ### What is your feature request?
> > > Have the Recipe Bar go around the Crafting Tab in a Backpack. ![image](https://private-user-images.githubusercontent.com/91026414/309119387-dc2dc0dc-2187-40c6-9268-573dcd175b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjYxMTMsIm5iZiI6MTcwOTU2NTgxMywicGF0aCI6Ii85MTAyNjQxNC8zMDkxMTkzODctZGMyZGMwZGMtMjE4Ny00MGM2LTkyNjgtNTczZGNkMTc1YjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDE1MWU3MGNjMWY4ZjdlNzg2NDM2M2IxMmQ2ZDNiODE5NDM2Yjk0YTlkZmQwNGViNGI4ZmVlODFlYzQ1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hsf18eyclDySDAN8g4WZk2m3fPsO9NWCxH3XSsNDiCE)
> > > ### What do you think this change is of?
> > > 
> > > * [x]    Visual
> > > * [ ]    Recipe Lookup
> > > * [ ]    Cheat Mode
> > > * [ ]    Plugin Integration / JEI Plugin Compatibility
> > > * [ ]    Others
> > 
> > 
> > Hello, I've solved this by installing REIPC(REI Plugin Compatibilities) mod for REI, and then everything works fine with Sophisticated Backpack and Sophisticated Storage， you can give it a try.
> 
> Hey, with REIPC we have a crash that we can't report (Issue Templates are down or something like that), where if we click a recipe with Ad Astra's Compressor the game just freezes and crashes (seems like RAM/CPU usage goes way, way up since my entire PC's audio cuts out for a brief moment)

Yeah I see, I'm not using Ad Astra in my modlist, but in Ad Astra's Github issue section, there are a few people report issues about crashing with REI, maybe you should try JEI then :)

**Comment by Xaligal** [comment]
> > > > ### What is your feature request?
> > > > Have the Recipe Bar go around the Crafting Tab in a Backpack. ![image](https://private-user-images.githubusercontent.com/91026414/309119387-dc2dc0dc-2187-40c6-9268-573dcd175b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjYxMTMsIm5iZiI6MTcwOTU2NTgxMywicGF0aCI6Ii85MTAyNjQxNC8zMDkxMTkzODctZGMyZGMwZGMtMjE4Ny00MGM2LTkyNjgtNTczZGNkMTc1YjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDE1MWU3MGNjMWY4ZjdlNzg2NDM2M2IxMmQ2ZDNiODE5NDM2Yjk0YTlkZmQwNGViNGI4ZmVlODFlYzQ1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hsf18eyclDySDAN8g4WZk2m3fPsO9NWCxH3XSsNDiCE)
> > > > ### What do you think this change is of?
> > > > 
> > > > * [x]     Visual
> > > > * [ ]     Recipe Lookup
> > > > * [ ]     Cheat Mode
> > > > * [ ]     Plugin Integration / JEI Plugin Compatibility
> > > > * [ ]     Others
> > > 
> > > 
> > > Hello, I've solved this by installing REIPC(REI Plugin Compatibilities) mod for REI, and then everything works fine with Sophisticated Backpack and Sophisticated Storage， you can give it a try.
> > 
> > 
> > Hey, with REIPC we have a crash that we can't report (Issue Templates are down or something like that), where if we click a recipe with Ad Astra's Compressor the game just freezes and crashes (seems like RAM/CPU usage goes way, way up since my entire PC's audio cuts out for a brief moment)
> 
> Yeah I see, I'm not using Ad Astra in my modlist, but in Ad Astra's Github issue section, there are a few people report issues about crashing with REI, maybe you should try JEI then :)

I totally forgot about Ad Astra's issue page, and yeah that's fair but I really don't wanna switch to JEI, after I tried REI I can't go back to JEI now lol, JEI has a very "rough around the edges" feel while REI feels a whole lot smoother to me

**Comment by rozbrajaczpoziomow** [comment]
> Issue Templates are down or something like that

Found this issue https://github.com/terrarium-earth/Ad-Astra/issues/499, so I'd guess your issue is the exact same, and if it *isn't*, it'd seem like Issue Templates are working, so would be worth to report it either to https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues or Ad Astra.

**Comment by Xaligal** [comment]
> > Issue Templates are down or something like that
> 
> Found this issue [terrarium-earth/Ad-Astra#499](https://github.com/terrarium-earth/Ad-Astra/issues/499), so I'd guess your issue is the exact same, and if it _isn't_, it'd seem like Issue Templates are working, so would be worth to report it either to https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues or Ad Astra.

yep, it's the same exact bug, thanks!
