### ISSUE TITLE
[Feature] Disable glints for books/bottles

### ISSUE THREAD

**Issue by Dekamir** [shedaniel/RoughlyEnoughItems#160]
They simply drop FPS for no reason.

You can also make it so that user can toggle if it's on, vanilla only or off.

**Comment by shedaniel** [comment]
this sounds way easier to do than #158

**Comment by Dekamir** [comment]
That amount of items still drop FPS. You can set "max grid/column" for item list GUI.

**Comment by shedaniel** [comment]
Done is v3.1.4
