### ISSUE TITLE
[Bug] Crash with Modernfix heavily modded tho

### ISSUE THREAD

**Issue by PabloDnSS** [shedaniel/RoughlyEnoughItems#1609]
### What happened?

Occur when trying to join a world 1.20.1 forge 47.2.21
[rei-issues.log](https://github.com/shedaniel/RoughlyEnoughItems/files/14983143/rei-issues.log)
[2024-04-15-4.log.gz](https://github.com/shedaniel/RoughlyEnoughItems/files/14983144/2024-04-15-4.log.gz)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/14983145/rei.log)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
--
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by vizthex123** [comment]
Same issue here.

My logs:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/14983671/latest.log)

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/14983673/rei.log)

Downgraded to v12.0.697 for now.

**Comment by shedaniel** [comment]
This is caused by ModernFix using REI internals. I have contacted the developer of ModernFix and they said they are fixing it in a week or so, this is very unfortunate.

**Comment by vizthex123** [comment]
> This is caused by ModernFix using REI internals. I have contacted the developer of ModernFix and they said they are fixing it in a week or so, this is very unfortunate.

noice, thanks.

**Comment by Fleepe** [comment]
> This is caused by ModernFix using REI internals. I have contacted the developer of ModernFix and they said they are fixing it in a week or so, this is very unfortunate.

They fixed it in modernfix 5.16.1. At least now it doesn't crash.
