### ISSUE TITLE
[Bug] Few errors in logs

### ISSUE THREAD

**Issue by Fleepe** [shedaniel/RoughlyEnoughItems#1611]
### What happened?

After entering the world on Minecraft 1.20.1, REI creates several errors in the logs

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Here they are:
java.lang.UnsupportedOperationException
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.Collections$UnmodifiableCollection.removeIf(Collections.java:1096)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.Collections$SynchronizedCollection.removeIf(Collections.java:2135)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.endReload(DisplayRegistryImpl.java:205)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:454)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:162)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$25(RoughlyEnoughItemsCoreClient.java:485)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[REI-ReloadPlugins/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Anything else?

If necessary, here are all the logs:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15002238/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15002240/rei.log)
rei-issues.log is empty.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
@Fleepe Please test if [this pre-production REI build](https://cdn.discordapp.com/attachments/804158821861556275/1230390846965284884/RoughlyEnoughItems-12.1.9999-fabric.jar?ex=663325c5&is=6620b0c5&hm=a4a87bdcb3c5ce894b02b2d83d4c80a615578a15c6d32eec06b75147db0f0a65&) solves your issue, if not, please send the new logs with this build.

**Comment by Fleepe** [comment]
Sorry for the late reply @shedaniel, I was not at home.
Minecraft cannot start with the version of the mod you posted above. Here are the logs:
[crash-2024-04-20_19.49.19-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/15049076/crash-2024-04-20_19.49.19-client.txt)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15049074/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15049075/rei.log)
rei-issues.log is empty.
