### ISSUE TITLE
[Bug] me.shedaniel.math.Rectangle doesn't exist for List<Widget> 

### ISSUE THREAD

**Issue by swapmasterx** [shedaniel/RoughlyEnoughItems#1616]
### What happened?

I'm adding REI compatibility to my mod and punching in setupDIsplay puts Rectangle with its full path. Cutting it down to just Rectangle or manually adding the import doesn't find a valid path. TLDR the mods Rectangle path doesn't seem to set up right or the auto creation of setupDisplay is using an oudated autofill

MC version 1.20.4
REI version 14.1.714

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
C:\Users\Izzy\Desktop\New folder\PvZCubedMod-2.1.0\src\main\java\io\github\GrassyDev\pvzmod\compat\BotanyStationCatagory.java:40: error: package me.shedaniel.math does not exist
	public List<Widget> setupDisplay(BasicDisplay display, me.shedaniel.math.Rectangle bounds) {

See attachments for shown otherwise
```

### Anything else?

![15](https://github.com/shedaniel/RoughlyEnoughItems/assets/44793093/f1f0b9ff-98fd-42df-9d3c-15054bc0cce5)
![15a](https://github.com/shedaniel/RoughlyEnoughItems/assets/44793093/b53bc903-9244-44ff-bf1f-e69d85d6655d)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Ryhon0** [comment]
What's the solution? I'm having this issue in 14.1.727
