### ISSUE TITLE
[Feature] be compatible with more overlays

### ISSUE THREAD

**Issue by sauphle** [shedaniel/RoughlyEnoughItems#1619]
### What is your feature request?

The highlight overlay can be disabled in moreoverlay's config, if REI absolutely does not work with moreoverlays even with this disabled you should have the forced crash, but if it isn't maybe just have a warning telling the player to disable it.

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Superceded by #1648
