### ISSUE TITLE
[Bug] Fabric API missing in depends

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#162]
REI now uses the fluid renderer provided by fabric api but is not listed it in mod dependencies meaning the game loads just fine without fabric api and only crashes once you open the inventory or scroll ( depending on gui scale (if all items fit on one page or not) )

**Comment by shedaniel** [comment]
REI uses the tick callback and multiple other stuff from fabric api already, and I don’t really know how to enforce fabric api: I don’t want to enforce “fabric” but neither each module
