### ISSUE TITLE
[Bug] When I enter a world (single/multi) it crashes almost immediately

### ISSUE THREAD

**Issue by Rinpyre** [shedaniel/RoughlyEnoughItems#1621]
### What happened?

Today I updated from 12.0.684 to 12.1.718 and after I joined my server, the mc crashed. At first I thought it was because of the server (since I updated only on client not the sv-component on the sv). After updating the sv-component, it crashed again. I try to go on singleplayer and still crashed when entering the world.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
I put them below in files as it said "body too long".
```

### Anything else?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15125620/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/15125634/rei.log)

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
Update ModernFix
