### ISSUE TITLE
[Feature] Remove More Overlays Updated from the blacklist (1.19.4+)

### ISSUE THREAD

**Issue by r8420** [shedaniel/RoughlyEnoughItems#1648]
### What is your feature request?

Because [More Overlays Updated](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated) now uses a different way of communicating with JEI, it's compatible with REI since 1.19.4. The modid "moreoverlays" can be removed from PrimitivePlatformAdapterImpl.java in future versions since it won't cause any problems.

This request is similar to #1619 and by the way does not require anyone to change the config.

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by cauamachado51** [comment]
Up. is currently incompatible with [More Overlays](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated) Updated:
![Captura de tela 2024-06-14 221909](https://github.com/shedaniel/RoughlyEnoughItems/assets/132782265/947dd735-f2a8-459f-ae61-a2ed114e38c5)

So I'm using [Light Overlay](https://www.curseforge.com/minecraft/mc-mods/light-overlay/files/all?page=1&pageSize=20) to remedy it, I hope if there are no conflicts, in the future the mod will let me play with More Overlays. If not, I hope he puts that incompatible in the related projects on CurseForge.

Minecraft 1.20.1, Forge 47.2.21, All The Mods 9 - No Frills 0.1.14, REI 12.1.725, REI Plugin Compatibilities 12.0.93.
