### ISSUE TITLE
[Bug] Only “Enchanted Book” shows up, no longer able to search specific enchants

### ISSUE THREAD

**Issue by QueenDiancieTTV** [shedaniel/RoughlyEnoughItems#1666]
### What happened?

So when searching for enchants, only a blank “enchanted book” shows up, you can’t search for specific enchants anymore, is this intentional? 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No logs
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by kazyofloof** [comment]
As an addendum, this bug seems to affect creative search as well. With the mod installed, only the generic "Enchanted Book" shows in creative search, though they still seem to appear as normal in the Ingredients tab. This is on Fabric 1.21 with REI 16.0.729.
