### ISSUE TITLE
wrong recipe in crafting table

### ISSUE THREAD

**Issue by MelanX** [shedaniel/RoughlyEnoughItems#17]
If I Shift Leftclick an "+" while not on page 1 there will be moved the recipe from page 1 to the crafting table.
Example:
1. Press U on Redstone Dust
2. Go to page 5 to craft Redstone Blocks
3. Shift Leftclick on "+"
4. Recipe from Redstone Lamp will be moved to crafting table (maybe another recipe if using other gui size)

Fabric: 0.1.4.77
REI: 2.1.0.45
Minecraft: 19w04b

**Comment by shedaniel** [comment]
Alright, this should be an easy fix if I can reproduce the bug.
