### ISSUE TITLE
[Bug] Minecraft crashes and reports not enough memory

### ISSUE THREAD

**Issue by ChunkyMonkey00** [shedaniel/RoughlyEnoughItems#1724]
### What happened?

When using fabric REI for 1.21.1 (either release, as of right now this is just 16.0.762 and 16.0.754) and fabric api 1.21.1 version 0.16.5, Minecraft will boot to a white screen, crash, and report not enough memory (exit code: -805306369).

Expected output: Minecraft boots properly and normally.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
No log output, as Minecraft was never able to start.
```

### Anything else?

To reproduce:
1. Install Fabric Loader 0.16.5 for Minecraft 1.21.1.
2. Add Fabric API version 0.103.0+1.21.1.
3. Add REI version 16.0.754.
4. Launch Minecraft through and observe the error.

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by Shingen96** [comment]
Hello, i had the same issue as you and could be that you missed two required API for mod to work properly
Requires [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-api) & [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config).

**Comment by sargeow** [comment]
did you allocate enough MEM? as well as check all of the depends [FABRIC](https://modrinth.com/mod/rei/version/14.1.760+fabric) [FORGE](https://modrinth.com/mod/rei/version/14.1.760+forge) for REI.

**Comment by ChunkyMonkey00** [comment]
> Hello, i had the same issue as you and could be that you missed two required API for mod to work properly Requires [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-api) & [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config).

This fixed my problem, architectury was missing and it didn't tell me. Yes enough dedicated wam (ram) was available lol.
