### ISSUE TITLE
Can't Change Keybinds

### ISSUE THREAD

**Issue by LikeableMonkey** [shedaniel/RoughlyEnoughItems#174]
When I Go To Controls, The Option For REI Disappeared And The Options For Volex Map Appeared.
The Mods I Use (Fabric1.14.4) :
![image](https://user-images.githubusercontent.com/56303654/66394557-24beb400-e9de-11e9-8976-bb49c3929c28.png)

> I Haven't Tried Starting Fresh ... My Goal Is To Change The Keybinds To The Brackets ... Keybinds Are Limited When You Use A Hack Client!

**Comment by shedaniel** [comment]
Please download REI and all the other mods from https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items Other sites are just a mirror of it and is usually outdated and unofficial.

In any case, REI does **NOT** and will **NOT** provide support for any hacked client incompatibilities, you are on your own here.

For the actual fix for this issue: Check if you have the Build 166 of Fabric Loader, it currently is buggy and broke keybinds, downgrade to Build 165.

**Comment by LikeableMonkey** [comment]
Sorry ... Found This After Reinstalling My Game In My Options Folder!
key_key.roughlyenoughitems.recipe_keybind:key.keyboard.left.bracket
key_key.roughlyenoughitems.usage_keybind:key.keyboard.right.bracket
key_key.roughlyenoughitems.hide_keybind:key.keyboard.backslash
key_key.roughlyenoughitems.previous_page:key.keyboard.unknown
key_key.roughlyenoughitems.next_page:key.keyboard.unknown

**Comment by shedaniel** [comment]
And? Did you downgrade fabric loader
**EDIT: As that bug in Fabric Loader is fixed, are you on loader 0.6.3?**
