### ISSUE TITLE
[Bug] 16.0.783 missing API jars on the maven

### ISSUE THREAD

**Issue by kb-1000** [shedaniel/RoughlyEnoughItems#1740]
### What happened?

For some reason, they're simply not there: https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-api-fabric/16.0.783/
They were still there in 16.0.777: https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-api-fabric/16.0.777/
The architectury common API JARs still appear to exist, but I don't think that helps me, and does not match the documentation.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Not relevant
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by solonovamax** [comment]
Yea, experienced this as well.

It's an extremely annoying soft-error and took me way too long to figure out the cause of it.
