### ISSUE TITLE
[Bug] I don't even know how to explain this (See the screenshot)

### ISSUE THREAD

**Issue by SrUca** [shedaniel/RoughlyEnoughItems#1747]
### What happened?

So... this happen in a Mohist server, Minecraft 1.12.2, latest version of ROIDs. As far i could see, it also happens in singleplayer. 

![2024-10-10_17 34 17](https://github.com/user-attachments/assets/b57e0dee-5fff-4f82-8480-6d88590bec5c)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Any log i could send are too big
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by rozbrajaczpoziomow** [comment]
how is this related to REI.

**Comment by SrUca** [comment]
> how is this related to REI.

Because if i start a world with Just Enough IDs instead of REI... Shit, this is nor Roughly Enough IDs, but Roughly Enough Items I'm so sorry i will close this
