### ISSUE TITLE
[Bug] Crash on Launch when REI + JEI present with Sinytra Connector

### ISSUE THREAD

**Issue by chdonncha** [shedaniel/RoughlyEnoughItems#1764]
### What happened?

I've a setup where I have a NeoForge Modloaded Mincecraft 12.0.1 that uses Sinytra Connector to install Modern Industrialization and a few other dependencies. I had to install JEI on Fabric side due to an issue where Recipes were missing when installed on NeoForge due to not pulling the Fabric Recipes.

I've installed REI as suggested by Modern Industrialization, putting it on NeoForge causes me to lose the Recipes so I install it in unison with JEI on the Fabric end leveraging Sinytra Connector. However, the game crashes only after adding REI Fabric. 

I've posted on Sinytra Connector and they've said it's not an issue related to their mod so I'm seeing if there's anything else of note that could be uncovered here since I'm not sure where the actual error lays in which mod or if there's an incompatibility between them.

#  Versions

MineCraft: 1.20.1
NeoForge: 47.1.106

## NeoForge Mods:
Quark: 4.0-460
Zeta: 1.0-24
Embeddium: 0.3.31 + mc1.20.1
Valkyrienskies: 2.3.0-beta.5
Oculus: 1.7.0
Oculus Flywheel Compat: 1.1.3

##  Fabric Mods :
```
		Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| Modern-Industrialization-1.8.6$magna-1.10.1+1.20.1 | OmegaConfig                    | omega_config                   | 1.0.8                |
		| Modern-Industrialization-1.8.6$PlayerAbilityLib-1. | Pal                            | playerabilitylib               | 1.8.0                |
		| RoughlyEnoughItems-12.1.785-fabric$error-notifier- | Error Notifier                 | error_notifier                 | 1.0.9                |
		| Modern-Industrialization-1.8.6$magna-1.10.1+1.20.1 | Magna                          | magna                          | 1.10.11.20.1         |
		| Modern-Industrialization-1.8.6$NoIndium-1.1.0+1.20 | No Indium?                     | noindium                       | 1.1.01.20            |
		| jei-1.20.1-fabric-15.20.0.104_mapped_srg_1.20.1.ja | Just Enough Items              | jei                            | 15.20.0.104          |
		| Modern-Industrialization-1.8.6_mapped_srg_1.20.1.j | Modern Industrialization       | modern_industrialization       | 1.8.6                |
		| RoughlyEnoughItems-12.1.785-fabric_mapped_srg_1.20 | Roughly Enough Items           | roughlyenoughitems             | 12.1.785             |
		| Modern-Industrialization-1.8.6$energy-3.0.0_mapped | Energy                         | team_reborn_energy             | 3.0.0                |
```

### What mod loaders are you seeing the problem on?

Fabric, Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/chdonncha/3adec7a5db0221edd5df9f9a6b33d965
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
The error is caused by using REI Fabric with Architectury Forge. **I do not support the use of Sinytra Connector at all, and you should be on your own and not report any issues to us mod developers if you so choose to**

That on the side, you can try using REI Forge
