### ISSUE TITLE
Recipe Key

### ISSUE THREAD

**Issue by sinabagheri865** [shedaniel/RoughlyEnoughItems#178]
As you know you can view recipes by either pressing r on the item or left clicking it, my spirnt key is bound to r and the rei recipe key makes it so my sprint key doesnt work. plz add the ability to change the recipe key, if there is a way already plz tell me how.

**Comment by shedaniel** [comment]
you can edit via controls settings

**Comment by sinabagheri865** [comment]
> you can edit via controls settings

control settings? i already looked at all the configs and cant find anything plz show me a screen shot or explain it more, so sorry

**Comment by sinabagheri865** [comment]
i went in the control settings, nothing about it i see every control setting and nothing else
