### ISSUE TITLE
Recipe Key 2

### ISSUE THREAD

**Issue by sinabagheri865** [shedaniel/RoughlyEnoughItems#179]
im sorry for making a 2nd issue but this is all i see when i open configs menu, i cant find "control settings" anywhere
![2019-10-29_23 58 22](https://user-images.githubusercontent.com/57139700/67769351-6bb53c00-faa8-11e9-8960-20312fcaab63.png)

**Comment by shedaniel** [comment]
I said. Controls Settings.

**Comment by shedaniel** [comment]
It is a vanilla thing.
