### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MelanX** [shedaniel/RoughlyEnoughItems#18]
Game crashes if showing recipe while recipe book is open.

Example:
- You have Slime Block in Inventory
- You have the recipe book open
- You wanna know how Slime Block are crafted
- You press R on Slime Blocks
- You ehm.. Game Crashes :D 

Minecraft: 19w04b
REI: 2.1.0.45
Fabric: 0.1.4.77

Crash Log: https://pastebin.com/YHumzaEP

If that's not because of REI: sorry. But I think it is. :)

**Comment by shedaniel** [comment]
Never mind I can reproduce with recipe book on
