### ISSUE TITLE
recipe key 3

### ISSUE THREAD

**Issue by sinabagheri865** [shedaniel/RoughlyEnoughItems#180]
im so sorry... i dont understand what u mean im new to this mod and know almost nothing idk where control settings is plz help, dont be mad im slow lol, i dont see anything ive tried everything
![2019-10-30_00 10 47](https://user-images.githubusercontent.com/57139700/67770189-019d9680-faaa-11e9-9601-c63e593b43ac.png)

**Comment by shedaniel** [comment]
**NOTE:** Please stop making new issues, use the original issue.

The Control Settings: http://www.minecraft101.net/g/controls-and-keyboard.html

Please use Google.

**Comment by sinabagheri865** [comment]
i have gone there
i thought u meant the mod had one sorry
there is nothing about the mod there, it doesnt say anything about recipe keys or anything like that

**Comment by shedaniel** [comment]
Logs?

**Comment by sinabagheri865** [comment]
ill show u ss 1 sec

**Comment by shedaniel** [comment]
I would like a log, not a screenshot or screenshare (SS can mean basically anything)

**Comment by sinabagheri865** [comment]
wdym from log, as of mc logs in logs folder and the latest one etc?

**Comment by shedaniel** [comment]
Open up the `latest.log` from the `logs` folder, and paste its content to https://paste.ee/ or any other similar sites.

**Comment by sinabagheri865** [comment]
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/3783708/latest.log)
this?

**Comment by shedaniel** [comment]
Should've pasted it into paste.ee instead but whatever I am tired now.

Update Fabric Loader, it is outdated.

**Comment by sinabagheri865** [comment]
ok thx

**Comment by shedaniel** [comment]
I will close this.
