### ISSUE TITLE
[Bug] Config won't open on v3.2 b43

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#181]
**Describe the bug**
In latest REI - version 3.2 build 43 the configuration screen will not open. The other buttons (gamemode, weather, recipe toggle, even shift+config to toggle cheat mode) work.

**Steps to Reproduce**

1. Open inventory
2. Press REI config button
3. Inventory closes

-

1. Open Mod Menu
2. Press REI config button
3. Nothing happens

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - REI 3.2 b 43
 - Fabric Loader 0.6.3 b 168
 - Fabric API 0.4.1 b 245

**Logs**
Relevant log piece:
https://privatebin.net/?233b416c36aede7f#G8UTsjSkramMR2A9SX57mxgWyFM5zFfr8HcZcfaq24dY

**Additional context**
no

**Comment by shedaniel** [comment]
Command Keybinds is the cause of this, report to them to fix it.

**Comment by kyrptonaught** [comment]
I apologize for the inconvenience, this has been fixed in 1.3.2 
https://www.curseforge.com/minecraft/mc-mods/command-macros/files/2821459

**Comment by shedaniel** [comment]
Thank you
