### ISSUE TITLE
[Bug] On any item click stone is given

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#182]
**Describe the bug**
In REI 3.2 b 43, clicking on any item gives the user stone.

**Steps to Reproduce**
- Enable cheating
- Enable "showing all" (bug does not occur when set to "showing craftable")
- Make sure the search is empty
- May affect: set view scrollable instead of paginated
- Click on any item to get stone

**Screenshots**
nah

**Environment (please complete the following information with the version):**

- Minecraft: 1.14.4
- REI 3.2 b 43
- Fabric Loader 0.6.3 b 168
- Fabric API 0.4.1 b 245

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: 
doesn't contain anything relevant, no stacktraces

**Additional context**
nah

**Comment by shedaniel** [comment]
Reproduced.
