### ISSUE TITLE
[Bug] Fix delay when opening Inventory when there is a filter and a lot of items. 

### ISSUE THREAD

**Issue by Khaelum** [shedaniel/RoughlyEnoughItems#184]
When opening the Inventory when there is an old filter, the mod seems to search through all items again, causing a small hang of <1s but more than 0.5s, which is noticeable. Hence, I suggest the implementation of a cache or something that prevents it from searching again.

![Demo](https://user-images.githubusercontent.com/46039421/68088703-5a6d8600-fe40-11e9-9b1b-d52db551c14a.gif)

Didn't post as bug because I feel this is a result of how the modder decided to make his mod rather than a bug.

**Comment by shedaniel** [comment]
should be a bug instead

**Comment by shedaniel** [comment]
Entry List is now cached.
