### ISSUE TITLE
[Bug][1.15-pre1] CTD on start

### ISSUE THREAD

**Issue by NateMcCloud** [shedaniel/RoughlyEnoughItems#192]
**Describe the bug**
The game crashes at start even with only Fabric API and this mod loaded.

**Steps to Reproduce**
- Start Minecraft 1.15-pre1 with this mod and Fabric API loaded
- Swear profusely as game crashes

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15-pre1
 - Mod Loader: Fabric 0.7.1 - Build 173

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/WLrY6PJg

**Additional context**

**Comment by shedaniel** [comment]
You have the 1.14 version of REI, please check next time if you have the corresponding REI version to your minecraft version.
