### ISSUE TITLE
[Feature] Mob Drops/Dungeon Loot/Ore Gen/Plant Drops

### ISSUE THREAD

**Issue by yLordMagnus** [shedaniel/RoughlyEnoughItems#193]
Like [Just Enough Resources (JER)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) does, but now on Fabric and in 1.14.4

**Comment by shedaniel** [comment]
I have recently took over the Roughly Enough Resources mods and maintained it, you can now use that mod.
