### ISSUE TITLE
[Bug] "Favorite entry" missing on keybinds

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#207]
**Describe the bug**
Keybind "favorite entry" is missing from vanilla keybind config.

**Steps to Reproduce**
- Look at the vanilla keybind settings

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15
 - Mod Loader: Fabric
- REI 3.2.20

**Logs**
N/A

**Additional context**
N/A

**Comment by shedaniel** [comment]
Working as intended. I plan to not support keybinds in the future as keybinds have an annoying map to hold it, and causes conflict because they both use "A"

**Comment by Madis0** [comment]
I suggest removing all keybinds from vanilla view then and keeping them in a separate tab on REI settings.
