### ISSUE TITLE
Game crash on inventory open [Bug]

### ISSUE THREAD

**Issue by Sarelth** [shedaniel/RoughlyEnoughItems#217]
**Describe the bug**
The Game crashes when attempting to open inventory.

**Steps to Reproduce**
Using MultiMC - 
 1) Install 1.15.1 MC
 2) Install Fabric
 3) Install mods
 4) Run game
 5) Open Inventory & Crash

**Screenshots**
Not able to take one.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1 Run vi MultiMC
 - Mod Loader: Fabric - 0.7.2 - build 175

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/hqnAEEU0

**Additional context**
When I attempted to open inventory, with the E keybind, the game crashed fully to desktop with no error.
 
Loaded Mods:
Fabric API
Hwyla
I need keybinds
Metatips
Mod Menu
Orderly
Roughly Enough Items
Shulker Box Tooltips
Voxelmap

**Comment by shedaniel** [comment]
This is an invalid bug report as there is no logs provided, logs are always generated by minecraft, please check if there is a log in the logs folder called latest.log.

**Comment by Sarelth** [comment]
Updated the bug report. Which had additional mods.

**Comment by shedaniel** [comment]
You have the 1.14 version of REI instead of the required 1.15 version.
