### ISSUE TITLE
Craft with one click if possible

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#22]
Another feature similar to the recipe book - the mod should craft the item instead of just showing the recipe interface when items are available in the inventory and the cheat mode is disabled.

Edit: I noticed strings starting with `text.speed_craft`, is it already in progress?

**Comment by shedaniel** [comment]
Umm, it is already crafting it for you. Trying shift-clicking the plus button.

**Comment by Madis0** [comment]
Right, it does work as expected. However, it is fairly unobvious and uncomfortable, could you add an option to do it with just a click on the item in REI menu?

**Comment by shedaniel** [comment]
It should move 1 item with just a click and all with shift-click.

**Comment by shedaniel** [comment]
Just like NEI / JEI

**Comment by Madis0** [comment]
Let me elaborate:

* If the cheat mode is enabled and player clicks on an item in REI menu, give the item with commands
* If the cheat mode is disabled and player has recipe ingredients (and respective inventory opened), craft/smelt/brew the item (move to correct slot)
* If the cheat mode is disabled and player does not have the ingredients or does not have the correct inventory open, show the recipe

The plus button is a nice extra, but not that useful as a default and only way to do it.

**Comment by shedaniel** [comment]
You mean like this: [https://minecraft.curseforge.com/projects/easiercrafting](https://minecraft.curseforge.com/projects/easiercrafting)?

**Comment by Madis0** [comment]
Yes, like that. But instead of having separate mods it could also be built to REI.

**Comment by shedaniel** [comment]
Not sure if I will do this, as I am just trying to maintain basic functionality as a JEI alterative.

**Comment by shedaniel** [comment]
What if an option in the config which allows you to shift click an item to craft it

**Comment by Madis0** [comment]
Sure, that sounds good too.

**Comment by thiagokenis** [comment]
> What if an option in the config which allows you to shift click an item to craft it

It would be a good feature!

**Comment by shedaniel** [comment]
I will see how I will implement this

**Comment by shedaniel** [comment]
On second thought, no.
