### ISSUE TITLE
duping items 

### ISSUE THREAD

**Issue by Load-of-salt** [shedaniel/RoughlyEnoughItems#224]
![image](https://user-images.githubusercontent.com/54795606/71460093-6a3a8400-2778-11ea-8eb8-5c172fbd7435.png)

I'm using both cloth events and config, and also I'm using version 3.2.31
I'm also on my server, if that helps anything.

**Comment by shedaniel** [comment]
It has been fixed by demeter in his dev environment, don't know when he is going to release the update
