### ISSUE TITLE
when i open mc's creative mode, the style of REI changed

### ISSUE THREAD

**Issue by yzqdev** [shedaniel/RoughlyEnoughItems#230]
**Describe the bug**
when i open mc's creative mode, the style of REI changed. below is the picture.

**Steps to Reproduce**
- open creative mode

**Screenshots**
![image](https://user-images.githubusercontent.com/20037151/71616519-8ebbb380-2bf1-11ea-85c0-27d326e11007.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.4
 - Mod Loader:fabric version 0.7.0

**Comment by shedaniel** [comment]
please try on 1.15
