### ISSUE TITLE
Initializing game

### ISSUE THREAD

**Issue by DatrixTHLK** [shedaniel/RoughlyEnoughItems#237]
**Describe the bug**

I keep crashing to Desktop with REI: 3.3.3/4

**Steps to Reproduce**
- Load up Minecraft
- CTD

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Fabric Loader: 0.7.2+build.175

**Logs**
Crash: https://gist.github.com/DatrixTHLK/a4cb5e54fab248b438a1fe45136b8b36

**Comment by shedaniel** [comment]
Outdated Cloth Config, an updated version should be automatically in REI, you don't need to download it.
