### ISSUE TITLE
Improve recipe shift click

### ISSUE THREAD

**Issue by MelanX** [shedaniel/RoughlyEnoughItems#24]
What I did:
I pressed u (show usae) on sticks. I choosed Ladder. Shift-leftclick on "+". Items were shown:
![2019-02-01_12 28 50](https://user-images.githubusercontent.com/26039509/52120594-0e758280-261d-11e9-9fb2-11c38f836749.png)

After just closing the workbench: 
![2019-02-01_12 31 54](https://user-images.githubusercontent.com/26039509/52120681-5eece000-261d-11e9-8d53-7245a6fc357e.png)
So, the items move into the crafting table but it isn't shown.
This happens sometimes but I can still craft the items.

REI: 2.2.0.47
Minecraft: 19w04b
Fabric: 0.1.5.84

**Comment by shedaniel** [comment]
The speed crafting system is still really buggy, I hope I can fix them quick.

**Comment by shedaniel** [comment]
Shouldn't be closed

**Comment by shedaniel** [comment]
This issue can be fixed by simply reopening the gui, but fixing the bug would be better.

**Comment by Knito58** [comment]
I wanted to craft a blast furnace. Didn't have smooth stone in the inventory and the recipe did show up in REI but did not move the items to the crafting table. In that case it should not have moved the items. Instead it should have shonw the "missing ingredients pattern".

But after I got smooth stone there was the game's message about unlocking some recipes. And after that, in the same minute, the blast furnace's recipe was moved to the crafting table when trying again.

One condition seems to be that the recipe has to be unlocked by the game itself before it can be used by REI.

**Comment by shedaniel** [comment]
As I stated above, the bug can be simply fixed by reopening the gui, but I've been wanting to revamping the whole moving items system all together

**Comment by Knito58** [comment]
No that didn't help in that case. Before the recipe-advancement was made I tried several times opening and closing the GUI. This time I could isolate the unlocking of recipes as one (of x) reason for the issue.

**Comment by shedaniel** [comment]
Fixing in v3.0-pre, hopefully out in September
