### ISSUE TITLE
Repeated crashing when opening inventory & typing in search [Bug]

### ISSUE THREAD

**Issue by Graywaren** [shedaniel/RoughlyEnoughItems#241]
**Describe the bug**
Inconsistently, though multiple times in a row when it happens, REI will crash my game when I open inventory and type to search for items either clicking in the REI search, or if I hit letters on my keyboard without clicking anything.

**Steps to Reproduce**
- Hit e to open inventory
- Either start typing bc I forgot to click in a search bar, or click in REI search bar and start typing. Possibly also trying to use the R/U shortcuts and/or while typing in creative tab search
- Game crashes
- Restart minecraft
- Try again
- Sometimes it crashes again, sometimes it's fine for the next 20 minutes

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.1
 - Fabric

**Logs**
https://pastebin.com/z7jx2vsi

**Additional context**
I am playing on a multiplayer vanilla server only with client side mods. I can't remember if I have encountered this on single player.

**Comment by shedaniel** [comment]
Can you please try with latest REI?

**Comment by Graywaren** [comment]
Yep! I'll give that a shot tomorrow, didn't see there was an update.

**Comment by Graywaren** [comment]
So far this has not happened again with the updated version. I'll comment again if it ever comes back, but seems to be fixed! Thanks!
