### ISSUE TITLE
Trying to change controls will crash the game

### ISSUE THREAD

**Issue by cs127** [shedaniel/RoughlyEnoughItems#252]
Basically, while scrolling down the controls page, when it gets to the Roughly Enough Items section, the game crashes. I've tried it without using any other mods, it still crashes.
I have attached the crash report
[crash-2020-01-22_18.45.27-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/4098002/crash-2020-01-22_18.45.27-client.txt)

**Comment by shedaniel** [comment]
Duplicate of #246
