### ISSUE TITLE
[Feature] Burning times in items

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#255]
It would be nice to see burning times for fuel types in smeltable items count instead of ticks, similar to 
https://minecraft.gamepedia.com/Smelting#Items_that_can_be_used_as_fuel 

Essentially just divide tick values by 200 and divide that by 2 if in a blast/smoker furnace.

**Comment by shedaniel** [comment]
I'd rather not have this. We can display the burning time as seconds though.
