### ISSUE TITLE
REI still works when hidden

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#26]
Using REI 2.1.0.15 on Minecraft 1.13.2 (Rift fork).

When hiding REI with it's keybind (default `o`), it still reacts to clicks made inside it's area - with cheat mode it gives the respective items, without cheat mode it shows recipes where available.

May be related to #15

**Comment by shedaniel** [comment]
Thanks for reporting <3 Reproduced
