### ISSUE TITLE
[Bug] Smooth Scrolling config menu has placeholder values

### ISSUE THREAD

**Issue by JessiAuro** [shedaniel/RoughlyEnoughItems#266]
**Describe the bug**
The config screen for smooth scrolling in v3.4.0 has a placeholder title and a tab which is a placeholder/ui test for Cotton Config.

**Steps to Reproduce**
- Open config screen
- Click "Smooth Scrolling Settings"

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric
 - Mod Version: 3.4.0

**Screenshots**
![2020-02-12_00 24 47](https://user-images.githubusercontent.com/48600976/74316391-4df5a500-4d2e-11ea-82e7-1ddd5c0b1136.png)
![2020-02-12_00 24 44](https://user-images.githubusercontent.com/48600976/74316398-50f09580-4d2e-11ea-93cf-838d27be98ff.png)

**Logs**
Not applicable.

**Comment by shedaniel** [comment]
Cotton Config? How did that get into here?

REI "Smooth Scrolling Settings" will open Cloth Config which actually is the smooth scrolling settings, not a placeholder.

**Comment by JessiAuro** [comment]
Hmm, when I run it on a fresh install I don't have the issue, so it must be a weird interaction with another mod.

**Comment by JessiAuro** [comment]
That Smooth Scrolling button doesn't show up on a fresh install, it just seems odd that other mods I have installed could somehow affect your config screen unless it's a bug in Cotton Config.

**Comment by shedaniel** [comment]
Are you sure, the Smooth Scrolling Settings button should show up regardless of mods.

**Comment by JessiAuro** [comment]
Yeah, it's just not there. I created a fresh instance of 1.15.2 with MultiMC, installed fabric, the latest fabric api, and REI 3.4.0.

I don't see anything useful showing up in the log, but I'll attach it.
https://pastebin.com/nfjUJT8p


![2020-02-12_00 47 26](https://user-images.githubusercontent.com/48600976/74318044-54d1e700-4d31-11ea-824d-80d4a9035055.png)

I guess it's just shy.

**Comment by JessiAuro** [comment]
Also it appears I mixed up Cotton Config and Cloth config, my bad.

**Comment by shedaniel** [comment]
oh right, it only show up if modmenu is installed currently.

**Comment by JessiAuro** [comment]
Now we're back to this:
![2020-02-12_01 13 23](https://user-images.githubusercontent.com/48600976/74320154-fc044d80-4d34-11ea-81ff-78d75d5cc51b.png)

**Comment by shedaniel** [comment]
click scrolling on top, the demo part can be ignored.
