### ISSUE TITLE
REI v2.2.0.47: Second page shows wrong recipies

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#27]
Second page seems ok but shows recipies of first page.
Reprod: Filtered items for "@that" with "this & that" mod installed.

**Comment by shedaniel** [comment]
Can I have a screenshot of those?

**Comment by Knito58** [comment]
Ok you can make the bug work right away. No filtering needed. Just get the second page and click on the item's icon. The recipe shown is the one from the item in the same place on the first page.

**Comment by Knito58** [comment]
Some more details: Fabric loader 0.3.5.105, Game version 19w05a.6, fabric 0.1.5.88

**Comment by Knito58** [comment]
Found it working properly atm after a fresh world reload. But flipping the page back and forth instantly brings the bug back. Filtering and/or page flipping seem to enable the bug.

**Comment by shedaniel** [comment]
Alright, thanks for reporting the bug. However, I can't reproduce the bug.

**Comment by Madis0** [comment]
FWIW, I think this is the easiest way to reproduce:

1. Open a recipe in the "show all" view
2. Toggle "show all" to "show craftables"
3. Click the same positions as in "show all" view
4. REI will show recipes for items of "show all" view, not of "show craftables" view

**Comment by Knito58** [comment]
v2.2.0.49: Not fixed yet. But looking closer the bug is not fixed to the first page but to the page where the last recipe was shown successfully. Then flipping to next or previous page and clicking on the icon in the same space shows the wrong recipe.

**Comment by shedaniel** [comment]
~Related to #15~

**Comment by shedaniel** [comment]
Fixing in REI v2.4
