### ISSUE TITLE
Crash while opening GUI 

### ISSUE THREAD

**Issue by Dragonracer1973** [shedaniel/RoughlyEnoughItems#274]
**Describe the bug**
Downloaded Version 3.5.2 and Upon loading into a flat world to try out a new mod (Mob Grinder) this happened 

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
1.15.2 REI version 3.5.2
 - Mod Loader: [e.g. forge, fabric]
Fabric Version Loader 0.7.6+build 181 Api 0.4.32+build.292
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash-2020-02-21_16.48.17-client - Copy.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/4238364/crash-2020-02-21_16.48.17-client.-.Copy.txt)
**Additional context**

**Comment by Dragonracer1973** [comment]
Nevemind, I was unaware the Fabric Loading API had been updated

**Comment by shedaniel** [comment]
Confirmed, fixing later

**Comment by shedaniel** [comment]
Use 3.5.0 for now
