### ISSUE TITLE
REI Crashes when loging in to my Server[Bug]

### ISSUE THREAD

**Issue by Issacozzman** [shedaniel/RoughlyEnoughItems#279]
**Describe the bug**
Chashes Client when loging in my Server 

**Steps to Reproduce**
- First Step Log in Server 
- Second Step Log in Server 

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 20w19a
 - Mod Loader: Fabric
**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/5BVJgNwz
**Additional context**

**Comment by shedaniel** [comment]
Please report this issue again in another issue if this persists on latest snapshot or release.
