### ISSUE TITLE
[20w10a] Game Crashes when trying to delete text in world creation screen

### ISSUE THREAD

**Issue by Sar4h-3** [shedaniel/RoughlyEnoughItems#288]
hi, i downloaded the newest versions of both fabric API (build.304-1.16) and the REI version (4.0.6 unstable) and when trying to delete the text out of the text box, the game crashes. Here´s the log: https://paste.ee/p/mA4zy. I hope you can help me.

**Comment by shedaniel** [comment]
retry after updating REI
