### ISSUE TITLE
[20w10a]The game crash[Bug]

### ISSUE THREAD

**Issue by skyinr** [shedaniel/RoughlyEnoughItems#294]
**Describe the bug**
Initializing game

**Steps to Reproduce**
Initializing game

**Environment (please complete the following information with the version):**
 - Minecraft: [20w10a]
 - Mod Loader: [fabric]

**Logs**
[crash-2020-03-08_12.40.18-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/4302832/crash-2020-03-08_12.40.18-client.txt)

**Comment by shedaniel** [comment]
You didn't install Fabric API
