### ISSUE TITLE
New Version Crashes on 1.13.2

### ISSUE THREAD

**Issue by leeadama** [shedaniel/RoughlyEnoughItems#3]
The addon loads and I can see the item listing when a crafting table is up, but when I click on any of the items the client crashes.  

Link to error Log : https://paste.ee/p/SpO72
short video showing what happens : https://youtu.be/Q_AHMw5Xkog

If I can do anything else to help you figure it out please let me know.

Thanks.

**Comment by shedaniel** [comment]
Reproduced only with the recipe book opened. Thanks for reporting <3
I will fix this asap

**Comment by shedaniel** [comment]
Fixed in 1.4b-6, please tell me if the problem proceeds.
