### ISSUE TITLE
[Bug] Fabric and Optifine crashes with REI on 1.15.2 3.6.4

### ISSUE THREAD

**Issue by JAWalmsley** [shedaniel/RoughlyEnoughItems#303]
**Describe the bug**
When installing optifine with optifabric, the game will crash

**Steps to Reproduce**
- Install optifabric and optifine
- Install REI
- Crashes game

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/bazHgaUU

**Comment by shedaniel** [comment]
Update optifabric
