### ISSUE TITLE
Cannot close all containers with TAB even when the TAB fix setting is enabled

### ISSUE THREAD

**Issue by Jannis636** [shedaniel/RoughlyEnoughItems#304]
**Describe the bug**
When you remove the recipe book and enable the option to close containers with TAB you still cannot close anvil containers and also when you open a recipe with "r" you cannot close that container either.

**Steps to Reproduce**
- Disable the recipe book in the settings under "Modules"
- Enable the tab fix also in the settings
-> Here you go. You can test it yourself

**Environment (please complete the following information with the version):**
 - Minecraft: 20w12a
 - Mod Loader: fabric

**Comment by shedaniel** [comment]
Will look into this issue soon.

**Comment by shedaniel** [comment]
Should be fixed.
