### ISSUE TITLE
[Bug] Scrolling in creative mode is inconsistent (mc 1.15.2)

### ISSUE THREAD

**Issue by Fixer-007** [shedaniel/RoughlyEnoughItems#308]
**Describe the bug**
Either creative tabs get scrolled or REI tab gets scrolled depending on mouse pointer position.

**Steps to Reproduce**
1. Creative mode
2. Open inventory, move mouse to REI list, scroll while pointing at middle of the list, then move pointer to bottom of the list, scroll, then top of the list, scroll, observe that REI list scrolls only when mouse points in the middle of the list, see screenshot.

**Screenshots**
![зображення](https://user-images.githubusercontent.com/16494741/78451796-5adca800-7690-11ea-93bb-5e89d4554475.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2 / Windows 7
 - Mod Loader: fabric loader 0.7.8+build.189/fabric api 0.5.0+build.239-1.15
 - REI 3.6.4

**Comment by shedaniel** [comment]
I can not fix this, scrolling in creative tabs is not a feature of REI nor vanilla, it is a feature from another mod.

**Comment by Fixer-007** [comment]
After some figuring out it turns out it is "Mouse Wheelie" mod feature that conflicts with REI.
