### ISSUE TITLE
[Bug] Favourites cover Tech Reborn upgrade slots

### ISSUE THREAD

**Issue by Tanath** [shedaniel/RoughlyEnoughItems#312]
**Describe the bug**
Favourites cover Tech Reborn upgrade slots. Mousing over shows tooltips for both things.

**Steps to Reproduce**
- Install [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) & REI.
- Place [Tech Reborn machines](https://wiki.techreborn.ovh/doku.php?id=blocks#machines). Upgrade slots on left in interface are accessible.
- Add 1 or more full rows of favourites in REI. Note they cover the upgrade slots.

**Screenshots**
![screenshot](https://imgur.com/TvWMkP6.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Additional context**
I think shortening the number of favourites in a row by 1 should fix the issue.

**Comment by shedaniel** [comment]
Roughly Enough Items provides an API to register exclusion zones, the results are like this: 
![image](https://user-images.githubusercontent.com/34910653/79044124-f2646c80-7c35-11ea-8f24-eb9d2f3b0597.png)

Please report an issue on their side
