### ISSUE TITLE
[Bug] Weird split button rendering with large window size

### ISSUE THREAD

**Issue by sargunv** [shedaniel/RoughlyEnoughItems#318]
**Describe the bug**
When I maximize the window or go to full screen in the settings screen, the buttons at the bottom render in this weird split way. They still function fine. My display is 2560x1440, If I go a bit smaller than that, the buttons revert to normal.

**Screenshots**
![](https://i.imgur.com/F1Tk8NI.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Logs**
https://paste.ee/p/NpZYG

**Comment by shedaniel** [comment]
Vanilla issue, I don't plan to fix this so rip

**Comment by shedaniel** [comment]
move to shedaniel/ClothConfig#46
