### ISSUE TITLE
[Bug] Crashing to Desktop after pressing ESC Button

### ISSUE THREAD

**Issue by Issacozzman** [shedaniel/RoughlyEnoughItems#319]
**Describe the bug**
I get a Crash to Desktop after pressing ESC Button to get out of INV Screen in the Latest Update

**Steps to Reproduce**
Enter in to Inventory Screen
Press ESC Button 
Crash 

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 20w16a JAVA
 - Mod Loader: Fabric 

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/3RLdmUwx

**Additional context**

**Comment by Issacozzman** [comment]
This Crash dose not Happen in the 4.1.8 Version on the Mod if that Helps

**Comment by shedaniel** [comment]
Can you try with this: https://send.firefox.com/download/d70cdfc3ab367d34/#UbVN5djI3RRU2SW1uT69Aw

**Comment by Issacozzman** [comment]
Loading it up now

**Comment by Issacozzman** [comment]
That seemed to fix it thanks

**Comment by Issacozzman** [comment]
Yes its fixed Thanks Again and Keep up the Great Work on this Mod I cant live without it
Issac
