### ISSUE TITLE
Smelting progress texture overlaps with brewing stand texture

### ISSUE THREAD

**Issue by TechniKris** [shedaniel/RoughlyEnoughItems#32]
**Problem:** In the smelting menu both the remaining fuel time texture and the smelting progress texture have the top pixel cut off.
**Cause:** The smelting progress texture overlaping with the brewing stand texture. What I mean by that is: the textures themselves don't overlap, but the game grabs the texture from too low.

The cut-off texture in-game
![image](https://user-images.githubusercontent.com/30842158/52458919-6999fe80-2b62-11e9-8615-42fe24922241.png)

I added two 1-pixel-wide lines at the very top of the brewing stand texture using a resourcepack
![image](https://user-images.githubusercontent.com/30842158/52458950-ad8d0380-2b62-11e9-99f1-25060f9de4da.png)

The same lines appear on the arrow
![image](https://user-images.githubusercontent.com/30842158/52458968-c1d10080-2b62-11e9-964c-037807e5d668.png)

Tested on _[Rift 1.13.2] v2.2.0.16_ and _[Fabric 19w05a] v2.2.0.49_. Both yield the same result.

**Comment by shedaniel** [comment]
Thanks for reporting, currently on vacation, will fix the issue when I am back
