### ISSUE TITLE
[Feature] Add method to update FilteringEntry's cached stacks

### ISSUE THREAD

**Issue by Linguardium** [shedaniel/RoughlyEnoughItems#322]
**Describe the solution you'd like**
implement a method in RoughlyEnoughItemsCore (or other) that allows refreshing the entrystack list in FilteringEntry. 

**Additional context**
Currently, i dynamically add items to the server on load via libcd and to the client on load via a custom packet. because of the dynamic nature, the items are added to the item registry after load. REI will retain incorrect item stacks between game sessions. These items cannot be given to the player via cheat, nor are they a part of recipes and anything else (as the game does not have these old items registered anymore)
I cannot force update the cached stacks, but if the user types any search criteria, the stacks refresh and are correct.

**Comment by shedaniel** [comment]
From what I understand, you simply want a method to refresh the cache like how searching does it?

**Comment by Linguardium** [comment]
yep
Ideally a method/message to tell REI that the entrystack has been updated and to refresh it on its own

**Comment by Linguardium** [comment]
Is it safe to say getPreFilteredList will provide the currently cached items while getStacksList provides the "real" list for when it refreshes?

**Comment by shedaniel** [comment]
nope, you should use `getPreFilteredList` anyways, the prefiltered list never changes after you join a world unless you change the config filtering, prefiltered list is just for prefiltering the config filtering

**Comment by shedaniel** [comment]
Basically I need a hook for api to call this https://github.com/shedaniel/RoughlyEnoughItems/blob/e2a97e33f9df882e34f0480d5d023c8678e64add/src/main/java/me/shedaniel/rei/gui/widget/EntryListWidget.java#L557

**Comment by Linguardium** [comment]
what i've experienced, is that when adding stacks after the lists are generated, if i add to prefiltered, the stacks are lost if going into settings and changing one of several settings.
if adding to getStacksList, it wont show up until i go into settings and mess with settings.
if added to both, it shows up and continues to work (though, i am adding via registerEntryAfter rather than getStacksList)

I am sure this isnt an issue if adding via the registerItems plugin stuff, but as i mentioned, i need to be able to modify the list after loading. under normal operation, both lists should be identical (unless filters are in place in the settings, of course)

**Comment by shedaniel** [comment]
both lists are identical unless filters are in the settings, but when the settings change, the prefiltered list is recalculated from the stack list. the current system is not designed to be changed after init, what you want to do is to edit the stack list and run the following code to refresh the cache:
```java
((EntryRegistryImpl) EntryRegistry.getInstance()).refilter();

// Clear Cache Again!
((DisplayHelperImpl) DisplayHelper.getInstance()).resetCache();
ScreenHelper.getOptionalOverlay().ifPresent(overlay -> overlay.shouldReInit = true);
```

However none of this code is in the API, I might consider exposing these into the API.
