### ISSUE TITLE
Typo on README

### ISSUE THREAD

**Issue by lobsterwise** [shedaniel/RoughlyEnoughItems#323]
There is a misspelling:
                                                            HERE v
Cloth, which is Roughly Enough Items's depenency,

**Comment by shedaniel** [comment]
? Where

**Comment by lobsterwise** [comment]
"dependency" is incorrectly spelled as "depenency"

**Comment by shedaniel** [comment]
Fixed in 4.x readme, too lazy to fix on the 3.x one :^)
