### ISSUE TITLE
[Bug] Crash on no user event

### ISSUE THREAD

**Issue by AstragoDE** [shedaniel/RoughlyEnoughItems#326]
**Describe the bug**
Sometimes Minecraft crashes for no reason 

**Steps to Reproduce**
- Play Minecraft
- wait a few minutes
- CRASH

**Screenshots**
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2020-04-28 13:16:46 MESZ
Description: Rendering screen

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.15)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.getCurrentGameMode(ContainerScreenOverlay.java:490)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.access$300(ContainerScreenOverlay.java:66)
    at me.shedaniel.rei.gui.ContainerScreenOverlay$4.render(ContainerScreenOverlay.java:278)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:635)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:567)
    at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$7(RoughlyEnoughItemsCore.java:295)
    at me.shedaniel.rei.RoughlyEnoughItemsCore$$Lambda$1800/777118307.render(Unknown Source)
    at net.minecraft.client.gui.screen.Screen.handler$zdd000$onPostDraw(Screen:1091)
    at net.minecraft.client.gui.screen.Screen.render(Screen:83)
    at net.minecraft.client.gui.screen.ingame.ContainerScreen.render(ContainerScreen:87)
    at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen:42)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen:91)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:803)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:989)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.main.Main.main(Main:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: net.minecraft.class_490
  Mouse location: Scaled: (844, 127). Absolute: (2533.000000, 382.000000)
  Screen size: Scaled: (854, 463). Absolute: (2560, 1387). Scale factor of 3.000000

-- Affected level --
  All players: 1 total; [class_746['Astrago'/48540, l='MpServer', x=234.76, y=4.00, z=442.60]]
  Chunk stats: Client Chunk Cache: 18225, 171
  Level dimension: minecraft:overworld
  Level name: MpServer
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: {}
  Level spawn location: World: (-217,4,1253), Chunk: (at 7,0,5 in -14,78; contains blocks -224,0,1248 to -209,255,1263), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
  Level time: 654761 game time, 1 day time
  Known server brands: 
  Level was modded: false
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT-GOMME:2b88b0f:unknown) <- Spigot
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3453429912 bytes (3293 MB) / 6375342080 bytes (6080 MB) up to 10737418240 bytes (10240 MB)
  CPUs: 16
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Roughly Enough Items (roughlyenoughitems), Fabric Loader (fabricloader)
  Fabric Mods: authme: Auth Me 1.1.1
               autoconfig1u: Auto Config v1 Updated 2.0
               blue_endless_jankson: jankson +
               carpet: Carpet Mod in Fabric 1.3.19
               cloth: Cloth Events 1.2.0
               cloth-basic-math: Cloth Basic Math 0.4.1
               cloth-config2: Cloth Config v2 2.13.1
               cmdkeybind: Command Macros 1.4.2
               csb: Custom Selection Box Fabric 4.1.0
               dark-loading-screen: Dark Loading Screen 1.2.0
               fabric: Fabric API 0.5.12+build.296-1.15
               fabric-api-base: Fabric API Base 0.1.2+28f8190f42
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+0fb9af840c
               fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabricloader: Fabric Loader 0.8.0+build.192
               lightoverlay: Light Overlay 4.3
               litematica: Litematica 0.0.0-dev.20200302.233247
               loadcatcher: Entrypoint Catcher 1.1.0
               malilib: MaLiLib 0.10.0-dev.20+arne.6
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               minecraft: Minecraft 1.15.2
               minihud: MiniHUD 0.19.0-dev.20200121.203515
               mm: Manningham Mills 2.0
               modmenu: Mod Menu 1.10.2+build.32
               multiconnect: MultiConnect 1.2.2
               multiconnect-api: MultiConnect API 1.2.2
               notenoughcrashes: Not Enough Crashes 1.2.3+1.15.1
               okzoomer: Ok Zoomer 2.1.4-1.15.2
               optifabric: Optifabric 1.0.0-beta8
               orderly: Orderly 1.2.1+build.4-1.15
               org_jetbrains_annotations: annotations 18.0.0
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               replaymod: Replay Mod 1.15.2-2.3.0-b1
               roughlyenoughitems: Roughly Enough Items 3.6.6
               roughlyenoughresources: Roughly Enough Resources 1.3.2
               shuffle: Shuffle 1.14.4-1.15.2-20w07a-1.1.1
               terraform: Terraform 1.4.4+build.33
               vanillaplusbiomes: Vanilla Plus Biomes 0.1.3
               worldedit: WorldEdit 7.1.0;8e55131
  Launched Version: fabric-loader-0.8.0+build.192-1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, optifine, file/VanillaTweaks_NEU.zip
  Current Language: Deutsch (Deutschland)
  CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
  Launched Version: fabric-loader-0.8.0+build.192-1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, optifine, file/VanillaTweaks_NEU.zip
  Current Language: Deutsch (Deutschland)
  CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2020-04-28 13:16:46 MESZ
Description: Rendering screen

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.15)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.getCurrentGameMode(ContainerScreenOverlay.java:490)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.access$300(ContainerScreenOverlay.java:66)
    at me.shedaniel.rei.gui.ContainerScreenOverlay$4.render(ContainerScreenOverlay.java:278)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:635)
    at me.shedaniel.rei.gui.ContainerScreenOverlay.render(ContainerScreenOverlay.java:567)
    at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$7(RoughlyEnoughItemsCore.java:295)
    at me.shedaniel.rei.RoughlyEnoughItemsCore$$Lambda$1800/777118307.render(Unknown Source)
    at net.minecraft.client.gui.screen.Screen.handler$zdd000$onPostDraw(Screen:1091)
    at net.minecraft.client.gui.screen.Screen.render(Screen:83)
    at net.minecraft.client.gui.screen.ingame.ContainerScreen.render(ContainerScreen:87)
    at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen:42)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen:91)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:803)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:989)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.main.Main.main(Main:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: net.minecraft.class_490
  Mouse location: Scaled: (844, 127). Absolute: (2533.000000, 382.000000)
  Screen size: Scaled: (854, 463). Absolute: (2560, 1387). Scale factor of 3.000000

-- Affected level --
  All players: 1 total; [class_746['Astrago'/48540, l='MpServer', x=234.76, y=4.00, z=442.60]]
  Chunk stats: Client Chunk Cache: 18225, 171
  Level dimension: minecraft:overworld
  Level name: MpServer
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: {}
  Level spawn location: World: (-217,4,1253), Chunk: (at 7,0,5 in -14,78; contains blocks -224,0,1248 to -209,255,1263), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
  Level time: 654761 game time, 1 day time
  Known server brands: 
  Level was modded: false
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT-GOMME:2b88b0f:unknown) <- Spigot
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3453429912 bytes (3293 MB) / 6375342080 bytes (6080 MB) up to 10737418240 bytes (10240 MB)
  CPUs: 16
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Roughly Enough Items (roughlyenoughitems), Fabric Loader (fabricloader)
  Fabric Mods: authme: Auth Me 1.1.1
               autoconfig1u: Auto Config v1 Updated 2.0
               blue_endless_jankson: jankson +
               carpet: Carpet Mod in Fabric 1.3.19
               cloth: Cloth Events 1.2.0
               cloth-basic-math: Cloth Basic Math 0.4.1
               cloth-config2: Cloth Config v2 2.13.1
               cmdkeybind: Command Macros 1.4.2
               csb: Custom Selection Box Fabric 4.1.0
               dark-loading-screen: Dark Loading Screen 1.2.0
               fabric: Fabric API 0.5.12+build.296-1.15
               fabric-api-base: Fabric API Base 0.1.2+28f8190f42
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+0fb9af840c
               fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabricloader: Fabric Loader 0.8.0+build.192
               lightoverlay: Light Overlay 4.3
               litematica: Litematica 0.0.0-dev.20200302.233247
               loadcatcher: Entrypoint Catcher 1.1.0
               malilib: MaLiLib 0.10.0-dev.20+arne.6
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               minecraft: Minecraft 1.15.2
               minihud: MiniHUD 0.19.0-dev.20200121.203515
               mm: Manningham Mills 2.0
               modmenu: Mod Menu 1.10.2+build.32
               multiconnect: MultiConnect 1.2.2
               multiconnect-api: MultiConnect API 1.2.2
               notenoughcrashes: Not Enough Crashes 1.2.3+1.15.1
               okzoomer: Ok Zoomer 2.1.4-1.15.2
               optifabric: Optifabric 1.0.0-beta8
               orderly: Orderly 1.2.1+build.4-1.15
               org_jetbrains_annotations: annotations 18.0.0
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               replaymod: Replay Mod 1.15.2-2.3.0-b1
               roughlyenoughitems: Roughly Enough Items 3.6.6
               roughlyenoughresources: Roughly Enough Resources 1.3.2
               shuffle: Shuffle 1.14.4-1.15.2-20w07a-1.1.1
               terraform: Terraform 1.4.4+build.33
               vanillaplusbiomes: Vanilla Plus Biomes 0.1.3
               worldedit: WorldEdit 7.1.0;8e55131
  Launched Version: fabric-loader-0.8.0+build.192-1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, optifine, file/VanillaTweaks_NEU.zip
  Current Language: Deutsch (Deutschland)
  CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
  Launched Version: fabric-loader-0.8.0+build.192-1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, optifine, file/VanillaTweaks_NEU.zip
  Current Language: Deutsch (Deutschland)
  CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Additional context**

**Comment by shedaniel** [comment]
Can you update Roughly Enough Items to the latest version for 1.15.2 and see if it crashes?

**Comment by AstragoDE** [comment]
Sure. I will keep you updated

**Comment by shedaniel** [comment]
Closing this due to no updates from the issue author
