### ISSUE TITLE
[Feature] Search in nearby inventories (chests etc)

### ISSUE THREAD

**Issue by rapus95** [shedaniel/RoughlyEnoughItems#327]
**Describe the solution you'd like**
NEI had a feature to search in nearby inventories that made every chest getting some sort of marker (like particles) that contains the item which is currently selected in the mod filter. That way it was easy to find an item in a large amount of chests w/o having to look into each.
(like that: https://www.reddit.com/r/feedthebeast/comments/414i11/nei_tip_for_quickly_finding_items_in/)

**Comment by shedaniel** [comment]
This is out of the scope of REI, I will not be adding this, please ask someone else for this to be an independent mod.

**Comment by rapus95** [comment]
is there some plugin mechanic/api which one could use to access the currently selected item of REI? (to use it as input to such a mod)
