### ISSUE TITLE
Cannot see Item list[Bug]

### ISSUE THREAD

**Issue by iamcurse** [shedaniel/RoughlyEnoughItems#332]
**Describe the bug**
Cannot see item list in inventory menu.

**Steps to Reproduce**
-open inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/28333142/80855852-dff6b500-8c6e-11ea-8584-2341c1b5fcc2.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/zayZx7Z3

**Additional context**
No

**Comment by shedaniel** [comment]
1.14 is no longer supported.
