### ISSUE TITLE
[Feature] Missing firework recipes

### ISSUE THREAD

**Issue by ChabaneAmaury** [shedaniel/RoughlyEnoughItems#333]
**Describe the bug**
Some items are missing recipes

**Steps to Reproduce**
I have currently in mind the firework rocket:
- Go in your inventory and search for the firework rocket
- Try to show the recipe

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: fabric

**Logs**
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/4568011/latest.log)

**Comment by shedaniel** [comment]
Fireworks doesn't relay on normal json recipes, which is why you don't see it in recipe books as well, I need to hardcode if I am implementing this

**Comment by ChabaneAmaury** [comment]
Oh ok I see. You sure there isn't another way ? Because I remember it was in NEI some time ago, so I guess there still is another way (with changing crafts like the wiki)

**Comment by MorningSage** [comment]
I was going to open another issue for this, but I'm not sure if this also falls under the "wontfix" portion?

On the Forge version, the plain fireworks recipe does not show up at all.  Fabric at least shows something, but while using Forge, hovering over the fireworks item in REI and hitting R does not do anything.

Shall I open an issue for this as I'd expect at least one to show up on Forge like it does on Fabric?  Or is this a difference in recipe handling between the modloaders and not something to address?

**Comment by shedaniel** [comment]
The Forge specific issue is not related to this issue.
