### ISSUE TITLE
[Bug] Crash from the mods REI uses.

### ISSUE THREAD

**Issue by MagmaSlime123** [shedaniel/RoughlyEnoughItems#334]
**Describe the bug**
Game crashes with no report being created.

**Steps to Reproduce**
Install REI with the 2 mods it requires.

**Screenshots**
See below.

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric]
Latest Fabric API/Loader on 20w19a.

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
REI requires 2 other mods that when added, cause the game to insta-crash, with no report being created.
![image](https://user-images.githubusercontent.com/51277766/81458808-57d24d00-9151-11ea-97e9-05a57cbbe3e8.png)
It's mainly Cloth Events that causes this, the other random mod your wanting may do this too, but I don't know. Otherwise, the mods your requiring to run REI cause issues.

**Additional context**
None.

**Comment by shedaniel** [comment]
The two mods both have beta versions to support snapshots, and REI doesn't require you to install them manually since it's already in the jar

**Comment by MagmaSlime123** [comment]
Well, REI just insta-crashes on its own. So it can't be used.

**Comment by shedaniel** [comment]
Remove the two mods and send logs

**Comment by MagmaSlime123** [comment]
The game loaded fine apparently...


Well, the Curse page may wanna mention that those 2 mods don't need to be installed since it causes issues.

Issues fixed I guess, ugh.

**Comment by shedaniel** [comment]
It does not cause issue, you just installed the wrong versions of the two mods.
![image](https://user-images.githubusercontent.com/34910653/81478742-c991c000-9251-11ea-8596-5a8cadce6413.png)
Also it says bundled
