### ISSUE TITLE
[Feature] Allow filtering to optionally filter recipes as well

### ISSUE THREAD

**Issue by ejektaflex** [shedaniel/RoughlyEnoughItems#338]
**Describe the solution you'd like**
Currently, filtering changes which items show up in REI's item menu on the right side of the screen. However, you can click through the possible recipes by left/right clicking on an item and *still find other items in the modpack that way*. 

Example: Filter out all items except for a Gold Ingot. Now go into JEI and click on it. You can see all recipes using a Gold Ingot and that make Gold Ingots - but perhaps we don't want those to show up?

For some modpacks, this might be a bad thing if you're trying to hide some items from the player (as I am doing).

A good solution would be to add a single option in the config menu:
* One option to limit recipes shown to require all ingredients to also pass through the filter.

Example of what I mean:

If you made a filter for only: [Sticks, Cobblestone, Iron Ingots, Stone Sword, Iron Sword], then the game would only show recipes for these items:
* Stone Sword
* Iron Sword

And the game would NOT show recipes for any of these items, because their ingredients do not also pass the filter:
* Wooden Sword (Planks do not match filter)

This would allow for much greater flexibility when it comes to which items to show the player, and not give them recipes that require items *that don't even show up in REI*.

**Additional context**
This is also very helpful for adventure maps - because some items are unobtainable, so it's misleading to show them recipes that require an item that they could never get anyways.

**Comment by shedaniel** [comment]
Filtering recipes via filtered stacks is a feature now
