### ISSUE TITLE
Item models with multiple cubes are not rendered correctly upon recipe export

### ISSUE THREAD

**Issue by FoundationGames** [shedaniel/RoughlyEnoughItems#339]
**Bug:**
Item models with multiple cubes are not rendered correctly upon recipe export

**Steps to Reproduce**
-Create an item model with cube faces hidden behind other cubes (as viewed from item icon)
-Find REI Recipe with respective item
-Export recipe
-See cube faces rendered on top of cubes they shouldn't be rendered on top of

**Environment**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric

**Comment by shedaniel** [comment]
Please send an image of the exported recipe

**Comment by FoundationGames** [comment]
![image](https://user-images.githubusercontent.com/43485105/82930053-9a5d9d00-9f39-11ea-8462-31ca1d2f936e.png)

**Comment by shedaniel** [comment]
ah this is annoying, I guess I would remove this feature from 1.15, since I did remember fixing it after spending a long time on 1.15

**Comment by shedaniel** [comment]
Fixed.
