### ISSUE TITLE
Filter method

### ISSUE THREAD

**Issue by DanShu15** [shedaniel/RoughlyEnoughItems#342]
I'm sorry to waste your time but I couldn't find the syntax for how to filter things in the wiki and the methods for NEI were different (drop down menu, iirc). I'm on the 1.15.2 latest version

	"filtering": { 
		"filteredStacks": [ 
]

How would I filter out recipes for SimplePipeTest and Exotic Blocks?

Two other things real quickly - would it be possible to filter an entire group by mod like that but then re-enable 1 type of a recipe? I've got 407 pages of recipes, mostly because of those two mods - but it'd be handy for someone to be able to see the birch version of a set of Exotic Blocks.

-Third and last thing was the 1.14 bug report that gent made earlier about not being able to see recipe's. With a boatload of recipes like I have, it takes over a minute for the recipe's to load up. I'd imagine that's what his issue was, and he could wait for REI to catch up. 

I'm hoping filtering those recipes will resolve it for me :)
Thanks!

**Comment by shedaniel** [comment]
1.14 REI is heavily outdated, sorry, there was a lot of development in 1.15.

As for filtering, it is impossible to filter out **recipes**, but what you can do is to filter out the items, you can open up the config screen, click the "Filtering" category, and drag the part you don't want and click hide.

**Comment by shedaniel** [comment]
The config isn't meant to be edited by hand, the gui is responsible for editing it because it is complicated

**Comment by DanShu15** [comment]
Ahh!
With it so bogged down my filtering tab was blank before and I just moved to the next tab without even noticing it was a "filter" tab.
Much easier than I thought :)
Thanks!
