### ISSUE TITLE
REI Slow with a lot of entries

### ISSUE THREAD

**Issue by DanShu15** [shedaniel/RoughlyEnoughItems#343]
**Describe the solution you'd like**
A way to filter items out that saves it's state and no longer checks for those items, and a way to call items that have been saved as filtered to be accessed for reverting items back to the list.
**Additional context**
When a mod has hundreds of recipes generated it delays REI's loading (for me it was Exotic Blocks and Simple Pipes). When you have 400 pages of options it can take 2 to 3 minutes for REI to load (8700k processor, 2080 video card, 32gb of ram with 8gb to the client and a 16gb dedicated server).

When you filter those recipes out the problem persists because they're still being checked for.
This is the report made to Simple Pipes https://github.com/AlexIIL/SimplePipes/issues/39 and I thought maybe something like a hard list where known items aren't bothered with unless it's intentionally refreshed might be a possible solution and improvement to REI in general

**Comment by shedaniel** [comment]
Yes I do need to profile and optimise this.

To get more context, is REI slow on init (on world load / datapacks reload), or is REI slow on accessing the recipes or searching?
Also would like to get a log.

**Comment by DanShu15** [comment]
it didn't noticeably affect load times at all thankfully, you just go into a crafting table or your inventory and there's nothing showing on the right hand side (similar to what was reported with 1.14 a while back).
At this point if you try to go into the modmenu for REI it says reloading plugins, then works fine after a while but you're stuck there until it's finished.
If you don't go into its options you can do anything you want, searches just don't work and nothing shows on the right-hand side for a minute or so, then everything loads fine and it works normally after that.
I'm quite a few updates past taking out Simple Pipes and Exotic Blocks, so I can't really do a server log without disrupting everyone. With the massive amount of recipes they add a single player install with just fabric, exotic blocks, simple pipes, and REI will probably reproduce it.
Or just add those two mods to any thoroughly modded install you have, load the world and go into your inventory, a crafting table, or modmenu and try opening the REI menu

**Comment by shedaniel** [comment]
Does it also affect the time opening recipes after everything is registered? and the time searching?

**Comment by DanShu15** [comment]
No, it only seemed to affect the initial load time of the list. It might have a bigger impact on slower machines, but I didn't get much information on it since I noticed the problem and removed the two mods with the most entries before I put out the next update

**Comment by shedaniel** [comment]
Should be fixed in the latest versions.
