### ISSUE TITLE
"no handlers are applicable" when hovering over the + button on an improper crafting menu.

### ISSUE THREAD

**Issue by AwwShoot** [shedaniel/RoughlyEnoughItems#348]
**Describe the bug**
When hovering over the + button on a recipe provided by REI, the button displays "no handlers are applicable" if the recipe involves a crafting menu that's not the 2x2 or 3x3 crafting menu (e.g. furnaces, brewing stands, ect) and the player is not currently in that recipe's menu.

**Steps to Reproduce**
- open inventory
- press <recipe button> over an item with a furnace recipe
- go to the furnace tab
_ hover over the + button on the recipe menu

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.15.2] more specifically AoF 2 3.0.0
 - Mod Loader: [fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by shedaniel** [comment]
This is not a bug, this is intended as you can't move furnace items while not opening a furnace.

**Comment by MikeVoider** [comment]
Can anyone help me i have this problem. 
![2021-05-25_19 35 36](https://user-images.githubusercontent.com/84320616/119543061-8937ae00-bd90-11eb-8757-ea66790cb674.png)
![2021-05-25_19 36 06](https://user-images.githubusercontent.com/84320616/119543066-8b017180-bd90-11eb-8ff3-dc896f8c11c0.png)

**Comment by MorningSage** [comment]
Yeah I haven't created an issue on this one, yet, but it also seems that AE2 and RS aren't compatible with REI.  I don't have specifics on this and I don't know if this is ALWAYS the case, just sometimes the case, etc.  Once I gather enough information to make a helpful ticket, I'll open one.  But all that takes time which I haven't had a lot of.
