### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [shedaniel/RoughlyEnoughItems#353]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by shedaniel** [comment]
Unforunately I failed to reproduce this issue as there is a forge version of this mod.|
I SHALL BE PROTECTED BY FORGE. o/

**Comment by natanfudge** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by Maowcraft** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by calloatti** [comment]
Put me on the Screenshot!

**Comment by vini2003** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by cs127** [comment]
shedaniel please close this

**Comment by natanfudge** [comment]
Wow, unresolved Roughly Enough Items issues once again striked down by stalebot

**Comment by shedaniel** [comment]
sad
