### ISSUE TITLE
[Bug] REI prevents TAB to select next button

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#356]
**Describe the bug**
REI prevents TAB to select next button whilst search box is active.

**Steps to Reproduce**
Open up any screen that has the REI overlay and a button e.g. player inventory screen with recipe book button.
TAB to select next button, once the REI search text field is selected it prevents selecting the next button.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.15.2
 - Mod Loader: Fabric
 - Mod Version: 3.6.21

**Logs**
Nothing logged by REI in relation to this issue.

**Additional context**
Note, the vanilla creative search text field also does this, however the TAB key provides no functionality inside the text field so I believe it should be changed to help with accessibility.

**Comment by shedaniel** [comment]
I gave up fixing tab controls in REI long ago
