### ISSUE TITLE
[Bug] Issue an item via the menu

### ISSUE THREAD

**Issue by CanslerW** [shedaniel/RoughlyEnoughItems#363]
Please help me, I have an op on the server, I want to give myself an item via REI but I can't, here is an error: http://prntscr.com/t6hd23 (I am Russian).
I use /give {player_name} {item_identifier}{nbt} {count}

**Comment by CanslerW** [comment]
fix = /give {player_name} {item_name} {count}

**Comment by shedaniel** [comment]
that's essentials, blame them
