### ISSUE TITLE
REI: Forge

### ISSUE THREAD

**Issue by shedaniel** [shedaniel/RoughlyEnoughItems#365]
- [x] Initial Port to Forge 1.16
- [x] Sync with clients to know whether it is on a modded server
- [x] Actually implement the fuels
- [x] Implement brewing recipes
- [ ] Implement JEI API

**Comment by bANNji** [comment]
Does this mean Forge support is on the roadmap?

**Comment by shedaniel** [comment]
Superseded by issues with actual todos
