### ISSUE TITLE
[Bug] Recipe Preview for 4.6.6

### ISSUE THREAD

**Issue by Unseenfury** [shedaniel/RoughlyEnoughItems#370]
**Describe the bug**
Previewing Recipe's While Previewing a Recipe Using Mouse Clicks Does not Work in Version 4.6.6

**Video**
This is my best way to Describe the bug
https://youtu.be/Wu7Kf0izK-I

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: Fabric

**Comment by shedaniel** [comment]
Thank you for reporting!
