### ISSUE TITLE
[Bug] [Fabric] REI crash when opening Config Menu with Optifine and Optifabric

### ISSUE THREAD

**Issue by Slycan** [shedaniel/RoughlyEnoughItems#371]
**Describe the bug**
When opening Roughly Enough Items' configuration menu with Optifabric 1.16.1 / Optifine 1.16.1 PRE2 installed, the game closes. It could be a Optifine issue but I can't seem to get my other mods to crash when opening their config menus

**Steps to Reproduce**
-First Step
 Mods Installed
Fabric API 0.14.1 Build 372 1.16
Roughly Enough Items 4.6.6
Optifabric 1.1.0 Beta
OptiFine 1.16.1 Preview 2

- Second Step
Open REI's configuration menu, crashes with Mod Menu installed as well.

**Environment (please complete the following information with the version):**
 - Minecraft: [1.16.1]
 - Mod Loader: [fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/EK0adQy6

**Comment by shedaniel** [comment]
Consider reporting to optifabric instead.

**Comment by pointydev** [comment]
This appears to have been fixed with OptiFabric 1.1.0-beta2 (see modmuss50/OptiFabric#223), however due to the warning screen implemented by REI, the config menu can't be used.

**Comment by shedaniel** [comment]
Ah alright, I will remove the warning screen.

**Comment by shedaniel** [comment]
It doesn't look like beta2 fixed the issue for config. It only fixed the crash on launch, they are separate bugs, I am keeping the warning screen for now.
