### ISSUE TITLE
[Feature] 1.16 REI Maven Repository

### ISSUE THREAD

**Issue by yuesha-yc** [shedaniel/RoughlyEnoughItems#376]
Is there a maven repository for REI so that I can use as dependencies in my project's build scripts?

**Comment by shedaniel** [comment]
it's the same, but change to the version

**Comment by yuesha-yc** [comment]
Where can I find it?

**Comment by shedaniel** [comment]
check the wiki

**Comment by yuesha-yc** [comment]
Thanks

**Comment by yuesha-yc** [comment]
Sorry, but what version should I change it to? 
`	modCompile "me.shedaniel:RoughlyEnoughItems:4.8.1"
`
Is this OK?

**Comment by shedaniel** [comment]
that's correct
