### ISSUE TITLE
[Bug] crashing when clicking buttons

### ISSUE THREAD

**Issue by Linguardium** [shedaniel/RoughlyEnoughItems#381]
**Describe the bug**
crashing when rendering new screens/handling mouse clicks

**Steps to Reproduce**
open REI
search for mushroom
click next screen or the composting icon
(or go into settings, or really any number of button presses)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.1
 - Mod Loader: fabric

**Logs**
https://paste.ee/p/Iszqq

**Additional context**

**Comment by shedaniel** [comment]
Not sure how that is possible.

**Comment by Linguardium** [comment]
Run into this problem on multiple computers. can reproduce it with composter menu and options menu, also occurs when attempting to disable cheat mode via shift+click.
I will try to determine which version actually broke it as i upgraded 2 minor versions (there were a few quick updates so i skipped one).  
I concede that It may be a compatibility issue with other mods (i havent done a thorough test), but crashing didnt occur until i updated REI.

It seems this is not the only mod that has a crash in this exact spot as i saw another complaint with an almost identical stacktrace (minus REI) on the discord the other day

**Comment by Linguardium** [comment]
Alright, issue seems to be resolved in 4.10.1 and was occurring in 4.9.3 and 4.9.2 but did not occur in 4.9.0, tested 4.10.2 as well and got no crash either. You must have fixed it already 🤷

**Comment by shedaniel** [comment]
Weird
