### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#382]
**Describe the bug**
When viewing mob drops through Roughly Enough Resources, the client crashes when viewing the last pane of the specific search.

**Steps to Reproduce**
- Search for 'Cursed Droplets' (Kibe mod)
- Cycle through the panes of the result
- The client crashes when switching to page 24

**Screenshots**
![image](https://user-images.githubusercontent.com/918422/87527402-5f036300-c68c-11ea-891c-38f00ccff015.png)

![image](https://user-images.githubusercontent.com/918422/87527249-22376c00-c68c-11ea-9615-4a976babb1fb.png)

**Environment (please complete the following information with the version):**
 - Minecraft 1.16.1
 - Fabric: 0.8.9+build 203
 - Roughly Enough Items 4.9.0
 - Roughly Enough Resources 2.0.2

**Logs**
https://pastebin.com/Hj1cUkcS

**Additional context**
I suspect the cause is a modded creature on page 24, I don't know which creature this could be.  If there is a way to to list all mobs for my specific combination of mods, I could find out through process of elimination.  I think it's a Better Nether mob, but can't be sure.

**Comment by shedaniel** [comment]
Please report to Roughly Enough Resources.
