### ISSUE TITLE
Light Overlay

### ISSUE THREAD

**Issue by GreenLEDPlugins** [shedaniel/RoughlyEnoughItems#39]
I know there already is a light overlay issue opened on Jan. 21 but I was wondering if there was any chance this could be implemented into REI so there wouldn't be a need for another mod. Currently I can't find a good light level overlay for 1.13.x for forge and I saw there you had one made for 1.14. 

Thanks :)

**Comment by shedaniel** [comment]
No, Light Overlay won't be implemented into REI, instead, I might want to port Light Overlay to Forge
