### ISSUE TITLE
[Bug] EasierCrafting GUI not shown when installed with REI

### ISSUE THREAD

**Issue by Samekichi** [shedaniel/RoughlyEnoughItems#390]
Description:
  When installing REI with EasierCrafting, GUI of the latter cannot show. 
Environment: 
This has been tested under Minecraft 1.16.1, Fabric-API 0.16.0, REI 4.10.3, EasierCrafting 1.6.1 beta5, and Fabric-loader 0.9.0.

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/88471000-e88d1d80-cf35-11ea-8d74-dda1d47fd664.png)

Please read the description of mods, thanks.

**Comment by Samekichi** [comment]
Well sorry for that, the update of hotkey isn't mentioned in its changelog. My bad.
