### ISSUE TITLE
Hotkeys for R (recipe) and U (uses) active while focused/typing in search field

### ISSUE THREAD

**Issue by MrKashew** [shedaniel/RoughlyEnoughItems#391]
On version: RoughlyEnoughItems-4.10.3.jar for 1.16.1

Can be quite disrupting when leaving your cursor on some item (in inventory or REI panel) accidentally, not sure if this is due to some other UI mod I have installed

**Comment by MrKashew** [comment]
Noticed this is an ongoing issue (#58 ) sorry for the duplicate!

**Comment by shedaniel** [comment]
no worries!
