### ISSUE TITLE
[Bug] Crash with Slotlink

### ISSUE THREAD

**Issue by Adirelle** [shedaniel/RoughlyEnoughItems#392]
**Describe the bug**
The game crashes when searching an item while using slotlink's storage request.

**Steps to Reproduce**
- Create a slotlink network, with a chest, storage link cable, cable, network master and storage request,
- Open the storage request's GUI.
- Click on REI's search input box.
- Try to type a few character to start a search.
At this point the game crashes.

**Screenshots**

slotlink network:
![2020-07-30_08 52 25](https://user-images.githubusercontent.com/24633/88891026-c00d6800-d242-11ea-8acb-a355e2f1bb65.png)

**Environment**
- Minecraft: 1.16.1
- Mod Loader: fabric-loader-0.9.0+build.204-1.16.1
- REI:  4.10.2
- Slotlink: 0.3.6+minecraft-1.16.1

**Logs**

https://pastebin.com/xSiDm55S

**Additional context**
Slotlink : https://www.curseforge.com/minecraft/mc-mods/slotlink

I reproduce this bug in a brand new world with only slotlink, REI and their dependencies.

**Comment by Adirelle** [comment]
Another crash that happens when also using InventorySorter.

## Steps to Reproduce

- Create a slotlink network, with a chest, storage link cable, cable, network master and storage request,
- Open the storage request's GUI.
- Click on an item to show the recipe (eg. Oak Planks).
- Close the recipe screen by hiting Escape.

## Environment

- Minecraft: 1.16.1
- Mod Loader: fabric-loader-0.9.0+build.204-1.16.1
- REI: 4.10.2
- Slotlink: 0.3.6+minecraft-1.16.1
- Inventory Sorter : 1.7.0-1.16

## Logs
https://pastebin.com/gtfBZPwK

## Additional context
Inventory Sorter : https://www.curseforge.com/minecraft/mc-mods/inventory-sorting

**Comment by shedaniel** [comment]
Did you delete some logs from the second one?

**Comment by Adirelle** [comment]
> Did you delete some logs from the second one?

No, this is the exact content of the crash report file.
