### ISSUE TITLE
[Bug] Languages missing from Crowdin

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#393]
**Describe the bug**
[REI's Crowdin](https://crowdin.com/project/roughly-enough-items) has less languages than before, presumably due to

> shedaniel changed this project's target languages

on Jul 27

**Steps to Reproduce**
- [Open REI's Crowdin](https://crowdin.com/project/roughly-enough-items/)
- Notice no Estonian and no contribution by me :(

**Screenshots**
![Languages](https://user-images.githubusercontent.com/8611110/89107847-9750c280-d43c-11ea-878e-4fd96a6e00c9.png)

**Environment (please complete the following information with the version):**
REI 4.10.3 is unaffected but 5.x.x very likely is (did not test yet).

**Logs**
N/A

**Additional context**
N/A

**Comment by shedaniel** [comment]
sorry!
