### ISSUE TITLE
[Bug] Unbale To Add Info Display In Plugin As Of 5.x

### ISSUE THREAD

**Issue by TheBrokenRail** [shedaniel/RoughlyEnoughItems#395]
**Describe the bug**
As of 5.x it is recommend to include REI with:
```gradle
dependencies {
    [...]
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api:ABC"
    modRuntime "me.shedaniel:RoughlyEnoughItems:ABC"
}
```
This however make ``DefaultPlugin`` not in the classpath so you can't call ``DefaultPlugin.registerInfoDisplay``.

**Steps to Reproduce**
Try to add info display.

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16-pre1
- REI 5.1.0

**Logs**
N/A

**Additional context**
N/A

**Comment by shedaniel** [comment]
will expose that into api

**Comment by TheBrokenRail** [comment]
Any updates?

**Comment by TheBrokenRail** [comment]
Thank you!
