### ISSUE TITLE
[Feature] Add a default config file that will be used, if no changes have been made in-game.

### ISSUE THREAD

**Issue by Luro02** [shedaniel/RoughlyEnoughItems#396]
### The problem
If a modpack provides a default configuration and the user changes the config in the settings, the user changes will be overwritten every time the modpack is updated.

### Describe the solution you'd like

Roughly Enough Items should have a default configuration file (`default_config.json5`) and if the config is changed in-game a second file will be created (`config.json5`), which will be used instead of the default config.

modpack authors would only provide a `default_config.json5`, so when an update is released the changes made by the user won't be overwritten.

### Additional context

Having the same file twice would be very space inefficient. Instead of mirroring the `default_config.json5`, only the changes from the default config would be written to the `config.json5`:

`config.json5`
```json5
{ 
    "basics": { 
        "favorites": [ 
            "{\"type\":\"stack\",\"nbt\":\"{id:\\\"techreborn:industrial_electrolyzer\\\",Count:127b}\"}",
        ],
        // Declares whether cheating mode is on.
        "cheating": true,
        "favoritesEnabled": true,
        "keyBindings": { 
            "recipeKeybind": { 
                "keyCode": "key.keyboard.unknown",
                "modifier": 0
            },
        },
        // Declares whether REI is visible.
        "overlayVisible": true,
        "cheatingStyle": "GIVE"
    }
}
```

I am not sure how difficult this is in java, but it would definitely increase the amount of code, just to save a few kb of disk space. (imo not worth it)

https://github.com/TeamAOF/All-of-Fabric-3/issues/43

**Comment by shedaniel** [comment]
Use a default options mod like https://www.curseforge.com/minecraft/mc-mods/your-options-shall-be-respected-yosbr

**Comment by kreezxil** [comment]
why is it extension json5 and not just json? I thought it was bug and was about to report that.

**Comment by Luro02** [comment]
> why is it extension json5 and not just json? I thought it was bug and was about to report that.

JSON5 supports comments and you need to differentiate between the two?

**Comment by kreezxil** [comment]
I never heard of it. that's why I asked.
