### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SpeedRider** [shedaniel/RoughlyEnoughItems#400]
**Describe the bug**
crash

**Steps to Reproduce**
trying to craft a shovel 

**Screenshots**

**Environment (please complete the following information with the version):**
1.16.1
fabric mod pack

**Logs**
[crash-2020-08-14_03.56.14-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/5071175/crash-2020-08-14_03.56.14-client.txt)

**Additional context**
crashed when crafting 
not enough crashes said your mod could be the cause and 2 others ill send them a crash report as well.

**Comment by shedaniel** [comment]
sodium is not compatible with fermion
