### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SpeedRider** [shedaniel/RoughlyEnoughItems#401]
**Describe the bug**
when i search in REI it crashes.

**Steps to Reproduce**
search in REI it could do something to do with exotic matter 

**Screenshots**

**Environment (please complete the following information with the version):**
 fabric 1.16.1

**Logs**
[crash-2020-08-14_11.07.26-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/5072490/crash-2020-08-14_11.07.26-client.txt)

**Additional context**

**Comment by shedaniel** [comment]
sodium is not compatible with fermion

**Comment by SpeedRider** [comment]
I don't have fermion.
It not in my mod folder

**Comment by shedaniel** [comment]
some mod is bundling fermion

**Comment by SpeedRider** [comment]
how can I work out what's doing it?

**Comment by SpeedRider** [comment]
it was exotic blocks all good
