### ISSUE TITLE
Hide Recipe Book when REI is Installed

### ISSUE THREAD

**Issue by raphydaphy** [shedaniel/RoughlyEnoughItems#41]
This might be a controversial opinion, but since the recipe book is just a less useful version of REI, if REI is enabled and not hidden, it would be nice if the recipe-book button was hidden automatically. Perhaps as a config option (preferably on by default).

**Comment by shedaniel** [comment]
Possibly not defaulted on, no matter what it is still a vanilla feature.

**Comment by shedaniel** [comment]
Coming in REI v2.4
