### ISSUE TITLE
[Bug] Failed to read accessWidener file from mod roughlyenoughitems-default-plugin

### ISSUE THREAD

**Issue by Domaman202** [shedaniel/RoughlyEnoughItems#411]
**Describe the bug**
I'm creating my own mod, I need to add Rey to view the correct recipes, but when I add Rey to the mods folder, the fabric throws an error: exception in the "main" Java thread for.yaz..RuntimeException: couldn't read the accessWidener file from mod roughlyenoughitems-default-plugin
 in the network.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.Java:60)
AccessWidener.Java:60
 online.fabricmc.loader.start. node. Node.init(node.Java: 130)
Node.Java: 130
 online.fabricmc.loader.start. node.Notclient. main(KnotClient.Java:26)
NetClient.Java:26
 in the network.fabricmc.dellendirecto.Main.home(Main.Java: 86)
Called: java. yaz..RuntimeException: namespace (intermediate) does not match the current runtime namespace (named)
 online.fabricmc.loader.transformer.accesswidener.AccessWidener.read(AccessWidener.Java: 78)
AccessWidener.Java: 78

**Steps to Reproduce**
At first, the launch went fine, but then an error occurs!

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: fabric

**Logs**
https://pastebin.com/wDp0azNF

**Additional context**
Non

**Comment by shedaniel** [comment]
Are you using loom <0.2.7, please update to 0.4-SNAPSHOT

**Comment by Domaman202** [comment]
Okay thx)
