### ISSUE TITLE
[Bug] Failed to read accessWidener file from mod roughlyenoughitems-default-plugin on Fabric-loom 4-SNAPSHOT

### ISSUE THREAD

**Issue by Domaman202** [shedaniel/RoughlyEnoughItems#412]
**Describe the bug**
Failed to read accessWidener file from mod roughlyenoughitems-default-plugin

**Steps to Reproduce**
Non

**Screenshots**
![2020-09-23 (4)](https://user-images.githubusercontent.com/51743763/93968392-2c53a600-fd72-11ea-8b51-c1c6d4780bee.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: fabric

**Logs**
https://pastebin.com/wDp0azNF

**Additional context**
Non

**Comment by shedaniel** [comment]
can you try deleting the .gradle folder in your project and try again

**Comment by Domaman202** [comment]
okay

**Comment by Domaman202** [comment]
dont work =<
https://github.com/Domaman202/4aukaCraft - this my mod repository

**Comment by shedaniel** [comment]
Wait where did you even declare REI? Do it the correct maven way: https://shedaniel.gitbook.io/roughly-enough-items/setup/gradle-setup

**Comment by Domaman202** [comment]
thx
