### ISSUE TITLE
[Feature] Option to disable left-side delete

### ISSUE THREAD

**Issue by Nixill** [shedaniel/RoughlyEnoughItems#414]
**Describe the solution you'd like**
With REI in cheat mode, attempting to drop items out of the left side of an inventory (or even into inventory-side item slots like the upgrade slots in Tech Reborn) deletes the items instead of dropping them. I reflexively use the left side of the inventory to drop items into the world and would like an option to disable this delete field.

**Comment by shedaniel** [comment]
I have decided to completely remove this feature.

**Comment by shedaniel** [comment]
Removed in 5.7.0
