### ISSUE TITLE
[Feature] Have toggle to prevent Custom Filter from removing info on disabled/removed mods automatically

### ISSUE THREAD

**Issue by Abbanon** [shedaniel/RoughlyEnoughItems#421]
I'm asking for a toggle feature that will let users specify if they want to disable the automatic "cleaning" of filters on mods that have been disabled/removed, so that information stays intact.

Because as of right now, if REI detects custom filters for mods that are no longer being used, it automatically deletes the filter information for them. So if the mods are re-added or re-enabled in the future, users have to custom set the filters for them all over again. It causes troubles for people that like to temporarily disable some mods sometimes.

> As an example (using MultiMC):
I install [Mo Glass](https://www.curseforge.com/minecraft/mc-mods/mo-glass), which adds a debug block type called Test Slab:
![Screenshot_2](https://user-images.githubusercontent.com/37251822/95090954-dbd63400-06f3-11eb-9c3a-534e1bc80a7d.png)
> 
> I obviously don't want it to appear in REI, so I custom filter it from view.
> 
> In the future, I want to play without the mod for a while, so I temporarily disable Mo Glass and launch the game:
![Screenshot_3](https://user-images.githubusercontent.com/37251822/95091220-2e175500-06f4-11eb-97eb-37569f0fba83.png)
> 
> Then, after wanting to play with the mod again, I re-enable it and launch the game. I suddenly see the Test Slab in REI!
> So I have to manually filter it all over again.

**Comment by shedaniel** [comment]
Possibly you can try and use the search filtering rule? and define the search filter to that block, like `@moglass "Test Slab"` (idk what the modid is)

**Comment by Abbanon** [comment]
So in the `config.json5`, I would add the following to the `"filteringRules":` section like this?
`"{rule:{},id:\"betterslabs:test_slab\"}"`

*(edit: turns out the Test Slab is from [Better Slabs](https://www.curseforge.com/minecraft/mc-mods/better-slabs), not Mo Glass)*

**Comment by shedaniel** [comment]
Nope, just open the config, and click the plus button on the top right when you are at the filtering menu

**Comment by Abbanon** [comment]
Did some testing, and that seemed to have worked! The filter persists, thank you!

But some further questions about it: 
If I were to filter multiple items from a single mod, and/or filter items from multiple mods, how would I format the string?
Would it be something like this?
`@examplemod "example1" "example 2" "example3" @examplemod2nd "example1st" "example 2nd" "example3rd"`

**Comment by shedaniel** [comment]
that filter is the same as the search field, so you can experiment in that, try this:
`@examplemod "example1"|@examplemod2nd "example 2"|@examplemod2nd "example 3"`

**Comment by Abbanon** [comment]
Okay, so entries are separated with `|`. 
Looking into this right now, and it's all working just fine! Thank you again so much!
