### ISSUE TITLE
[1.16.3] Game closes (no crash report) after hovering the cursor over some items

### ISSUE THREAD

**Issue by Desempregago** [shedaniel/RoughlyEnoughItems#425]
**Describe the bug**
The game closes itself and doesn't give any crash report or log entry regarding the problem

**Steps to Reproduce**
- Open the inventory screen
- Hover the cursor over some items (specially some from other mods, like Expanded Storage)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: Fabric v0.10.0-b208 + FabricAPI v0.24.0-b411
 - REI: v5.6.2
 - JVM (if useful for troubleshooting): AdoptOpenJDK 15 (Hotspot) build 36

**Logs**
[latest.log {can't find anyting useful in there}](https://pastebin.com/cLRws7sw)

**Comment by Desempregago** [comment]
PS: It doesn't happen 100% of the time, but it tends to happen very often, and I don't know which mod is causing this.

**Comment by shedaniel** [comment]
Possibly issue with canvas, try removing canvas.

**Comment by Desempregago** [comment]
It did work with Canvas, but I'll switch back to Sodium for the time being. Thanks.
