### ISSUE TITLE
[Feature] Ability to show "advanced" block recipes in the recipe menu (MC 1.16.3, REI Forge)

### ISSUE THREAD

**Issue by Wodong77** [shedaniel/RoughlyEnoughItems#429]
**Describe the solution you'd like**
While I really enjoy REI Forge, one gaping hole is several recipes that are "advanced" versions of a recipe will not show in REI.  

**Additional context**
For example, in Mekanism there is a basic machine, but it also has advanced tiers based on the same machine and those recipes will not show at all.  I would like to be able to see these recipes with REI. If I have a basic smelting factory and want to know how to upgrade it to an advanced smelting factory, REI simply does not "know" that there is a recipe for it.

I would prefer to keep using, REI for my Forge modded, and I do hope you continue to update it.

**Comment by shedaniel** [comment]
REI Forge will keep being updated, major work has been put into supporting a JEI compatibility later that will allow REI to communicate with mods that add advanced recipes into the game. I have no estimated time on when that will be done, all I can say is that it will come.

Thanks for the support! :p

**Comment by shedaniel** [comment]
This has been implemented effectively with the JEI compatibility layer
