### ISSUE TITLE
[Feature] Item zoom

### ISSUE THREAD

**Issue by shouxd** [shedaniel/RoughlyEnoughItems#430]
Hello! I just think REI lateral pages should have a bindable zoom key (or a true/false setting) to better differenciate some very similar items. It'd also help people who dont see very well or who play with some distance off the monitor!

Please let me know your thoughts!

**Comment by shedaniel** [comment]
Can you elaborate on your suggestion? I am not sure I understand.

**Comment by shouxd** [comment]
Sure! it is exactly what this mod does: https://www.curseforge.com/minecraft/mc-mods/itemzoom
I think it'd fit very well with already existing REI features.

**Comment by ozokuz** [comment]
There is already a mod for this on fabric: https://www.curseforge.com/minecraft/mc-mods/big-items-duh/

**Comment by shedaniel** [comment]
Going to take this suggestion in another direction, making the item that you are hovering on bigger.
