### ISSUE TITLE
[Bug] v5.8.1 Crash on load

### ISSUE THREAD

**Issue by MechanosG** [shedaniel/RoughlyEnoughItems#432]
**Describe the bug**
Updated to v5.8.1 and the game crashes on load.

**Steps to Reproduce**
- Update to v5.8.1
- Launch the game

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.3
 - Mod Loader: Fabric 0.6.1.51 via Jumploader

**Logs**

> ---- Minecraft Crash Report ----
> // You should try our sister game, Minceraft!
> 
> Time: 2020-11-05 18:12:22 PST
> Description: Unexpected error
> 
> java.lang.AssertionError: REI Internals have not been initialized!
>     at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
>     at me.shedaniel.rei.impl.Internals.throwNotSetup(Internals.java:75)
>     at me.shedaniel.rei.impl.Internals.getConfigManager(Internals.java:80)
>     at me.shedaniel.rei.api.ConfigManager.getInstance(ConfigManager.java:41)
>     at me.shedaniel.rei.api.ConfigObject.getInstance(ConfigObject.java:43)
>     at me.shedaniel.rei.impl.ScreenHelper.isOverlayVisible(ScreenHelper.java:140)
>     at me.shedaniel.rei.impl.ScreenHelper.lambda$null$2(ScreenHelper.java:287)
>     at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
>     at net.minecraft.client.MinecraftClient.handler$dbl000$onEndTick(MinecraftClient:17826)
>     at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1577)
>     at net.minecraft.client.MinecraftClient.render(MinecraftClient:996)
>     at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
>     at net.minecraft.client.main.Main.main(Main:215)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
>     at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
>     at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
>     at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
>     at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
>     at java.util.HashMap$Values.forEach(Unknown Source)
>     at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
>     at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
>     at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
>     at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
>   Minecraft Version: 1.16.3
>   Minecraft Version ID: 1.16.3
>   Operating System: Windows 7 (amd64) version 6.1
>   Java Version: 1.8.0_271, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 3962797440 bytes (3779 MB) / 5234491392 bytes (4992 MB) up to 5234491392 bytes (4992 MB)
>   CPUs: 4
>   JVM Flags: 20 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5120m -Xms256m -XX:PermSize=256m -Xms5G -Xmx5G -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+DisableExplicitGC
>   Suspected Mods: REI (Runtime) (roughlyenoughitems-runtime), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1), Fabric Loader (fabricloader), REI (API) (roughlyenoughitems-api)
>   Fabric Mods: advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
>                allure: Allure 1.2.7
>                amecs: Amecs 1.3.2+mc.1.16.3
>                amecsapi: Amecs API 1.1.1+mc1.16-rc1
>                aopalliance_aopalliance: aopalliance 1.0
>                appleskin: AppleSkin 1.0.11
>                artifacts: Artifacts 1.0.1+1.16.4-fabric
>                artifice: Artifice 0.13.2+1.16.3
>                autoconfig1u: Auto Config v1 Updated 3.3.1
>                automated_crafting: Automated Crafting 1.3.13+MC1.16.2-1.16.4
>                balance_of_exile: Balance of Exile 1.0.3
>                bedrockify: BedrockIfy 0.1.9
>                bettercaves: YUNG's Better Caves 1.16.2-1.0.3
>                betterdroppeditems: Better Dropped Items 1.2.2-1.16.2
>                bettereating: Better Eating 0.2.0
>                betterend: Better End 0.5.2-beta
>                bettergraves: Better Graves 0.4.1
>                betternether: Better Nether 4.1.8
>                betterstones: Better Stones 0.0.4
>                biomemakeover: Biome Makeover 1.16.3-1.0.2
>                blockus: Blockus 1.6.5
>                blue_endless_jankson: jankson 1.2.0
>                breakprogress: Break Progress 1.0.0
>                buildersblocks: Builders' Blocks 1.16.3-beta.8
>                campanion: Campanion 1.2.0+build.39
>                can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
>                canvas: Canvas Renderer 1.0.989
>                cardinal-components: Cardinal Components API 2.7.3
>                cardinal-components-base: Cardinal Components API (base) 2.7.3
>                cardinal-components-block: Cardinal Components API (blocks) 2.7.3
>                cardinal-components-chunk: Cardinal Components API (chunks) 2.7.3
>                cardinal-components-entity: Cardinal Components API (entities) 2.7.3
>                cardinal-components-item: Cardinal Components API (items) 2.7.3
>                cardinal-components-level: Cardinal Components API (world saves) 2.7.3
>                cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.3
>                cardinal-components-util: Cardinal Components API (utilities) 2.7.3
>                cardinal-components-world: Cardinal Components API (worlds) 2.7.3
>                chainmail: Chainmail 0.5.0
>                cinderscapes: Cinderscapes 1.2.4+build.43-1.16.4
>                cleancut: CleanCut mc1.16-2.1-fabric
>                clearview: Clear View 2.1
>                clickthrough: ClickThrough 1.16.2-fabric0.17.2-0.3
>                climbable: Climbable 0.2.0
>                cloth-armor-api-v1: Cloth Armor API v1 1.4.8
>                cloth-basic-math: Cloth Basic Math 0.5.1
>                cloth-client-events-v0: Cloth Client Events v0 1.4.5
>                cloth-common-events-v1: Cloth Common Events v1 1.4.8
>                cloth-config2: Cloth Config v4 4.8.2
>                cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
>                cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
>                cloth-utils-v1: Cloth Utils v1 1.4.5
>                colormatic: Colormatic 2.2.7+mc.1.16.3
>                com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
>                com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
>                com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
>                com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
>                com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
>                com_google_inject_guice: guice 4.2.3
>                com_typesafe_config: config 1.4.0
>                computercraft: CC:T for Fabric 1.91.2
>                connected_block_textures: Connected Block Textures 0.1.3+1.16
>                convenient-mobgriefing: Convenient mobGriefing 1.1.3
>                creeperspores: Creeper Spores 1.4.1
>                croptopia: Croptopia 1.0.4-1.16.3-FABRIC
>                crowdin-translate: CrowdinTranslate 1.1
>                crowmap: Crowmap 1.0.1
>                curios: Curios API 0.0.10-1.16.3
>                customspawns: Custom Spawns 0.1.2
>                dankstorage: Dank Storage 1.8c-1.16.3
>                dark-loading-screen: Dark Loading Screen 1.5.0
>                darkness: True Darkness 1.6.50
>                demeter: Demeter 2.0.0
>                direbats: Direbats 1.0.0+1.16.3-fabric
>                disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
>                dontdropit: Don't Drop It! 2.1.0+1.16
>                dungeons_of_exile: Dungeons of Exile 1.1.1
>                easiercrafting: EasierCrafting 1.16.2-fabric0.17.2-1.6.5
>                edit_sign: Edit Sign 2.1.3
>                expandedstorage: ExpandedStorage 5.6.30
>                fabric: Fabric API 0.25.0+build.415-1.16
>                fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
>                fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
>                fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
>                fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
>                fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
>                fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
>                fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
>                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
>                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
>                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
>                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
>                fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
>                fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
>                fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
>                fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
>                fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
>                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
>                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
>                fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
>                fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
>                fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
>                fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
>                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
>                fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
>                fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
>                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
>                fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
>                fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
>                fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
>                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
>                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
>                fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
>                fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
>                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
>                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
>                fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
>                fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
>                fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
>                fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
>                fabricloader: Fabric Loader 0.10.6+build.214
>                fastbench: FastBench 2.3
>                fastfurnace: FastFurnace 2.3
>                fermion: Fermion 2.6.206
>                fermion-orientation: Fermion Orientation 1.1.205
>                fermion-varia: Fermion Varia 2.4.206
>                fiber: fiber 0.23.0-2
>                frex: FREX 3.4.140
>                gbfabrictools: GBfabrictools 1.2.3+1.16.2
>                glassdoor: Glass Doors 1.5.0-1.16
>                glowingbeds: Glowing Beds 1.2.1
>                gottaclimbfast: Gotta Climb Fast! 1.0
>                gunpowder-base: Gunpowder 0.2.10+1.16.2
>                gunpowder-sleepvote: Gunpowder SleepVote 1.0.1+gunpowder.0.2.10.mc.1.16.2
>                iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
>                illuminations: Illuminations 1.2.3
>                indrev: Industrial Revolution 1.7.3-BETA
>                inmis: Inmis 1.3.1-1.16.2
>                inventoryprofiles: Inventory Profiles 0.4.2
>                inventorytabs: Inventory Tabs 0.2.3-1.16.3
>                jankson: Jankson 3.0.1+j1.2.0
>                javax_inject_javax_inject: javax.inject 1
>                javax_vecmath_vecmath: vecmath 1.5.2
>                json-model-extensions: JSON Model Extensions 1.15.124
>                jumploader: Jumploader 2.1.0
>                justmap: Just Map 1.2.13
>                kirin: Kirin UI 1.7-1.16.2
>                kubejs: KubeJS 1.5.4
>                lambdynlights: LambDynamicLights 1.3.2+1.16.4
>                lapisreserve: Lapis Reserve 1.0.6
>                libblockattributes: LibBlockAttributes 0.8.4
>                libblockattributes_core: LibBlockAttributes (Core) 0.8.4
>                libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
>                libblockattributes_items: LibBlockAttributes (Items) 0.8.4
>                libcd: LibCapableData 3.0.2+1.16.2
>                libgui: LibGui 3.2.1+1.16.3
>                library_of_exile: Library of Exile 1.0.6
>                libstructure: LibStructure 1.5
>                linkedstorage: Linked Storage 1.3.11-1.16
>                lionutils: LionUtils 6.0.1+1.16
>                lithium: Lithium 0.5.6
>                loadcatcher: Entrypoint Catcher 2.0.0
>                maelstrom_library: Maelstrom Library 0.4.1
>                magna: Magna 1.4.3-1.16.2
>                mambience: MAmbience 2.1.0+1.16.2
>                materialisation: Materialisation 3.0.3
>                megane: megane 2.1.0+1.16
>                megane-api: megane-api 2.1.0+1.16
>                megane-impl: megane-impl 2.1.0+1.16
>                megane-runtime: megane-runtime 2.1.0+1.16
>                minecraft: Minecraft 1.16.3
>                mmorpg: Age of Exile 1.7.6
>                mo_glass: Mo Glass 1.4-MC1.16.3
>                mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
>                modern_industrialization: Modern Industrialization 0.3.4
>                modid: Damage Tilt 1.16-fabric-0.1.0
>                modmenu: Mod Menu 1.14.6+build.31
>                moreberries: More Berries 1.3.3
>                muffle: Muffle 0.1.1
>                mysql_mysql-connector-java: mysql-connector-java 5.1.46
>                nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
>                notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
>                nourish: Nourish 1.1.1
>                okzoomer: Ok Zoomer 4.0.1+1.16.2
>                org_jetbrains_annotations: annotations 20.0.0
>                org_jetbrains_exposed_exposed-core: exposed-core 0.23.1
>                org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.23.1
>                org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.23.1
>                org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
>                org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
>                org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
>                org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
>                org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
>                org_postgresql_postgresql: postgresql 42.2.2
>                org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
>                org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
>                org_yaml_snakeyaml: snakeyaml 1.26
>                patchouli: Patchouli 1.16.2-44-FABRIC
>                phosphor: Phosphor 0.6.0+build.7
>                pling: Pling 1.2.0
>                presencefootsteps: Presence Footsteps r28+1.16.2
>                reach-entity-attributes: Reach Entity Attribute 1.0.1
>                reborncore: Reborn Core 4.5.0+build.84
>                respawnablepets: Respawnable Pets 1.16.3-1
>                roughlyenoughitems: Roughly Enough Items 5.8.1
>                roughlyenoughitems-api: REI (API) 5.8.1
>                roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.1
>                roughlyenoughitems-runtime: REI (Runtime) 5.8.1
>                roughlyenoughresources: Roughly Enough Resources 2.1.2
>                sandwichable: Sandwichable 1.1.2
>                shieldisruptor: Shield Disruptor 1.1.1
>                simpledrawers: Simple Drawers 1.8.0-1.16.3
>                slotlink: slotlink 2.0.2+1.16.3
>                smokeextender: Smoke Extender 1.4.0
>                smoothboot: Smooth Boot 1.1.0
>                special-circumstances: Special Circumstances 1.7.206
>                spinnery: Spinnery 3.0.49
>                spruceui: SpruceUI 1.6.4
>                step-height-entity-attribute: Step Height Entity Attribute 1.0.0
>                strongandfairanvils: Strong and Fair Anvils 0.3.0+1.16
>                tacobell: Taco Bell 1.1.1
>                tcrafting: TCrafting 1.2.1-1.16.2
>                team_reborn_energy: Energy 0.1.1
>                techreborn: Tech Reborn 3.6.1+build.143
>                terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
>                terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
>                terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
>                terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
>                terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
>                terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
>                terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
>                terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
>                terrestria: Terrestria 2.1.4+build.26
>                tinytweaks: TinyTweaks 1.0.15
>                tis3d: TIS-3D 1.5.0
>                trinkets: Trinkets 2.6.7
>                unforgivingvoid: Unforgiving Void 2.0.0
>                universalcomponents: Universal Components 0.7.3+1.16.2
>                waila: Hwyla 1.9.22
>                woodenhoppers: Wooden Hoppers 1.0.0
>                ynet: YNet 0.2.0
>                zoob: Monster Of The Ocean Depths 2.5.0
>   Patchouli open book context: n/a
>   Launched Version: Jumploader
>   Backend library: LWJGL version 3.2.2 build 10
>   Backend API: AMD Radeon(TM) R9 290X GL version 4.6.14736 Compatibility Profile Context 20.9.2 27.20.12031.1000, ATI Technologies Inc.
>   GL Caps: Using framebuffer using OpenGL 3.0
>   Using VBOs: Yes
>   Is Modded: Definitely; Client brand changed to 'fabric'
>   Type: Client (map_client.txt)
>   Graphics mode: fancy
>   Resource Packs: vanilla, buildersblocks:resourcepack, fabric/gunpowder-base, fabric/fabric-keybindings-v0, fabric/notenoughcrashes, fabric/fabricloader, fabric/mobs_attempt_parkour, fabric/strongandfairanvils, fabric/edit_sign, fabric/betternether, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/reborncore, fabric/darkness, fabric/shieldisruptor, fabric/betterstones, fabric/roughlyenoughresources, fabric/iamverysmart, fabric/waila, fabric/fabric-blockrenderlayer-v1, fabric/mo_glass, fabric/fabric, fabric/fabric-networking-v0, fabric/pling, fabric/techreborn, fabric/fabric-screen-handler-api-v1, fabric/muffle, fabric/modmenu, fabric/phosphor, fabric/fabric-tool-attribute-api-v1, fabric/roughlyenoughitems-runtime, fabric/fabric-events-interaction-v0, fabric/fabric-crash-report-info-v1, fabric/curios, fabric/fabric-language-kotlin, fabric/nbtcrafting, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/amecs, fabric/fabric-resource-loader-v0, fabric/smokeextender, fabric/expandedstorage, fabric/universalcomponents, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/justmap, fabric/creeperspores, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/bedrockify, fabric/lionutils, fabric/crowmap, fabric/fabric-renderer-api-v1, fabric/linkedstorage, fabric/mambience, fabric/allure, fabric/automated_crafting, fabric/mmorpg, fabric/maelstrom_library, fabric/fabric-containers-v0, fabric/lithium, fabric/fabric-object-builder-api-v1, fabric/glowingbeds, fabric/convenient-mobgriefing, fabric/fabric-rendering-data-attachment-v1, fabric/campanion, fabric/dontdropit, fabric/fabric-textures-v0, fabric/connected_block_textures, fabric/fabric-rendering-fluids-v1, fabric/glassdoor, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/bettereating, fabric/fabric-loot-tables-v1, fabric/fabric-networking-blockentity-v0, fabric/tcrafting, fabric/jankson, fabric/amecsapi, fabric/betterdroppeditems, fabric/fabric-renderer-indigo, fabric/demeter, fabric/dark-loading-screen, fabric/fabric-item-api-v1, fabric/roughlyenoughitems, fabric/libgui, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/autoconfig1u, fabric/fabric-content-registries-v0, fabric/bettergraves, fabric/fabric-tag-extensions-v0, fabric/fastfurnace, fabric/inmis, fabric/fabric-events-lifecycle-v0, fabric/inventorytabs, fabric/fabric-object-builders-v0, fabric/team_reborn_energy, fabric/appleskin (incompatible), fabric/artifice, fabric/bettercaves (incompatible), fabric/breakprogress, fabric/buildersblocks, fabric/cleancut, fabric/clickthrough, fabric/colormatic, fabric/croptopia, fabric/dankstorage, fabric/direbats, fabric/easiercrafting, fabric/fabric-biome-api-v1, fabric/fabric-command-api-v1, fabric/gbfabrictools, fabric/gottaclimbfast, fabric/illuminations (incompatible), fabric/jumploader (incompatible), fabric/lambdynlights, fabric/libblockattributes_core, fabric/libblockattributes_fluids, fabric/libblockattributes_items, fabric/library_of_exile (incompatible), fabric/megane, fabric/megane-api, fabric/megane-impl, fabric/megane-runtime, fabric/modid, fabric/okzoomer, fabric/patchouli (incompatible), fabric/presencefootsteps (incompatible), fabric/reach-entity-attributes (incompatible), fabric/spruceui, fabric/tis3d (incompatible), fabric/woodenhoppers, fabric/zoob, fabric/betterend, fabric/can-i-mine-this-block, fabric/canvas, fabric/cinderscapes, fabric/clearview, fabric/computercraft (incompatible), fabric/dungeons_of_exile (incompatible), fabric/fermion, fabric/fermion-orientation, fabric/fermion-varia, fabric/frex, fabric/indrev, fabric/json-model-extensions, fabric/libblockattributes, fabric/magna, fabric/materialisation, fabric/modern_industrialization, fabric/simpledrawers, fabric/slotlink, fabric/smoothboot, fabric/special-circumstances, fabric/terraform-biome-builder-api-v1, fabric/terraform-config-api-v1, fabric/terraform-dirt-api-v1, fabric/terraform-overworld-biome-extensions-api-v1, fabric/terraform-shapes-api-v1, fabric/terraform-surfaces-api-v1, fabric/terraform-tree-api-v1, fabric/terraform-wood-api-v1, fabric/terrestria, fabric/unforgivingvoid
>   Current Language: English (US)
>   CPU: 4x AMD Athlon(tm) II X4 640 Processor
>   Client Crashes Since Restart: 1
>   Integrated Server Crashes Since Restart: 0

**Additional context**
Going back to v5.7.1 allows the game to load again.

**Comment by shedaniel** [comment]
I will need more information from this, can you provide the full logs?

**Comment by MechanosG** [comment]
I couldn't find the log for some reason, almost like it wasn't archived after the error.  So I updated REI again and got you a new one lol.

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/5503537/latest.log)

**Comment by MechanosG** [comment]
While there is a newer version out (5.8.3) I've yet to test, I have tested 5.8.2 and it no longer crashes on load like 5.8.1 did.  So I'll go ahead and close this, under the assumption it's fixed.  Thx
