### ISSUE TITLE
[Bug] (sorry, wrong git channel) (1.16.3)

### ISSUE THREAD

**Issue by HetNeSS** [shedaniel/RoughlyEnoughItems#433]
Sorry, wrong git channel

**Comment by HetNeSS** [comment]
Cloth-thingy-creator claimed that was another mod (https://github.com/shedaniel/cloth-config/issues/64), but it didn't help. Issues had began upon me installing REN in addition to REI, so it began to crash

**Comment by shedaniel** [comment]
update slight gui modifications
