### ISSUE TITLE
[Bug] Item tooltips in recipe browser don't display when REI is hidden

### ISSUE THREAD

**Issue by Lykrast** [shedaniel/RoughlyEnoughItems#434]
While browsing recipes while the side REI menu is hidden (the CTRL O), item tooltips don't display.

- View any recipe
- Hide/unhide REI

Minecraft - 1.16.4
Fabric API - 0.25.1
REI - 5.8.2

While I took these particular screenshots in a heavily modded instance, the bug happens with only Fabric + REI.

![2020-11-08_12 27 34](https://user-images.githubusercontent.com/8684850/98463843-b939ae00-21be-11eb-97a6-a9c2f9bb6257.png)
![2020-11-08_12 27 37](https://user-images.githubusercontent.com/8684850/98463845-bb037180-21be-11eb-997c-f311cdb74cd6.png)

**Comment by LonelyMusicDisc** [comment]
I'm having it too even on the latest update from curse forge, hopefully it gets fixed

**Comment by ChloeDawn** [comment]
This bug is still present in 5.10.183

**Comment by IdrisQe** [comment]
Yep, still happening. Gotta say it's rather annoying. Would certainly appreciate a fix.

**Comment by shedaniel** [comment]
Should be fixed now.
