### ISSUE TITLE
[Bug] Mods refuses to load on 1.16.4 forge

### ISSUE THREAD

**Issue by BedrockLegends** [shedaniel/RoughlyEnoughItems#437]
**Describe the bug**
I added the latest version of REI into my modpack with 240 mods and the mod does not load

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**
![2020-11-10_21 02 11](https://user-images.githubusercontent.com/48525410/98760043-0624ac80-2398-11eb-90e2-f14d1574e6cc.png)

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14] 1.16.4
 - Mod Loader: [e.g. forge, fabric] Forge

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash-2020-11-10_21.00.48-fml.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/5521499/crash-2020-11-10_21.00.48-fml.txt)

**Additional context**

**Comment by xane256** [comment]
From the readme, "1.14, 1.15 and 1.16 version requires Fabric Mod Loader and Fabric API."

Forge is not supported for the 1.16 version.

**Comment by BedrockLegends** [comment]
@xane256 I was posting the issue cause there is a forge version https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-forge

**Comment by shedaniel** [comment]
You need Cloth Config to function over at Forge. https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge
