### ISSUE TITLE
Crash when opening Inventory

### ISSUE THREAD

**Issue by TheVillageid10t** [shedaniel/RoughlyEnoughItems#438]
1.16.3
cloth-api-1.4.9
config-2-4.8.3
RoughlyEnoughItems-5.8.3
fabric-api-0.25.4+1.16
Singleplayer world and Server (attached crash and logs are singleplayer)

Steps to Reproduce:
load world
Press "E"
Saving world (Crash)

[crash-2020-11-10_19.44.16-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/5521628/crash-2020-11-10_19.44.16-client.txt)

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/5521629/latest.log)

**Comment by shedaniel** [comment]
Update Slight Gui Modifications
