### ISSUE TITLE
[Bug] 5.8.2 & 5.8.3 Crash

### ISSUE THREAD

**Issue by greensad** [shedaniel/RoughlyEnoughItems#439]
**Describe the bug**
Opening the player inventory crashes minecraft when REI 5.8.2 or 5.8.3 are loaded. 5.6.2 and earlier does not crash.

**Steps to Reproduce**
- Open inventory
- Crash

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: fabric

**Logs**
https://pastebin.com/Fp0ULuYn

**Comment by shedaniel** [comment]
Update slight gui modifications

**Comment by greensad** [comment]
thanks it worked, I was probably trying to update SGM independently, getting a crash and then reverting back to 1.5.0
