### ISSUE TITLE
[Bug] Hidden items do not stay Hidden 1.16.4

### ISSUE THREAD

**Issue by IchigoGames** [shedaniel/RoughlyEnoughItems#444]
**Describe the bug**
i think this is a bug i hide some items like the bits from chisel and bits and liquid and saved closed game loaded back up and loaded into same world and most if not all of the things are un hidden.
**Steps to Reproduce**
- First Step hide some stuff save closed game
- Second Step reload game load back into world look to see if its still hidden

 - Minecraft:1.16.4
 - Mod Loader:Forge
 - RoughlyEnoughItems-Forge-5.8.4+20201115-1134

**Comment by shedaniel** [comment]
Thanks for reporting, can you share your REI config data, it is in a sub folder in the configs folder

**Comment by IchigoGames** [comment]
[roughlyenoughitems.zip](https://github.com/shedaniel/RoughlyEnoughItems/files/5571476/roughlyenoughitems.zip)

**Comment by shedaniel** [comment]
Should be fixed.
