### ISSUE TITLE
[Bug] Out of place items

### ISSUE THREAD

**Issue by Flytre** [shedaniel/RoughlyEnoughItems#447]
**Describe the bug**
Items will sometimes render in the top left of my screen rather than the right column.
**Steps to Reproduce**
Unknown

**Screenshots**
https://imgur.com/2VV0Xgo

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://hastebin.com/urozehoxor.sql

**Additional context**
Running a custom REI plugin I wrote but does not register an exclusion zone for the creative menu or anything like that

**Comment by Flytre** [comment]
Is it that favorite items feature JEI had? I have no clue how undo it if so?

**Comment by shedaniel** [comment]
You can press A, also you can drag it around and stuff, you can also completely disable this feature in the config.
