### ISSUE TITLE
[Bug] Favorites Crash to Desktop 

### ISSUE THREAD

**Issue by ZaneR42** [shedaniel/RoughlyEnoughItems#456]
**Describe the bug**
Client instantly crashes to desktop when pressing A to favorite item

**Steps to Reproduce**
- Open inventory
- Mouse over Item
- Press A to favorite

**Environment**
 - Minecraft 1.16.4
 - Fabric Loader 0.10.8.1 - 1.16.4

**Logs**
Adventure Pack + extras 
https://pastebin.com/t8cSGhVR
Can replicate crash with Fabric API and REI only
https://pastebin.com/K8QrDj6k 

**Additional context**
Causes client side crash in single or multiplayer
Server states player disconnected, nothing else
Disabling favorites prevents crash
Can replicate with Fabric API 028.3 and 0.29.1

**Comment by shedaniel** [comment]
Please delete your REI config.json5.
