### ISSUE TITLE
[Bug] Crash after entering the credits in REI settings

### ISSUE THREAD

**Issue by zeabdullah** [shedaniel/RoughlyEnoughItems#457]
**Description:**
Game crashes after entering the credits in REI settings (happened mid-way through the animation)

**Steps to Reproduce:**
- Open a world
- Open Inventory
- Enter REI's `Settings`
- Enter `Credits`

**Environment:**
 - Minecraft: 1.16.4
 - Mod Loader: fabric-loader-0.10.8-1.16.4

**Logs:**
Pastebin link: https://pastebin.com/bPvG5Nja

**Additional context:**
The crash report shows that the Fabric Cloth Config API could be a reason for this crash, so, I made sure to open this same issue on Cloth Config repo, too.

One more thing, it happened once but never happened again.

**Comment by shedaniel** [comment]
Try updating REI
