### ISSUE TITLE
[Bug] Binding show/hide to left click

### ISSUE THREAD

**Issue by DaDarkDeity** [shedaniel/RoughlyEnoughItems#458]
I accidentally bound and saved left click as the button  for show/hide. I was then unable to click the settings button because it would hide it whenever I click on it, disabling my ability to repair my mistake. I don't think I need to add anything else in terms of evidence, just please fix it for idiots like me.

**Comment by shedaniel** [comment]
You may access the REI configuration screen via Mod Menu.
