### ISSUE TITLE
[Feature] TMI Features Added

### ISSUE THREAD

**Issue by Wolfipoo** [shedaniel/RoughlyEnoughItems#459]
Not sure if this has been asked before, but the old TooManyItems mod had a number of features that would be amazing to have in REI.

- Inventory Loadouts
- Weather, Time, and Difficulty Toggles
- Different Mob Spawners shown in the 'Items' area to be grabbed
- Enchanted Weapon Tab

There's a ton of features, and any of them would be amazing to have, if you had the time!

**Comment by Katniss218** [comment]
I approve of this suggestion 😄 
Would be cool to have an item NBT generator thingy builtin (the enchanter but better). Sort of like mcstacker.net website but in minecraft.

**Comment by shedaniel** [comment]
I believe Weather and Time toggles are added into REI already now.
Inventory Loadouts is in vanilla as well with the creative hotbars.
Enchanting UI is #137 
Spawners is kinda meh
so I will close this issue
