### ISSUE TITLE
[Bug] Ticking screen crash report

### ISSUE THREAD

**Issue by saltyseadoggo** [shedaniel/RoughlyEnoughItems#463]
**Describe the bug**
Our game crashed to launcher upon trying to open REI's configuration menu from Mod Menu. The crash report told us to report the issue.

**Steps to Reproduce**
- Enter any world with REI and Mod Menu in the mods folder.
- Pause the game, then go Mods > REI, and click on the config button.
- Observe the crash.
If the crash cannot be replicated this way, it may be a mod conflict; I can provide a list of mods we are using. Entering a world may not be nessecary, but the crash occurred in a world.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
[crash-2021-02-03_23.15.24-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/5923893/crash-2021-02-03_23.15.24-client.txt)

**Comment by shedaniel** [comment]
Please update REI, this is already fixed.
