### ISSUE TITLE
Translate gamemodes and weather

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#47]
Gamemodes can be taken directly from the game:

Without "mode":

- selectWorld.gameMode.survival
- selectWorld.gameMode.creative
- selectWorld.gameMode.adventure
- selectWorld.gameMode.spectator

With "mode":
- gameMode.survival
- gameMode.creative
- gameMode.adventure
- gameMode.spectator

The first letter can be obtained from the strings programmatically.

Weather would need custom phrases as they don't exist in the game right now, unfortunately.

**Comment by shedaniel** [comment]
Won't be getting the first letter from the strings programmatically as there might be lots of languages.

**Comment by shedaniel** [comment]
Added in 68a8a9b2ad9094cfc836f1283a189cfbeeead36e

**Comment by shedaniel** [comment]
>
