### ISSUE TITLE
[Bug] Crash since 178

### ISSUE THREAD

**Issue by ThexXTURBOXx** [shedaniel/RoughlyEnoughItems#473]
**Describe the bug**
I am using other mods next to REI, but this wasn't a problem until version 178. Since then, I get a crash on startup (it works on verison 173).

**Steps to Reproduce**
- Update REI to 178
- Start the game

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
https://paste.ee/p/knf6R

**Additional context**
This crash occurs since commit 62aaa590ce0fb1c6c5bc80d1e57057b4c4721af4

**Comment by shedaniel** [comment]
Paste expired, couldn't reproduce at the time of reporting it.
