### ISSUE TITLE
Bring stable versions of REI to Modrinth

### ISSUE THREAD

**Issue by JustAPotota** [shedaniel/RoughlyEnoughItems#474]
**Describe the solution you'd like**
Title. There's currently only an [unstable 20w49a version on Modrinth](https://modrinth.com/mod/roughly-enough-items-unstable/version/VDSmucGM).

**Additional context**
I'd like to make a modpack using Modrinth, but not having any item/recipe browser is a big issue.

**Comment by shedaniel** [comment]
Done.
