### ISSUE TITLE
[Feature] ability to change the dimensions of the recipe window

### ISSUE THREAD

**Issue by classabbyamp** [shedaniel/RoughlyEnoughItems#475]
**Describe the solution you'd like**
In other JEI/TMI/etc-type mods I've been able to change the size of the recipe window, for example to a size more consistent with other Minecraft GUIs. The same/similar in REI would be nice.

**Additional context**

![image](https://user-images.githubusercontent.com/5366828/108397320-d16d9000-71e5-11eb-987b-76aca32f5fe4.png)

**Comment by shedaniel** [comment]
More options limiting the size of the window has been added.
