### ISSUE TITLE
Improve weather/gamemode selection

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#48]
It would be great if we could "toggle" the weather/gamemode with one click and switch between all of them with another. 

E.g.:
- click toggles between clear/rain and survival/creative
- shift-click switches between all weather and game modes

Game mode list should also include the spectator mode.

**Comment by shedaniel** [comment]
Hmm not sure about this one, but I will add back spectator mode.

**Comment by shedaniel** [comment]
Spectator mode added in 68a8a9b2ad9094cfc836f1283a189cfbeeead36e

**Comment by shedaniel** [comment]
Ugh maybe I will close this as I don't really like "shift-click switches between all weather and game modes"

**Comment by Madis0** [comment]
Well, it doesn't have to be shift-click per se, was just thinking of something as a compromise between usability (what is used the most) and precision (keeping all options available). Toggling between all options is inefficient and may be impossible too (on servers you might only have two gamemode options for example). 

What about a submenu system similar to Bedrock Edition? For example, clicking the weather button expands it to 3 buttons for every weather state. Then after selection it collapses back to currently selected one.
