### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Natedagr840** [shedaniel/RoughlyEnoughItems#480]
When I click the button to open the REI config screen on 1.16.5 (even with Cloth Config API installed) It crashes my game.
![image](https://user-images.githubusercontent.com/80119562/110147882-2bf01a00-7daa-11eb-9aac-c1600c3d635a.png)
I was on version 1.16.5 and using the fabric launcher.

**Comment by shedaniel** [comment]
Update REI
