### ISSUE TITLE
[Bug]Crash when opening the settings screen

### ISSUE THREAD

**Issue by Phoupraw** [shedaniel/RoughlyEnoughItems#482]
**Describe the bug**
Game crashed when I click the REI settings button in player inventory.

**Steps to Reproduce**
- First Step : open player inventory
- Second Step: click the REI settings button

**Scrrenshot**
![2021-03-10_20 19 38](https://user-images.githubusercontent.com/50520903/110628599-2e090d00-81de-11eb-9e0a-ea85b129835c.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
[crash-2021-03-10_20.11.40-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6115694/crash-2021-03-10_20.11.40-client.txt)

**Additional context**

**Comment by shedaniel** [comment]
Update REI
