### ISSUE TITLE
[Bug] Crash on opening config screen

### ISSUE THREAD

**Issue by UltraBlackLinux** [shedaniel/RoughlyEnoughItems#483]
**Describe the bug**
Crashes when pressing the config button

**Steps to Reproduce**
Press the config button in the inventory

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.4
 - Mod Loader: fabric

**Logs**
https://paste.ee/p/00see

**Additional context**
Another mod also has this (Aurora Keystrokes)

**Comment by shedaniel** [comment]
Please update REI
