### ISSUE TITLE
[Bug] Crashes on Launch

### ISSUE THREAD

**Issue by asteroidb12** [shedaniel/RoughlyEnoughItems#487]
**Describe the bug**
Game doesn't start up and instead crashes.

**Steps to Reproduce**
- Start Up Game

**Screenshots**
![image](https://user-images.githubusercontent.com/68461874/111426451-e852b580-86b1-11eb-9a60-d7d85dad512e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric 0.11.2, 0.32.0 API

**Logs**
https://pastebin.com/S7VnDVGN

**Additional context**
Here's a mod list:
![image](https://user-images.githubusercontent.com/68461874/111426865-834b8f80-86b2-11eb-9666-f10f95cb3820.png)

**Comment by shedaniel** [comment]
Your log doesn't show that crash, try clicking "View Crash Report" on that dialog

**Comment by asteroidb12** [comment]
Here's the Crash Report:
https://pastebin.com/1UP4SF6T

**Comment by shedaniel** [comment]
Your log suggests that Entity Outliner is crashing
