### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SkinLink** [shedaniel/RoughlyEnoughItems#491]
**Describe the bug**
When i open the inventory or a chest(Furnace, workbench, etc...), my game just crash.

**Steps to Reproduce**
- First Step:
I open the inventory(Chest, Furnace, workbench, etc..)
- Second Step:
The mod crash my game.

**Screenshots**
My mods:
![image](https://user-images.githubusercontent.com/81001389/111908423-fef16780-8a37-11eb-9bbe-e7d3b2bd4310.png)

**Environment**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric
 
**Logs**
[https://drive.google.com/file/d/1VaFUQ9pb44USZ95QxTiXiewTnW9pkTzR/view?usp=sharing](url)

I upload in google drive because the text is so large(16 MB?????)

**Additional context**
i use the mod Not Enough Crashes, and he talk that your mod as been crash, he says the main suspect mod is REI RUNTIME.

Sorry from my english, is not my native language.
If want more informations, tell me.

**Comment by shedaniel** [comment]
Please remove REI and see if the issue persists

**Comment by SkinLink** [comment]
It took too long, but i have found the problem, is another mod, sorry for the inconvenience.
