### ISSUE TITLE
[Bug?][1.16.5] REI simply isn't working at all. But is installed and detected on the mod list.

### ISSUE THREAD

**Issue by aking4125** [shedaniel/RoughlyEnoughItems#510]
Hello,

I don't quite know any other way to explain this other than pictures. But REI doesn't work at all. It's installed on a private Fabric modpack but nothing is shown on the inventory screen. Pressing CTRL + O doesn't show or hide it at all. Pressing R or U to view recipes doesn't work at all. Yet the .jar file is installed and detected. Any ideas? 

![Screenshot_5](https://user-images.githubusercontent.com/11141831/113595227-b83e6880-9606-11eb-930e-7652376231e3.png)

This is in-game. No mod name or REI on the right side.

![Screenshot_6](https://user-images.githubusercontent.com/11141831/113595237-bd031c80-9606-11eb-8d1e-1185a9fe0627.png)

In the "Mod list", REI shows up and can be configured. I literally didn't really mess with any setting. Changing Keybinds there does nothing. It's just "Not working" is the best description I can give.

I've attached to the log file to hopefully give a clue but I have no idea how else to describe it. Every other mod installed is properly detected and seems to be working.

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6259055/latest.log)

**Comment by shedaniel** [comment]
![IMG_0241](https://user-images.githubusercontent.com/34910653/113596051-5e708980-966c-11eb-807e-0d194863e638.jpeg)

It is not really REI’s fault, some mod is crashing during recipe sync and that stopped it entirely. Unfortunately it is really hard to debug this, could you attach an error log with Java 14 and Helpful NullPointerException errors enabled?

**Comment by aking4125** [comment]
I have no idea how you even do that to be completely honest with you.

**Comment by aking4125** [comment]
Sorry for the delay, been busy with work. 

I researched a bit on enabling "Helpful NullPointerException errors enabled" using Java 14. I've found the following argument that I think enables it and loaded the pack with JDK 14.

`-XX:+ShowCodeDetailsInExceptionMessages`

I've attached an updated .log file. Hopefully, I've done everything correctly. If not, I legit have no idea how you enable such a request. Perhaps someone here can properly inform me on it or?

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6289611/latest.log)

**Comment by shedaniel** [comment]
Just checked your logs, it seems like some mod's item has a null rarity, this is very hard to find out which mod is causing the issue, as it is usually just a dumb mod.

Anyway, this is unfortunately not an issue from REI, and I am unable to provide any support beyond this point as I am as clueless as you are, thank you for providing the info though.
