### ISSUE TITLE
REI "Failed to Parse Mod Menu Version"

### ISSUE THREAD

**Issue by officialeleri** [shedaniel/RoughlyEnoughItems#511]
My game is able to launch normally, however just before the main screen loads I get the following message:

"Errors during Roughly Enough Items' Initialization"
"Errors: Failed to parse Mod Menu Version: Could not parse version number component 'v1'!"

I've attached a picture of all the mods and clients I use below.
I have 0 experience with coding and developing, so I'm hoping someone will be able to explain as simple as possible what I can do to fix this problem :)
I also apologize if there's a very obvious answer, again I don't have any experience with mod compatibility and coding

I'm using 1.16.5 with fabric loader and optifine using OptiFabric

![Error JEI](https://user-images.githubusercontent.com/82015805/113731914-264a6480-96c7-11eb-8441-6668cdd4cb0f.png)

![Mods Installed](https://user-images.githubusercontent.com/82015805/113731957-2fd3cc80-96c7-11eb-8914-918a5c8cfcb9.png)

**Comment by shedaniel** [comment]
Please attach a log

**Comment by officialeleri** [comment]
Thanks so much for the quick reply, I took screenshots of the entire log but I'm assuming it's just the part with that error that you're wanting to see, so I've only attached that one
![Log Pt1](https://user-images.githubusercontent.com/82015805/113735288-1bdd9a00-96ca-11eb-8c17-2c042b0e3631.png)

**Comment by dkmk100** [comment]
Deleting and reinstalling mod menu worked for me when I had this issue

**Comment by officialeleri** [comment]
I didn't even have the mod menu in my mods folder, but I found the file and deleted then reinstalled, now it's working, thanks so much

**Comment by shedaniel** [comment]
Where did you find the jar? I am still trying to investigate on how this happens.

**Comment by wisecracked** [comment]
ive got the same error

**Comment by OctoFlareDev** [comment]
> Where did you find the jar? I am still trying to investigate on how this happens.

For me it's contained in the mod Immersive Portals

**Comment by officialeleri** [comment]
I found the jar by using the spotlight search bar and typing in mod menu. I have a mac so that's what worked for me. I would assume other pcs and windows can search for "mod menu" on their computer instead of just in the Minecraft folder. Hope this helps, sorry for the late response I've been on vacation.
