### ISSUE TITLE
Crashes when opening inventory

### ISSUE THREAD

**Issue by energy11a** [shedaniel/RoughlyEnoughItems#513]
Crashes when opening inventory while search is active.

**Steps to Reproduce**
1 open inventory
2 search from REI

Minecraft: 1.16.4
Mod Loader: fabric

**Logs**
[crash-2021-04-08_23.11.55-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6281231/crash-2021-04-08_23.11.55-client.txt)

**Comment by shedaniel** [comment]
Should be fixed.
