### ISSUE TITLE
failing to launch into game

### ISSUE THREAD

**Issue by AlistairS04** [shedaniel/RoughlyEnoughItems#514]
I have basically no idea whats happening here I'm going, to be honest I'm playing Minecraft with a fair few other mods and have been adding them in one by one into my mods folder however when I go to add roughly enough items it just seems to show this every time

<img width="853" alt="Screenshot 2021-04-09 at 14 53 40" src="https://user-images.githubusercontent.com/47298218/114191441-53577b00-9944-11eb-98b7-9da46cf19b78.png">

**Comment by shedaniel** [comment]
Fixed
