### ISSUE TITLE
[Bug] The game crashed whilst mouseclicked event handler Error: java.util.NoSuchElementException: null

### ISSUE THREAD

**Issue by ZeroDhita** [shedaniel/RoughlyEnoughItems#515]
Game crashes every time i try to use crafting table while REI is enabled

- Right clic on a crafting table 

- Try to move an item from the inventory to the crafting grid

 - Minecraft version: 1.16.5
 - Mod Loader: Forge 36.1.4
 - Mod version: 6.0.0.200-alpha-forge

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6289882/latest.log)

It may be a compatibility Issue, but for what i can understand (it's not mutch) this is caused by REI, it has only happened since i updated it.

**Comment by MisakiCopperrose** [comment]
Same crash, but this time with the bench saw.

[crash-2021-04-13_23.23.39-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6306816/crash-2021-04-13_23.23.39-client.txt)
