### ISSUE TITLE
the mod dosent work[Bug]

### ISSUE THREAD

**Issue by zaze06** [shedaniel/RoughlyEnoughItems#521]
**Describe the bug**
it doesn't do anything

**Steps to Reproduce**
- use forge
- install rei
- start Minecraft and test

**Screenshots**
linked file

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16
 - Mod Loader: forge
 - mod list: https://gist.github.com/zaze06/361d6946ee0cbea25677dd4bc8ce9fa2

**Logs**
https://gist.github.com/zaze06/57b034f4087e80790b0e409a88e51f1a

**Additional context**
Ender Addition is my own mod so I can easily fix that if that is the issue

**Comment by shedaniel** [comment]
ironfurnaces blocked the recipe sync, report the issue on their end. however, I will keep this opened to make it not stop REI loading if that is blocked.

**Comment by zaze06** [comment]
ok thx
