### ISSUE TITLE
[Bug] Possible conflict with Mo'Colors

### ISSUE THREAD

**Issue by shaneknysh** [shedaniel/RoughlyEnoughItems#526]
**Describe the bug**
Crashes the client when viewing a specific page, in my case page 6.

**Steps to Reproduce**
- Open inventory
- Progress to next page
- repeat until you hit page 6
- Client crashes

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Additional context**

These are all the plugins that I have installed. Adding them one at a time no crash occurs unless Mo'Colors is added. Removing just Mo'Colors and the crash no longer occurs. Crash does not happen with only REI and Mo'Colors

alaskanativecraft-1.1.1.jar
architectury-1.12.148-fabric.jar
bedspreads-fabric-1.3.1-1.16.4.jar
biome_locator-1.1.2.jar
byg-1.1.7.jar
cloth-config-4.11.19-fabric.jar
Couplings-1.3.6.jar
Croptopia-1.16.4-FABRIC-1.3.6.jar
deep-dungeons-1.0.0-1.16.5.jar
DualRiders-1.0.5.jar
expandedstorage-5.6.33+1.16.5.jar
fabric-api-0.34.0+1.16.jar
FallingTree-1.16.5-2.11.3.jar
flytre_lib-0.2.9.jar
full-slabs-2.0.1.jar
geckolib-fabric-1.16.5-3.0.33.jar
gravestones-v1.9.jar
immersive-portals-0.90-mc1.16.5-fabric.jar
lithium-fabric-mc1.16.5-0.6.4.jar
llamasteeds-2020.02.08.jar
micalibria-1.0.2.jar
modmenu-1.16.9.jar
mostructures-1.1.1+mc.1.16.5.jar
okzoomer-4.0.1+1.16.2.jar
phosphor-fabric-mc1.16.3-0.7.2+build.12.jar
rightclickharvest-1.0.0.jar
riverredux-0.1.6.jar
RoughlyEnoughItems-5.11.218.jar
shelf-1.2.jar
SimpleBackpack_Fabric_1.16.5-1.0.38.jar
sodium-fabric-mc1.16.4-0.1.1-ipc2.jar
stonetotools-1.0.0.jar
untitledduckmod-0.1.1-fabric.jar
villagernames-1.16.4-1.6.0.jar
worldedit-mod-7.2.5-dist.jar
WorldEditCUI-1.16.5+02.jar
Xaeros_Minimap_21.7.1_Fabric_1.16.5.jar
XaerosWorldMap_1.13.4_Fabric_1.16.5.jar

mocolors-1.1.2.jar

I've created the same issue at Mo' Colors
[https://github.com/GabrielOlvH/Mo-Colors/issues/4](https://github.com/GabrielOlvH/Mo-Colors/issues/4)

**Comment by shedaniel** [comment]
Please attach the logs

**Comment by shaneknysh** [comment]
Crash Report
https://pastebin.com/uQn5A4i1

Latest.log
https://pastebin.com/ZUt3JZJV

**Comment by shedaniel** [comment]
Not an issue caused by REI.
