### ISSUE TITLE
calculateBoundary crash

### ISSUE THREAD

**Issue by shedaniel** [shedaniel/RoughlyEnoughItems#53]
Original Crash Report: https://pastebin.com/n38yyPh9
Reproduced: https://paste.ee/p/Oe5uD

**Comment by MoonlightSystem** [comment]
yep, I just got that crash as well

**Comment by shedaniel** [comment]
Please try https://www.dropbox.com/s/zj3fyyzv91y8q56/RoughlyEnoughItems-2.6.2.81.jar?dl=0
