### ISSUE TITLE
[Bug] Game crash after favoriting any item

### ISSUE THREAD

**Issue by mcffbn** [shedaniel/RoughlyEnoughItems#535]
**Describe the bug**
Game crashes after favoriting any item

**Steps to Reproduce**
- Favorite any item

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/05mA9rW6

**Additional context**

**Comment by shedaniel** [comment]
Duplicate of #496
