### ISSUE TITLE
[Bug] Cannot Open REI Settings Screen

### ISSUE THREAD

**Issue by MorningSage** [shedaniel/RoughlyEnoughItems#540]
**Describe the bug**
In some instances, when using the Forge version, the settings button does nothing when clicked.  This only seems to happen only in creative mode, but more testing may be required.

**Steps to Reproduce**
- Load up a new random world with *just* REI and dependencies.
- Switch into creative mode using a method other than REI (F3+F4 or /gamemode for instance)
This step is optional if you load up a saved game already in Creative.
- Open the creative inventory
- Attempt to click on the Settings button

**Screenshots**
https://files.catbox.moe/fscm9l.mp4

**Environment (please complete the following information with the version):**
 - Minecraft (1.16.5)
 - Forge (36.1.23)
 - REI (6.0.0.228)
 - Architectury (1.14.157)
 - Cloth Config (4.11.26)

**Logs**
https://gist.github.com/MorningSage/3793858a59aa3dec736b7c8ad2f53a60

**Additional context**
This happens somewhat randomly.  Resizing the window with the creative menu open appears to help the situation at times.  Hiding and showing REI with CTRL+O does not have any effect.

**Comment by MaxNeedsSnacks** [comment]
This is a known bug with an unknown cause and **exclusively** happens in the creative inventory screen and on Forge, so one of my personal workarounds has been to open a chest or inventory :p

***Why*** this happens is a mystery to me so I‘ll leave it up to Dan to find out

**Comment by MorningSage** [comment]
I have not yet looked into debugging for Forge.  I got Fabric up (and will eventually test there) but I wanted to work my way through my Forge bugs first.  If I can figure out debugging for Forge, I'll try and help, but I'm not familiar with the code base.

(I'm really sorry for inundating you, Dan... Lol)

**Comment by shedaniel** [comment]
I know what’s happening, I just haven’t fixed it :p
