### ISSUE TITLE
[Bug] AppleSkin Compatibility

### ISSUE THREAD

**Issue by MorningSage** [shedaniel/RoughlyEnoughItems#543]
**Describe the bug**
When AppleSkin is being used in a Forge Mod Pack, the additional rendering it does near the tooltip appears behind the items in REI.  I'm opening this here because JEI doesn't have this issue, so I assume that this is something that REI is doing/can fix?  If I need to open the issue elsewhere, just let me know.  I've included a second screenshot in a larger modpack (ATM6 - To The Sky) where the whole tooltip is rendered behind the items.  This is presumably due to the additional shank rendering that SOME mod is doing (I don't know which, at the moment).  This appears to be the same issue, though.

**Steps to Reproduce**
- Hover over any item that you can eat
- Observe that the tooltip is rendered behind the items in REI

**Screenshots**
Just AppleSkin: https://files.catbox.moe/ceoyr4.png
Actual ATM6 Playthrough: https://files.catbox.moe/ujnz2p.png

**Environment (please complete the following information with the version):**
 - Minecraft (1.16.5)
 - Forge (36.1.23)
 - REI (6.0.0.228)
 - Architectury (1.14.157)
 - Cloth Config (4.11.26)
 - AppleSkin (1.0.14)

**Logs**
https://gist.github.com/MorningSage/184283bdfa4516603ad3ee438d295a9b

**Additional context**
N/A

**Comment by MorningSage** [comment]
In addition to the screenshots above, this happens when rendering the tooltip for food items in the QIO from Mekanism.

![image](https://user-images.githubusercontent.com/51978143/119235936-d272ce00-bb02-11eb-99c4-ce6fee01c5dd.png)

**Comment by squeek502** [comment]
This is probably fixed with AppleSkin 2.0.0, but haven't tested it.

**Comment by MorningSage** [comment]
> 
> 
> This is probably fixed with AppleSkin 2.0.0, but haven't tested it.
>
![image](https://user-images.githubusercontent.com/51978143/122857893-44e3f300-d2e7-11eb-8f7f-90d5432104b3.png)

Thanks!  Indeed it does.  However, now none of the info is not being displayed when hovering over an item in REI.  The space for it is there, but nothing is rendered.  I'll close this issue as the original problem has been fixed and open one for AppleSkin.

![image](https://user-images.githubusercontent.com/51978143/122857964-6644df00-d2e7-11eb-8ba0-b5df1a82d717.png)
