### ISSUE TITLE
[Bug] Jei compat does not work on server side

### ISSUE THREAD

**Issue by Trinsdar** [shedaniel/RoughlyEnoughItems#544]
**Describe the bug**
Compat for jei plugins on the server side does not seem to work till I manually add the rei config onto the server, seems the real issue is the rei config does not generate on the server side.

**Steps to Reproduce**
- Run server with rei and mod that has jei plugin
- try to look up recipes in that jei plugin, like machine recipes

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: forge
 - REI: 6.0.0.226

**Comment by shedaniel** [comment]
I need logs

**Comment by Trinsdar** [comment]
https://gist.github.com/Trinsdar/4aead07cb1472a953b66f28042b26258
here it is, doesn't seem like there's anything useful though

**Comment by Trinsdar** [comment]
and here's the client too: 
https://gist.github.com/Trinsdar/43118b23a9b873472616f82055a18af1

**Comment by Trinsdar** [comment]
so update: seems other mods work fine, it's just antimatter based mods so far

**Comment by shedaniel** [comment]
Why does JEI compat need to exist on the server? REI only handles some networking on the server and doesn't need to generate any configs, plus JEI plugins are entirely client sided.

**Comment by Trinsdar** [comment]
so update on this: seems the issue is less that it needs to be on the server and more it's not working very well with antimatter's dynamic resource pack, cause it works on the server side once I enter a single player world first. this is the dynamic resource pack I'm talking about: https://github.com/GregTech-Intergalactical/AntimatterAPI/blob/dev/src/main/java/muramasa/antimatter/mixin/SimpleReloadableResourceManagerMixin.java#L36
