### ISSUE TITLE
[Bug] Crash when turning to certain page

### ISSUE THREAD

**Issue by ChromaPIE** [shedaniel/RoughlyEnoughItems#546]
**Describe the bug**
As the title

**Steps to Reproduce**
(It may caused by certain icons from other mods, probably not REI's main fault.)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs**
Crash Log: https://paste.ubuntu.com/p/vKsGTNpsXB/
Log: https://paste.ubuntu.com/p/NPbzHfGCnW/

**Comment by ZEROX7** [comment]
it would be nice to know waht its trying to render like waht item or block or from wich mod it is

**Comment by shedaniel** [comment]
Please use the vanilla creative menu to crash to see which item is crashing, otherwise, in REI 6 there are improved crash details.
