### ISSUE TITLE
[Bug] internal server error on player join, kicking the player

### ISSUE THREAD

**Issue by LordDecay26** [shedaniel/RoughlyEnoughItems#548]
**Describe the bug**
internal server error on player join, kicking the player

**Steps to Reproduce**
-install serverpack 3.0.2 for the BesmirchmentPSM modpack to a server
-join server while running update 3.0.2

**Screenshots**
n/a
**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: forge, but running the Jumploader mod, so also fabric

**Logs**
server latest.log: https://pastebin.com/Qn6qGL93

client latest.log: https://pastebin.com/82DjhvWv

**Additional context**
i believe the issue occurred on the version  RoughlyEnoughItems-5.11.218.jar - in the event the mod itself is not the issue, and the issue is instead, for example a null item being added by another mod, can you give me any insight into which mod might be adding the null item? any and all information, helpful or derogatory, would at this point be a massive help to me and my playerbase. thank you in advance.

**Comment by shedaniel** [comment]
There seems to be an issue on the server with "sendWorldInfoMixin", can you double check by removing REI to see if it removes the error?:

**Comment by shedaniel** [comment]
Not REI's issue, please reopen the issue if you believe otherwise.
