### ISSUE TITLE
[Feature] Add drag items from REI into filter

### ISSUE THREAD

**Issue by Parmers249** [shedaniel/RoughlyEnoughItems#549]
**Describe the solution you'd like**
Have a feature where you can drag an item or block from REI into filters so you don't have to make the item for the filter

**Comment by shedaniel** [comment]
what filter

**Comment by Parmers249** [comment]
As in filters in pipes such as Industrial Revolution's pipes

**Comment by hugeblank** [comment]
I don't think this is something that should be implemented on REI's side. If you wanted to report this issue on Industrial Revolution's GitHub I'm sure they'd consider adding it. To be clear your idea is not a bad one, REI is just not the right place.

**Comment by shedaniel** [comment]
Please ask Industrial Revolution, I've added a thing that allows other mods to extend the new draggable contexts in REI 6 (1.17)
