### ISSUE TITLE
Crash at startup with latest version of REI

### ISSUE THREAD

**Issue by MoonlightSystem** [shedaniel/RoughlyEnoughItems#55]
The game crashed on startup with REI and a couple other mods

[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/3060725/latest.log)

Mods list:
![image](https://user-images.githubusercontent.com/8211402/55830426-bb5cf780-5ac5-11e9-91e6-f1dad7166e9e.png)

**Comment by shedaniel** [comment]
For now download Cloth Events and drop it into the mods folder, I will try to work it out

**Comment by sargunv** [comment]
Downloading Cloth Events doesn't fix the issue. I was able to reproduce this with just REI and also with REI+Cloth. 

It also seems very similar to https://github.com/Terrails/Health-Overlay/issues/1

**Comment by shedaniel** [comment]
What about using the bare REI with no included dependencies? The version uploaded as an addictional file of REI?
This certainly is a problem with Jar in Jar

**Comment by sargunv** [comment]
The crash still happens with the bare version: https://paste.ee/p/qkxEb

![image](https://user-images.githubusercontent.com/1320357/55862436-50dfa200-5b2d-11e9-9c5c-8d12f6f9a659.png)

**Comment by shedaniel** [comment]
Is this just a bug for Cloth Events and not Cloth Config?

**Comment by shedaniel** [comment]
I will try to recompile Cloth Events

**Comment by shedaniel** [comment]
Does it crash with only Cloth Events?

**Comment by sargunv** [comment]
Nope, it doesn't crash if I install fabric/cloth-events/cloth-config. Only when REI enters the picture.

**Comment by shedaniel** [comment]
That is interesting hmm

**Comment by sargunv** [comment]
This launches fine: 
![image](https://user-images.githubusercontent.com/1320357/55862724-e11de700-5b2d-11e9-9ccc-32e802d8f13a.png)

**Comment by shedaniel** [comment]
Here's what I've reproduced:
Running only REI: No crash
Running only LightOverlay: No crash
Running REI + LightOverlay: Crash
Running REI + LightOverlay + Cloth + ClothConfig: No crash

This seems like a confusing crash

**Comment by sargunv** [comment]
That's interesting, since I'm getting the crash with only REI. Are you getting the same exception as what's in my log? Perhaps there's a difference in loader version?

**Comment by shedaniel** [comment]
My crash is the same as yours. Currently, I am on Loader 0.4 Build 116

**Comment by sargunv** [comment]
Same version as me. Interesting that we're not reproducing it the same way. Given the exception, makes me wonder if this bug is somewhere in the fabric toolchain.

**Comment by shedaniel** [comment]
The issue has been fixed. An update will come to REI later. For now, Cloth Events got an update to fix that bug. Updating Cloth Events will fix it.

![image](https://user-images.githubusercontent.com/34910653/55876138-7c17cf00-5bc9-11e9-8334-e76ebcdba1fc.png)
