### ISSUE TITLE
REI not displaying [Bug]

### ISSUE THREAD

**Issue by YaGirlCara** [shedaniel/RoughlyEnoughItems#553]
**Describe the bug**
I recently started playing in a world but the whole time the REI menu is not displayed. I never turned off the display. I've restarted the game one or two times since I started but nothing has happened. I tried using the keybind to turn on/off the display but nothing happened. I also tried making a new world, nothing seems to be working.

Unfortunately, I don't know any way to replicate this potential bug. I can't seem to figure out what's causing this.

**Screenshots**
![2021-06-08_15 53 05](https://user-images.githubusercontent.com/85584899/121248800-daa46a80-c871-11eb-8f3f-bf75ff5783c7.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Fabric

**Logs(Updated)**
(Server Side)[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6681242/latest.log)
(Client Side)[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6722445/latest.log)

**Additional context**
I'm trying to build a modpack for a server, I will leave a .txt list of the mods just in case it's one of them
[currentmodlist.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6619697/currentmodlist.txt)
.

**Comment by YaGirlCara** [comment]
Please I need help. I can't figure this out and it sticks even after a restart or two and on different worlds.

**Comment by scarha** [comment]
I am having the same issue as well. It was working before and now it isnt. I can send you the mod list if you need.

**Comment by Cora2004** [comment]
I am also having the same issue with the 1.16.5 version, is there any known incompatibility that would cause the above issue?

**Comment by shedaniel** [comment]
Can you provide a log on the client?

**Comment by YaGirlCara** [comment]
> Can you provide a log on the client?

Where would I find it? Because the only type of log I know about is already a part of the post.

**Comment by shedaniel** [comment]
It's in .minecraft/logs/latest.log

**Comment by YaGirlCara** [comment]
> It's in .minecraft/logs/latest.log

Okay, I'll put it under the server side's.

**Comment by shedaniel** [comment]
Your logs remapped to yarn: https://hastebin.com/ejumudehey.apache

Basically some random mod is ￼providing a broken rarity for their items, causing a crash in some code that syncs the recipes, this is not REI's issue, I recommend taking out mods half by half to try and eliminate the cause of the issue. Unfortunately I won't be providing more help on that since this is not my issue.
