### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by ctrlmeep** [shedaniel/RoughlyEnoughItems#555]
When I load my game with the mod the game just crashes and says Could not find required mod: roughlyenoughitems requires {minecraft @ [~1.16.2-rc.1]} Could you help me? I'm using fabric-loader-.11.3-1.17 to load it and the mods I have are 
-autoreconnect-1.1.0
-fabric-api-0.34.9 + 1.17
-farbicmod_VoxelMap-1.10.15_for_1.17.0
-optifabric-1.11.1
-preview_OptiFine_1.17_HD_U_G9_pre18
-wthit-3.5.1 
-and of course wthit-3.5.1-fabric

**Comment by shedaniel** [comment]
you used the REI for 1.16 for 1.17
