### ISSUE TITLE
[Bug] Auto crafting is broken on servers

### ISSUE THREAD

**Issue by paulzzh** [shedaniel/RoughlyEnoughItems#558]
**Describe the bug**
The autocrafting does not work on servers.

**Steps to Reproduce**
- Join a minecraft server
- Press 'plus' in inventory or crafting table

**Screenshots**
<img width="960" alt="1 17" src="https://user-images.githubusercontent.com/28055560/122351872-27c6c180-cf81-11eb-8d7f-934ab1acb8ae.png">

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric 0.11.6
 - REI: 6.0.251-alpha-fabric
 - Fabric API: 0.35.2+1.17

**Logs**
server: https://paste.ubuntu.com/p/YpwBhtBq4Z/
client: https://paste.ubuntu.com/p/4ThxHFvjRR/

**Comment by milkev** [comment]
seems to work fine in the slotlink terminals, but nothing else ive tested so far
