### ISSUE TITLE
Item glow effect not getting masked properly

### ISSUE THREAD

**Issue by sargunv** [shedaniel/RoughlyEnoughItems#56]
On any given page, if the item in the top-left-most corner of the page has a glowing effect, that effect is not masked to the item's sprite. All other items on the page render fine.

Here are a couple of screenshots to show what I mean:

![image](https://user-images.githubusercontent.com/1320357/55915864-8e7d1300-5b9f-11e9-8003-e41dd6530aa9.png)

![image](https://user-images.githubusercontent.com/1320357/55915888-9c329880-5b9f-11e9-9421-28c35356bdc6.png)

This is with RoughlyEnoughItems-2.7.1.84.

**Comment by shedaniel** [comment]
This is not fixed in the latest build >:(
