### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#562]
**Describe the bug**

Doesnt show candles crafting on servers
Latest version 1.17

**Steps to Reproduce**
- First Step : log on to a server
- Second Step : go to candles on the menu thing crafting idk that the mod gives to you and click on it, and it wont show any crafting

**Screenshots**
![kép](https://user-images.githubusercontent.com/86217660/122711259-2f78b580-d262-11eb-9418-b3aabce0a48b.png)

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14] 1.17
 - Mod Loader: [e.g. forge, fabric] fabric 
![kép](https://user-images.githubusercontent.com/86217660/122711338-4b7c5700-d262-11eb-907c-58d537bfd64f.png)

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: no logs

**Additional context**
-

**Comment by ghost** [comment]
in singleplayer, works 
![kép](https://user-images.githubusercontent.com/86217660/122711491-84b4c700-d262-11eb-8ba6-a1de68cff4e5.png)
In multiplayer, doesnt work

**Comment by shedaniel** [comment]
Maybe try on a vanilla server? could be their server's fault?

**Comment by ghost** [comment]
Good idea, i did that, and now more recipes missing, not just the candles, even on the server i was first on.
Update: They work now on the server that I was first on

**Comment by shedaniel** [comment]
If it happens again, please attach the logs.
