### ISSUE TITLE
[Bug] Happiness is a Warm Gun Crash

### ISSUE THREAD

**Issue by lartts** [shedaniel/RoughlyEnoughItems#563]
**Describe the bug**
Crashes with Happiness is a Warm Gun

**Steps to Reproduce**
- Spell "Gun" in the search bar

**Screenshots**
![2021-06-21_19 38 30](https://user-images.githubusercontent.com/74058566/122763281-58cc2c80-d2c8-11eb-81f9-afe74bd747d6.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: 0.11.6

**Logs**
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6686630/latest.log)

**Additional context**
- After the first crash, whenever I open the inventory it crashes again

**Comment by shedaniel** [comment]
Not REI crashing,
