### ISSUE TITLE
Crash when searching [Bug]

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#567]
**Describe the bug**
Enter a search string. First character was "@"

**Steps to Reproduce**
- open REI (tab in my case)
- enter st into the search field

**Environment**
 - Minecraft: 1.17
 - Mod Loader: Fabric
 - REI 6.0.257

**Logs**
https://pastebin.com/UkVfCZXZ

**Comment by shedaniel** [comment]
"mod.azure.hwg" is crashing, not REI.

**Comment by Knito58** [comment]
Thank you for reading that for me. I was in the "looking-at-pictures-only-mode" and did not understand. Dismissed the offending mod and it works with weirdest strings I can think of.

Bug fixed.

PICNIC

Problem In Chair Not In Computer
