### ISSUE TITLE
Crashing on lunch[Bug]

### ISSUE THREAD

**Issue by YourMotherr** [shedaniel/RoughlyEnoughItems#569]
**Describe the bug**
My minecraft simply crashes when i lunch or press play

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/79705789/122935400-faab5200-d378-11eb-975f-f29241c22b00.png)
**Environment**
 - Minecraft: 1.17
 - Mod Loader: [fabric]

**Logs**
https://pastebin.com/29vTb48C

**Additional context**
I've tried latest version of every needed mod like cloth config fabric api fabric modloader arch all of them

**Comment by shedaniel** [comment]
update optifabric
