### ISSUE TITLE
1.14.snapshot: CC-Tweak Computer GUI blocked

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#57]
When I open the computer GUI of a Computercraft computer (cc-tweaked) then it will not recognize any Input. REI's item list is shown.

When I uninstall REI then the computer's GUI will work properly and allow coding.

**Comment by shedaniel** [comment]
Can I get a screenshot?

**Comment by shedaniel** [comment]
REI version + Snapshot version?

**Comment by Knito58** [comment]
Sorry - was away from home for 3 days. Last version (REI 2.7.6.+build.90)  seems to fix the issue although the items are still shown in the CC GUI.
