### ISSUE TITLE
[Bug] [Forge] REI bypasses RenderTooltipEvent when rendering tooltips

### ISSUE THREAD

**Issue by squeek502** [shedaniel/RoughlyEnoughItems#570]
**Describe the bug**

REI [calls an overload of `Screen.renderTooltip`](https://github.com/shedaniel/RoughlyEnoughItems/blob/6809f7d16a541127a52fad19e79bd19684ab9963/RoughlyEnoughItems-runtime/src/main/java/me/shedaniel/rei/gui/ContainerScreenOverlay.java#L606) that is not hooked by Forge, meaning that Forge's RenderTooltipEvent events are never fired. These events are relied on by mods that do custom tooltip rendering like AppleSkin.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Additional context**

https://github.com/squeek502/AppleSkin/issues/117

**Comment by shedaniel** [comment]
Should be fixed now.
