### ISSUE TITLE
[Bug] Crashes on startup if used with Industrial Revolution and Happines is a Warm Gun

### ISSUE THREAD

**Issue by filipesn** [shedaniel/RoughlyEnoughItems#571]
The game will only crash if all 3 mods are present, removing one stops the crash
Minecraft also passes the blame to REI

I am using the fabric loader 0.11.6-1.17 , with 
architectury-2.0.11-fabric
fabric-api-0.36.0+1.17
fabric-language-kotlin-1.6.1+kotlin.1.5.10
geckolib-fabric-1.17-3.0.5
HWGMod-1.17-1.0.4
indrev-1.10.0-alpha.5
modmenu-2.0.2
RoughlyEnoughItems-6.0.258-alpha-fabric
here are the logs:
https://hastebin.com/yeqisucovu.yaml

**Comment by shedaniel** [comment]
Can you try joining a world with REI disabled to see if that crashes? Even tho you say it is crashing with REI, but REI is just loading a vanilla class.

**Comment by PikachuPlaysSKY** [comment]
I also got those mods and when launching without REI, works fine. adding REI, i crash
https://pastebin.com/zG7a3ZHL

**Comment by filipesn** [comment]
Removing REI does infact stop the crash. Actually, removing any one of them stops the crash

**Comment by warjort** [comment]
What version of sponge mixin do you have?

This looks a lot like this:
https://github.com/SpongePowered/Mixin/issues/430
e.g. see AE2 workround and reference to similar error with Patchoulli
https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/06a8843a65db6b1be914089f91c369d39410312c

AFAICT, this was fixed back in December in mixin 0.8.3 which was only finally released 9 days ago?

**Comment by filipesn** [comment]
In the newer versions of REI this has been fixed
