### ISSUE TITLE
[Bug] Favoriting items causes crash.

### ISSUE THREAD

**Issue by ArrowFX** [shedaniel/RoughlyEnoughItems#572]
When you favourite items Minecraft crashes (Error code:The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1 )

I have made sure that it isn't because of any keybind conflicts or mod conflicts.

Crash file:

[crash-2021-06-23_15.06.21-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6702086/crash-2021-06-23_15.06.21-client.txt)

or if you don't like it like that then here:

https://pastebin.com/0AwrcKLG

**Comment by shedaniel** [comment]
got a full log?

**Comment by ArrowFX** [comment]
> 
> 
> got a full log?

full crash log here: https://pastebin.com/NBihqnzR

full log here: https://pastebin.com/f2TK8xjr
