### ISSUE TITLE
[Bug] REI is not updating its entries

### ISSUE THREAD

**Issue by idkimanerd** [shedaniel/RoughlyEnoughItems#573]
**Describe the bug**
When searching in rei, the gui doesn't change

**Steps to Reproduce**
- download these mods
- search 

**Screenshots**
![image](https://user-images.githubusercontent.com/81585709/123476127-2b75cc00-d5b1-11eb-9b05-50486a208c5e.png)
 

**Environment (please complete the following information with the version):**
 - Minecraft: 1.166
 - Mod Loader: fabric

**Logs**
https://pastebin.com/85h2gwKc

**Additional context**
mods:
https://www.mediafire.com/file/tt0vrb6s19nsr4q/mods.zip/file

**Comment by shedaniel** [comment]
Try removing sodium before reporting any rendering issues.

**Comment by idkimanerd** [comment]
sorry, it was a config issue
