### ISSUE TITLE
[Feature] Add Pinyin/Kana support

### ISSUE THREAD

**Issue by shedaniel** [shedaniel/RoughlyEnoughItems#574]

**Comment by Dr-WeiAL** [comment]
The function of pinyin should be able to be implemented with this
https://github.com/Towdium/PinIn

**Comment by vfyjxf** [comment]
Will REI's Pinyin search conflict with [JustEnoughCharacters](https://github.com/Towdium/JustEnoughCharacters)' Pinyin support for REI. Maybe we should remove REI support from [JustEnoughCharacters](https://github.com/Towdium/JustEnoughCharacters) in the future?

**Comment by shedaniel** [comment]
There will be an api to add custom input methods, but rei will come with its own as well, if there are any ime rei itself doesn't support (i.e. I don't support duopin), JEC can support that

**Comment by shedaniel** [comment]
Added the feature, the docs can be found [here](https://www.craft.do/s/qj8mHyTVd7qkOZ/b/01E0F2A2-1D8A-4A8A-ADDB-A6CA5D2D4D11/Input_Methods_(Client)),
