### ISSUE TITLE
[Bug] Recipes not displayed for some items in TechReborn

### ISSUE THREAD

**Issue by wbsp9999** [shedaniel/RoughlyEnoughItems#577]
**Describe the bug**
As of alpha-255, some items from TechReborn do not display their recipes. Not sure if this is something that needs to be addressed in TR due to changes or is a bug in REI

**Steps to Reproduce**
- Open REI with TR 5.0.2 beta38 (current latest curse release)
- Search for lithium ion battery
- Click on it or bring to inv and use keybinds to try to view recipes/uses
- No recipe is displayed. This works properly in alpha-254

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft 1.17
 - Mod Loader: fabric

**Logs**
Nothing odd shows up in the logs

**Additional context**
Testing was completely client-side with only TR and REI installed.

**Comment by shedaniel** [comment]
Can you check if the new update: 6.0.262-alpha fixes it

**Comment by wbsp9999** [comment]
Yep, that did it, thanks for the quick fix!
