### ISSUE TITLE
[Bug] Crash at stratup with REI v6.0.262-alpha on FABRIC

### ISSUE THREAD

**Issue by Freggels** [shedaniel/RoughlyEnoughItems#578]
**Describe the bug**
Crash at startup with REI v6.0.262-alpha

**Steps to Reproduce**
- Setup for REI v6.0.262-alpha with its dependencies
- Start the game and see it crash

**Environment:**
 - Minecraft: 1.17
 - Mod Loader: fabric 0.11.6

**Logs**
https://paste.ee/p/RH0bC

**Additional context**
Reverting back to REI v6.0.260-alpha solves the issue

**Comment by shedaniel** [comment]
You have 6.0.263, a build that is removed now (pretty lucky :p), please try to downgrade to proper 262
