### ISSUE TITLE
[1.17 Bug] Client crashes when searching scrolling through REI Pages

### ISSUE THREAD

**Issue by kalinzange** [shedaniel/RoughlyEnoughItems#585]
**Describe the bug**
Whenever I start 'scrolling' through pages of REI my client crashes

**Steps to Reproduce**
Steps to reproduce the behaviour:
- Press E
- Start from the page final page until page N# 1
- Client Crashes

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[crash-2021-07-19_22.56.52-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/6844135/crash-2021-07-19_22.56.52-client.txt)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/6844156/latest.log)

**Additional context**
N/A

**Comment by ghost** [comment]
Same in 1.16.5

logs: https://pastebin.com/JBt2cnHq

**Comment by shedaniel** [comment]
Report to Entity Banners
