### ISSUE TITLE
[Bug - Fabric 1.17.1] REI unable to load with Rei Compatibility plugin.

### ISSUE THREAD

**Issue by Luligabi1** [shedaniel/RoughlyEnoughItems#586]
**Describe the bug**
When adding REI support on my mod (source code and up-to-date release [here](https://github.com/Luligabi1/MagicFungi), it works fine on 1.17, but completely breaks on 1.17.1, making REI not even load.

**Steps to Reproduce**
- Run the mod on 1.17.1, and log into a world. The error will be printed into the log with no additional info.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/MYdgmAA7 

**Additional context**
Result was the same with two different REI versions (v6.0.258-alpha and v6.0.264-alpha), with the only difference being additional "Entry minecraft:item does not exist!" being spammed in the former.

**Comment by shedaniel** [comment]
You broke vanilla recipe books
 java.lang.NullPointerException: Cannot read the array length because the return value of "net.minecraft.recipe.Ingredient.getMatchingStacks()" is null
