### ISSUE TITLE
Game Crashes when scrolling through REI pages

### ISSUE THREAD

**Issue by ayuwooh** [shedaniel/RoughlyEnoughItems#588]
**Describe the bug**
Whenever I start 'scrolling' through pages of REI my client crashes

**Steps to Reproduce**

- Press E
- Scroll through pages (mine crashes exactly at page nº4)
- Client Crashes

**Environment (please complete the following information with the version):**

- Minecraft: 1.17.1
- Mod Loader: Fabric 0.7.4

**Logs**
Pastebin the log [e.g. logs/latest.log] and link it below:
Crash: https://pastebin.com/8LpChCK0
Log: https://pastebin.com/riSkBu6p

**Additional context**
I'm using other mods

**Comment by DavidDudson** [comment]
This is the exact issue i got today, using AOF4 + Iris

https://pastebin.com/uy1xSqYu

**Comment by DavidDudson** [comment]
![KtzmBzLc6B](https://user-images.githubusercontent.com/2680733/128481294-4750f2cd-dc67-42e9-af06-cfa502901ab4.gif)

It crashes either on tech reborn. Or whatever mod is after it. Shaders from Iris don't actually affect this.

**Comment by Muffintiem** [comment]
I think part of the problem is because it includes items that aren't craftable like spawn eggs, it ends up including incomplete stuff from mods. I think the number of crashes would be drastically reduced if only craftable things were included.

**Comment by shedaniel** [comment]
that's not how it works, it's the mods problem to crash, no items in vanilla crashes even if it is not designed to be visible.

**Comment by Muffintiem** [comment]
Is it possible to blacklist things from REI but still have them show up in the game? Or would such a thing be impossible?

**Comment by shedaniel** [comment]
It is, newer REI versions now also include the item being rendered into the description so you can know what items is failing to render. My idea is you have sodium without iridium
