### ISSUE TITLE
[Bug] Favourites saved in older versions (1.16 and before) don't appear after updating to 1.17.x

### ISSUE THREAD

**Issue by Katniss218** [shedaniel/RoughlyEnoughItems#589]
**Describe the bug**
Pretty self-explanatory, favorites just disappear, as if the loader can't parse them.

**Steps to Reproduce**
- Save favourites in an old version of the mod (or copy my old config linked below)
- Load up the config in a new version, the favourites are missing

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17/1.17.1 (tested on both)
 - Mod Loader: fabric

**Logs**
https://pastebin.com/xU5BNhzT

**Additional context**
It heavily affects be as I have a list of over 1000 favourites with custom NBT data, so I can't use a chest or something to move them over.
Config with over 1k favs: https://drive.google.com/file/d/1PVGedyYQhBfRqEa76pPWJ0FRIt6_3oHD/view?usp=sharing

**Comment by shedaniel** [comment]
Sorry, this is not something I want to particularly support.
