### ISSUE TITLE
[Bug] Fluids stop rendering with Iris shaders 1.17

### ISSUE THREAD

**Issue by Desempregago** [shedaniel/RoughlyEnoughItems#590]
**Describe the bug**
Title explains itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/14002834/127753567-524f7790-c828-4855-b925-345ba4e0777d.png)

**Environment:**
 - Minecraft: [1.17.1]
 - Mod Loader: [Fabric 0.11.6 with API 0.37.1]
 - REI: 6.0.624-alpha

**Additional context**
Iris shaders

**Comment by shedaniel** [comment]
Can you also cross-report this issue to Iris as well? I am not familiar with how Iris works. Would be great if we can get some help from them.

**Comment by Panderine** [comment]
The fluids stop rendering in REI as soon as you enable shaders (any shader)

**Comment by shedaniel** [comment]
Fixed on Iris side.
