### ISSUE TITLE
[Bug] Keybinds register in search bar

### ISSUE THREAD

**Issue by TheFireOcean** [shedaniel/RoughlyEnoughItems#596]
**Describe the bug**
Sometimes when trying to type in the search bar- actually most of the time, it registers keybinds and I end up closing my inventory.

**Steps to Reproduce**
- Try to type e in search bar

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
Forge 1.17

**Logs**
https://pastebin.com/F5Dk3zhj

**Comment by shedaniel** [comment]
Duplicate of #594
