### ISSUE TITLE
[Bug] v6.0.267 not marked as compatible with 1.17.1 on Curseforge

### ISSUE THREAD

**Issue by HandyHat** [shedaniel/RoughlyEnoughItems#597]
**Describe the bug**
On curseforge, the game version for `v6.0.266` and `v6.0.267` is `1.17` rather than `1.17.1`.

**Screenshots**
![image](https://user-images.githubusercontent.com/58530748/128615146-7545a382-43ed-42e1-8ff5-5d298069822c.png)

**Additional context**
This means that the Curseforge launcher marks `v6.0.264` as the latest compatible version when using 1.17.1 rather than `v6.0.267`, which is misleading.

**Comment by shedaniel** [comment]
Thanks for reporting, the file has been updated with 1.17.1 added.
