### ISSUE TITLE
[Bug] Dragging from favourite removes the item from favourite (v0.6.260-alpha)

### ISSUE THREAD

**Issue by Azercoco** [shedaniel/RoughlyEnoughItems#598]
**Describe the bug**
Dragging an item from the favourites to use with MI Slot Locking  (which uses `me.shedaniel.rei.api.client.registry.transfer.TransferHandler`) removes the item from the favourite. This should not happend and the item should stay in the favourite.

**Steps to Reproduce**
- Add an item to favourite
- Open a MI inventory 
- Drag an item to slot lock
- The item has disappeared from the favourites

**Screenshots**
![image](https://user-images.githubusercontent.com/20425137/128762350-b33cfa55-f4eb-4d58-bc0f-6ebf194ef47a.png)
![image](https://user-images.githubusercontent.com/20425137/128762510-ab2f745b-8bfe-4486-a146-6f75db199b48.png)
![image](https://user-images.githubusercontent.com/20425137/128762425-01f42886-267a-402e-8ccc-687bf1e9751a.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Comment by shedaniel** [comment]
This should be fixed on REI 1.18.1 as there are modes of consuming a dragging stack.
