### ISSUE TITLE
[Bug] Crash when saving settings

### ISSUE THREAD

**Issue by maicol07** [shedaniel/RoughlyEnoughItems#599]
**Describe the bug**
The game crashes when settings are saved

**Steps to Reproduce**
- Open a world
- Go to REI settings
- Hit "Save & Quit"

**Environment:**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Crash report: https://bytebin.lucko.me/ldOOLVO11b

**Comment by shedaniel** [comment]
Please re-open the issue with a working crash report, I know I am late but yes.
