### ISSUE TITLE
[Bug] REI is not working until you press 'Reload Plugins' in config options

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#601]
1.17.1 
Latest REI
-

When you join the server, REI is non functional, hotkeys do not work, nothing. You must go into Mod menu -> REI -> and click Reload Plugins.

Once reloaded, the recipes start showing and everything is back to normal. Not sure what the cause of this is, it was working before update.

**Comment by shedaniel** [comment]
I believe this is now fixed with REI forcefully reloading if it is not yet reloaded.
