### ISSUE TITLE
[Bug]i cannot pick up my items

### ISSUE THREAD

**Issue by minkey-paloozi** [shedaniel/RoughlyEnoughItems#602]
**Describe the bug**

**Steps to Reproduce**
- First Step
- Second Step

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14]
 - Mod Loader: [e.g. forge, fabric]

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**

**Comment by shedaniel** [comment]
REI does not modify item pickup.
