### ISSUE TITLE
[Bug] Interacting with the menu makes my cursor stuck on top of my game.

### ISSUE THREAD

**Issue by Snoe0** [shedaniel/RoughlyEnoughItems#603]
**Describe the bug**
When I do anything related to REI, my cursor gets stuck on top of my game and I can't press anything or interact, but the game still continues.

**Steps to Reproduce**

First Step: Open inventory.
Second Step: Click any of the recipes or the settings wheel.
**Screenshots**

Screenshots hide my mouse cursor.

https://user-images.githubusercontent.com/83789327/130333720-036de91b-fc3c-4a85-bb8d-8d64ef7f977a.mp4

**Environment (please complete the following information with the version):**
1.17.1 Fabric
Fabric API
Architectury
Cloth Config
Carpet Mod

**Logs**
Pastebin the log [e.g. logs/latest.log] and link it below:

Logs are empty

**Comment by shedaniel** [comment]
Do you have replay mod?

**Comment by Snoe0** [comment]
Yes

**Comment by Snoe0** [comment]
Alright, replay mod is what broke it. Thanks!

**Comment by Bannta** [comment]
Thanks, I was wondering why the mod would leave me in mouse hosed state. I have the replay mod loaded as well.

**Comment by StudentWeis** [comment]
You can ues the up-to-date RM(2.6.1)，because this issue has been resolved.
https://www.replaymod.com/download/
