### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by johannesmateboer** [shedaniel/RoughlyEnoughItems#604]
**Describe the bug**
REI crashes when searching

**Steps to Reproduce**
- Open REI
- Star typing

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
 - REI 6.0.268-alpha

**Logs**
https://bytebin.lucko.me/Ls4ZZjw6D4

**Additional context**
Sometimes randomly crashes when going through the pages

**Comment by shedaniel** [comment]
Should be fixed
