### ISSUE TITLE
[Bug] Tooltip rendering is not the same as vanilla for line breaking

### ISSUE THREAD

**Issue by Azercoco** [shedaniel/RoughlyEnoughItems#605]
**Describe the bug**
When adding empyt line with `tooltip.add(new LiteralText(""));` in a custom item, those lines appear in the vanilla tooltip but not in REI.

**Steps to Reproduce**
- Create a custom tooltip with `tooltip.add(new LiteralText(""));`
- Compare the vanilla tooltip and the REI tooltip

**Screenshots**
![image](https://user-images.githubusercontent.com/20425137/130521990-44c27708-bee8-4cf0-ab31-fccdf7c6cc8b.png)
vs 
![image](https://user-images.githubusercontent.com/20425137/130522031-29dee0d7-760a-4c73-a903-00c1a38f4b78.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
 - REI: v6.0.260-alpha

**Comment by shedaniel** [comment]
Is this still an issue? Just checking since it has been so long
