### ISSUE TITLE
[Bug] Wont show recipes when i click on items 1.17.1

### ISSUE THREAD

**Issue by Jec1042** [shedaniel/RoughlyEnoughItems#606]
Hello, 
Thank you for your time and help 
R.E.I will not  show recipes or use of items no matter what button is clicked
Please help, 
Thank you.

**Comment by nmay231** [comment]
Are you clicking an item in the right panel or are you pressing "u" or "r"? If pressing u or r is not working, I would double check your keybinds to make sure they are not being used for another mod.

**Comment by shedaniel** [comment]
Incomplete issue

**Comment by silentnyte** [comment]
I experienced the same issue with 1.17.1 Fabric server using Loader 0.12.12 and REI 6.3.358. To corrected it I had to start a single player game and open the crafting menu. Then when I returned to the multiplayer server the crafting menu worked.

I am also getting a message "REI not yet fully initialized. Missing stages: END"
Here is the REI log. https://pastebin.com/tdDiKmeG
