### ISSUE TITLE
[Bug] Crashes upon using search bar

### ISSUE THREAD

**Issue by just-chubbyfoxx** [shedaniel/RoughlyEnoughItems#609]
Whenever the search bar is used, crash.
I go click the search bar, type in something and then crash occurs

Very happy that i crashed during recording

**Comment by Metal-666** [comment]
I have the same issue. Seems like there is a conflict with Inspecio (mod that adds various tooltips to items).

**Comment by shedaniel** [comment]
Please re-open the issue with the crash report.
