### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AlisterGontineac** [shedaniel/RoughlyEnoughItems#613]
Tried crafting from inventory with wood palm blocks from Barren Isles ( https://www.curseforge.com/minecraft/mc-mods/barren-isles ) and game crashed

- tried crafting from inventory with wood palm blocks from Barren Isles and game crashed
- relaunched game, got past that point of crafting blocks, then crashed again when trying to craft the crafting table.

**Environment 
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
https://gist.githubusercontent.com/natanfudge/41916d59ca7adea0e62c55ed43e6f4f4/raw/e9dc3b201b7fa375f364107977aaf5e0b3c5fd16/crash.txt

**Comment by shedaniel** [comment]
I believe that there are other issues in place for this, please reopen with the **full log**.
