### ISSUE TITLE
[Feature] Hide items and/or crafting recipes

### ISSUE THREAD

**Issue by alexmozaidze** [shedaniel/RoughlyEnoughItems#624]
**Describe the solution you'd like**
It would be cool if there was a config file for disabling crafting recipes and items.
I see it as being a json/json5 file with a structure that's something like this:
```json5
{
    // Recipes to hide
    "recipes": {
        "namespace": ["item_recipe1", "item_recipe2"]
    },
    // Items to hide
    "items": {
        "namespace": ["item1", "item2"]
    }
}
```

**Additional context**
I make a modpack and I disable a lot of things with Fabrication's yeet recipe feature, which removes the recipes but items still show up in REI. I kind of only want to hide items, but hiding recipes would be cool if I were to make a super-duper secret recipe for an item that only the coolest could unravel.

**Comment by elhertz** [comment]
You can currently do this with KubeJS. Although it would be a good feature for REI.

**Comment by alexmozaidze** [comment]
KubeJS devs don't want to do 1.17 version

**Comment by elhertz** [comment]
What do you mean? I'm using the 1.17 version and it works just fine

**Comment by alexmozaidze** [comment]
Can you give a link?

**Comment by elhertz** [comment]
https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric/files/3355296

**Comment by Muffintiem** [comment]
It still would be good to have this implemented in the mod since not everyone knows how to use KubeJS.

**Comment by shedaniel** [comment]
Disabling items are doing with the base mod with Manual Filtering, scroll to the bottom of REI config menu. Doing so will also hide appropriate recipes.
