### ISSUE TITLE
[Bug] REI doesn’t display farmers delight cooking pot recipes 

### ISSUE THREAD

**Issue by HeyBosoc** [shedaniel/RoughlyEnoughItems#625]
When attempting to see the recipe of cooked food made in the farmers delight pot, it doesn’t bring up a recipe. unlike foods that are made in the crafting table. This is very frustrating since there are little to no images online of the recipes, so im unable to create the cooked foods.

This seems to be happending on both 1.16.5 and 1.17.1. and restarting the game or deleting the configs doesnt help.

I am on fabric 1.17.1-0.1.1. OF farmers delight 
And version 6.0.272-alpha-fabric of REI

**Comment by shedaniel** [comment]
You should report this to them instead to tell them to add integration with REI, REI doesn't handle custom recipe types :p

**Comment by HeyBosoc** [comment]
> You should report this to them instead to tell them to add integration with REI, REI doesn't handle custom recipe types :p

ooo good point, ty!
