### ISSUE TITLE
[Bug] REI Crafting Recipe Menu Basically Freezes Game

### ISSUE THREAD

**Issue by DakotaPride** [shedaniel/RoughlyEnoughItems#628]
**Describe the bug**
Whenever I open a crafting recipe (For any item), I can't exit the screen without freezing. I usually press escape, which ends in the same case of me being in chat, without chat open. I can move my mouse, but I can't move, look around, access containers, or reopen my inventory or anything related to the GUI.

**Steps to Reproduce**
- Open Inventory
- Open Crafting Recipe for any item (pressing R for me)
- Press 'escape' or 'E'

**Screenshots**
![Screenshot (349)](https://user-images.githubusercontent.com/82760983/134820529-0767dfa3-871c-401a-9d29-c970349c5443.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
(Game did not crash)

**Additional context**
Modlist:
- Architectury
- Backslot
- BBOutlineReloaded
- Durability Viewer
- Fabric API
- Carpet
- MCDW (Minecraft Dungeons Weapons)
- Mod Menu
- Optifabric
- Polymorph
- preview optifine 1.17.1
- Replay Mod
- Roughly Enough Items
- World Edit
Happens on Singleplayer

**Comment by DakotaPride** [comment]
My mouse doesn't show up, but my mouse is allowed to move all it wants when this happens

**Comment by shedaniel** [comment]
Update both replay mod and REI (if outdated), that should fix the issues.
