### ISSUE TITLE
[Bug] Can't click on item when using "craftable" filter.

### ISSUE THREAD

**Issue by violetazx** [shedaniel/RoughlyEnoughItems#629]
**Describe the bug**
When using the "craftable" filter, I can't select an item to view its recipe. Works when "craftable" filter is off.

**Screenshots**
https://media.giphy.com/media/n1MBe2KRXcZFZHsF9G/giphy.gif?cid=790b7611c022721dd2f00590c751a7d45f301bc69370449c&rid=giphy.gif&ct=g

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
 - REI: v6.0.279-alpha

**Comment by shedaniel** [comment]
Cannot reproduce.
