### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lolteam4u** [shedaniel/RoughlyEnoughItems#630]
**Describe the bug**
So https://www.curseforge.com/minecraft/mc-mods/immersive-portals-survival-adaptation needs to use something called NBTCrafting so the version nbtcrafting 2.0.19 is installed on our server however doing so has killed REI it displays errors on boot and will not run/ connect the backend server the current version of REI I am running is [Fabric 1.17.1] v6.0.279-alpha

**Steps to Reproduce**
I believe it as follows
Install nbt crafting 2.0.19  from here https://www.curseforge.com/minecraft/mc-mods/nbt-crafting and try and load the mod for it to error and display an error in-game saying 

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Fabric 1.17.1

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://paste.ee/p/Wn1wO
**Additional context**
It will display but does not initialize 
https://prnt.sc/1tymylh
it says missing stage end

**Comment by shedaniel** [comment]
NBTCrafting is causing the issue, not us.
