### ISSUE TITLE
[Bug]Crash on forge, not sure what I did, I think I tried viewing a recipe?

### ISSUE THREAD

**Issue by Trinsdar** [shedaniel/RoughlyEnoughItems#632]
**Describe the bug**
Crashed on client

**Steps to Reproduce**
Not sure yet, I'll try to reproduce it

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: forge

**Logs**
https://gist.github.com/Trinsdar/38aa2426d69ba12973311c939cd49043

**Additional context**
This seems very similar to a multithread crash I've encountered before, but I could be wrong and it is simply an array out of bounds exception. if it is a multithread crash my best guess is to syncronize whatever method is crashing

**Comment by shedaniel** [comment]
Don't think this is related to REI.
