### ISSUE TITLE
How do i make plugins for REI

### ISSUE THREAD

**Issue by Errorbot1122** [shedaniel/RoughlyEnoughItems#633]
I looked at the [wiki](https://github.com/shedaniel/RoughlyEnoughItems/wiki) (The world's most empty wiki...), clicked the [link](https://shedaniel.gitbook.io/roughly-enough-items/) and read the page, it did not help that much. It's even a year old and was made for REI 5, which is outdated. (I think)

so how do you make plugins for this?

P.S: Act like I am a beginner at making Minecraft mods because I am!! (only watch a few tutorials for fabric)

**Comment by ghost** [comment]
i dont think this issue is technical enough for github, maybe ask this in the discord?
