### ISSUE TITLE
[Feature] Search filter - Display only blocks with a crafting recipe. 

### ISSUE THREAD

**Issue by PrincessPwny** [shedaniel/RoughlyEnoughItems#634]
**Describe the solution you'd like**
A new search filter that only displays blocks that have a crafting recipe. 

**Additional context**
I play on a server that disables most of the normal vanilla crafting recipes and would find it useful to know what I can actually craft. I'd consider this as a not very common use case, but it could be useful on any multiplayer server that disables crafting recipes for balance or server health.

This could also be implemented as a setting in the option menu, making REI act as more of a dedicated recipe book for those who would more permanently like REI to take on that role, or even a UI toggle to swap between all items and only items REI has crafting methods for.

**Comment by shedaniel** [comment]
Yeah I have to say that this is quite specific so I have sorry to say that I will deny this suggestion.
