### ISSUE TITLE
[Bug]Pressing U on brown wool to see uses in recipes crashes my game

### ISSUE THREAD

**Issue by FearAK** [shedaniel/RoughlyEnoughItems#635]
**Describe the bug**
Pressing U on brown wool to see uses in recipes crashes my game

**Steps to Reproduce**
- press U on brown wool
- crash
- ????
- no profit

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
[crash-2021-10-04_19.24.08-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/7280433/crash-2021-10-04_19.24.08-client.txt)

**Additional context**

**Comment by shedaniel** [comment]
Report to mocolors

**Comment by FearAK** [comment]
Oh, didn't realise that was the mod causing it. very sorry and thank you!
