### ISSUE TITLE
[Bug] Kick from the server when trying to place items.

### ISSUE THREAD

**Issue by shideus** [shedaniel/RoughlyEnoughItems#640]
**Describe the bug**
Sometimes, when you click on the "+" button to automatically place items for crafting, the player kicks from the server. This does not happen with all objects, but only with some. Currently, this problem is observed when trying to craft the "Energy Box" from the Tech Reborn mod. At the same time, a message appears in the server console: `shnakm lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes`

**Steps to Reproduce**
- Install REI and Tech Reborn
- Collect the necessary items for crafting "Battery Box"
- Open the workbench, open the "Battery Box" craft in REI and press the "+" button

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: 

**Additional context**

**Comment by shedaniel** [comment]
This is being fixed in the near future, thanks for bearing with this for now
