### ISSUE TITLE
[Bug] Viewing a recipe crashed Minecraft client

### ISSUE THREAD

**Issue by teoWei** [shedaniel/RoughlyEnoughItems#644]
**Describe the bug**
Left-clicking or pressing key to view a crafting recipe crashes Minecraft client.

**Steps to Reproduce**
-View any crafting recipe
-Minecraft crashes

**Screenshots**
-

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric
(v6.0.304-alpha)

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/eCQgD7fq

**Additional context**
-

**Comment by Anubeia** [comment]
Can confirm, issue occurs in this version and not the version I used prior, which is 6.0.298. The changelog indicates that code regarding recipes seems to have been changed in this version, so I assume that it's a regression between versions.

EDIT: clarified version I used prior to this one.

**Comment by shedaniel** [comment]
Thanks for reporting, this is an issue with REI's new integration with Fabric's fluid api, this should be fixed in a future update.
