### ISSUE TITLE
[mod incompatability]

### ISSUE THREAD

**Issue by DontarX** [shedaniel/RoughlyEnoughItems#648]
**Describe the bug**
Disconnect when attempting to connect to any 1.17.1 multiplayer server when using both litematica and REI
recieve error "Interal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: inflate data is bad"
**Steps to Reproduce**
- First Step install Fabric Loader, Fabric API, architectury Fabric, Cloth Config API, RoughlyEnoughItems Fabric, install litematica and malilib fabric
- Second Step Connect to 1.17.1 server

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/a0WrikL1
**Additional context**
the bad inflate data error does not show up in the logs
tried to google the issue, and "Bad Inflate Data" does not show up at all

**Comment by shedaniel** [comment]
Seems unrelated to REI.
