### ISSUE TITLE
[Feature] Include Token Enchanter Recipes

### ISSUE THREAD

**Issue by Zarepheth** [shedaniel/RoughlyEnoughItems#649]
**Describe the solution you'd like**
I added [Token Enchanter](https://www.curseforge.com/minecraft/mc-mods/token-enchanter) to the mod pack I've been playing, but REI does not display the Token Enchanter machine's recipes. And since the mod author says to use JEI for recipes, I'm stuck with trial and error or swapping out recipe mods.

**Additional context**
Playing modpack Valhelsia 4 for 1.17. The modpack came with REI.
Added Token Enchanter via the Curse Forge Overwolf launcher.

**Comment by shedaniel** [comment]
REI pretends to be JEI, if the recipes from this mod doesn't appear, I can look into this. (Pretending to be JEI isn't perfect)

**Comment by shedaniel** [comment]
This has been fixed, please test <3

**Comment by Zarepheth** [comment]
Tested fine. The update brings the Token Enchanter Recipes into REI! Thank you!
It also appears that other things have been improved with the update.
