### ISSUE TITLE
Fabric crash after using search bar/scrolling through filtered items[Bug]

### ISSUE THREAD

**Issue by CynnicalSloth** [shedaniel/RoughlyEnoughItems#650]
**Describe the bug**
Occasionally after using the search bar or scrolling through filtered items, the game will freeze for a few seconds, save, and CDT

**Steps to Reproduce**
- Open Inventory 
- Enter text into REI 
- After a few seconds the game may crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17
 - Mod Loader: Fabric

**Logs**
https://pastebin.com/UaeZTPmQ

The main seems to be this one

https://pastebin.com/7hkupB2P

**Additional context**
-if exited quickly enough the crash can be avoided many times before actually happening
-The less vague the search the less likely the crash.

**Comment by CynnicalSloth** [comment]
You may want to look into Appleskin and this mod as I believe removing Appleskin solved the issue.

**Comment by shedaniel** [comment]
Seems to be fixed / unrelated to REI.
