### ISSUE TITLE
Fabric Crash After Just Scrolling down the page [Bug]

### ISSUE THREAD

**Issue by alvileg** [shedaniel/RoughlyEnoughItems#652]
**Describe the bug**
The game just crashes when scrolling down the menu with all the items
**Steps to Reproduce**
- Open the game, enter a world
- Open inventory, and scroll down the menu where the items are.
-  Crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
`The game crashed whilst adding entry
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.get(net.minecraft.class_3611)" because "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.INSTANCE" is null
Exit Code: -1`
https://pastebin.com/XbQhqrn6

**Additional context**

**Comment by etaripde** [comment]
appears to my games after updating to [1.17.1] Fabric API 0.42.0 from [1.17.1] Fabric API 0.41.3

**Comment by alvileg** [comment]
Apparently, it is an issue with Fabric API 0.42.0, and downgrading to 0.41.3 fixes the issue.
