### ISSUE TITLE
[Bug] Failed to fill displays!

### ISSUE THREAD

**Issue by cody-quinn** [shedaniel/RoughlyEnoughItems#654]
**Describe the bug**
It spams the logs with the error and doesn't render anything

**Steps to Reproduce**
- Launch game
- Sometimes it will happen, sometimes it wont. When it happens it happens for the entire duration of the session, when it doesnt it doesnt start happening mid way through a session

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1 (All of Fabric 4)
 - Mod Loader: Fabric

**Logs**
https://paste.jordanosterberg.com/uxagawobig.properties

**Additional context**
Java 17

**Comment by shedaniel** [comment]
Need the full log

**Comment by cody-quinn** [comment]
Here is a google drive:
https://drive.google.com/file/d/1IQVzQMot8Fz3Xp15Wy_Vou9gSAIa0_xN/view?usp=sharing
All the paste sites I tried either crashed or didn't let me upload it when I tried. The file is 8Mb
