### ISSUE TITLE
[Bug] Incompatibility with AE2

### ISSUE THREAD

**Issue by Micalobia** [shedaniel/RoughlyEnoughItems#655]
**Describe the bug**
Typing into the REI textbox while in an AE2 terminal has some weird issues

**Steps to Reproduce**
- Start to type a word
- When `e` is pressed, it exits the inventory
- When `backspace` is pressed, it goes into the AE2 textbox instead of REI, without refocusing

**Environment**
 - Minecraft 1.17.1
 - Latest Fabric loader for 1.17.1
 
 Mirrored issue on AE2 github: AppliedEnergistics/Applied-Energistics-2#5658

**Comment by shedaniel** [comment]
It looks like it is resolved now?
