### ISSUE TITLE
[Bug] [1.18] (REI) Crash once open inventory

### ISSUE THREAD

**Issue by Mini-kun** [shedaniel/RoughlyEnoughItems#657]
**Describe the bug**
It happying every time i open the Inv.

**Steps to Reproduce**
- Boot the game
- Go to a SP or MP
- Open Inv. =Crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18-beta.1
 - Mod Loader: Fabric

**Logs**
Log = https://pastebin.com/kHGtEzUa
Crash Log = https://pastebin.com/CKdanfRn

**Additional context**
I don't really have more context as it just crashs

**Comment by shedaniel** [comment]
Versions of REI for 1.18 is available only on my Patreon for early access, public builds will have to wait until release candidates.
