### ISSUE TITLE
[Bug] GUI sizes are inconsistent

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#664]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/142987987-bd5b4b7b-4a30-4edb-9f11-0a7eda421f06.png)
![image](https://user-images.githubusercontent.com/15698722/142988013-c6eac2ee-407b-4174-b792-f316417b2f50.png)
The second is slightly shorter, and moving between them noticeably lowers top.

![image](https://user-images.githubusercontent.com/15698722/142988124-e76c2c98-c91b-4583-8bfd-98cc50da6c28.png)
![image](https://user-images.githubusercontent.com/15698722/142988129-5b89a081-f901-4bc7-94de-d7d97924fcec.png)
Water is wider, and both are wider than normal crafting recipes.

![image](https://user-images.githubusercontent.com/15698722/142988231-32455a25-ff5e-4af0-89e3-86c9ff6d73f3.png)
This page from JEED is tiny and cramped, and requires multiple pages to read rather than just being taller or wider.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Comment by shedaniel** [comment]
I believe the tabs moving is now fixed.
