### ISSUE TITLE
[Feature] Cannot select multiple specific items in Customized Filtering GUI

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#666]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/142988939-2451f755-4558-4222-96d5-4897ecbe09ea.png)
I want to hide all Bits, but I can't select them all.
![image](https://user-images.githubusercontent.com/15698722/142989023-e3c50eb9-f9a5-4de6-b842-f637feac74d5.png)
If I do Select All, that includes the Chisels themselves.
I have to Select All then Hide Selected, then click a Chisel, unhide it, click the second chisel, unhide *that*, and so on.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Comment by shedaniel** [comment]
You should be able to drag and select, like how you select multiple items on the desktop

**Comment by aaronhowser1** [comment]
Ah, I can. I tried to control-click and shift-click only.

**Comment by aaronhowser1** [comment]
I can't *deselect* only certain items while keeping others selected, however.

**Comment by shedaniel** [comment]
This should be implemented now.
