### ISSUE TITLE
[Bug] Recipe category order is inconsistent

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#668]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/142989733-ab22e102-e1b2-48a0-a7c9-bb78b83615b7.png)
As expected, the normal crafting table category for this item is first, and the Create one is second

However, for some reason, AE2 facades have that category at the end, defaulting to the Create one
![image](https://user-images.githubusercontent.com/15698722/142989751-fd47adc4-3943-41cb-9b8c-6e0bf30cb729.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Comment by shedaniel** [comment]
To update this issue, this issue only occurs for generated displays
