### ISSUE TITLE
[Bug] Incorrect items showing

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#673]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/142996380-e76fe9e5-7e4e-4c32-8b9d-39929ff28a54.png)
I searched "Basin" and almost none of these actually have basin in the name or tooltip
![image](https://user-images.githubusercontent.com/15698722/142996424-61a4cdec-883e-42db-b426-652fc9d5039e.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Comment by Snownee** [comment]
I think that is because the user disabled the "Append Mod Names" option and the item name is the same as the mod name. So the tooltip becomes empty then the item displays everywhere

**Comment by DaFuqs** [comment]
That sounds very much like it could be it.
I have that happen with "chalk:chalk" and have heard it happening to Dwarf Coal, too.

**Comment by lizfinite** [comment]
If I disable "append mod names" I just get no names if the mod has this issue; but they'll show up in all searches regardless of either setting. 
Only happening with a specific set of mods but I used chalk for testing.

Without "Append Mod Names":
![2022-01-12_01 51 39](https://user-images.githubusercontent.com/36245622/149086018-50e85996-354d-4f9c-b337-c9d68e3191ae.png)
![2022-01-12_01 51 40](https://user-images.githubusercontent.com/36245622/149086021-2eebcf55-d323-4169-ad0d-bbe5a2b6a3c5.png)
With "Append Mod Names":
![2022-01-12_01 52 06](https://user-images.githubusercontent.com/36245622/149086022-50d469a7-67d4-43f2-908c-754f29004de1.png)
![2022-01-12_01 52 07](https://user-images.githubusercontent.com/36245622/149086024-667e19e3-2c52-40ba-af4e-aec02e7ec608.png)
Searching "obsidian":
![2022-01-12_01 54 56](https://user-images.githubusercontent.com/36245622/149086355-cb2c3e56-5409-4c4a-b69a-5631c44e7f1d.png)
