### ISSUE TITLE
[Bug] Hovering over the + button highlights the wrong slots in some recipes

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#675]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15698722/143004328-73b50cac-3c4f-4a2e-863b-954162e0c0e0.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge

**Comment by shartte** [comment]
This happens on 1.18 Fabric too.

I.e. Book And Quill:
![grafik](https://user-images.githubusercontent.com/1261399/145814799-6305b6cd-ba96-4493-84e4-db2a8df69d30.png)

**Comment by itsdinkd** [comment]
Still happens. occurs on any recipe when using the add sign

**Comment by shedaniel** [comment]
This should be fixed now.
