### ISSUE TITLE
World crashes whenever I type "rail"

### ISSUE THREAD

**Issue by ReiNAce** [shedaniel/RoughlyEnoughItems#677]
**Describe the bug**
The world/game crashes whenever I searched for "rail". I am not sure if it is because of some mod incompatibilities or just REI malfunctioning. I haven't tried searching for other words yet though if REI also crashes. I only searched for "rail".

**Steps to Reproduce**
- click E
- typed in search bar "rai" from "rail"
- game crashes

**Environment (please complete the following information with the version):**
 - Minecraft 1.17.1
 - Fabric 0.12.5
 - REI 6.2.335

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7630766/latest.log)
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7630767/rei.log)

**Additional context**
Crash report
[crash-2021-12-01_12.07.43-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/7630758/crash-2021-12-01_12.07.43-client.txt)
:

**Comment by Flyvee** [comment]
The problem seems to come from the game trying to render the rail from the platform mod, try updating the platform mod first and also see if the same crash happens if you try to access that rail in creative mode inventory screen.

**Comment by shedaniel** [comment]
Unrelated to REI
