### ISSUE TITLE
[Bug] Game hard-crashes when accessing any inventory

### ISSUE THREAD

**Issue by Delfite** [shedaniel/RoughlyEnoughItems#678]
**Describe the bug**
As soon as I boot up my main world and open any inventory the game crashes. I don't have any mods that add their own items.

**Steps to Reproduce**
1. Create a new world
2. Open your inventory
3. Crash :|

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: fabric-loader-0.12.8-1.18

**Logs**
Crash log: https://pastebin.com/cyQfggR6
Latest.log: Can't upload because pastebin is offended by some lines of code you or someone else put in their mod(s).

Here's what the launcher shits out when I crash:
```
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void me.shedaniel.math.Rectangle.setBounds(double, double, double, double)'
Exit Code: -1
```

**Additional Context**
Apparently pastebin finds something about my latest.log file offensive. Did you do something with your mod that probably shouldn't be there because I'm 90% sure that pastebin tries to filter out what it thinks is "hate speech"...

**Comment by Delfite** [comment]
Quite suspicious that pastebin of all things finds something offensive about a log file lmao

**Comment by shedaniel** [comment]
Don’t worry, actually funny lmao, thanks for reporting

**Comment by oktkas** [comment]
Just had this crash on 1.18... Turns out the version curseforge automatically downloads is for 1.17.1 🙄.

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files

**Comment by shedaniel** [comment]
Please update Cloth Config.
