### ISSUE TITLE
[Bug] Crash when going to previous page

### ISSUE THREAD

**Issue by Goretantath** [shedaniel/RoughlyEnoughItems#681]
**Describe the bug**
Was trying to go to the previous page in rei and it crashed.
**Steps to Reproduce**
Click the left pointing arrow
Crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric 0.12.8

**Logs**
https://crashy.net/OlaHgNH9XGyUxl51ejof

**Additional context**

**Comment by shedaniel** [comment]
Perhaps report to Entity Banners
