### ISSUE TITLE
Game crashes when left clicking on any item in the REI menu

### ISSUE THREAD

**Issue by Pluettmann** [shedaniel/RoughlyEnoughItems#682]
**Describe the bug**
I tried to look up a recipe. So I opened my inventory with the REI menu on the right side and searched for the item. After that I left clicked on the item to show the recipe. Before the recipe window appeared the game crashed.

**Steps to Reproduce**
- Open the invetory
- (optional) search for any item
- click on an item to show the recipe
- see the game crash

**Environment (please complete the following information with the version):**
Minecraft: 1.17.1
Mod Loader: Fabric 0.12.8
Logs
https://crashy.net/hDN2fRqix9ats6kJBzRE

**Additional context**
When only using the inventory and clicking "r" to see how the item is crafted, everything is fine.

**Comment by shedaniel** [comment]
Your crash report link doesn't work

**Comment by Pluettmann** [comment]
For me it is working. I could upload the file as txt if you want

**Comment by shedaniel** [comment]
Please do

**Comment by Pluettmann** [comment]
[crash-2021-12-06_14.07.48-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/7660936/crash-2021-12-06_14.07.48-client.txt)

**Comment by shedaniel** [comment]
Issue with RER
