### ISSUE TITLE
[Feature] Add the option to move potion status effects to the left side instead of the right side.

### ISSUE THREAD

**Issue by PlazmaKG** [shedaniel/RoughlyEnoughItems#683]
**Describe the solution you'd like**
Add an option, to move the potion status effect timers, back to the left side of the inventory like they were in 1.17-
![image](https://user-images.githubusercontent.com/38696130/145133354-c6289473-3cf4-4409-baea-a85bea11c031.png)

**Additional context**
As we all know, Minecraft will show you what potion statuses you have in the inventory. Previously, the game showed you this information on the **left** side of the screen, which is fine, since it didn't really block anything in the context of REI/JEI, but in 1.18, they moved it to the right. Sure, it works to move the icons around it, but I don't like that, when potion status effects were previously on the left.

**Comment by milkev** [comment]
id like to second this one. It kinda feels like a petty move by mojang to promote their recipe book (we all know rei is superior), but it is actually a pain to have a large portion of rei taken up, especially when around max beacon settups and/or on large gui scales. It would be great if rei just moved them back over to the left, even as a config option or maybe another mod if its deemed to not be within the scope of rei.

**Comment by Shockks** [comment]
This would be a very important change. Others are making mods that move the potion status effects to the left side, but REI is still producing the gap:

![image](https://user-images.githubusercontent.com/9029288/149458834-a4d5ef16-a5cb-417e-a277-5faed8a909b7.png)

**Comment by CammiePone** [comment]
Technically needs to happen with REI, but I plan to make a mixin to fix it (assuming I even can)

Also just realised Github took me to the mentioned issue when I clicked view issue from my email. Very cool.

**Comment by shedaniel** [comment]
With the new REI update released, you can configure REI to move the potion effects to the left hand side now.
![image](https://user-images.githubusercontent.com/34910653/149552958-3ced0e68-be34-4bee-a290-c9211cd84eff.png)
