### ISSUE TITLE
[Bug] TR viewing certain recipes crash the game

### ISSUE THREAD

**Issue by Polarite** [shedaniel/RoughlyEnoughItems#685]
Describe the bug
When trying to view centrifuge of raw iron from rei, game crashes

Steps to Reproduce

Open game and load in a world
Try to view centifuge of iron to get nickel
Screenshots
I got crash logs... cant ss that

Environment (please complete the following information with the version):

Minecraft: 1.17
Mod Loader: Fabric 0.12.8
Logs
Pastebin the log [e.g. logs/latest.log] and link it below:
https://paste.ee/p/iNYWR
https://paste.ee/p/YH6OZ
Additional context
I play on a server if that matters but happens in singleplayer too

**Comment by shedaniel** [comment]
Sorry for being late, I don't check issues much, but your paste has expired. Please re-open the issue if you link a new paste.
