### ISSUE TITLE
[Bug] Regex searching not working for tooltips

### ISSUE THREAD

**Issue by Texbio** [shedaniel/RoughlyEnoughItems#686]
**Describe the bug**
Trying to see different enchants on items using #r/.\*Efficiency\sV.\*/ and other regex and cant see the highlighted items with those specific enchants. Regex is not working for tooltips.

**Steps to Reproduce**
open rei
make sure to put a # or enable searching with tooltips enabled
try searching for the item you want to search for using tooltips
cant find the item.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18
 - Mod Loader: Fabric 12.8
 - Rei 7.0.34

**Additional context**
Would be cool if this worked, tried /g but does not work, idk what to try to make it search tooltips

**Comment by Texbio** [comment]
bump

**Comment by shedaniel** [comment]
As intended, would be a big performance impact otherwise, searching by enchantment should be doable by default anyways.
