### ISSUE TITLE
[Bug] Crash when using search with Iris installed - "quads" is null

### ISSUE THREAD

**Issue by devvoid** [shedaniel/RoughlyEnoughItems#688]
**Describe the bug**
With Iris installed, trying to use the search bar causes a crash due to "quads" being null.

**Steps to Reproduce**
- Install Iris
- Attempt to use the searchbar.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: https://pastebin.com/u8Z09kBw

**Comment by shedaniel** [comment]
Report to them, not me
