### ISSUE TITLE
[Feature] Recipe pages are far too long, leaving recipes uncentered

### ISSUE THREAD

**Issue by mosharky** [shedaniel/RoughlyEnoughItems#689]
**Describe the bug**
The recipe page just feels unnecessarily long, despite only showing a single recipe. Other recipes pages have varying heights, even if they're only displaying one recipe.

**Screenshots**
This is what a candle recipe looks like
![image](https://user-images.githubusercontent.com/32606683/145705658-123f7828-1be4-48d2-bed9-61bf735a408d.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric

**Comment by shedaniel** [comment]
Intentional, it just looks weird if there's very short

**Comment by mosharky** [comment]
I assume there wont be an option to center the recipe then?
