### ISSUE TITLE
[Bug] rei doesn't show in the inventory 

### ISSUE THREAD

**Issue by robdcgYT** [shedaniel/RoughlyEnoughItems#692]
**Describe the bug**
So rei doesn't show the modmenu shows it but the inventory not ps normaly it works

**Steps to Reproduce**
- i dont know bc it happend itslef like

**Screenshots**
![16402620509571716375210377326885](https://user-images.githubusercontent.com/96578175/147239857-526ab7f9-e7a1-4ba7-a5c8-bb96539c94af.jpg)
![16402620945392313286096728526733](https://user-images.githubusercontent.com/96578175/147239917-b0baa472-fc83-43ea-a4d3-30cf345c2637.jpg)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: https://pastebin.com/bQ18cx2y

**Comment by robdcgYT** [comment]
I already updated all mods

**Comment by shedaniel** [comment]
We don't support hacked clients.
