### ISSUE TITLE
[Bug] Conflict with More Bundles

### ISSUE THREAD

**Issue by Quizer9O8** [shedaniel/RoughlyEnoughItems#695]
**Describe the bug**
The game crashes as soon as you try to find something in REI

**Steps to Reproduce**
- Create a new world
- Search something inside of the REI (possibly starting with the letter H)
- The game crashes in a few seconds

**Screenshots**
- N/A

**Environment**
 - Minecraft: [1.18.1]
 - Mod Loader: [Fabric 0.12.12]

**Logs**
https://crashy.net/SmQowHHi46CcweJYuJv1?raw

**Additional context**
See crash log and mods used: https://crashy.net/KrlnIdbxm0yHiI0zQxtr

**Comment by shedaniel** [comment]
Report to them
