### ISSUE TITLE
[Feature] proper inventory highlighting

### ISSUE THREAD

**Issue by superon** [shedaniel/RoughlyEnoughItems#697]
**Describe the solution you'd like**
the current implementation of "inventory highlighting" appears to "lowlight" all slots that don't contain the search term.
this is especially pointless when using a resource pack with a dark themed inventory.
could we have it reversed so the slots containing items with the search-term get highlighted instead?
also a good option would be a simple custom overlay option for these slots.

**Additional context**
https://imgur.com/a/GsrDyl1

**Comment by ghost** [comment]
@superon Roughly Searchable has a setting, "Darken Background" (accessible from the REI plugin settings), which dims items that don't match. It's not on by default though.
<img width="1591" alt="REI Settings" src="https://user-images.githubusercontent.com/15851438/151431998-a5d1ae18-7620-4866-96cd-d909d9ff5ca1.png">
<img width="601" alt="Darker Background" src="https://user-images.githubusercontent.com/15851438/151432017-1e5814bf-908b-41df-b771-d3664998243d.png">

**Comment by superon** [comment]
huh, well i did find that option but for whatever reason it didn't work like the pic you included for me:/  maybe it did something but was so slight i didn't notice.. i just assumed it was darkening the "background" (as in the slot behind the items, which obviously doesn't help with a dark inventory)..
i'd changed the scale of the items to be almost non existent and that was working reasonably well, will load up and grab images..
![Screen Shot 2022-01-28 at 14 33 25](https://user-images.githubusercontent.com/5957924/151565728-8817a955-5ebc-49b0-b169-42baf23bfc67.png)
![Screen Shot 2022-01-28 at 14 34 24](https://user-images.githubusercontent.com/5957924/151565767-c11ddd22-0200-4b65-85ec-ecd5f3dc151a.png)

**Comment by superon** [comment]
darkening the "background" sounds like default behaviour to me, perhaps that's just me of course ...  also tried this without a resource pack an experience the same thing (images don't darken).
so at this point i feel pretty certain there's another option i'm missing.

**Comment by shedaniel** [comment]
Can someone here link a resource pack that I can use for testing that is dark

**Comment by superon** [comment]
this is what i've been recently looking at:
https://www.curseforge.com/minecraft/texture-packs/conquest_

**Comment by shedaniel** [comment]
Thanks for your suggestions, it will now look like this in the next updates.

![image](https://user-images.githubusercontent.com/34910653/151653299-19ad7396-5588-4311-8bf6-a5db2a7b1cdc.png)

**Comment by superon** [comment]
that looks awesome, v much a fan of green too so that fits my theme :) looking forward to this update <3
