### ISSUE TITLE
click an item and game crash  19w02 snapshot

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#7]
fabric api [19w02a] Fabric API 0.1.4 build 71
fabric loader 19w02a
rei [Fabric 18w50a] v1.5.1c-20

click an item in REI and after a few seconds game auto saves and crashes

crash log https://pastebin.com/8q8qvMus

**Comment by Siphalor** [comment]
This is not strictly related to clicking; The crash also happens when using key bindings like `R` or `U`.

**Comment by ghost** [comment]
yeah I did notice that. but it took a few seconds to crash and I didnt realise if it was the click or the key presses that caused it.  I should have read the crash log better

**Comment by shedaniel** [comment]
Oh welp, it should be REI not supporting 19w02a
