### ISSUE TITLE
Crash w/o typing anything

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#70]
roughlyenoughitems: 2.7.10+build.96
Minecraft Version: 19w14b

There's a little "Z" behind .isFocused() which looks like a typo....
[crash-2019-04-19_11.40.33-client.txt](https://pastebin.com/mbECg9Bz)

**Comment by shedaniel** [comment]
It is not a typo

**Comment by shedaniel** [comment]
Downgrade REI to 19w14b version

**Comment by Knito58** [comment]
ok

**Comment by Knito58** [comment]
Sorry false positive. After upgrading fabric's mc version to latest it works.
Very, very sorry.

**Comment by shedaniel** [comment]
It's alright
