### ISSUE TITLE
REI Fabric 1.16.5 Crashes Whilst Initializing Game [Bug]

### ISSUE THREAD

**Issue by endersketch** [shedaniel/RoughlyEnoughItems#701]
I've been working on a 1.16.5 modpack that worked for a server we had a while ago. While trying to get back on the world the mods have stopped working. I cannot read crash reports well so I've been going through every mod to see what is causing the crash.
So far, RIE is the only one that I cannot get working, no matter what version I use. I've seen fixes with mod loader but Im hoping someone can help me figure out whats happening.

Game Crash Error Code:
`The game crashed whilst initializing game`
`Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed`
`Exit Code: -1`

**Environment:**
 - Minecraft 1.16.5
 - Mod Loader: Fabric 

**Logs**
`https://pastebin.com/6AQ02Dwp`

Any and all help would be appreciated. Let me know if I forgot any info that you might need.

**Comment by shedaniel** [comment]
Currently an underlying issue with fabric loader, we are trying to work out what is wrong

**Comment by shedaniel** [comment]
Tracking FabricMC/Mixin#80
