### ISSUE TITLE
Tooltip crash [Bug]

### ISSUE THREAD

**Issue by cupcie** [shedaniel/RoughlyEnoughItems#705]
Crash happens when I search in the gui for some recipes for other mods.

Steps to Reproduce
- Open gui
- Search for some modded armor, weapons and drag the cursor on it

 - Minecraft: Fabric 1.17.1
 - Modpack: Origins smp with added mods 

https://gist.githubusercontent.com/natanfudge/113ece4c34beb77912a6b8871c527fec/raw/f1963b5f236ff0e4d88fd0ec56548742608cdbb5/crash.txt

Edit: Can confirm its crashing when I try to check the vanilla item recipes such as Iron sword, Netherite Chestplate etc...

**Comment by shedaniel** [comment]
Can you attempt to update AppleSkin?

**Comment by shedaniel** [comment]
Please reopen the issue if you answer, my guess is that this should be caused by AppleSkin.
