### ISSUE TITLE
REI won't let my server load

### ISSUE THREAD

**Issue by kxazd** [shedaniel/RoughlyEnoughItems#706]
When booting my server for Minecraft if I run REI and Just enough resources with Chisels and Bits it gets stuck loading the JEI plugin 7 out of 10 times

**Steps to Reproduce**
- Have JER, REI, and chisels and bits on a server
- Boot it up
**Screenshots**

![image](https://user-images.githubusercontent.com/61312045/147964015-64643284-a415-45a7-9b7b-621a09512467.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Forge 39.0.9

**Logs**
No logs, it doesn't crash it just gets stuck on it forever.

**Comment by shedaniel** [comment]
hmm, interesting issue

**Comment by itsdinkd** [comment]
happened to me as well, fixed when deleting chisel and bits.

**Comment by shedaniel** [comment]
Failed to reproduce the issue
