### ISSUE TITLE
[Bug Forge] REI displaying in waystones

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#707]
Open a waystone in 1.18.1 and you will be shown the search bar, and items on the top left that are cycable 

![image](https://user-images.githubusercontent.com/35115304/148322364-92c9159b-f813-442f-ad48-a6d871757c10.png)

**Comment by shedaniel** [comment]
Should be fixed in https://github.com/shedaniel/RoughlyEnoughItems/commit/6524d9a4aa1fb83e097f4754f1d82b7044cef5cb
