### ISSUE TITLE
REI Crash when browsing items- Incompatibility with multibeds?

### ISSUE THREAD

**Issue by CrusaderRabbit** [shedaniel/RoughlyEnoughItems#708]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/7/22, 12:14 PM
Description: Rendering entry

java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "quads" is null
	at net.minecraft.class_918.method_23182(class_918.java:1548)
	at net.minecraft.class_918.method_23179(class_918.java:170)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:255)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:196)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:283)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:125)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:290)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:608)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:506)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:341)
	at net.minecraft.class_757.handler$zik000$renderScreenPost(class_757.java:10552)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_918.method_23182(class_918.java:1548)
	at net.minecraft.class_918.method_23179(class_918.java:170)

-- Screen details --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:198)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:283)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:125)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:290)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:608)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:506)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:341)
	at net.minecraft.class_757.handler$zik000$renderScreenPost(class_757.java:10552)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: multibeds:cot

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: cot
	Item Damage: 0
	Item NBT: {BlockEntityTag:{texture_item:{Count:1b,id:"minecraft:oak_planks"}}}
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.class_481

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.EntryListEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@6698570f[height=18,width=18,x=929,y=64]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: multibeds:cot

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: cot
	Item Damage: 0
	Item NBT: {BlockEntityTag:{texture_item:{Count:1b,id:"minecraft:oak_planks"}}}
	Item Foil: false

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (804, 448). Absolute: (1608.000000, 896.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Tech_Rabbit'/211, l='ClientWorld minecraft:overworld', x=6960.23, y=64.00, z=603.71]]
	Chunk stats: Client Chunks (ImmPtl) 729
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,78,0), Section: (at 0,14,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 103917 game time, 4539 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, moreberries/modifiedsweetberrybushmodel

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1423109632 bytes (1357 MiB) / 6056574976 bytes (5776 MiB) up to 8187281408 bytes (7808 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 67515.11
	Virtual memory used (MB): 33846.71
	Swap memory total (MB): 34816.00
	Swap memory used (MB): 534.72
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7808m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
		alaskanativecraft: Alaska Native Craft 1.4.1
		apoli: Apoli 2.2.2
		appleskin: AppleSkin mc1.18-2.2.0
		arcanus: Arcanus 1.25
		architectury: Architectury 3.4.9
		awesomedungeon: Awesome Dungeon 2.0.2
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.1
		bclib: BCLib 1.2.2
		betterend: Better End 1.0.0
		betternether: Better Nether 6.0.8
		bettersleeping: BetterSleeping 0.5.1+1.18
		bewitchment: Bewitchment 1.18-4
		bitsandchisels: BitsAndChisels 2.6.4
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.4
		botania: Botania 1.18.1-427-FABRIC
		bottledair-fabric: Bottled Air (Fabric) 1.0
		calio: Calio 1.4.2
		camsbackpacks: Cammie's Wearable Backpacks 2.7
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chat_plus: Chat+ 2.1.6
		chisel: Chisel Refabricated 1.4.4
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.4
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_typesafe_config: config 1.4.1
		comforts: Comforts 1.0.0-1.18
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		controlling: Controlling For Fabric 9.0.8
		copperarmorandtools: Copper Armor & Tools 1.9.2
		craftablechainmail: Craftable Chainmail Armor 1.18.1-1.5.0-[FABRIC]
		creeperoverhaul: Creeper Overhaul 0.2.1
		croptopia: Croptopia 1.8.0
		customfence_fabric: Customfence 1-18-1
		darkness: True Darkness 2.0.89
		darkwaters: Dark Waters 0.0.9
		decorative_blocks: Decorative Blocks 2.0.2
		dehydration: Dehydration 1.2.7
		difficultyplus: Difficulty Plus 1.0.1
		drinkbeer: Drink Beer 3.0.2
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		editsign: EditSign 2.2.7
		entityculling: EntityCulling-Fabric 1.3.3
		expert_armor: Expert_Armor 1
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9514
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9514
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9514
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a14
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		fiber: fiber 0.23.0-2
		firstjoinmessage-fabric: First Join Message (Fabric) 1.3
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.4
		forgeconfigapiport: Forge Config API Port 3.1.0
		ftbchunks: FTB Chunks 1801.3.3-build.100
		ftblibrary: FTB Library 1801.3.5-build.106
		ftbteams: FTB Teams 1801.2.4-build.46
		geckolib3: Geckolib 3.0.23
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.4.1
		graveyard: The Graveyard 1.1
		guild: Guild 0.3.7
		harvest_scythes: Harvest Scythes 2.4.0
		huskspawn-fabric: Husk Spawn (Fabric) 1.4
		imm_ptl_core: Immersive Portals Core 1.1.8
		immersive_portals: Immersive Portals 1.1.8
		impersonate: Impersonate 2.4.0
		incantationem: Incantationem 1.1.3+1.18.1
		inventorysorter: Inventory Sorter 1.8.4-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.2
		magiccombatwands: Magic Combat Wands 1.0.1
		magicfungi: Magic Fungi 0.6.2-BETA+1.18.1
		marketcrates: Marketcrates 1.4.1
		medievalorigins: Medieval Origins 3.1.0
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		moreberries: More Berries 1.4.5
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.20
		multibeds: MultiBeds 1.2.0
		myron: Myron 1.6.1-1.17.1
		mythic-mounts: Mythic Mounts 1.18-4.0
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notenoughbreeding: Not Enough Breeding 1.18.1-1.0.0-fabric
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.1
		origins-classes: Origins: Classes 1.2.4
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		patchouli: Patchouli 1.18.1-64-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.5.0
		puzzleslib: Puzzles Lib 3.1.3
		q_misc_util: QMiscUtil 1.1.8
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.1.357
		rpgstats: RPGStats 4.3.2+1.18.1
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		shetiphiancore: ShetiPhianCore 1.2.0
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		sodium: Sodium 0.4.0-alpha5+build.9
		stacc: Stacc 1.2.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.1
		strayspawn-fabric: Stray Spawn (Fabric) 1.5
		taverns: Taverns 1.0.2
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		thonkutil: ThonkUtil 1.3
		tinyskeletons: Tiny Skeletons 3.1.0
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		transportables: Transportables 1.1
		trinkets: Trinkets 3.1.0
		valley: ValleyCraft 2.1
		veinmining: Vein Mining 0.0.11-1.18
		waig: Where Am I Going 1.0.2
		waystones: Waystones 2.4.1
		wthit: wthit 4.4.1
		yigd: You're in Grave Danger 1.2.11
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Tech_Rabbit'/211, l='ServerWorld minecraft:overworld New World', x=6960.23, y=64.00, z=603.71]]
	Data Packs: vanilla, Fabric Mods

**Comment by shedaniel** [comment]
Yep, and you should report to them instead since we don't do anything special to render it, we just do the normal way, so if it crashes, it is their fault
