### ISSUE TITLE
Do you not support 1.18 Forge? 

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#709]
I've opened up several tickets now on REI crashing but have had no response / fix released. If its not supported that is fine, I'll switch to JEI. But if it is supported, i'd appreciate it if you can at least acknowledge that these issues exist as I am using your mod in my modpack and people keep reporting the same issue to me, and I have nothing I can say about it to them.

**Comment by shedaniel** [comment]
Sorry, I am currently going through finals atm so I am only putting some time on modding

**Comment by itsdinkd** [comment]
Ah. Makes sense! Good luck!
