### ISSUE TITLE
Filling the crafting area with items only works with vanilla recipes

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#71]
roughlyenoughitems: 2.7.10+build.96
Minecraft Version:1.14 Pre-Release 5

I tested a long time until I was sure what was the issue. Sometimes the plus sign won't fill the grid and sometimes it will. The difference is: It works perfectly with vanilla recipes. A non - vanilla recipe like for example the "shearer" from the "@wool" mod will not be filled in. But: The recipes for the needed iron bars and the dropper will work as expected. Only the non-vanilla shearer will not be filled in when the plus button is clicked. Even when all the ingredients are in the player's inventory. The shearer is not the only recipe where this happens. It is an issue to all non-vanilla recipes.

**Comment by Knito58** [comment]
Maybe that is an issue due to when and how mods are declared to the game. Is it possible to tell REI to get loaded as the very last mod?

**Comment by shedaniel** [comment]
Recipes are loaded when you load a world so I don’t think it is an issue related to ordering

**Comment by shedaniel** [comment]
Related with #24

**Comment by Knito58** [comment]
RoughlyEnoughItems V2.0.1+build.102
MC 1.14
Sorry not fixed. It does still not fill the items for block "tree cutter" of mod "wool" into the crafting area for me. Dropper and iron bars (needed items) do work instead. I have all the required items in the inventory. 

I have an error in latest.log concerning a parsing error for recipe "trapexpansion:slippery_stone" not finding "minecraft:ice". But after that it happily continues execution and REI writes 

```
[Server thread/INFO]: Saving chunks for level 'NewHope'/minecraft:overworld
[18:50:23] [main/INFO]: [REI] Registered 1320 recipes, 7 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Brewing) in 340 ms.
```
to the latest.log.

The "slippery stone" is shown in REI but clicking on it just does not do anything. minecraft:ice seems to be a valid block that can not be crafted and which is needed in the vanilla recipe for "packed ice". 

But disabling the "trap expansion mod" did not help and REI still not fills the "tree cutter" from "wool".

**Comment by shedaniel** [comment]
REI doesn’t detect bad recipes, it only loads good recipes. This issue is a duplicate of #24
