### ISSUE TITLE
[Bug] Huge Performance Drop

### ISSUE THREAD

**Issue by Julienraptor01** [shedaniel/RoughlyEnoughItems#712]
**Describe the bug**
When the mod is installed the inventory has less fps even when the menu is disabled, and it gets worse in some situations like if you have many echanted items displayed.

**Steps to Reproduce**
Put yourself somewhere and let your fps stabilize and remember it.
Then open your inventory and disable REI.
Then activate REI.
And finally search for "potion".

**Screenshots**
The first 4 are with my optimized good looking modpack and the last 4 are with just sodium and sodium-extra installed so i could have the fps counter.

![First 2022-01-11_22 18 50](https://user-images.githubusercontent.com/49841713/149025106-381e11a8-d674-45f3-9551-a0f5fe455c36.png)
Out of inventory

![Second 2022-01-11_22 19 27](https://user-images.githubusercontent.com/49841713/149025129-8cb8c22b-a134-41e0-bc46-a0884f75d24e.png)
In inventory with REI disabled

![Third 2022-01-11_22 19 48](https://user-images.githubusercontent.com/49841713/149025444-da73e2a2-459e-4454-94f0-747f338231f3.png)
In inventory with REI enabled

![Fourth 2022-01-11_22 20 29](https://user-images.githubusercontent.com/49841713/149025581-c7833bcb-5b45-4aa4-81c4-35845a38ee9b.png)
In inventory with REI enabled and "potion" search

![Fifth 2022-01-11_22 24 33](https://user-images.githubusercontent.com/49841713/149025678-c5d0eded-02b8-4186-9fc4-1bab0b74c9ee.png)
Out of inventory

![Sixth 2022-01-11_22 25 24](https://user-images.githubusercontent.com/49841713/149025708-f06154c6-080c-467f-99dc-a1022ae816a1.png)
In inventory with REI disabled

![Seventh 2022-01-11_22 25 44](https://user-images.githubusercontent.com/49841713/149025735-7c3ef717-cc70-4b40-8763-d2dbf2634774.png)
In inventory with REI enabled

![Eigth 2022-01-11_22 26 06](https://user-images.githubusercontent.com/49841713/149025756-2b8449ae-8995-4a8f-b0f8-b4b2a0c7f88c.png)
In inventory with REI enabled and "potion" search

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric 0.12.12

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below: The first one is for the first 4 screenshots and the second one for the last 4 screenshots.
https://gist.github.com/Julienraptor01/81a25bc7553d7c80f22b614b7bdaf374
https://gist.github.com/Julienraptor01/42c110d942b25ba8f60fe0ed5aa55f63

**Additional context**

**Comment by shedaniel** [comment]
That's expected, rendering items is an expensive task due to how the game implements it, REI already optimises this a slight bit by 33%, but further optimisation is not worth the hackery in REI, for further optimisations use sodium.
