### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by EclipseBear7** [shedaniel/RoughlyEnoughItems#714]
"REI not yet fully initialized!"

how do i fix this?

plesae help
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7874253/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7874254/latest.log)
both my latest log and rei log

**Comment by shedaniel** [comment]
Report to cammiescorner.arcanus
