### ISSUE TITLE
[Bug] Multiplayer server recipe screen does not open

### ISSUE THREAD

**Issue by silentnyte** [shedaniel/RoughlyEnoughItems#716]
When playing a multiplayer server the recipe screen does not open. If we disconnect and start a single player world and open a REI recipe and then return to multiplayer the recipe screen starts working. This happens every time we first launch minecraft.

**Steps to Reproduce**
- Launch mc
- Connect to multiplayer server
- Try and open REI recipe
- Disconnect
- Load single player world
- Open REI recipe
- Close and save
- Reconnect to multiplayer world
- Open REI recipe

Another issue is that the "REI not yet fully initialized!" message never goes away.
https://i.imgur.com/MPl9lQM.png

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: 0.12.12
 - REI: 6.3.358

**Logs**
 - Minecraft server: https://pastebin.com/ygEAtDjV
 - Minecraft client: https://pastebin.com/4F4nj2MQ
 - REI server: https://pastebin.com/5ZL095SU
 - REI client connect to server: https://pastebin.com/TrGV6dF1
 - REI client single player: https://pastebin.com/BdYp9wQk & https://pastebin.com/0YVXFtDZ

**Comment by shedaniel** [comment]
This issue is caused by NBTCrafting, please report to them.
