### ISSUE TITLE
Effects not showing in inventory

### ISSUE THREAD

**Issue by muluffel** [shedaniel/RoughlyEnoughItems#717]
**Describe the bug**
In the inventory, there is the space for the potion/beacon effects but the effects are not showing

**Steps to Reproduce**
- Just have some Beacon or potion effects.

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/65601356/149663251-cf169a83-554c-487d-a833-5d535696a23c.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.0
 - Mod Loader: fabric

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/NFFPG3uh

**Comment by shedaniel** [comment]
We don't support hacked clients and optifine.

**Comment by muluffel** [comment]
without both it doesnt work either
