### ISSUE TITLE
[Bug] [Fabric 1.17.1] Cloth Config version is always out of date.

### ISSUE THREAD

**Issue by RamblesOnn** [shedaniel/RoughlyEnoughItems#721]
**Describe the bug**
When attempting to load the game with REI v6.3.382, v6.3.379, and v6.389 with Cloth Config v5.2.47, an error stating that the Cloth Config version is too old will appear. However there is no newer version of Cloth Config than v5.2.47 for 1.17.

**Steps to Reproduce**
- Install REI v6.3.382, v6.3.379, or v6.389 with its dependencies, including the latest version of Cloth Config on Fabric 0.12.12-1.17.1
- Attempt to load Minecraft

**Screenshots**
![2022-01-17_11 35 29](https://user-images.githubusercontent.com/86580774/149819400-bda9dab8-6070-4250-afa6-c9a0f4f680b8.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.17.1
 - Mod Loader: Fabric 0.12.12

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://pastebin.com/KajLMHBE

**Additional context**
I am attempting to load this with other mods, and have not attempted to load without those other mods, but I anticipate that this issue will persist regardless. If more context or information is necessary, then I will be happy to provide.

**Comment by shedaniel** [comment]
shulkerboxtooltip is force loading an older version of cloth config
