### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RyansConfused** [shedaniel/RoughlyEnoughItems#727]
**Describe the bug**
After launching Forge from the Minecraft Launcher, this error loading mods screen appeared.

**Steps to Reproduce**
- Open Minecraft Launcher
- Load into Forge: 1.18.1-forge-39.0.19

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/98085144/150308589-b3e84458-3005-49c9-83d3-484761b5508a.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Forge 39.0.19

**Logs**

https://pastebin.com/82ZWJ7tS

**Additional context**
N/A

**Comment by shedaniel** [comment]
You need to install Architectury and Cloth Config.

**Comment by RyansConfused** [comment]
> 

Sorry I’m a bit new too modding, do you know where I can find them?
