### ISSUE TITLE
Crash after opening integrated dynamics book

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#728]
**Describe the bug**
Title

**Steps to Reproduce**
Open on the dynamics of integration from id

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: forge

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
https://gist.github.com/freopt/e5697dea85b51a46ae8dbb4ea5d9d266

**Comment by shedaniel** [comment]
Your log does not include the crash, please re-open the issue when you upload a new log.

**Comment by freopt** [comment]
my bad heres the crash https://gist.github.com/freopt/5ebf78697a5c787264cf8416a130a896
