### ISSUE TITLE
[Bug] Starting a modpack with REI installed the first time results in a crash

### ISSUE THREAD

**Issue by MarkNoName** [shedaniel/RoughlyEnoughItems#729]
Working on a custom made modpack with REI included build for CurseForge. When ever I try to start the freshly installed/imported profile that worked before, it crashes and gives out a error message that says "Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!", but only on the **first attempt** of starting the modpack. Starting the modpack a second time works just fine?

**Steps to reproduce the behavior:**
Honestly: No clue, I am guessing some mod/s in the pack is/are conflicting because I tested it out with just REI itself and the dependencies installed. Also there are no override files on my attempts on trying to fix the problem in the curse forge profile.

**Environment:**
 - Minecraft: 1.18.1
 - Mod Loader: fabric 0.12.12
 - RoughlyEnoughItems-7.1.390

**Logs:**
https://pastebin.com/7Gv1tDNm

**Crash Report (first start attempt):**
https://pastebin.com/aTGtp8PR

**Comment by shedaniel** [comment]
I am not sure that this is an issue of mine, it is somehow not able to find some classes in the mod.

**Comment by MarkNoName** [comment]
Yeah I had this issue in other Modpacks too when REI is installed. Booting it up a second time works just fine.

Just to clarify:
I got a friend of mine to test out the same things i've tested, no issues or crashes on his sides?

Has to be an issue on my side.
