### ISSUE TITLE
[Bug]1.18.1 Bugs related to Recipe Exporting

### ISSUE THREAD

**Issue by sorat0mo** [shedaniel/RoughlyEnoughItems#731]
**Describe the bug**
1. Exporting does not work for Composite Mode, only Classic mode
2. Exported recipe has no background

**Steps to Reproduce**
1. Install the mod
2. Choose Composite mode for recipe
3. Try to export recipes

and

1. Install the mod
2. Choose Classic mode for recipe
3. Try exporting recipes
4. Check exported results

**Screenshots**
![2022-01-21_20 22 28](https://user-images.githubusercontent.com/11853019/150527809-be00aef5-0fab-4449-b164-47cf6d6bd0bd.png)

This is the recipe export output png.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: fabric
 - Launcher: MultiMC version 0.6.14-2998

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:

latest.log:
https://paste.ee/p/IAGzA

rei.log:
https://paste.ee/p/Abitb

**Additional context**

**Comment by ghost** [comment]
Subscribed, looking forward for the updates. Happens to me as well on latest REI and Fabric API on 1.18.1

UPD Feb 3rd: Still happens on latest REI. Tried installing Cloth API and Cloth Config API, both released a day or two ago, still no luck.

**Comment by KuCZik** [comment]
Can confirm the same behavior on my modpack

**Comment by alex3236** [comment]
Confirmed on 1.18.2

**Comment by shedaniel** [comment]
Will be fixed very soon, working on an update to improve this
