### ISSUE TITLE
[Bug] Crash wnen try to display rei gui

### ISSUE THREAD

**Issue by NiTiSon** [shedaniel/RoughlyEnoughItems#732]
**Describe the bug**
Crash when try to display rei gui

**Steps to Reproduce**
Open any block (chest | crafting table)
or
Open inventory

**Logs**
[Crashlog](https://pastebin.com/xzapXbWG)

**Comment by shedaniel** [comment]
Somehow your game has an outdated Cloth Basic Math, try removing mods until it works.
