### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#733]
**Description:**
Crash on startup after updating to the latest version;

_RoughlyEnoughItems-5.12.385.jar_

**Environment:**
 - Minecraft: 1.16.5
 - Launcher: 0.12.12
 - Fabric Api: 0.42.0
 
 - Architectury-1.26.42
 - Cloth-config-4.11.26

**Logs:**
1. https://pastebin.com/955WKAhx
2. https://pastebin.com/QGEYqDt9

**Extras**:
**same problem on 1.18.1**,
If you need more information just tell me what to send to you,

thanks.

**Comment by shedaniel** [comment]
LVT issues by Architectury.
