### ISSUE TITLE
Performance issue with using REI (Fabric, MC 1.18.1)

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [shedaniel/RoughlyEnoughItems#734]
**Describe the bug**
Massive performance hit when using REI, turns game into a slow slideshow

**Steps to Reproduce**
- Start Game
- Create world
- Lots of lag making game unplayable
- Forced to kill process

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric (Loader: 012.12 and API: 0.46.2+11.8)

**Logs**
Latest: https://pastebin.com/v6ZWDJnY
REI log: https://pastebin.com/uPvjttqG

**Additional context**

**Comment by shedaniel** [comment]
You don't seem to have enough memory allocated

**Comment by DJTobi1Kenobi** [comment]
Hi Shedaniel, thank you very much for your fast response and you'er awesome Mod.

Does REI greatly increase RAM usage? The game runs fine when playing without REI at 4gb allocated. 

Here it is after increasing the max allocation to 16gb, still the same issue, view distance set to 6
Latest log: https://pastebin.com/Yh4HxiLa

**Comment by shedaniel** [comment]
Ah, this looks like a conflict between Enchantment Descriptions and  Limitless, as Enchantment Descriptions tries to register a new recipe with REI for every enchantment level, limitless unlimits the range of that, making it register millions of recipes to rei

you can look at this issue https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues/91

**Comment by DJTobi1Kenobi** [comment]
Omg thank you so much.
