### ISSUE TITLE
agricraft issue?

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#735]
**Describe the bug**
I opened the world, tried to search "water" and then crash
**Steps to Reproduce**
above

**Environment (please complete the following information with the version):**
 - Minecraft:1.16.5
 - Mod Loader: forge

**Logs**
https://gist.github.com/freopt/69a1139d2a834f11623af09cb39bbb71

**Comment by freopt** [comment]
another crash: https://gist.github.com/freopt/e9e905ff87691d5f280c3cc4eeddf2bf

**Comment by shedaniel** [comment]
Personally thinking that this could be an issue by Agricraft itself, but I am not sure, I need to check.

**Comment by shedaniel** [comment]
Likely agricraft issue
