### ISSUE TITLE
[Bug] Crash at startup with REI and Optifabric / Optifine 1.16.5

### ISSUE THREAD

**Issue by Emedo80** [shedaniel/RoughlyEnoughItems#736]
Crash at startup with REI and Optifabric / Optifine 1.16.5

- Create a new profile with fabric in CurseForge
- Add REI
- Add Architectury (not downloaded automaticaly)
- Add Optifabric
- Download lastest optifine for 1.16

**Screenshots**
![image](https://user-images.githubusercontent.com/45518634/151060496-381ce14f-b42a-4df5-8819-f9b89493ef05.png)

![image](https://user-images.githubusercontent.com/45518634/151061360-ae7488d0-6142-4e94-bc56-95181580d6f8.png)

![image](https://user-images.githubusercontent.com/45518634/151060569-3b34cddf-16bb-44ac-bb53-3ba58f45d8cc.png)

**Environment:**
 - Minecraft: 1.16.5
 - Mod Loader: fabric0.12.12
 - RoughlyEnoughItems-5.12.385
 - architectury-1.28.48
 - optifabric-1.12.10
 - OptiFine_1.16.5_HD_U_G8
 - cloth-config-4.13.49-fabric

**Logs**
Pastebin: https://pastebin.com/uNAPVYpu

**Comment by shedaniel** [comment]
Please report to OptiFabric, I do not support it, they should support us.
