### ISSUE TITLE
3 way mod conflict between inspecio, guard villagers (fabric) and this mod  [Bug]

### ISSUE THREAD

**Issue by BossCreeper81** [shedaniel/RoughlyEnoughItems#740]
Game crashes when searching anything, while REI, Guard villagers and Inspecio are installed.

1. Install REI, Inspecio and Guard villagers (fabric)
2. Start the game
3. *Crash*

Disabling the search tooltip feature "fixes" the bug

1.18.1
fabric

logs:
https://pastebin.com/xcPZP2si  //only the 3 mods and their dependencies installed
https://crashy.net/43KxFDcVH6NL5g7QqqM2 // crashy with my full setup

Removing either inspecio or guard villagers also fixes the bug

**Comment by shedaniel** [comment]
This shouldn't be caused by REI

**Comment by BossCreeper81** [comment]
Thanks for the fast reply!
