### ISSUE TITLE
natures aura plugin incompatability

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#742]
**Describe the bug**
crash 

**Steps to Reproduce**
look up certain natures aura recipes
crash

**Screenshots**

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: forge

**Logs**
https://gist.github.com/freopt/9742de4151ed7863b1c44afb19312038

**Comment by shedaniel** [comment]
Can you try update REI

**Comment by freopt** [comment]
ye i tested it and still happens https://gist.github.com/freopt/0f24774cb937fc3db4bb5fad8350f1de

**Comment by shedaniel** [comment]
Thanks for confirming
