### ISSUE TITLE
[Bug] failure to launch with modpack (no crashlog)

### ISSUE THREAD

**Issue by superon** [shedaniel/RoughlyEnoughItems#743]
**Describe the bug**
when roughlySearchable is installed with fabric modloader 0.12.3+ in this pack it'll fail to launch
if i downgrade to 0.11.7 it seems fine.
https://pastebin.com/UceDcZht
just letting you know incase you really want to solve this one bc i've been at it for long enough now, running in circles asking people who i should post this to

**Comment by shedaniel** [comment]
It’s  their issue
