### ISSUE TITLE
[Bug] plugin incompatability

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#745]
**Steps to Reproduce**
Load game with those 2 mods and look in log

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14] 1.18.1
 - Mod Loader: [e.g. forge, fabric] forge

**Logs**
[Pastebin the log [e.g. `logs/latest.log`] and link it below:

**Additional context**
Add any other context about the problem here.](https://pste.ch/doxosomifo.sql)

**Comment by Raidobw2** [comment]
Same thing as Sunekaer as well, with Tinkers and CobbleGenRandomizer this time (+Cyclic that he got).
https://paste.feed-the-beast.com/view/7e5dae46
`Minecraft 1.18.1`, `Forge 39.0.64` & `RoughlyEnoughItems-jei-internals-workaround-7.2.418.jar`

**Comment by Raidobw2** [comment]
Works like a charm, thank you very much 😄 
![image](https://user-images.githubusercontent.com/17010632/152644617-4dcffedf-e844-469b-ae82-addc83fc5fea.png)
