### ISSUE TITLE
"O" toggles REI while typing in inventories

### ISSUE THREAD

**Issue by Madis0** [shedaniel/RoughlyEnoughItems#75]
The REI panel keeps toggling while typing "o" in the creative search field or anvil name tag field.

- REI 2.7.11 build 97
- Fabric Loader 0.4.2 build 132
- Minecraft 1.14

**Comment by shedaniel** [comment]
Related to #58, I guess this bug is not solved properly.

**Comment by shedaniel** [comment]
Related to #58, I guess this bug is not solved properly.
