### ISSUE TITLE
[Feature](?) Delay plugin init until after mod init is complete

### ISSUE THREAD

**Issue by TropheusJ** [shedaniel/RoughlyEnoughItems#752]
**Describe the solution you'd like**
Create relies on configs to define some available recipes. On Fabric, we rely on a library for this. However, configs are not loaded until after the config library loads. If REI loads before this, the Create REI plugin will crash due to configs not being present. 

Alternatively, allowing mods to opt-in to delayed init could be an option, if changing the current init time has too much breaking potential.

**Comment by shedaniel** [comment]
Why would you be doing much on constructor init? shouldn't you only do stuff on the methods called?

**Comment by TropheusJ** [comment]
@AlphaMode is the one who set up our REI compat and would be able to answer better

**Comment by shedaniel** [comment]
Please do a follow-up, I am going to mark this as stale for now. You can also contact me on discord if that's the preferred way. (I'm on my own discord / create discord)
