### ISSUE TITLE
[Bug] Middle-click to get recipe doesn't work on machines from Integrated Dynamics

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#753]
**Describe the bug**
Middle-click to get recipe doesn't work on machines from Integrated Dynamics

**Environment (please complete the following information with the version):**
 - Minecraft: [e.g. 1.14] 1.18.1
 - Mod Loader: [e.g. forge, fabric] forge

**Comment by shedaniel** [comment]
Are you sure this is only on REI? I think they might also not show on REI. (If you mean the recipe id that is)

**Comment by Sunekaer** [comment]
Just checked JEI Doesnt show recipe id either

**Comment by shedaniel** [comment]
yeah shouldn't be my issue, JEI only checks if the registered object is a Recipe, then gets the id.
