### ISSUE TITLE
Crashes on startup[Bug]

### ISSUE THREAD

**Issue by Kratos-Lee520** [shedaniel/RoughlyEnoughItems#754]
**Describe the bug**
The game crashes upon startup from REI versions after 7.2.409  to version 7.2.422, with no crashlog or anything. 7.2.409 works, so something after breaks another mod maybe? I did test every Fabric version after 409 up to 422. 

**Steps to Reproduce**
- First Step- Use the mods I have (https://drive.google.com/file/d/1iI9qSWeTBla0OzRlGy-32CiNXqpDgNJT/view?usp=sharing). 
- Second Step- Use one of the versions specified above, and launch MC. 

**Screenshots**
N/A

**Environment (please complete the following information with the version):**
 - Minecraft: 1.18.1
 - Mod Loader: Fabric 0.12.12

**Logs**
Pastebin the log [e.g. `logs/latest.log`] and link it below:
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/7982170/latest.log)

**Additional context**
Crash report
[crash-2022-02-05_10.31.56-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8008383/crash-2022-02-05_10.31.56-client.txt)

**Comment by shedaniel** [comment]
Your logs doesn't include a crash

**Comment by Kratos-Lee520** [comment]
It wouldn't crash with a crashlog to my knowledge, usually it crashes and it would say on the launcher, "close" & "crash report" or something like that, and anytime it crashed with REI in it, there was no crash report button. Would a log still be created and put into the crash folder?

**Comment by Kratos-Lee520** [comment]
I got a crash report from the new REI version 422. I added it to the first post.

**Comment by LilyRose2798** [comment]
You're using Slight GUI Modifications v2.0.2 which had a [known issue with REI](https://github.com/shedaniel/slight-gui-modifications/issues/56). Update your version of Slight GUI Modifications to v2.0.3 to fix the issue.

**Comment by Kratos-Lee520** [comment]
okay thank you!
