### ISSUE TITLE
[Bug] Brewing recipes from crafttweaker not showing up in brewing tab

### ISSUE THREAD

**Issue by sauphle** [shedaniel/RoughlyEnoughItems#755]
**Describe the bug**

I added the example "brewing.addRecipe(<item:minecraft:dirt>, <item:minecraft:apple>, <item:minecraft:arrow>);" to my scripts and when trying to look at the recipe in REI it doesn't show up, even after scanning through all the brewing recipes. The recipe still exists, but it doesn't show up.

**Steps to Reproduce**
- download "_crafttweaker_" and "_REI_". You will also need _jeitweaker_, _rei compatibility workaround_, _cloth config_, and architectury, but these should automatically be added if you're downloading from the app.
- using visual studio code or some coding software create a file with name.zs ("name" can be anything)
- paste "brewing.addRecipe(<item:minecraft:dirt>, <item:minecraft:apple>, <item:minecraft:arrow>);" into the file ignoring the quotes
- save 
- in game enter /reload
- Look at the recipes for dirt and look to see if a brewing recipe doesn't show up 

**Environment**
 - Minecraft: 1.16.5
 - Mod Loader: forge 36.2.23

**Comment by jaredlll08** [comment]
Just to save some time, we add brewing recipes to the Forge `BrewingRecipeRegistry` over here:
https://github.com/CraftTweaker/CraftTweaker/blob/e8cd826790b94e1eeff34b1ccab22778b603c8ca/src/main/java/com/blamejared/crafttweaker/impl/actions/brewing/ActionAddBrewingRecipe.java#L24

That is called in a reload listener though, I'm not sure how / when REI looks up recipes, but it would be possible that we add the recipe after REI caches it?

**Comment by shedaniel** [comment]
Thanks, looks like REI never handled the forge brewing recipe registry.
