### ISSUE TITLE
[Bug] Forge 1.18.1 Crashing when "Add recipe" clicked

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#759]
### What happened?

In my modpack, Another Quality Modpack 3, when players hit the "add recipe" on a crafting table, they crash instantly. 

This has happened on the last 10 versions of REI. I will add a crash report asap.

modloader: 39.0.x - 39.0.59

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Please add the crash report asap

**Comment by shedaniel** [comment]
Please reopen with the logs
