### ISSUE TITLE
[Feature] Add a third option for cheat mode toggle: "Gamemode"

### ISSUE THREAD

**Issue by magnus-ISU** [shedaniel/RoughlyEnoughItems#768]
### What is your feature request?

When choosing this, you're in cheat mode if your gamemode is creative, and you're in recipe mode if your gamemode is in survival.

Solves the same problem as #737, but in a better way I think, because at least I personally would never need to configure it, while that suggestion would involve configuring it at least once per world.

Also, should be easier to implement because it doesn't need to change how settings are stored (except changing that option from a boolean to a dropdown menu)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by dillion20** [comment]
> ### What is your feature request?
> When choosing this, you're in cheat mode if your gamemode is creative, and you're in recipe mode if your gamemode is in survival.
> 
> Solves the same problem as #737, but in a better way I think, because at least I personally would never need to configure it, while that suggestion would involve configuring it at least once per world.
> 
> Also, should be easier to implement because it doesn't need to change how settings are stored (except changing that option from a boolean to a dropdown menu)
> 
> ### What do you think this change is of?
> * [ ]  Visual
> * [x]  Recipe Lookup
> * [x]  Cheat Mode
> * [x]  Plugin Integration / JEI Plugin Compatibility
> * [x]  Others

**Comment by dillion20** [comment]
https://github.com/shedaniel/RoughlyEnoughItems/issues/768#issuecomment-1870941092
