### ISSUE TITLE
[Feature] Add option to ignore effects in inventory

### ISSUE THREAD

**Issue by energy11a** [shedaniel/RoughlyEnoughItems#775]
### What is your feature request?

Add toggle in settings to act as if potion icons didn't exist.
For example tweakeroo hides potion effects in inventory gui.
https://www.curseforge.com/minecraft/mc-mods/tweakeroo

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by yesn0t** [comment]
ability to hide permanent effects only would be nice x)

**Comment by energy11a** [comment]
I meant option to toggle that effects don't change rei layout.

**Comment by shedaniel** [comment]
Declined
