### ISSUE TITLE
[Bug] Crash with Mana and Artifice

### ISSUE THREAD

**Issue by ModernGamingWorld** [shedaniel/RoughlyEnoughItems#777]
### What happened?

The developer look for the issue in their project and could not figure out what is causing this https://github.com/Mithion/Mana-And-Artifice/issues/433

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Its all on the link I listed above
```

**Comment by shedaniel** [comment]
It is on their end. I commented on their issue now.
