### ISSUE TITLE
[Bug] Recipes not showing up until you check them from their crafting source

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#787]
### What happened?

Some recipes/uses don't show up until you check the recipe from the "source". Not easy to put into words, just check the gifs below:

Checking the recipe for the infuser, then the seed by pressing R:
![coal_seed_no_recipe](https://user-images.githubusercontent.com/17010632/154801390-16b6d06e-fba7-44c7-ad83-c5132e276e09.gif)

Then check the uses for the infuser, go to the coal seed page just to look at it. Quit page, check recipe for infuser and seed, now the recipe for the seed shows:
![coal_seed_has_recipe](https://user-images.githubusercontent.com/17010632/154801427-26a52049-b602-49ad-bde8-1da4e9c79613.gif)

Versions:
Minecraft 1.18.1
Forge 39.0.79
RoughlyEnoughItems-7.3.432.jar

Modlist:
![image](https://user-images.githubusercontent.com/17010632/154801455-bcc5eaed-a34c-4750-ab7a-05572f1693b7.png)

KubeJS is in although the KubeJS folder is wiped, so this is without scripts.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by Sunekaer** [comment]
Same issue with modded recipes

**Comment by Raidobw2** [comment]
It works now thank you!
