### ISSUE TITLE
[Bug] RIE not visible

### ISSUE THREAD

**Issue by Repla7Noobx** [shedaniel/RoughlyEnoughItems#789]
### What happened?

When you press "R" u can see the recipie but REI is invisbe. Modpack is Valhelsia Enchanted

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Anything else?

![image](https://user-images.githubusercontent.com/52977994/154812915-3efca16b-0d18-46c2-a528-0ba3ac314333.png)
![image](https://user-images.githubusercontent.com/52977994/154812939-c35483df-32ad-47ce-9160-613b2e08cf83.png)

**Comment by shedaniel** [comment]
Please re-open the issue with the logs, also make sure REI and architectury is the latest version.
