### ISSUE TITLE
[Bug] Rei is loaded, but doesnt shows up in game

### ISSUE THREAD

**Issue by Thspooks** [shedaniel/RoughlyEnoughItems#791]
### What happened?

Using 1.18.1 fabric, rei7.3.432, the mod is loaded but it doesnt shows up in game. Its not hidden, i tried unhiding. Ill provide more info if needed

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://pastebin.com/4geD2Q9H Heres rei latest log

https://pastebin.com/HHcp3sXq heres mc latest log
```

### Anything else?

![image](https://user-images.githubusercontent.com/54241208/154861045-a9054386-1108-41e6-8799-fb8b80b4e6ff.png)

**Comment by Thspooks** [comment]
id forget modlist https://pastebin.com/uN1hpfs9

**Comment by shedaniel** [comment]
Update architectury

**Comment by Thspooks** [comment]
oi thank u kind man
