### ISSUE TITLE
[Bug] CHANGE ME Crashing when trying to see something with REI with Paradise Lost mod

### ISSUE THREAD

**Issue by MontMontgomery** [shedaniel/RoughlyEnoughItems#792]
### What happened?

If i try to see a recipe, or even just hover the mouse over the REI menu, it crashes

I've talked to Paradise Lost team, and they recommended try to talk with you guys
[](https://github.com/devs-immortal/Paradise-Lost/issues/608)

I have a world with 100+ hours everything fine, but with Paradise Lost, i can't use REI .

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://pastebin.com/tMamPUx5

(There was an error creating your Issue: body is too long (maximum is 65536 characters).)
```

### Anything else?

![image](https://user-images.githubusercontent.com/93541980/154950926-db21f9a5-c3d6-44f4-86cb-9797d84e5260.png)
My mods

Crash Report:

(due to Comment is too long (maximum is 65536 characters) i'll link a pastebin)
https://pastebin.com/qDXGdSgM

**Comment by shedaniel** [comment]
Please report to RER

**Comment by Jack-Papel** [comment]
https://github.com/theorbtwo/RoughlyEnoughResources/issues
