### ISSUE TITLE
REI compatibility issue with vanilla tweaks brewing guide

### ISSUE THREAD

**Issue by EGOIST1372** [shedaniel/RoughlyEnoughItems#795]
### What happened?

REI compatibility issue with vanilla tweaks brewing guide
![image](https://user-images.githubusercontent.com/86555131/154985290-f353f67a-7939-45b9-b7f6-d20c29792ba7.png)
![image](https://user-images.githubusercontent.com/86555131/154985468-d6890006-c095-4459-8213-4e3faf4d0f10.png)

vanilla tweaks brewing guide
![image](https://user-images.githubusercontent.com/86555131/154985634-61b27be2-7396-405f-88ce-4db468900e6e.png)

possible solution: it would be great that we had an option to turn off the REI GUI in brewing stand

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
This is not a bug in REI sorry, you can manually hide REI with Ctrl+O.
