### ISSUE TITLE
[Bug] When REI is shown heavy freezing occurs and after I get very low fps

### ISSUE THREAD

**Issue by veryredpp** [shedaniel/RoughlyEnoughItems#798]
### What happened?

When any GUI ,that REI gets loaded with, gets opened huge freezes happen and after that either it works but with very low fps or it doesn't and the REI list is transparent without displaying anything.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [x] Others

### Relevant log output

```shell
n/a
```

### Anything else?

[list.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8127898/list.txt)(mod list)
I have also tried it without Create with the same results.

![2022-02-23_23 31 51](https://user-images.githubusercontent.com/37497515/155412068-1e19fb24-c228-40bd-8087-0146e06e5a3f.png)
Example of REI not loading anything.

**Comment by shedaniel** [comment]
Please DO NOT put n/a in the logs field. Closed due to Invalid Issue

**Comment by veryredpp** [comment]
> Please DO NOT put n/a in the logs field. Closed due to Invalid Issue

How am I supposed to get logs if no crash occurs?

**Comment by Jack-Papel** [comment]
`.minecraft/logs/latest.log`
