### ISSUE TITLE
[Bug] Crafting area not always filled with recipe (vanilla recipes concerned)

### ISSUE THREAD

**Issue by Knito58** [shedaniel/RoughlyEnoughItems#80]
Needed a "minecart with hopper". Had all the ingredients in inventory. From the recipe for "minecraft with hopper" in REI I produced a chest, a hopper and finally a cart. All of them by clicking them into the crafting area from the recipe view of REI. 

Problems:

- When it came to put cart and hopper together in the final step the recipe was not filled into the grid.
- All the rails are also not filled into the crafting area in my version of the game.

Versions:
MC 1.14
Fabric v0.2.7+build.127
REI v2.8.1.+build.102

**Comment by shedaniel** [comment]
As I said this is a duplicate. The speed crafting system is very buggy.

**Comment by Knito58** [comment]
Ah sorry I did not understand that the bug is still alive and thought it was closed by error. My fault.

**Comment by shedaniel** [comment]
It’s alright
