### ISSUE TITLE
[Bug] REI Fabric 'move items' broke

### ISSUE THREAD

**Issue by Polarite** [shedaniel/RoughlyEnoughItems#801]
### What happened?

When you view a recipe with REI in crafting terminal it should show the missing ingredients, instead it is making the + button yellow tint only if you have a missing ingredient.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://paste.ee/p/myoae
```

### Anything else?

![unknown-6](https://user-images.githubusercontent.com/34978332/156143220-2b36bef7-aae6-42ce-9cda-6666b889e80c.png)

**Comment by Polarite** [comment]
Also opened an issue in applied energistics github in case its about AE2 side issue

**Comment by shedaniel** [comment]
Issue in AE2
