### ISSUE TITLE
Compatibility issue with mini effect mod

### ISSUE THREAD

**Issue by EGOIST1372** [shedaniel/RoughlyEnoughItems#803]
### What happened?

Compatibility issue with [mini effect](https://www.curseforge.com/minecraft/mc-mods/mini-effects-fabric) mod
REI has an option that moves potion effect icon to left and when it's activated it's just not working properly and mini effect icon is still in right side and when I hover over it, it moves to left but the effect is still on right and create a gap in REI menu
screenshots:
![image](https://user-images.githubusercontent.com/86555131/156663679-c71399db-95db-491b-8f98-716f0a259871.png)
![image](https://user-images.githubusercontent.com/86555131/156663685-99ff102c-a696-4873-89b7-8967db891b54.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
no log
```

**Comment by shedaniel** [comment]
Unfortunately I think they should fix it

**Comment by EGOIST1372** [comment]
It got fixed from mini effect mod side
thanks
