### ISSUE TITLE
[Feature] Port to 1.18.2

### ISSUE THREAD

**Issue by kittech0** [shedaniel/RoughlyEnoughItems#806]
### What is your feature request?

Port for fabric 1.18.2

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Ever considered checking the CurseForge page out to see if there is a 1.18.2 release? If you did that we wouldn't be chatting here...
