### ISSUE TITLE
Scrolling unaffected by exclusion zones.

### ISSUE THREAD

**Issue by ghost** [shedaniel/RoughlyEnoughItems#81]
I'm using an exclusion zone for cursed chests so that REI doesn't block the scrollbar. Whilst items are correctly not being placed there, mouse wheeling whilst the cursor is over that area will still cause the REI Item pane to change page. 

What I would expect is for REI to ignore this input or pass it to the current screen.

**Environment**
 - Minecraft: 1.14
 - Mod Loader: fabric
- REI 2.8.1.103

**Comment by ghost** [comment]
Also just noticed that clicking in this exclusion zone doesn't get sent to my screen.

**Comment by shedaniel** [comment]
Is the version that uses exclusion zone of cursed chests on CF now? I want to test the thing
