### ISSUE TITLE
[Bug] KubeJS hiding doesn't work if the item/block isn't in a creative tab

### ISSUE THREAD

**Issue by mosharky** [shedaniel/RoughlyEnoughItems#812]
### What happened?

I'm not sure if this is an issue with KubeJS or REI, but I assume it's the latter since REI imports items that aren't in creative tabs in an odd way? I don't know
```js
onEvent('rei.hide.items', rei => {
	rei.hide([
		// tables and beehives added by Compat O' Plenty aren't hidden by this?
		/(biomesoplenty|compatoplenty|decorative_compat|supplementaries):(.*magic.*|.*umbran.*|.*palm.*)/,
		// this works fine
		/refinedstorage:(?!red).+_(controller|creative_controller|grid|crafting_grid|pattern_grid|fluid_grid|network_receiver|network_transmitter|relay|wireless_transmitter|disk_manipulator|crafter|crafter_manager|crafting_monitor|security_manager|detector)/,
		// this doesn't work either
		/biomesoplenty:potted.*/,
		// lootr blocks aren't being hidden
		/lootr:(?!trophy).*/,
	])
})
```
all of the blocks that weren't hidden, as i commented, have one thing in common: they aren't in a creative tab. What's even more confusing is that [Compat O' Plenty does actually register beehives and tables into a creative mode tab](https://github.com/ManaStar/compat-o-plenty/blob/b2e5081fdfe6046ab05ecb00d7f72903a8abc461/src/main/java/seleneandmana/compatoplenty/core/registry/CompatBlocks.java#L38), but all tables and beehives aren't in creative mode tabs once I'm in-game, but I guess that's a bug with that mod, not REI.

My current assumption is that REI is implementing things that don't have a creative menu in a way that KubeJS can't handle with hiding. I wish I could give more information, but this is all I could do. It's reproduceable with blocks that aren't in creative tabs.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No errors whatsoever in the log
```

**Comment by shedaniel** [comment]
I believe this is an issue from the KubeJS side.
