### ISSUE TITLE
[bug] items are not visible in list on side. 

### ISSUE THREAD

**Issue by SMGPro123** [shedaniel/RoughlyEnoughItems#813]
### What happened?

when in my inventory, the list of items, the search bar, and the settings button are invisible. i know they still are there cause i can click on them if i randomly click. 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
it wont let me paste things in here -_- i have the logs saved.
```

### Anything else?

this is in 1.18.1, I have the 7.3.443 version, architectury 3.6.15, cloth config 6.2.57, and fabric api 046.1. no resource packs, no shaders. 
![image](https://user-images.githubusercontent.com/64209862/158885652-b48595f6-a2f6-453d-bae9-a5bf13cf3730.png)
![image](https://user-images.githubusercontent.com/64209862/158885709-a3030060-e81a-45ab-a0e9-0af232620259.png)
![image](https://user-images.githubusercontent.com/64209862/158885874-837f3a9b-2b1e-4c79-92a3-b656c9909dd5.png)

**Comment by shedaniel** [comment]
Update architectury
