### ISSUE TITLE
[Bug] [Fabric 1.18.2] Fix Z-fighting for items in tooltip components

### ISSUE THREAD

**Issue by MisterPeModder** [shedaniel/RoughlyEnoughItems#815]
### What happened?

Items that have tooltip components (such as bundles) do not display contained items when inside the favorites section of REI.

This affects bundles and ender chests (when ShulkerBoxTooltip is installed).

Bundle in inventory:
![image](https://user-images.githubusercontent.com/7838479/159618156-6f5af7e7-81d1-46ab-9321-f89b3639f452.png)

Bundle in REI favorites
![image](https://user-images.githubusercontent.com/7838479/159618248-11ac2c07-d282-4a62-9d47-e43cb0d13a6b.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
No errors are present in the logs
```

**Comment by shedaniel** [comment]
@MisterPeModder Are there any negative implications in injecting to the ItemStack method instead of the current injection to Screen?

**Comment by MisterPeModder** [comment]
I'm sorry, I don't get what you mean, are you talking about ShulkerBoxTooltip? If so, the issue does still occur when REI is the only non-API mod installed.

**Comment by shedaniel** [comment]
> I'm sorry, I don't get what you mean, are you talking about ShulkerBoxTooltip? If so, the issue does still occur when REI is the only non-API mod installed.

@MisterPeModder Yep, I am just asking that since REI gets the tooltip data directly from the ItemStack instead of going with the Screen method

**Comment by MisterPeModder** [comment]
I just put quick a `System.out.println()` in my component render method, the data is correct but the items wont display...

**Comment by MisterPeModder** [comment]
The items are actually rendered, but behind the background texture.

This seems to be a z-index issue, the only difference between the rendering in inventories and REI is: https://github.com/shedaniel/RoughlyEnoughItems/blob/1b9c1f87fddb5d9cae7575d6e015baf370c5417f/fabric/src/main/java/me/shedaniel/rei/impl/client/gui/fabric/ScreenOverlayImplImpl.java#L71

As far as I can see, the translation just gets ignored by the item renderer, it has no methods that take a MatrixStack/PoseStack as a parameter
