### ISSUE TITLE
[Feature] Translation Key

### ISSUE THREAD

**Issue by LeeroyGarfield** [shedaniel/RoughlyEnoughItems#816]
### What is your feature request?

**I would like the option to display Translation Key in the tooltip.**

Most modpack creators would find it very convenient to rename certain vanilla/modified items/blocks to fit their ideas/themes using resource packs (assets/mods/lang/xx xx.json). Some people, including myself, can get nitpicky when the names of certain modded items/blocks do not seem right.

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
The translation key can be checked if you look at the mod's source en_us.json or make it up yourselves.

It's most likely block.modid.id

Turn on F3+H to find out the id
