### ISSUE TITLE
[Bug] Weirdness with Applied energistics 2

### ISSUE THREAD

**Issue by redstonerti** [shedaniel/RoughlyEnoughItems#819]
### What happened?

If you type on the me terminal and then try to use backspace on the REI search bar, it doesn't work. You need to exit the me terminal and come back in order for it to work. It also sometimes erases text from the me search bar instead of REI. Here's a video of that in action:
https://redstoner.me/downloads/videos/search%20bug.mp4

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Latest.log: https://mclo.gs/gFbUBCV
Rei.log: https://mclo.gs/gslNKUE
```

**Comment by shedaniel** [comment]
You might want to report this on AE2 instead, I remember Refined Storage had a better compatibility so I think this should be possible.
