### ISSUE TITLE
[Feature] Close search after pressing "Enter"

### ISSUE THREAD

**Issue by Chr0n4s** [shedaniel/RoughlyEnoughItems#82]
In the 1.14 version i'd like to finish searching when pressing enter.
ATM i just leave the search bar if i click in the inventory.

**Comment by shedaniel** [comment]
Like use enter to unfocus?

**Comment by Chr0n4s** [comment]
Exactly.

**Comment by Chr0n4s** [comment]
U sir, are a genius.

**Comment by shedaniel** [comment]
Np
