### ISSUE TITLE
[Bug] Quark plugin for JEI 9.5 API Support

### ISSUE THREAD

**Issue by Sunekaer** [shedaniel/RoughlyEnoughItems#821]
### What happened?

Quark plugin error

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://pste.ch/geyebuhupo.pl
```

**Comment by Raidobw2** [comment]
Looks to be 1.18.2 so I'm adding more for 1.18.2: https://paste.feed-the-beast.com/view/041e3515

**Comment by Raidobw2** [comment]
As well, this is specifically for Mekanism on 1.18.2 `Mekanism-1.18.2-10.2.0.459.jar`: https://paste.feed-the-beast.com/view/427ab0a4

**Comment by Raidobw2** [comment]
More tests incoming
Quark works fully for the 2 errors:
![image](https://user-images.githubusercontent.com/17010632/163036274-c05bb763-0424-4934-9a16-2c5202a52a92.png)
Farmer's Delight works fully:
![image](https://user-images.githubusercontent.com/17010632/163036801-d38368f6-695b-4296-91e3-6a59527cc121.png)

**Comment by Raidobw2** [comment]
Forbidden and arcanus ok!
![image](https://user-images.githubusercontent.com/17010632/163066210-3bd343c6-ca33-4d59-bd9e-373c706463e5.png)

**Comment by Raidobw2** [comment]
Problems remaining (1.18.2):
- [x] Sophisticated backpacks tooltip crashes while pressing Left-Shift
- [x] Immersive Engineering no recipes such as Crusher crushing redstone ore are shown
- [x] Mekanism Fission Reactor recipes not shown
- [x] All Mekanism machines don't show recipes

**Comment by Burgersim** [comment]
I was wondering, should Cobblemon Integrations work with REI? It does work with JEI/EMI and shows me dropes and evolution Items, but when I use REI it doesn't even seem to load, although according to the mod author it should just be like any JEI plugin.
