### ISSUE TITLE
[Bug] Unrelated Items Appear As Search Results

### ISSUE THREAD

**Issue by pawbap** [shedaniel/RoughlyEnoughItems#823]
### What happened?

I can type gibberish into the search bar, but certain items from certain mods always appear as results when they don't appear to be related to what I type. See the images for more info.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://pste.ch/oqolizufax.sql
```

### Anything else?

https://imgur.com/a/JOGGoWd

**Comment by pawbap** [comment]
Just found that issue #673 describes the same problem...

**Comment by shedaniel** [comment]
Yep, dupliicate of #673
