### ISSUE TITLE
[Bug] Wrong slots from craftTweaker recipes

### ISSUE THREAD

**Issue by Cursedth** [shedaniel/RoughlyEnoughItems#831]
### What happened?

I'll post this as a bug report with them as well.

Using craftTweaker making recipes that don't fill all ingredient slots don't fill correctly by Index.

Assuming familiarity with craftTwealer:
This ..
`craftingTable.addShaped( "name" , <item:out> , [`
`    [<item:in>, <item:in>],`
`    [<item:in>, <item:Air>],`
`    [<item:in>, <item:in>]`
`]);`

..works correctly in the crafting table and the REI + correctly transfers the ingredients to  the right slots Indexes in the craftingtable..
But when pressing show recipe REI (only) shows this pattern..

X X X
A X X
N N N

Should show
X X N
X A N
X X N

Regards,

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
NA
```

**Comment by shedaniel** [comment]
Unable to reproduce
