### ISSUE TITLE
[Bug] Settings button renders over item tooltip

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#833]
### What happened?

Title
![image](https://user-images.githubusercontent.com/45438411/163633213-a9d80e57-3311-4045-b015-72418ffff8d0.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
none
```

**Comment by shedaniel** [comment]
Duplicate of #387
