### ISSUE TITLE
[Bug] Inverted item cheating broken

### ISSUE THREAD

**Issue by freopt** [shedaniel/RoughlyEnoughItems#834]
### What happened?

If you turn "Item cheating amount" in the REI settings to "inverted", instead of actually inverting right and left click, it just makes both give a stack.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
none
```

**Comment by shedaniel** [comment]
Can not reproduce
