### ISSUE TITLE
[Feature] Disable option to show REI in some instances

### ISSUE THREAD

**Issue by EGOIST1372** [shedaniel/RoughlyEnoughItems#836]
### What is your feature request?

Disable option to show REI in some instances
Like when I open furnace, smoker, blast furnace and brewing stand, I like to have REI be disabled and only be active when I press E or opening crafting table
I know there is a key bind (ctrl+o) to close the REI but that's frustrating to do it each time you open a furnace or brewing stand
Please implement this option
Much appreciated <3 <3

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Not planned

**Comment by EGOIST1372** [comment]
@shedaniel sorry for tagging
I get it that you don't want to implement it but whenever REI menu get open my FPS drops from 200+ to 100-
So it's a legit request to consider. it's just not a visual but also performance related
