### ISSUE TITLE
[Feature] Add the ability to drag and drop when in creative mode even when cheat mode is off

### ISSUE THREAD

**Issue by EGOIST1372** [shedaniel/RoughlyEnoughItems#837]
### What is your feature request?

Add the ability to drag and drop when in creative mode even when cheat mode is off.
it's just makes so much sense when you are in creative mode, you want to access items no matter what, cheat mode is on or off.
Just make cheat mode work when you are in survival mode.
thanks in advance <3

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
Denied, You can change cheat mode in the config menu, there is an option to enable it only in creative mode
