### ISSUE TITLE
[Bug] [Netty Epoll Server IO #1/WARN]: Received invalid START packet for SplitPacketTransformer with packet id roughlyenoughitems:move_items for side C2S

### ISSUE THREAD

**Issue by mtailordev** [shedaniel/RoughlyEnoughItems#838]
### What happened?

Upon clicking the + button to auto-insert items from a REI recipe into the crafting grid, nothing happens and the server console prints the following message:
`[Netty Epoll Server IO #1/WARN]: Received invalid START packet for SplitPacketTransformer with packet id roughlyenoughitems:move_items for side C2S`

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
[Netty Epoll Server IO #1/WARN]: Received invalid START packet for SplitPacketTransformer with packet id roughlyenoughitems:move_items for side C2S
```

### Anything else?

Environment:
Minecraft 1.18.1 with Fabric Loader 0.13.3 running on Ubuntu 20.04
REI v7.3.443
Modpack All of Fabric 5 - AOF5 - 1.18.1 v1.1.5

**Comment by shedaniel** [comment]
I believe this is fixed on architectury's side.
