### ISSUE TITLE
Rei does not render in Multiplayer 1.18.2

### ISSUE THREAD

**Issue by IchigoGames** [shedaniel/RoughlyEnoughItems#843]
### What happened?

REI is installed on server and client but will not show up when you first log in unless you join singe player first then join a server
not sure what logs if any would show-prove this is a issue its happening on my pack 
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8559858/latest.log)
4

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
i know it says not to but log is to big for here or even pastbin so only way i can shere it is dropbox https://www.dropbox.com/s/0bwhfihlq2m31hd/latest.log?dl=0
```

### Anything else?

Modpack version 4.4 
Minecraft 1.18.2
Forge 40.1.0
RoughlyEnoughItems-8.1.457
RoughlyEnoughItems-jei-internals-workaround-8.1.45
https://www.curseforge.com/minecraft/modpacks/the-new-frontier-enhanced

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/933pqldorm655fa/rei.log?dl=0 in case you need it

**Comment by shedaniel** [comment]
not caused by rei, there is an error syncing recipes
