### ISSUE TITLE
[Bug] REI search box doesn't capture focus when clicked

### ISSUE THREAD

**Issue by shartte** [shedaniel/RoughlyEnoughItems#848]
### What happened?

Click REI search box while other widget on screen is focused, REI search box appears to have focus, but the screen will still forward events to the previously focused element.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
None
```

### Anything else?

I'll be honest: It's hard to know how MC's focus is *really* supposed to work. But it'd be nice if the overlay search field would onfocus the current screen's focus element before capturing itself.

**Comment by shedaniel** [comment]
Should be fixed recently
