### ISSUE TITLE
[Minor Feature] Support for Cammie's Wearable Backpacks for the Quick Craft feature

### ISSUE THREAD

**Issue by Desempregago** [shedaniel/RoughlyEnoughItems#849]
### What is your feature request?

![2022-05-03_09 52 44](https://user-images.githubusercontent.com/14002834/166456423-f10f5e3c-b2c9-4d86-bf9e-c06512a25166.png)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [x] Others

**Comment by shedaniel** [comment]
Support should come from the mod instead.
