### ISSUE TITLE
[Bug] Create crushing wheels percentage outputs, Tinkers alloying

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#850]
### What happened?

Create recipes sometimes have a % chance of outputting an item, and it's not rendered in REI
MC: `1.18.2`
Forge: `40.1.19`
REI: `RoughlyEnoughItems-8.1.457.jar`
REI workaround: `RoughlyEnoughItems-jei-internals-workaround-8.1.457.jar`
Create: `create-mc1.18.2_v0.4.1.jar`

What JEI shows:
![image](https://user-images.githubusercontent.com/17010632/167769962-f81693b8-288b-43d0-9b47-c386d7638086.png)

What REI shows:
![image](https://user-images.githubusercontent.com/17010632/167769986-93f62793-7804-4f1c-8015-1fa6a5d7685a.png)

I know nothing about this but it looks like the Crushing Wheel plugin is at https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/compat/jei/category/CrushingCategory.java and that uses the other plugin at https://github.com/Creators-of-Create/Create/blob/d8dd101fdf5c6e755b28b6f300e1e7fc10816c99/src/main/java/com/simibubi/create/compat/jei/category/CreateRecipeCategory.java#L111. So if I understand it properly, if you fix that one it will probably also fix any Create recipe that has a chance output.

Thanks a bunch in advance!

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [X] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A, nothing in logs about it
```

### Anything else?

N/A

**Comment by MaxNeedsSnacks** [comment]
FWIW this isn't specific to create, Tinker's Construct also has broken tooltips (the Fluid amount isn't shown)

**Comment by Raidobw2** [comment]
For Tinkers this is the plugin: https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/plugin/jei/AlloyRecipeCategory.java
Mod: `TConstruct-1.18.2-3.5.0.17.jar`

This is what JEI shows when pressing Shift. When not pressing Shift, you will also see the amount of ingots required:
![image](https://user-images.githubusercontent.com/17010632/167950486-39b130bb-2ef3-4df6-9a23-2c7133e1eeb6.png)

This is what REI shows:
![image](https://user-images.githubusercontent.com/17010632/167950532-02d93aad-f519-4af8-bda3-dd3772b214b2.png)

**Comment by Raidobw2** [comment]
Have a nice day and thank you!
