### ISSUE TITLE
[Feature] RegEx Search doesn't support "(term1|term2)" search method

### ISSUE THREAD

**Issue by Laifsyn** [shedaniel/RoughlyEnoughItems#851]
### What is your feature request?

![image](https://user-images.githubusercontent.com/99366187/168193659-518a3c75-355c-40dc-9581-55cdc1df7d25.png)

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by MaxNeedsSnacks** [comment]
I'm assuming it's parsing the "inner" `|` as an or so it doesn't even recognise that you have input a regex, so it's searching for literal strings instead

**Comment by shedaniel** [comment]
won't fix, this requires massive refactor in how REI parses the search argument, | is a built-in separator in REI itself
