### ISSUE TITLE
[Feature] Grant all recipes when recipe book is disabled

### ISSUE THREAD

**Issue by sisby-folk** [shedaniel/RoughlyEnoughItems#853]
### What is your feature request?

Not sure if this would be a bit overcomplicated due to potential differences in configuration on the client and serverside, but it would be helpful if, where possible and reasonable to assume, all recipes could be granted when recipe book is disabled, effectively suppressing the "new recipe unlocked" notifcation from appearing during play.

On a server, it's certainly not too hard to just run the command, but it'd be nice to have this occur in singleplayer at least.

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by SandWoodJones** [comment]
I think that unlocking all recipes may be considered cheating. I feel that just disabling the toast from showing up entirely would be the best option here.
