### ISSUE TITLE
[Crash Forge 1.18.2] Crash on startup

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#857]
### What happened?

Game crashes when launching

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Log is too large for this issue;

https://gist.github.com/itsdinkd/b600b5dcda34f6f0054f1f9ec1e79591
```

**Comment by shedaniel** [comment]
Does it only crash with REI?

**Comment by itsdinkd** [comment]
> Does it only crash with REI?

Correct. Tried JEI, works fine. tried without JEI and REI, works fine.

**Comment by itsdinkd** [comment]
@shedaniel anything on this? would love to use REI in my modpack, rather than JEI.

**Comment by shedaniel** [comment]
You might want to do a binary search on seeing if there is another mod causing the issue, basically disable half of the mods, then see if it crashes. If it doesn't, try the other pile, or else do half of the half

**Comment by itsdinkd** [comment]
So i removed RoughlyEnoughResources and i didnt get the main crash I reported above, but then I got an issue with Quest Additions, which is weird because it works when using JEI. 

Reading the logs, with the error with quest additions that prevents the game from launching 

![image](https://user-images.githubusercontent.com/35115304/170777324-c5e1f6a4-9b89-4ccb-b4d9-7d136005c66a.png)
and in logs it shows
```java
[27May2022 12:20:16.654] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[27May2022 12:20:17.317] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[27May2022 12:20:17.357] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[27May2022 12:20:17.359] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
```

I'm going to try removing quest additions and see what happens next. it looks like something is breaking on the client side of things when using rei

**Comment by itsdinkd** [comment]
Removing Quest Additions, while having REI did the trick.... still weird though that quest additions does not work with rei, but does with JEI. Reporting it to the Quest Additions Dev.


The Roughly Enough Resources one though (which is the main crash I posted in OP) seems to happen with just REI and RER
https://github.com/theorbtwo/RoughlyEnoughResources/issues/61

**Comment by itsdinkd** [comment]
Scratch that. So when viewing a recipe with REI, instantly crashes.

Errors in latest.log with it showing caused by REI; https://pastebin.com/UgNjkErB
crash log: https://pastebin.com/9qKDcsnz

**Comment by itsdinkd** [comment]
issue in #875
