### ISSUE TITLE
[Bug] Commands not working

### ISSUE THREAD

**Issue by Merisdarkmon** [shedaniel/RoughlyEnoughItems#858]
### What happened?

Hi,
My build:
Minecraft 1.18.2 Fabric loader 0.14.5-1.18.2
Optifabric 1.13.0
Optifine 1.18.2 HD U H7
Roughly Enough Items version 8.1.457

Dependencies:
Fabric-api 0.51.1+1.18.2
Architectury 4.4.60
Cloth-config 6.2.62 fabric

Settings on map generating:
Enable cheats On
Inventory stay on death On
Mob griefing Off

My problem:
When I start the game on a newly generated map after installing those mods and set up those settings I can see the block list on the right side of the screen when I open my inventory as it intended, but I can't use the command buttons, nor can I pull them to the above favorite bar. I've tried to change the game mode with manual typing in the chat and it works, but I still can't do anything with the command buttons after the manual game mode change. I've read on some forums that I should try to reload the mod with the reload button in the settings but it won't help.
Any idea what should I do/try to make it work?
Thanks,
Merisdarkmon

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Too long, can't post it.
```

**Comment by shedaniel** [comment]
OptiFine not supported, please find support on OptiFabric

**Comment by Merisdarkmon** [comment]
Still not working even without optifine and optifabric.

**Comment by shedaniel** [comment]
Can you attach a log though PasteBin or Google Drive?

**Comment by Merisdarkmon** [comment]
I will do it in a minute, but I try first to create a clean instance with only the fabric loader, Rei, and the dependencies.

**Comment by Merisdarkmon** [comment]
Here it is:
https://pastebin.com/TTg1nXFd

**Comment by Merisdarkmon** [comment]
And it's a clean instance only with the loader, REI, Architectury, Cloth-config, and Fabric-api

**Comment by Merisdarkmon** [comment]
Hi,
Any news about the bug?
Was the log file useful?

**Comment by shedaniel** [comment]
Can you attach the latest.log

**Comment by shedaniel** [comment]
Please re-open with latest.log.
