### ISSUE TITLE
[Bug] Trying to use the scroll bar on an information tab, instead tries to "save the recipe", and does not let you scroll

### ISSUE THREAD

**Issue by f-raZ0R** [shedaniel/RoughlyEnoughItems#865]
### What happened?

This issue is caused by two different outcomes being mapped to the same action. Trying to drag the scroll bar, also counts as "dragging the recipe", and that has higher priority. A simple fix could be to simply swap the priority of these actions, or to make it so scrolling overrides dragging
VIDEO:
https://user-images.githubusercontent.com/30442287/169823993-d65cdcb3-ab7b-45e2-90dc-e07e1d07c7ab.mp4

.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A
```

**Comment by MaxNeedsSnacks** [comment]
~~This is technically the same as #861, however it provides an additional important use case adding urgency to the original issue :P~~

Nevermind, this probably actually isn't the same issue since scrolling is handled globally, that one was just a bug in the clicking logic

**Comment by shedaniel** [comment]
I believe this is fixed in newer REI when the style of the information panel is changed. Thanks for reporting.
