### ISSUE TITLE
[Bug] Item Cheat Mode's Invetered setting makes both mouse buttons give a stack instead of just left click

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#866]
### What happened?

If you set it to inverted, both left and right click give a full stack instead of mirroring the default left for 64 right for 1.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A
```

**Comment by shedaniel** [comment]
Was this recently fixed? Or did this only start occuring from REI 8.2
