### ISSUE TITLE
[Bug] Mod Search is happening even when set to needing prefix

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#867]
### What happened?

![image](https://user-images.githubusercontent.com/15698722/170124114-4a080270-2a1c-44a9-9884-43d68737ba1c.png)
![image](https://user-images.githubusercontent.com/15698722/170124170-f5f409dc-ac9c-445b-bbe1-bd05964f71fb.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
N/A
```

**Comment by MaxNeedsSnacks** [comment]
I'm assuming it's because of the ID search, seeing as the modid is often also used as the namespace for IDs

**Comment by MaxNeedsSnacks** [comment]
(In other words, by setting that to require prefix or disabled, you won't have this overlap anymore)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/170310131-a21d6d7c-4d36-40b7-951b-379c03641da3.png)

Which option is that? It isn't Identifier Search, disabling that doesn't fix it.

**Comment by shedaniel** [comment]
Yeah tooltip is leaking the modid, I am not too sure what is happening
