### ISSUE TITLE
[Crash] Forge 1.18.2 - Crash when hovering over items in REI

### ISSUE THREAD

**Issue by itsdinkd** [shedaniel/RoughlyEnoughItems#875]
### What happened?

Game immediately crashed as soon as I hovered over items in the inventory window over items in REI. 

There is another crash I have where (it happened on a couple versions ago) it would crash when viewing a recipe, this latest version, I cant even get a second to get to the recipe. 

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://gist.github.com/itsdinkd/2bdc840351904c6208b6dcf16552c661
```

**Comment by itsdinkd** [comment]
REI Log: https://gist.github.com/itsdinkd/6a1330049f922d275b894f7f977ccb6c

**Comment by itsdinkd** [comment]
@shedaniel is there a ETA on when this will be fixed? my forge pack is taking a huge hit using JEI and not REI.

**Comment by shedaniel** [comment]
ATM 1.19 is more urgent, but I will get to this after that, so a few days.

**Comment by itsdinkd** [comment]
sounds good, thank you

**Comment by shedaniel** [comment]
Since your issue isn't trivial to fix, I am releasing a new version of REI to help tracing the issue. Please report back with a new latest.log when you crash with the new version.

**Comment by itsdinkd** [comment]
will do!

**Comment by itsdinkd** [comment]
With your latest update, it actually is not crashing anymore! I think updating to use the latest jei api worked? (don't quote me though)

**Comment by itsdinkd** [comment]
there is this however in rei-issues https://pastebin.com/qZj5TPeh
