### ISSUE TITLE
[Crash]  when I search something in search bar

### ISSUE THREAD

**Issue by Luppyn** [shedaniel/RoughlyEnoughItems#880]
### What happened?

Using my modpack, when I search something in search bar, can crash or not, I don't know the probability.

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
Rei.log — https://gist.github.com/Luppyn/e4c0f5edeb172df8ec799b2c84edd520
Latest.log — https://gist.github.com/Luppyn/7ec6e0afbc4e034774313e6cb1704235
```

### Anything else?

 [_Modpack↗_](https://www.mediafire.com/file/27ih9ncp1z4s4a9/mods.7z/file)

**Comment by shedaniel** [comment]
REI is not compatible with optifine. The general consensus with optifabric is that _if it works, it works, if it doesn't work, then too bad_.
Optifine is not open sourced, we cannot fix it.
