### ISSUE TITLE
[Feature] Durability in tooltip outside F3 + H

### ISSUE THREAD

**Issue by foul-fortune-feline** [shedaniel/RoughlyEnoughItems#881]
### What is your feature request?

Much like one can currently append the favorites hint and mod name, it feels as if it might be in the scope of REI to have the option to append tool/weapon/etc durability to the tooltip outside F3 + H. The utility of the feature is readily apparent imo, as there are a *lot* of tags that display in vanilla F3 + H that take up a lot of room when the only thing one's really interested in is displaying item durability

If there comes along an REI plugin that does this I would ofc appreciate a link to it (I wasn't able to find one last I checked), but it does feel like something that should likely be included in the unmodified version of REI

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by foul-fortune-feline** [comment]
This is less of an issue than I thought as I didn't realize it was another mod force-displaying all the tags

**Comment by shedaniel** [comment]
This is out of scope of REI, see the discussion in #1084
