### ISSUE TITLE
[Feature] Auto Clear Search Box after Closing

### ISSUE THREAD

**Issue by ardissaps** [shedaniel/RoughlyEnoughItems#895]
### What is your feature request?

So no need to keep pressing backspace, thank you !

### What do you think this change is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Maybe just right click on the search field?
