### ISSUE TITLE
REI encounters an error when paired with Jade

### ISSUE THREAD

**Issue by grundrow** [shedaniel/RoughlyEnoughItems#896]
### What happened?

Fabric REI version 9.0.472 when used with Jade encounters an error. 

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [x] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
12:14:58.041
The entrypoint used by Jade, "rei" is deprecated and will be removed in a future version of Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.
12:14:58.050
Could not create REI Plugin [REIPlugin] due to errors, provided by 'jade'!
12:15:00.385
Could not create REI Plugin [REIServerPlugin] due to errors, provided by 'jade'!
```

### Anything else?

![image](https://user-images.githubusercontent.com/107139804/172679131-b0027424-89e5-46ce-b46c-6ef1701bcefe.png)

**Comment by AzureDoom** [comment]
Jade needs to update for the changes introduced here https://github.com/shedaniel/RoughlyEnoughItems/commit/05bdd20873a170572b052ed159868c576a48a60d

**Comment by grundrow** [comment]
Jade has now fixed the issue
