### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by abrown4912** [shedaniel/RoughlyEnoughItems#90]
**Describe the bug**
the first potion when searching potions (and maybe enchanted items) has a tint around the entire item space instead of just the item itself

**Steps to Reproduce**
- First Step
search potion

**Screenshots**
https://i.imgur.com/sX37RVl.png

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14
 - Mod Loader: fabric

**Comment by shedaniel** [comment]
This should be fixed by build 106, please test on that version.
