### ISSUE TITLE
[Feature] Enchanted Book Collapsible Group

### ISSUE THREAD

**Issue by Dr-WeiAL** [shedaniel/RoughlyEnoughItems#903]
### What is your feature request?

Some enchanted books have many levels, which will take up a lot of space in the REI. Maybe it would be better to only display the highest level of enchanted books supported? Just like in the creative mode inventory
![image](https://user-images.githubusercontent.com/47446553/172973679-9397c9c8-d26f-4cb1-b670-5eace2c9bab7.png)
![image](https://user-images.githubusercontent.com/47446553/172973697-1ac3d664-6545-45f0-8731-11fcce4c5c44.png)

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
This will be handled by #846 with collapsable entries
