### ISSUE TITLE
[Bug] some crash reports

### ISSUE THREAD

**Issue by Dr-WeiAL** [shedaniel/RoughlyEnoughItems#909]
### What happened?

This is the crash caused by hitting "+" on the server
![image](https://user-images.githubusercontent.com/47446553/173233453-168a27a5-2ee2-478b-befd-36f12e234465.png)

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8885412/rei.log)
[crash-2022-06-11_11.14.37-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8885413/crash-2022-06-11_11.14.37-client.txt)
[crash-2022-06-11_12.36.40-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8885414/crash-2022-06-11_12.36.40-client.txt)

**Comment by shedaniel** [comment]
You have an outdated REI, this issue was already fixed. If it keeps happening, please open another issue with the new logs.
