### ISSUE TITLE
[Bug] REI gui dosen't show up (1.19)

### ISSUE THREAD

**Issue by ryanRoxd** [shedaniel/RoughlyEnoughItems#915]
### What happened?

Hi! The gui of the REI is not showing up. I tryed diffrent thing like reinstalling minecraft, fabric, the mod. can you help me?
The mod works, like when i press r on oak or crafteble items it shows the recipe. Can you help me?

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://throwbin.in/agxele 
i have puted it in a link because i can't post the issue
```

### Anything else?

 i will attach a link to some photos so you can see the problem more precisely (https://imgur.com/a/1q9K7pz)

**Comment by shedaniel** [comment]
I am unable to load your logs website, please use Github Gists

**Comment by rdrpenguin04** [comment]
Got it into a Gist for you: https://gist.github.com/rdrpenguin04/61fa30227d7c6929b17adbf6b3c6a7be

**Comment by ryanRoxd** [comment]
> I am unable to load your logs website, please use Github Gists

so what can i do?

**Comment by shedaniel** [comment]
Are you able to see any items / recipes in the vanilla recipe book? Can you also try toggling REI via Ctrl+O

**Comment by ryanRoxd** [comment]
i used ctrl+o, the gui was toggled off, thanks and sorry
