### ISSUE TITLE
1.18.2 REI Plugins sometimes don't reload, causing any REI GUI to not show

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/RoughlyEnoughItems#918]
### What happened?

Hi! I'm reporting this for 1.18.2, although this is likely an extension of #601 and #915. In short, there is sometimes a chance for you to enter a world (or server) and not have the plugins reload. This causes the REI guis to not show up until one manually reloads the plugins in the REI mod config.

How the screen looks like: Exactly if it was vanilla. Nothing else than the creative menu (in creative) is shown unless plugins are reloaded, or the world is joined again. I do not have steps to reproduce this consistently.

Versions:
REI: `RoughlyEnoughItems-8.2.479.jar`
REI Hacks: `RoughlyEnoughItems-jei-internals-workaround-8.2.479.jar`
Minecraft: `1.18.2`
Forge: `40.1.51`

----------------------------------------------------------------

I have logs in three folders that might help however:
`1. Initial world join` is when I initially joined a world and noticed no REI guis at all. I didn't move at all.
`2. Reloaded plugins` is when I reloaded the plugins in the world (with a mods button). Still didn't move at all after. The REI guis were restored in that step.

I then closed the game. I started the game again.

`3. Clean working launch` represents the launch right after, that worked well. I joined the world and the REI guis were there as expected. I didn't move at all either when taking this log.

----------------------------------------------------------------

Here are those logs:
[REI-Plugin-Issue.zip](https://github.com/shedaniel/RoughlyEnoughItems/files/8896466/REI-Plugin-Issue.zip)
If you would like them in a different format let me know, and which format.

----------------------------------------------------------------

Here's a visual comparison of `latest.log` to help.
On the left, is the log from step 3 (clean launch). &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the right, the log from step 1 (no GUIs shown):
![image](https://user-images.githubusercontent.com/17010632/173495926-c986a1c2-534e-4011-aebe-e2f697f28c06.png)
`[Render thread/WARN] [patchouli/]: Recipe minecraft:chest (of type minecraft:crafting) not found`

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
When you next encounter this, would you mind checking if the vanilla recipe book holds any recipes? REI uses the same packet as that one.

**Comment by Raidobw2** [comment]
Will do!

**Comment by XmerpX** [comment]
![2022-06-15_00 49 46](https://user-images.githubusercontent.com/107533389/173752548-adc7b80e-2471-4e41-ac71-6adea2c9628a.png)
Recipe book is blank
