### ISSUE TITLE
[Feature] Tag to hide items

### ISSUE THREAD

**Issue by Laifsyn** [shedaniel/RoughlyEnoughItems#928]
### What is your feature request?

An Innate tag that REI will check for to hide items by default. Any item added to the tag will directly hide the item. This will skip the step of needing to 'manually' open and add a filter. And would allow the possibility to toggle/untoggle the "Hide items in REI's tag" through key combination

### What do you think this change is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

**Comment by shedaniel** [comment]
Delivered with c:hidden_from_recipe_viewers, this tag also works for JEI and EMI.
