### ISSUE TITLE
Game Mode

### ISSUE THREAD

**Issue by TookUrSweetRoll** [shedaniel/RoughlyEnoughItems#934]
### What is your feature request?

Is there an option to remove/hide the Game Mode buttons in the favorites section?

### What do you think this change is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by shedaniel** [comment]
You can press A on it, this is a bug however since I didn't intend to make them show up by default

**Comment by TookUrSweetRoll** [comment]
Worked. Thank you.
