### ISSUE TITLE
[Bug] Crash on 33 page of REI 

### ISSUE THREAD

**Issue by xJasper222** [shedaniel/RoughlyEnoughItems#936]
### What happened?

When looking at certain recipies game crashed

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
very long
```

### Anything else?

[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8934426/rei.log)
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8934427/latest.log)
[crash-2022-06-18_23.33.38-client.txt](https://github.com/shedaniel/RoughlyEnoughItems/files/8934428/crash-2022-06-18_23.33.38-client.txt)

**Comment by shedaniel** [comment]
Caused by twilightforest
