### ISSUE TITLE
[Bug] REI not yet fully initialized

### ISSUE THREAD

**Issue by DynamicMountain** [shedaniel/RoughlyEnoughItems#946]
### What happened?

REI is not functioning. Running on 1.18.2, an error is produced above the search bar that looks like such
![image](https://user-images.githubusercontent.com/104180438/174904740-a8f23184-0eb2-45da-a274-13fdeba73886.png)

REI log linked below
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8953062/rei.log)
Latest log as well
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8953066/latest.log)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
REI log linked below
[rei.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8953062/rei.log)
Latest log as well
[latest.log](https://github.com/shedaniel/RoughlyEnoughItems/files/8953066/latest.log)
```

**Comment by shedaniel** [comment]
Please check if the vanilla Recipe Book contains any recipes, if not, this is not caused by REI.

I see in your logs that a mod that injected to the game did not account for the creative mode search indexing, which caused a crash for REI, this is not caused by REI, and you may need to find the offending mod by your own.

**Comment by Tenuuu** [comment]
I have a similar issue on 1.19. Recipe Book still shows recipes though

**Comment by DynamicMountain** [comment]
Found the issue, OdysseyHUD's latest update causes REI to freeze up!
