### ISSUE TITLE
[Bug] Cannot favorite things in the + menu in the bottom right

### ISSUE THREAD

**Issue by SlappMann** [shedaniel/RoughlyEnoughItems#950]
### What happened?

Cannot favorite things in the + menu in the bottom right 
Gamemode
Weather
Time
Cannot be favorited by dragging up

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
https://pastebin.com/Sy5BnCXx

( too long for github comment )
```

**Comment by shedaniel** [comment]
Could not reproduce, please consider attaching a description on how to reproduce this issue or a video
