### ISSUE TITLE
[Bug] Cheat mode sends command as a chat message on vanilla servers

### ISSUE THREAD

**Issue by Fourmisain** [shedaniel/RoughlyEnoughItems#952]
### What happened?

When trying to give yourself an item on a "vanilla" 1.19 server (any server without REI), the command is instead sent as a chat message.

Here's how that looks like:

![cheating_commands](https://user-images.githubusercontent.com/8464472/175657379-91bffe05-47ba-400d-ad9e-55eb89432338.png)

![example](https://user-images.githubusercontent.com/8464472/175657256-626a44cb-12f9-4ac5-ba70-0e1c88a4dc85.png)

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
-
```

### Anything else?

Since 1.19, commands are now sent via it's own packet (yarn name `CommandExecutionC2SPacket`) and the existing methods slightly changed, e.g. instead of the previous
`player.sendChatMessage("/give ...");`
it is now
`player.sendCommand("give ...");`

**Comment by shedaniel** [comment]
This has been fixed already, are you sure you are on the latest rei version?

**Comment by Fourmisain** [comment]
Oh!
I thought I was on the newest version because I'm using a mod updater - turns out the mod wasn't on the list, sorry about that!
