### ISSUE TITLE
[Feature] Force favorite item to start new row.

### ISSUE THREAD

**Issue by mk-pmb** [shedaniel/RoughlyEnoughItems#953]
### What is your feature request?

First up, not a duplicate of categories. While it might be used as a crude stopgap for #388, I'd like to actually use this feature even inside a category.

This feature is a flag that a favorites item might have which forces it to start a new row.

In case explicit visual indication is desired, we could add a thin horizontal line above the icon. I don't need it though.

In order to save on key bindings, I'd suggest we change the "delete existing favorite" key binding to "manage existing favorite", opening a context menu like the "+" menu, where we can view and toggle this flag, can choose to delete, and potentially other actions. (I have a few ideas what other favo actions would be useful.)

<details><summary>[Spoiler / Reminder to myself]</summary>

* renaming without the need for an anvil, because "add favorite" doesn't work in the anvil screen.

</details>

### What do you think this change is of?

- [X] Visual
- [X] Recipe Lookup
- [X] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

**Comment by mk-pmb** [comment]
In the categories issue, vertical distance was requested ("separated by empty spaces about 2x the item's height."), so maybe we should consider that direction of feature creep here as well. Instead of a flag, it could be an unsigned small integer property. If the property is present, "0" would be the original effect, just force a new line, and any positive number would be how many blank rows to insert.

**Comment by shedaniel** [comment]
I don't think this is a good solution, and I think we should go straight to favorites categories, and not make some middle ground features to be removed when categories finally arrive (Since implementing this also takes time)

**Comment by mk-pmb** [comment]
@shedaniel When you write,

> we should go straight to favorites categories, and not make some middle ground features

I wonder if there was a miscommunication. I don't see this as a middle ground. I knew this could be mistaken, that's why I added

> I'd like to actually use this feature even inside a category.

**Comment by shedaniel** [comment]
> I'd like to actually use this feature even inside a category.

Sorry I don’t actually think it is an user friendly option, yes, power users may love it, but it is so niche. I don’t think you need this level of precise control, this will only confuse users

**Comment by mk-pmb** [comment]
Would you be willing to merge and maintain the PR if it hides this feature behind a secret option? E.g. you have to manually edit the JSON to insert the first forced linebreak, but once it's detected on config read, it will be offered.

**Comment by shedaniel** [comment]
It is way too much code and special cases for just that, these code all need maintenance, and I will also need to support that when I actually do favorites groups.
