### ISSUE TITLE
[Bug] Modrinth source button missing

### ISSUE THREAD

**Issue by mooziii** [shedaniel/RoughlyEnoughItems#955]
### What happened?

Idk where to report this but on the modrinth page, the link to the github repository is missing 
![image](https://user-images.githubusercontent.com/63669478/175805137-4b98de6e-ed33-49e6-9f3d-7e1e6887c65f.png)

### What mod loaders are you seeing the problem on?

Fabric, Forge, Rift

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [X] Others

### Relevant log output

```shell
nothing
```

**Comment by shedaniel** [comment]
Thanks for noticing! I've added the source now
