### ISSUE TITLE
[Bug] [Netty Epoll Server IO #n/WARN]: Failed to handle packet roughlyenoughitems:create_item!

### ISSUE THREAD

**Issue by Napkin** [shedaniel/RoughlyEnoughItems#96]
**Describe the bug**
When taking an item (or a stack of 64) out of REI, this warning message shows up on the dedicated server. This doesn't happen in a single-player world. The items show up in the inventory fine. Don't see any issue, apart from the warning message in the server console.

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.1
 - Mod Loader: fabric 1.14.1+build.5-0.4.7+build.147 and fabric-api-0.3.0-pre+build.157a

**Logs**
https://gist.github.com/Napkin/615f8e30b63cdf58a907e055e6d484ad

**Additional context**
Great mod, thank you!

**Comment by shedaniel** [comment]
Thanks for reporting!

**Comment by shedaniel** [comment]
Please test on build 108, should be fixed!

**Comment by Napkin** [comment]
Thank you for fixing! Unfortunately, I can't verify. Please have a look at https://github.com/shedaniel/RoughlyEnoughItems/issues/98

**Comment by Napkin** [comment]
Build 119 works fine! Thanks!
