### ISSUE TITLE
[Bug] Outdated CurseForge link to architectury library

### ISSUE THREAD

**Issue by ClayenKitten** [shedaniel/RoughlyEnoughItems#966]
### What happened?

Mod's [CurseForge description page](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) has a [link](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) to the architectury library. However, the project has moved to [another location](https://www.curseforge.com/minecraft/mc-mods/architectury-api). Can be worth of fixing.

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [ ] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [x] Others

### Relevant log output

```shell
N/A
```

**Comment by shedaniel** [comment]
Thank you for noticing, this has been fixed now.
