### ISSUE TITLE
[Bug] Title Overlap in center of categories

### ISSUE THREAD

**Issue by DemonSlayer112** [shedaniel/RoughlyEnoughItems#967]
### What happened?

When you hover between two categories they both try to show at the same time combining.
Fabric 8.2.490

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
Im sry this is required(*) but idk what would be worth logging, just a visual issue.
```

### Anything else?

![image](https://user-images.githubusercontent.com/70122500/176581833-a33be11b-ad6f-4af3-94c1-5243c68534e0.png)

**Comment by shedaniel** [comment]
Update REI
