### ISSUE TITLE
2.9.1+build.118 causes dedicated server not to start

### ISSUE THREAD

**Issue by Napkin** [shedaniel/RoughlyEnoughItems#98]
**Describe the bug**
Added the mod to the server and on startup I get this error:
https://gist.github.com/Napkin/466eb228f94eb4a6cd140c5f798cb1c2

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.2
 - Mod Loader: fabric 1.14.2+build.1-0.4.8+build.154
 - Fabric-api: 0.3.0+build.173

**Logs**
https://gist.github.com/Napkin/466eb228f94eb4a6cd140c5f798cb1c2

**Additional question**
According to server logs, these mods are included in the jar:
cloth@0.3.1+build.23
cloth-config@0.2.1+build.14

Would adding ClothConfig-0.2.4.17.jar manually overwrite the included one?

**Comment by shedaniel** [comment]
Adding ClothConfig-0.2.4.17.jar would just update cloth config. I am fixing this bug in just a second

**Comment by shedaniel** [comment]
Fixed in build 109

**Comment by Napkin** [comment]
Build 119 works fine! Thanks!
