### ISSUE TITLE
[Bug] Invalid payload REGISTER!

### ISSUE THREAD

**Issue by fuck-shithub** [shedaniel/RoughlyEnoughItems#99]
**Describe the bug**
When joining a server (tested BungeeCord with Spigot 1.14.2, and just Spigot 1.14.2) you get kicked for "Invalid payload REGISTER!"

**Steps to Reproduce**
- Create a server running Spigot 1.14.2
- Join it and enjoy getting kicked for "Invalid payload REGISTER!"

**Environment (please complete the following information with the version):**
 - Minecraft: 1.14.2
 - Mod Loader: Fabric
- Fabric Game/Mappings version: 1.14.2+build.2
- Fabric Loader version: 0.4.8+build.154
- Mods:
ClothConfig-0.2.4.17
ClothEvents-0.3.1.23
fabric-api-0.3.0+build.175
ModMenu-1.5.4-85
RoughlyEnoughItems-2.9.1+build.119

**Logs**
Spigot console when trying to join game from client - https://pastebin.com/nyR984bF

**Comment by tkbeal** [comment]
Same problem. Not sure how to fix. I see in the description that this mid is client-side and server-side? Does that mean the server also needs to have it installed in order to join? I thought this was client-side only?

**Comment by shedaniel** [comment]
This mod is in the middle of client sided and server sided. It works if the server doesn't have the mod. But this seems like a bug for build 119.

**Comment by Napkin** [comment]
On non-spigot server it works fine - with and without server having the mod, fabric client with mod could join.

**Comment by shedaniel** [comment]
Please give me a second for me to publish the update to curseforge.

**Comment by tkbeal** [comment]
Will this fix connecting to Paper servers?

**Comment by shedaniel** [comment]
Was there an issue for connecting to Paper servers?

**Comment by shedaniel** [comment]
Uploaded as build 121: https://minecraft.curseforge.com/projects/roughly-enough-items/files/2717734

**Comment by tkbeal** [comment]
I was getting this error, the invalid payload Register, when connecting to my server running Paper 1.14.2

**Comment by shedaniel** [comment]
Not sure if build 121 will fix that but open another issue if it errors again.

**Comment by tkbeal** [comment]
Alright sounds good, thanks for the fast fix

**Comment by shedaniel** [comment]
np

**Comment by tkbeal** [comment]
Works! Connection to server successful
