### ISSUE TITLE
[Bug] Crash when opening REI config

### ISSUE THREAD

**Issue by StockiesLad** [shedaniel/RoughlyEnoughItems#997]
### What happened?

It crashed
Expected: to open the config

### What mod loaders are you seeing the problem on?

Fabric

### What do you think this bug is of?

- [X] Visual
- [ ] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
https://github.com/shedaniel/RoughlyEnoughItems/files/9103637/latest.log
```

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
You have a too new Cloth Config that is not for your Minecraft version
